from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

wb = Workbook()
ws = wb.active
ws.title = "Runo"

headers = ["A: Alkuperäinen säe", "B: Modernilla suomella", "C: Perusmuodot", "D: Käännökset (perusmuodot)", "E: Englanninkielinen käännös", "F: Trickster-huomioita"]
header_font = Font(name="Arial", bold=True, color="FFFFFF", size=11)
header_fill = PatternFill("solid", start_color="2E4057")
for col, h in enumerate(headers, 1):
    cell = ws.cell(row=1, column=col, value=h)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

verses = [
    ("Siitä häitä hankittihin,", "Siitä häitä hankittiin,", "siitä, häät, hankkia", "then, wedding, to prepare", "Then a wedding was prepared,", ""),
    ("Walmisteltihin pitoja,", "Valmisteltiin pitoja,", "valmistaa, pidot", "to prepare, feast", "A feast was made ready,", ""),
    ("Häitä Pohjolan tuwilla,", "Häitä Pohjolan tuvilla,", "häät, Pohjola, tupa", "wedding, Pohjola, cabin", "A wedding in the cabins of Pohjola,", ""),
    ("Pitoja Pimentolassa.", "Pitoja Pimentolassa.", "pidot, Pimentola", "feast, Pimentola (Place of Darkness)", "A feast in Pimentola.", ""),
    ("Mitä tuohon tuotanehe,", "Mitä tuohon tuotanehe,", "mikä, tuoda", "what, to bring", "What might be brought to that,", ""),
    ("Ja kuta we'ettänehe,", "Ja kuta vedettänehe,", "ja, kuka, vetää", "and, who/what, to fetch", "And what might be fetched,", ""),
    ("Noihin Pohjolan pitohin,", "Noihin Pohjolan pitoihin,", "noihin, Pohjola, pidot", "to those, Pohjola, feast", "To those feasts of Pohjola,", ""),
    ("Sariolan juominkihin,", "Sariolan juomingeihin,", "Sariola, juominki", "Sariola, drinking-feast", "To the drinking-feasts of Sariola,", ""),
    ("Hywän rahwahan ruuiksi,", "Hyvän rahwaan ruuiksi,", "hyvä, rahvas, ruoka", "good, common folk, food", "As food for the good common folk,", ""),
    ("Joukon suuren syötäwäksi?", "Joukon suuren syötäväksi?", "joukko, suuri, syötävä", "crowd, great, to be eaten", "To be eaten by the great crowd?", ""),
    ("Tuotu on muhia mulli,", "Tuotu on muhkea mulli,", "tuoda, muhkea, mulli", "to bring, hefty, young bull", "A hefty young bull was brought,", ""),
    ("Sonni saatuna lihawa.", "Sonni saatuna lihava.", "sonni, saada, lihava", "bull, to get, fat/plump", "A fat bull was gotten.", ""),
    ("Kaswo härkä Karjalassa", "Kasvoi härkä Karjalassa", "kasvaa, härkä, Karjala", "to grow, ox, Karelia", "An ox grew in Karelia", "The ox of cosmic proportions — straddling provinces, with a swallow flying a full day between its horns without reaching the other side — is a wildly exaggerated, almost absurdist image. This kind of grotesque hyperbole, where ordinary creatures balloon to impossible scale, recurs throughout the epic's trickster-tinged episodes (Vipunen, the giant pike) and functions here as comic, larger-than-life scene-setting for the wedding feast."),
    ("Sonni Suomessa sikesi,", "Sonni Suomessa siitettiin,", "sonni, Suomi, siittää", "bull, Finland, to breed", "A bull was bred in Finland,", ""),
    ("Eikä härkä suuren suuri,", "Eikä härkä suuren suuri,", "ei, härkä, suuri", "not, ox, very great", "The ox was not the greatest great,", ""),
    ("Eikä härkä pienen pieni;", "Eikä härkä pienen pieni;", "ei, härkä, pieni", "not, ox, very small", "Nor was the ox the smallest small;", ""),
    ("Hämehessä häntä häily,", "Hämeessä häntä häilyi,", "Häme, häntä, häilyä", "Häme (province), tail, to sway", "In Häme its tail swayed,", ""),
    ("Pää keikku Kemijoella,", "Pää keikkui Kemijoella,", "pää, keikkua, Kemijoki", "head, to sway/bob, Kemi River", "Its head swayed at the Kemi River,", ""),
    ("Jalk' on yksi Aunuksessa,", "Jalka on yksi Aunuksessa,", "jalka, yksi, Aunus", "leg, one, Aunus (Olonets)", "One leg was in Aunus,", ""),
    ("Toinen Turjan tunturilla,", "Toinen Turjan tunturilla,", "toinen, Turja, tunturi", "another, Turja, fell/mountain", "Another on the fells of Turja,", ""),
    ("Kolmansi koskella Wuoksen,", "Kolmas koskella Vuoksen,", "kolmas, koski, Vuoksi", "third, rapids, Vuoksi (river)", "A third at the rapids of the Vuoksi,", ""),
    ("Neljäs on Lapin lahella.", "Neljäs on Lapin lahdella.", "neljäs, Lappi, lahti", "fourth, Lapland, bay", "A fourth at the bay of Lapland.", ""),
    ("Päiwän lenti pääskylintu", "Päivän lensi pääskylintu", "päivä, lentää, pääskylintu", "day, to fly, swallow", "A swallow flew a whole day", ""),
    ("Härän sarwien wäliä,", "Härän sarvien väliä,", "härkä, sarvi, väli", "ox, horn, space between", "The space between the ox's horns,", ""),
    ("Kuun juoksi kesäorawa", "Kuun juoksi kesäorava", "kuu, juosta, kesäorava", "moon (month), to run, summer squirrel", "A summer squirrel ran for a month", ""),
    ("Häpeheltä hännän päähän,", "Häpeheltä hännän päähän,", "häpy, häntä, pää", "groin/loins, tail, tip", "From the loins to the tip of the tail,", ""),
    ("Eikä wielä päähän päässyt,", "Eikä vielä päähän päässyt,", "ei, vielä, pää, päästä", "not, yet, tip, to reach", "And still did not reach the tip,", ""),
    ("Ensinkänä ennättänyt,", "Ensinkään ennättänyt,", "ensinkään, ennättää", "at all, to manage in time", "Did not manage it at all,", ""),
    ("Keskelläpä yön pitäwi,", "Keskellä yön pitää,", "keskellä, yö, pitää", "in the middle of, night, to be (caught)", "In the middle of the night it was caught", ""),
    ("Härän hännällä lepäsi.", "Härän hännällä lepäsi.", "härkä, häntä, levätä", "ox, tail, to rest", "Resting on the ox's tail.", ""),
    ("Etsitähän iskiätä,", "Etsitään iskijää,", "etsiä, iskijä", "to search, striker/slaughterer", "A slaughterer is sought,", ""),
    ("Katsotahan kaatajata,", "Katsotaan kaatajaa,", "katsoa, kaataja", "to look for, feller/slayer", "A feller is looked for,", ""),
    ("Wienosta Wenäjän maasta", "Vienosta Venäjän maasta", "Vienä, Venäjä, maa", "Vienä (White Sea Karelia), Russia, land", "From the gentle land of Russia", ""),
    ("Kaunihista Karjalasta,", "Kaunihista Karjalasta,", "kaunis, Karjala", "beautiful, Karelia", "From beautiful Karelia,", ""),
    ("Suomen suurilta tiloilta,", "Suomen suurilta tiloilta,", "Suomi, suuri, tila", "Finland, great, farm/estate", "From Finland's great estates,", ""),
    ("Ruotsin maasta rohkiasta,", "Ruotsin maasta rohkeasta,", "Ruotsi, maa, rohkea", "Sweden, land, bold", "From Sweden's bold land,", ""),
    ("Tämän riikin riitamaasta,", "Tämän riikin riitamaasta,", "riikki, riitamaa", "realm, border/disputed land", "From this realm's border land,", ""),
    ("Tämän wallan wainojasta.", "Tämän vallan vainojasta.", "valta, vainio", "power/realm, field", "From this realm's fields.", ""),
    ("Läksi ukko iskemähän,", "Lähti ukko iskemään,", "lähteä, ukko, iskeä", "to leave, old man, to strike", "An old man set off to strike,", "Three figures (an old man, a 'Palwonen', and 'Wirokannas' — possibly mythic or comic stand-ins for ordinary slaughterers) all flee in terror up trees when the great ox merely shakes its head, an absurdly disproportionate display of cowardice against the comic giant-creature, undercutting the heroic register of the hunt with slapstick."),
    ("Palwonen pitelemähän,", "Palvonen pitelemään,", "Palvonen, pidellä", "Palvonen (figure's name), to hold/handle", "Palvonen to handle it,", ""),
    ("Wirokannas wiilemähän;", "Virokannas viilemään;", "Virokannas, viillellä", "Virokannas (figure's name), to slice", "Virokannas to slice it;", ""),
    ("Härkä päänsä häilähytti,", "Härkä päänsä häilähytti,", "härkä, pää, häilähtää", "ox, head, to sway/shake", "The ox shook its head,", ""),
    ("Mustat silmänsä mulisti,", "Mustat silmänsä mulisti,", "musta, silmä, mulistaa", "black, eye, to roll/glare", "Rolled its black eyes,", ""),
    ("Ukko kuusehen kawahti,", "Ukko kuuseen kavahti,", "ukko, kuusi, kavahtaa", "old man, spruce, to dart/jump", "The old man darted up a spruce,", ""),
    ("Palwonen pajun nenähän,", "Palvonen pajun nenään,", "Palvonen, paju, nenä", "Palvonen, willow, tip", "Palvonen up the tip of a willow,", ""),
    ("Wirokannas kannon päähän.", "Virokannas kannon päähän.", "Virokannas, kanto, pää", "Virokannas, stump, top", "Virokannas onto the top of a stump.", ""),
    ("Ukko kuusesta toruwi,", "Ukko kuusesta toruu,", "ukko, kuusi, torua", "old man, spruce, to scold/shout", "The old man shouts from the spruce,", "From their hiding places, the cowards still loudly demand an enormous reward (a hundred vats of meat, seven boatloads of blood) for a kill they haven't made and never will — a comically inflated, empty boast followed immediately by their permanent disappearance from the story, a deflating trickster-style anticlimax."),
    ("Palwonen pajun nenästä", "Palvonen pajun nenästä", "Palvonen, paju, nenä", "Palvonen, willow, tip", "Palvonen from the tip of the willow", ""),
    ("Wirokannas kannon päästä:", "Virokannas kannon päästä:", "Virokannas, kanto, pää", "Virokannas, stump, top", "Virokannas from the top of the stump:", ""),
    ("\"Kun ma tullen toisen kerran,", "\"Kun minä tulen toisen kerran,", "kun, minä, tulla, toinen, kerta", "if, I, to come, second, time", "\"If I come a second time,", ""),
    ("Toki saanen saalihiksi", "Toki saanen saaliiksi", "toki, saada, saalis", "indeed, to get, prey/spoils", "Indeed I should get as spoils", ""),
    ("Sata saawia lihoa,", "Sata saavia lihaa,", "sata, saavi, liha", "hundred, vat, meat", "A hundred vats of meat,", ""),
    ("Werta seitsemän wenettä,", "Verta seitsemän venettä,", "veri, seitsemän, vene", "blood, seven, boat", "Seven boatloads of blood,", ""),
    ("Kuuta kuusi tynnyriä.\"", "Kuuta kuusi tynnyriä.\"", "kuu, kuusi, tynnyri", "fat/tallow, six, barrel", "Six barrels of fat.\"", ""),
    ("Eipä toiste tullukkana,", "Eipä toiste tullutkaan,", "ei, toiste, tulla", "not, a second time, to come", "But they never came a second time,", ""),
    ("Eikä sen erän perästä.", "Eikä sen erän perästä.", "ei, se, erä, perästä", "not, that, occasion, after", "Nor after that occasion.", ""),
    ("Etsitähän iskiätä,", "Etsitään iskijää,", "etsiä, iskijä", "to search, slaughterer", "A slaughterer is sought,", ""),
    ("Katsotahan kaatajata;", "Katsotaan kaatajaa;", "katsoa, kaataja", "to look for, feller", "A feller is looked for;", ""),
    ("Etsitähän Tuonelasta,", "Etsitään Tuonelasta,", "etsiä, Tuonela", "to search, Tuonela", "Search is made in Tuonela,", ""),
    ("Manalasta maanki alta,", "Manalasta maankin alta,", "Manala, maa, alta", "Manala, earth, from under", "In Manala, even under the earth,", ""),
    ("Etsitähän, eipä löytty,", "Etsitään, eipä löydy,", "etsiä, ei, löytyä", "to search, not, to be found", "Search is made, but none is found,", ""),
    ("Haettihin, ei hawattu.", "Haettiin, ei havaittu.", "hakea, ei, havaita", "to seek, not, to notice/find", "Sought, but none was discovered.", ""),
    ("Mies pieni merestä nousi,", "Mies pieni merestä nousi,", "mies, pieni, meri, nousta", "man, small, sea, to rise", "A small man rose from the sea,", "The tiny man (a thumb's height, three fingers tall) who rises from the sea fully armed in stone armor with a golden knife is an archetypal trickster figure: diminutive, mysterious, appearing from nowhere with exactly the unconventional power needed when all conventional heroes have failed."),
    ("Uros aallosta yleni,", "Uros aallosta yleni,", "uros, aalto, yletä", "hero, wave, to rise", "A hero rose from the wave,", ""),
    ("Eikä uros pienen pieni,", "Eikä uros pienen pieni,", "ei, uros, pieni", "not, hero, very small", "The hero was not the smallest small,", ""),
    ("Eikä uros suuren suuri;", "Eikä uros suuren suuri;", "ei, uros, suuri", "not, hero, very great", "Nor was the hero the greatest great;", ""),
    ("Pystyn peukalon pituinen,", "Pystyn peukalon pituinen,", "pysty, peukalo, pituinen", "upright, thumb, length", "The length of an upright thumb,", ""),
    ("Kolmen sormen korkeuinen:", "Kolmen sormen korkuinen:", "kolme, sormi, korkuinen", "three, finger, height of", "The height of three fingers:", ""),
    ("Alla maljan maata mahtu,", "Alla maljan maata mahtui,", "alla, malja, maata, mahtua", "under, bowl, to lie, to fit", "He fit lying under a bowl,", ""),
    ("Seulan alla seisomahan.", "Seulan alla seisomaan.", "seula, alla, seisoa", "sieve, under, to stand", "Standing under a sieve.", ""),
    ("Part' on polwilla eessä,", "Parta on polvilla edessä,", "parta, polvi, edessä", "beard, knee, in front", "His beard was at his knees in front,", ""),
    ("Hiwus kannoilla takana,", "Hiukset kannoilla takana,", "hius, kanto, takana", "hair, heel, behind", "His hair at his heels behind,", ""),
    ("Päässä paasinen kypäri,", "Päässä paasinen kypärä,", "pää, paasinen, kypärä", "head, flagstone, helmet", "A stone-slab helmet on his head,", ""),
    ("Jaloissa kiwiset kengät,", "Jaloissa kiviset kengät,", "jalka, kivinen, kenkä", "foot, stone, shoe", "Stone shoes on his feet,", ""),
    ("Weitsi kultanen käessä,", "Veitsi kultainen kädessä,", "veitsi, kultainen, käsi", "knife, golden, hand", "A golden knife in his hand,", ""),
    ("Hopiainen huotra wyöllä.", "Hopeainen huotra vyöllä.", "hopeainen, huotra, vyö", "silver, sheath, belt", "A silver sheath at his belt.", ""),
    ("Jo tapasi tappajansa,", "Jo tapasi tappajansa,", "jo, tavata, tappaja", "already, to meet/find, killer", "Now (the ox) had found its killer,", ""),
    ("Sonni suuri sortajansa.", "Sonni suuri sortajansa.", "sonni, suuri, sortaja", "bull, great, feller/destroyer", "The great bull its destroyer.", ""),
    ("Heti kun näki eränsä,", "Heti kun näki eränsä,", "heti, kun, nähdä, erä", "immediately, when, to see, opportunity", "As soon as he saw his chance,", ""),
    ("Ruhto niskahan rutosti,", "Ryhtyi niskaan rutosti,", "ryhtyä, niska, rutosti", "to set about, neck, swiftly", "He set swiftly upon its neck,", ""),
    ("Sorti sonnin polwillehen,", "Sorsi sonnin polvilleen,", "sortaa, sonni, polvi", "to force down, bull, knee", "Forced the bull onto its knees,", ""),
    ("Kylin maahan kyykähytti.", "Kyljin maahan kyykähytti.", "kylki, maa, kyykähtää", "side, ground, to crouch/fall", "Made it fall onto its side on the ground.", ""),
    ("Saiko paljon saalihiksi?", "Saiko paljon saaliiksi?", "saada, paljon, saalis", "to get, much, spoils", "Did he get much as spoils?", ""),
    ("Wähän saapi saalihiksi:", "Vähän saapi saaliiksi:", "vähän, saada, saalis", "little, to get, spoils", "He got little as spoils:", "The tiny man's catch (a hundred vats of meat, seven boatloads of blood) is described as 'little' even though it's the exact same enormous bounty the cowardly giants had boasted about wanting but never achieved — a wry, ironic comparison: what the small, true hero modestly calls 'little,' the boastful cowards could never even claim."),
    ("Sata saawia lihoa,", "Sata saavia lihaa,", "sata, saavi, liha", "hundred, vat, meat", "A hundred vats of meat,", ""),
    ("Sata syltä makkaroa,", "Sata syltä makkaraa,", "sata, syli, makkara", "hundred, fathom, sausage", "A hundred fathoms of sausage,", ""),
    ("Werta seitsemän wenettä,", "Verta seitsemän venettä,", "veri, seitsemän, vene", "blood, seven, boat", "Seven boatloads of blood,", ""),
    ("Kuuta kuusi tynnyriä,", "Kuuta kuusi tynnyriä,", "kuu, kuusi, tynnyri", "fat/tallow, six, barrel", "Six barrels of fat,", ""),
    ("Hywän Pohjolan pitohin,", "Hyvän Pohjolan pitoihin,", "hyvä, Pohjola, pidot", "good, Pohjola, feast", "For the good feasts of Pohjola,", ""),
    ("Sariolan juominkihin.", "Sariolan juomingeihin.", "Sariola, juominki", "Sariola, drinking-feast", "For the drinking-feasts of Sariola.", ""),
    ("Siitä Pohjolan emäntä", "Siitä Pohjolan emäntä", "siitä, Pohjola, emäntä", "then, Pohjola, mistress", "Then the mistress of Pohjola", ""),
    ("Itse tuon sanoiksi wirkki:", "Itse tuon sanoiksi virkki:", "itse, tuo, sana, virkata", "herself, that, word, to utter", "Herself uttered these words:", ""),
    ("\"Mistäpä olutta saamma,", "\"Mistäpä olutta saamme,", "mistä, olut, saada", "from where, beer/ale, to get", "\"From where shall we get beer,", ""),
    ("Tahi taaria panemma,", "Tahi taaria panemme,", "tahi, taari, panna", "or, small beer, to brew", "Or brew small beer,", ""),
    ("Näille häille hankkimille,", "Näille häille hankkimille,", "tämä, häät, hankkia", "this, wedding, to prepare", "For these weddings to be prepared,", ""),
    ("Pioille piettäwille?", "Pidoille pidettäville?", "pidot, pitää", "feast, to hold", "For the feasts to be held?", ""),
    ("En tieä tekoa taarin,", "En tiedä tekoa taarin,", "ei, tietää, teko, taari", "not, to know, making, small beer", "I do not know the making of small beer,", ""),
    ("Enkä syntyä olosen.\"", "Enkä syntyä olueen.\"", "ei, syntyä, olut", "not, origin, beer", "Nor the origin of beer.\"", ""),
    ("Huuhuwi humala puusta,", "Huhuili humala puusta,", "huhuilla, humala, puu", "to call out, hop plant, tree/vine", "The hop called out from the tree,", "The hop-vine, water, and barley speaking aloud and asking when they will be brought together is an animistic, almost riddle-like moment where the very ingredients of beer anticipate and narrate their own transformation — a magical, slightly uncanny personification consistent with the epic's broader pattern of speaking trees, animals, and objects."),
    ("Wesi wirrasta wihelsi,", "Vesi virrasta vihelsi,", "vesi, virta, viheltää", "water, stream, to whistle", "The water whistled from the stream,", ""),
    ("Otra pellon pientaresta:", "Otra pellon pientareesta:", "otra, pelto, piennar", "barley, field, edge", "The barley from the edge of the field:", ""),
    ("\"Konsa me koolle saamma,", "\"Koska me koolle saamme,", "koska, me, koolle, saada", "when, we, together, to get", "\"When shall we be brought together,", ""),
    ("Konsa koolle ja koholle.\"", "Koska koolle ja koholle.\"", "koska, koolle, koholle", "when, together, into a mass/rising", "When together and rising up.\"", ""),
    ("Osmotar oluen seppä,", "Osmotar oluen seppä,", "Osmotar, olut, seppä", "Osmotar, beer, smith/maker", "Osmotar, maker of beer,", ""),
    ("Kapo kaljojen tekiä,", "Kapo kaljojen tekijä,", "kapo, kalja, tekijä", "maiden, small beer, maker", "The maiden, maker of small beer,", ""),
    ("Arwelee, ajattelewi:", "Arvelee, ajattelee:", "arvella, ajatella", "to ponder, to think", "Ponders, thinks:", ""),
    ("\"Mitä tuostaki tulisi,", "\"Mitä tuostakin tulisi,", "mikä, tuosta, tulla", "what, from that, to become/result", "\"What might come of that,", ""),
    ("Jos panen pa'an tulelle,", "Jos panen padan tulelle,", "jos, panna, pata, tuli", "if, to put, pot, fire", "If I put the pot on the fire,", ""),
    ("Laitan keiton kiehumahan?\"", "Laitan keiton kiehumaan?\"", "laittaa, keitto, kiehua", "to set, brew/stew, to boil", "Set the brew to boil?\"", ""),
    ("Otti otrasen jywiä,", "Otti otrasen jyviä,", "ottaa, otranen, jyvä", "to take, barley, grain", "She took barley grains,", ""),
    ("Kuusi otrasen jyweä,", "Kuusi otrasen jyvää,", "kuusi, otranen, jyvä", "six, barley, grain", "Six barley grains,", ""),
    ("Seitsemän humalan päätä,", "Seitsemän humalan päätä,", "seitsemän, humala, pää", "seven, hop, head/cone", "Seven hop-cones,", ""),
    ("Wettä kauhoa kaheksan;", "Vettä kauhoa kahdeksan;", "vesi, kauho, kahdeksan", "water, ladleful, eight", "Eight ladlefuls of water;", ""),
    ("Niin pani pa'an tulelle,", "Niin pani padan tulelle,", "niin, panna, pata, tuli", "so, to put, pot, fire", "Then she put the pot on the fire,", ""),
    ("Laitto keiton kiehumahan.", "Laittoi keiton kiehumaan.", "laittaa, keitto, kiehua", "to set, brew, to boil", "Set the brew to boil.", ""),
    ("Kuu kiwiä kuumettihin,", "Kuu kiviä kuumetettiin,", "kuu, kivi, kuumettaa", "moon (month), stone, to heat", "For a month stones were heated,", "The cosmic-scale exaggeration continues into the brewing process itself — a month spent heating stones, a whole summer boiling water, an entire forest's worth of wood burned — turning the domestic act of brewing beer into a mythic undertaking on the scale of the earlier monster-hunts, blurring the line between mundane craft and epic feat."),
    ("Kesä wettä keitettihin,", "Kesä vettä keitettiin,", "kesä, vesi, keittää", "summer, water, to boil", "For a summer water was boiled,", ""),
    ("Salo puita poltettihin,", "Salo puita poltettiin,", "salo, puu, polttaa", "wilderness, wood, to burn", "A wilderness of wood was burned,", ""),
    ("Salo puita, saari maita.", "Salo puita, saari maita.", "salo, puu, saari, maa", "wilderness, wood, island, land", "A wilderness of wood, an island of land.", ""),
    ("Kansa kaikki katsahtawi,", "Kansa kaikki katsahtaa,", "kansa, kaikki, katsahtaa", "people, all, to glance/look", "All the people look,", ""),
    ("Katsahtawi, kaiwahtawi:", "Katsahtaa, kaivahtaa:", "katsahtaa, kaivata", "to glance, to wonder/long", "Look, wonder:", ""),
    ("\"Mistäpä sawunen saapi,", "\"Mistäpä savuinen saapuu,", "mistä, savuinen, saapua", "from where, smoky, to arrive", "\"From where does the smoky thing come,", ""),
    ("Auer ilmahan ajaksen.\"", "Auer ilmaan ajautuu.\"", "auer, ilma, ajautua", "haze, air, to drift", "The haze drifts into the air.\"", ""),
    ("Tuoltapa sawunen saapi,", "Tuoltapa savuinen saapuu,", "tuolta, savuinen, saapua", "from there, smoky, to arrive", "From there the smoky thing comes,", ""),
    ("Auer ilmahan ajaksen;", "Auer ilmaan ajautuu;", "auer, ilma, ajautua", "haze, air, to drift", "The haze drifts into the air;", ""),
    ("Sawu saarella palawi,", "Savu saarella palaa,", "savu, saari, palaa", "smoke, island, to burn", "Smoke burns on the island,", ""),
    ("Tuli niemen tutkamessa,", "Tuli niemen tutkamessa,", "tuli, niemi, tutkain", "fire, cape, tip/point", "Fire at the tip of the cape,", ""),
    ("Pienikö soan tuleksi,", "Pienikö sodan tuleksi,", "pieni, sota, tuli", "small, war, fire", "Small as the fire of war,", ""),
    ("Suuri paimosen paloksi.", "Suuri paimosen paloksi.", "suuri, paimo, palo", "great, herder's, fire", "Great as the herder's fire.", ""),
    ("Osmotar oluen seppä,", "Osmotar oluen seppä,", "Osmotar, olut, seppä", "Osmotar, beer, maker", "Osmotar, maker of beer,", ""),
    ("Kapo kaljojen tekiä,", "Kapo kaljojen tekijä,", "kapo, kalja, tekijä", "maiden, small beer, maker", "The maiden, maker of small beer,", ""),
    ("Kesän keittäwi olutta,", "Kesän keittää olutta,", "kesä, keittää, olut", "summer, to brew, beer", "Brews beer for a summer,", ""),
    ("Talwen taaria rakenti;", "Talven taaria rakensi;", "talvi, taari, rakentaa", "winter, small beer, to build/make", "Built small beer for a winter;", ""),
    ("Pani otraista olutta", "Pani otraista olutta", "panna, otrainen, olut", "to put, barley, beer", "Put the barley beer", ""),
    ("Puisen uuen uurtehesen.", "Puisen uuden uurtehiin.", "puinen, uusi, uurre", "wooden, new, vat/trough", "Into the new wooden vat.", ""),
    ("Sai oluen panneheksi,", "Sai oluen pantua,", "saada, olut, panna", "to get, beer, to put/brew", "She managed to brew the beer,", "Despite perfect technical execution, the beer simply will not ferment — an ordinary craft process inexplicably failing, requiring magical/animal intervention to succeed. This motif of competent labor stalling until a trickster-adjacent solution (a squirrel, marten, and bee sent on supernatural errands) intervenes is a recurring epic pattern, here applied to brewing rather than combat or courtship."),
    ("Ei saanut hapanneheksi.", "Ei saanut hapantua.", "ei, saada, hapantua", "not, to get, to ferment", "But could not get it to ferment.", ""),
    ("Arwelee, ajattelewi,", "Arvelee, ajattelee,", "arvella, ajatella", "to ponder, to think", "Ponders, thinks,", ""),
    ("Sanan wirkko, noin nimesi:", "Sanan virkko, noin nimesi:", "sana, virkata, niin, nimetä", "word, to utter, so, to name", "Uttered a word, named it so:", ""),
    ("\"Mitä tuohon tuotanehe,", "\"Mitä tuohon tuotanehe,", "mikä, tuoda", "what, to bring", "\"What might be brought to that,", ""),
    ("Ja kuta kutsuttanehe,", "Ja kuta kutsuttanehe,", "ja, kuka, kutsua", "and, what, to summon", "And what might be summoned,", ""),
    ("Oluelle happameksi,", "Oluelle happameksi,", "olut, happama", "beer, sour/fermenting agent", "As a fermenting agent for the beer,", ""),
    ("Kaljalle kohottimeksi.\"", "Kaljalle kohottimeksi.\"", "kalja, kohotin", "small beer, riser/leavening agent", "As a rising agent for the small beer.\"", ""),
    ("Hyw' on tyttö Pohjan neiti,", "Hyvä on tyttö Pohjan neiti,", "hyvä, tyttö, Pohja, neiti", "good, girl, Pohjola, maiden", "Good is the girl, the maiden of Pohjola,", ""),
    ("Se on soma sormiltansa,", "Se on soma sormiltaan,", "se, soma, sormi", "she, neat/dainty, finger", "She is dainty with her fingers,", ""),
    ("Aina liukas liikunnolta,", "Aina liukas liikunnolta,", "aina, liukas, liikunta", "always, nimble, movement", "Always nimble in her movement,", ""),
    ("Aina kengältä kepiä.", "Aina kengältä kepeä.", "aina, kenkä, kepeä", "always, shoe/footstep, light", "Always light on her feet.", ""),
    ("Liikku sillon liitoksella,", "Liikkui sillan liitoksella,", "liikkua, silta, liitos", "to move, bridge/floor, joint", "She moved at the joint of the floor,", ""),
    ("Laaho keskilattialla,", "Laahoi keskilattialla,", "laahata, keskilattia", "to glide/drag, middle of floor", "Glided across the middle of the floor,", ""),
    ("Yhtä toista toimitteli", "Yhtä toista toimitteli", "yksi, toinen, toimittaa", "one, another, to busy oneself with", "Busied herself with this and that", ""),
    ("Kahen kattilan kesellä.", "Kahden kattilan keskellä.", "kaksi, kattila, keskellä", "two, cauldron, in the middle of", "In the midst of two cauldrons.", ""),
    ("Näki puikon lattialla,", "Näki puikon lattialla,", "nähdä, puikko, lattia", "to see, little stick/spindle, floor", "She saw a little stick on the floor,", ""),
    ("Otti puikon lattialta,", "Otti puikon lattialta,", "ottaa, puikko, lattia", "to take, little stick, floor", "Took the little stick from the floor,", ""),
    ("Katselewi, kääntelewi:", "Katselee, kääntelee:", "katsella, kääntää", "to look, to turn", "Looks at it, turns it over:", ""),
    ("\"Mitä tuostaki tulisi", "\"Mitä tuostakin tulisi", "mikä, tuosta, tulla", "what, from that, to become", "\"What might come of that", "The maiden's idle, curious experiment — picking up a random little stick and wondering what it might become in her hands — is itself a small act of playful, almost childlike trickster-style creativity, turning an ordinary found object into the seed of a magical transformation purely by wondering aloud."),
    ("Kawon kaunihin käsissä,", "Kavon kaunihin käsissä,", "kapo, kaunis, käsi", "maiden, beautiful, hand", "In the beautiful maiden's hands,", ""),
    ("Hywän immen hyppysissä?\"", "Hyvän immen hyppysissä?\"", "hyvä, impi, hyppyset", "good, maiden, fingertips", "In the good maiden's fingertips?\"", ""),
    ("Jo kanto kawon kätehen,", "Jo kantoi kavon käteen,", "kantaa, kapo, käsi", "to carry, maiden, hand", "She carried it to the maiden's hand,", ""),
    ("Hywän immen hyppysihin.", "Hyvän immen hyppysiin.", "hyvä, impi, hyppyset", "good, maiden, fingertips", "To the good maiden's fingertips.", ""),
    ("Kapo kaksin kämmeninsä,", "Kapo kaksin kämmeninsä,", "kapo, kaksi, kämmen", "maiden, two, palm", "The maiden with her two palms,", "Conjuring living creatures (a squirrel, then later a marten and a bee) simply by rubbing her palms together over a found stick, splinter, or leaf is pure, playful creation-magic — an act of transformation through simple repeated gesture rather than elaborate incantation, a distinctly different and more whimsical form of magic than the heavy ritualized speech-magic seen elsewhere in the epic."),
    ("Hykersi molempinensa,", "Hykersi molemmin puolin,", "hykertää, molemmin", "to rub, both", "Rubbed with both,", ""),
    ("Molempihin reisihinsä;", "Molempiin reisiinsä;", "molemmin, reisi", "both, thigh", "Onto both her thighs;", ""),
    ("Synty walkia orawa.", "Syntyi valkea orava.", "syntyä, valkea, orava", "to be born, white, squirrel", "A white squirrel was born.", ""),
    ("Niin se neuo poikoansa,", "Niin se neuvoi poikaansa,", "niin, neuvoa, poika", "so, to instruct, son/young one", "So she instructed her young one,", ""),
    ("Orawaistansa opasti:", "Oravaistansa opasti:", "oravainen, opastaa", "little squirrel, to guide", "Guided her little squirrel:", ""),
    ("\"Orawani lintuseni,", "\"Oravani lintuseni,", "orava, lintunen", "squirrel, little bird (term of endearment)", "\"My squirrel, my little bird,", ""),
    ("Orpolapseni omani!", "Orpolapseni omani!", "orpolapsi, oma", "orphan child, own", "My own orphan child!", ""),
    ("Juokse tuonne, kunne käsken,", "Juokse tuonne, kunne käsken,", "juosta, tuonne, käskeä", "to run, there, to command", "Run there, where I command,", ""),
    ("Kunne käsken ja kehotan,", "Kunne käsken ja kehotan,", "kunne, käskeä, kehottaa", "to where, to command, to urge", "Where I command and urge you,", ""),
    ("Mielusahan metsolahan,", "Mieluisaan metsoon,", "mieluisa, metsä", "pleasant, forest", "To the pleasant forest,", ""),
    ("Tarkkahan Tapiolahan;", "Tarkkaan Tapiolaan;", "tarkka, Tapiola", "keen, Tapiola (forest realm)", "To keen Tapiola;", ""),
    ("Nouse puuhun pienosehen,", "Nouse puuhun pienoiseen,", "nousta, puu, pienoinen", "to climb, tree, little/small", "Climb a little tree,", ""),
    ("Taiten tarhalatwasehen,", "Taiten tarhalatvaan,", "taitaen, tarhalatva", "skillfully, garden-treetop/orchard-top", "Skillfully to the orchard-top,", ""),
    ("Jottei kokko kopraseisi,", "Jottei kokko koprassaisi,", "jottei, kokko, kopata", "so that not, eagle, to grab/seize", "So that the eagle will not seize you,", ""),
    ("Eikä iskis ilman lintu.", "Eikä iskisi ilman lintu.", "ei, iskeä, ilma, lintu", "not, to strike, air, bird", "Nor the bird of the air strike you.", ""),
    ("Käpy pure käessäsi,", "Käpy pureppi kädessäsi,", "käpy, purra, käsi", "cone, to bite/take hold, hand", "Take a cone in your hand,", ""),
    ("Kanna kaksi kynnessäsi,", "Kanna kaksi kynnessäsi,", "kantaa, kaksi, kynsi", "to carry, two, claw", "Carry two in your claw,", ""),
    ("Ne kanna kawon kätehen,", "Ne kanna kavon käteen,", "ne, kantaa, kapo, käsi", "those, to carry, maiden, hand", "Carry those to the maiden's hand,", ""),
    ("Tuo olalle Osmottaren.\"", "Tuo olalle Osmottaren.\"", "tuoda, olka, Osmotar", "to bring, shoulder, Osmotar", "Bring them to Osmotar's shoulder.\"", ""),
    ("Osasi orawa juosta,", "Osasi orava juosta,", "osata, orava, juosta", "to know how, squirrel, to run", "The squirrel knew how to run,", ""),
    ("Matkaella maan ihana.", "Matkailla maan ihana.", "matkailla, maa, ihana", "to travel, land, lovely", "The lovely one of the land to travel.", ""),
    ("Pian juoksi matkan pitkän,", "Pian juoksi matkan pitkän,", "pian, juosta, matka, pitkä", "soon, to run, journey, long", "Soon it ran a long journey,", ""),
    ("Wälehen wälit lyhyet,", "Välehen välit lyhyet,", "väleen, väli, lyhyt", "quickly, gap, short", "Quickly the short gaps,", ""),
    ("Mäen poikki, toisen pitkin,", "Mäen poikki, toisen pitkin,", "mäki, poikki, toinen, pitkin", "hill, across, second, along", "Across one hill, along a second,", ""),
    ("Kolmannen wähän witahan,", "Kolmannen vähän vitahan,", "kolmas, vähän, vita", "third, a little, diagonally", "A little diagonally across a third,", ""),
    ("Mielusahan metsolahan,", "Mieluisaan metsoon,", "mieluisa, metsä", "pleasant, forest", "To the pleasant forest,", ""),
    ("Tarkkahan Tapiolahan.", "Tarkkaan Tapiolaan.", "tarkka, Tapiola", "keen, Tapiola", "To keen Tapiola.", ""),
    ("Siellä on kolme korpikuusta,", "Siellä on kolme korpikuusta,", "siellä, kolme, korpikuusi", "there, three, wilderness spruce", "There are three wilderness spruces,", ""),
    ("Neljä pienoista petäätä,", "Neljä pienoista petäjää,", "neljä, pienoinen, petäjä", "four, small, pine", "Four small pines,", ""),
    ("Nousi puuhun pienosehen,", "Nousi puuhun pienoiseen,", "nousta, puu, pienoinen", "to climb, tree, small", "It climbed a small tree,", ""),
    ("Taiten tarhalatwasehen,", "Taiten tarhalatvaan,", "taitaen, tarhalatva", "skillfully, orchard-top", "Skillfully to the orchard-top,", ""),
    ("Eikä kokko kopraissunna,", "Eikä kokko koprannut,", "ei, kokko, kopata", "not, eagle, to grab", "And the eagle did not seize it,", ""),
    ("Iskenynnä ilman lintu.", "Iskenyt ilman lintu.", "iskeä, ilma, lintu", "to strike, air, bird", "The bird of the air did not strike it.", ""),
    ("Katkasi käpyä kaksi,", "Katkaisi käpyä kaksi,", "katkaista, käpy, kaksi", "to snap off, cone, two", "It snapped off two cones,", ""),
    ("Päitä lehmän leikkaeli,", "Päitä lehmän leikkaili,", "pää, lehmä, leikata", "head, cow(?), to cut", "Cut off cow-head-(shaped pieces)?,", ""),
    ("Käwyt kätki kynsihinsä,", "Kävyt kätki kynsiinsä,", "käpy, kätkeä, kynsi", "cone, to hide, claw", "Hid the cones in its claws,", ""),
    ("Kääräsi käpälehensä,", "Kääräisi käpäleensä,", "käärätä, käpälä", "to wrap, paw", "Wrapped them in its paw,", ""),
    ("Niin kanto kawon kätehen,", "Niin kantoi kavon käteen,", "niin, kantaa, kapo, käsi", "so, to carry, maiden, hand", "So it carried them to the maiden's hand,", ""),
    ("Hywän immen hyppysihin.", "Hyvän immen hyppysiin.", "hyvä, impi, hyppyset", "good, maiden, fingertips", "To the good maiden's fingertips.", ""),
    ("Osmotar oluehensa,", "Osmotar oluehensa,", "Osmotar, olut", "Osmotar, beer", "Osmotar into her beer,", ""),
    ("Kapo pisti kaljahansa,", "Kapo pisti kaljaansa,", "kapo, pistää, kalja", "maiden, to put, small beer", "The maiden put (it) into her small beer,", ""),
    ("Ei ota olut hapata,", "Ei ota olut hapata,", "ei, ottaa, olut, hapata", "not, to take/start, beer, to ferment", "But the beer would not begin to ferment,", "The first magical attempt (pinecones) fails entirely, just as the first identification-guesses by Annikki and Vipunen's curses required multiple attempts before success — establishing a 'rule of three' pattern of repeated, escalating magical trials common to oral epic structure and frequently associated with trickster-tale logic of persistence through failure."),
    ("Eikä nouse nuori juoma.", "Eikä nouse nuori juoma.", "ei, nousta, nuori, juoma", "not, to rise, young, drink", "Nor would the young drink rise.", ""),
    ("Arwelee, ajattelewi,", "Arvelee, ajattelee,", "arvella, ajatella", "to ponder, to think", "Ponders, thinks,", ""),
    ("Mitä tuohon tuotanehe", "Mitä tuohon tuotanehe", "mikä, tuoda", "what, to bring", "What might be brought to that", ""),
    ("Oluelle happameksi,", "Oluelle happameksi,", "olut, happama", "beer, fermenting agent", "As a fermenting agent for the beer,", ""),
    ("Kaljalle kohottimeksi.", "Kaljalle kohottimeksi.", "kalja, kohotin", "small beer, rising agent", "As a rising agent for the small beer.", ""),
    ("Hyw' on tyttö Pohjan neiti,", "Hyvä on tyttö Pohjan neiti,", "hyvä, tyttö, Pohja, neiti", "good, girl, Pohjola, maiden", "Good is the girl, the maiden of Pohjola,", ""),
    ("Aina kengältä kepiä;", "Aina kengältä kepeä;", "aina, kenkä, kepeä", "always, footstep, light", "Always light on her feet;", ""),
    ("Liikku sillan liitoksella,", "Liikkui sillan liitoksella,", "liikkua, silta, liitos", "to move, floor, joint", "She moved at the joint of the floor,", ""),
    ("Laaho keskilattialla,", "Laahoi keskilattialla,", "laahata, keskilattia", "to glide, middle of floor", "Glided across the middle of the floor,", ""),
    ("Yhtä toista toimitteli", "Yhtä toista toimitteli", "yksi, toinen, toimittaa", "one, another, to busy with", "Busied herself with this and that", ""),
    ("Kahen kattilan kesellä,", "Kahden kattilan keskellä,", "kaksi, kattila, keskellä", "two, cauldron, in the middle", "In the midst of two cauldrons,", ""),
    ("Näki lastun lattialla,", "Näki lastun lattialla,", "nähdä, lastu, lattia", "to see, wood-chip, floor", "She saw a wood-chip on the floor,", ""),
    ("Otti lastun lattialta.", "Otti lastun lattialta.", "ottaa, lastu, lattia", "to take, wood-chip, floor", "Took the wood-chip from the floor.", ""),
    ("Katselewi, kääntelewi:", "Katselee, kääntelee:", "katsella, kääntää", "to look, to turn", "Looks at it, turns it over:", ""),
    ("\"Mitä tuostakin tulisi", "\"Mitä tuostakin tulisi", "mikä, tuosta, tulla", "what, from that, to become", "\"What might come of that", ""),
    ("Kawon kaunihin käsissä,", "Kavon kaunihin käsissä,", "kapo, kaunis, käsi", "maiden, beautiful, hand", "In the beautiful maiden's hands,", ""),
    ("Hywän immen hyppysissä?\"", "Hyvän immen hyppysissä?\"", "hyvä, impi, hyppyset", "good, maiden, fingertips", "In the good maiden's fingertips?\"", ""),
    ("Jo kanto kawon kätehen,", "Jo kantoi kavon käteen,", "kantaa, kapo, käsi", "to carry, maiden, hand", "She carried it to the maiden's hand,", ""),
    ("Hywän immen hyppysihin.", "Hyvän immen hyppysiin.", "hyvä, impi, hyppyset", "good, maiden, fingertips", "To the good maiden's fingertips.", ""),
    ("Kapo kaksin kämmeninsä,", "Kapo kaksin kämmeninsä,", "kapo, kaksi, kämmen", "maiden, two, palm", "The maiden with her two palms,", ""),
    ("Hykersi molempinensa,", "Hykersi molemmin puolin,", "hykertää, molemmin", "to rub, both", "Rubbed with both,", ""),
    ("Molempihin reisihinsä;", "Molempiin reisiinsä;", "molemmin, reisi", "both, thigh", "Onto both her thighs;", ""),
    ("Synty näätä kultarinta.", "Syntyi näätä kultarinta.", "syntyä, näätä, kultarinta", "to be born, marten, gold-breast", "A gold-breasted marten was born.", ""),
    ("Niin se neuo nääteänsä,", "Niin se neuvoi näätäänsä,", "niin, neuvoa, näätä", "so, to instruct, marten", "So she instructed her marten,", ""),
    ("Orpolastansa opasti:", "Orpolastansa opasti:", "orpolapsi, opastaa", "orphan child, to guide", "Guided her orphan child:", ""),
    ("\"Näätäseni lintuseni,", "\"Näätäseni lintuseni,", "näätä, lintunen", "marten, little bird", "\"My marten, my little bird,", ""),
    ("Orpolapseni omani!", "Orpolapseni omani!", "orpolapsi, oma", "orphan child, own", "My own orphan child!", ""),
    ("Mene tuonne, kunne käsken,", "Mene tuonne, kunne käsken,", "mennä, tuonne, käskeä", "to go, there, to command", "Go there, where I command,", ""),
    ("Kunne käsken ja kehotan,", "Kunne käsken ja kehotan,", "kunne, käskeä, kehottaa", "to where, to command, to urge", "Where I command and urge you,", ""),
    ("Kontion kiwikololle,", "Kontion kivikololle,", "kontio, kivikolo", "bear, stone-hollow", "To the bear's stone hollow,", ""),
    ("Metsän karhun kartanolle.", "Metsän karhun kartanolle.", "metsä, karhu, kartano", "forest, bear, estate", "To the forest bear's estate.", ""),
    ("Siellä karhut tappelewat,", "Siellä karhut tappelevat,", "siellä, karhu, tapella", "there, bear, to fight", "There bears are fighting,", "The image of bears fighting and foaming at the mouth, with the foam itself becoming the magic fermenting agent, is a wonderfully strange, almost surreal piece of folk-biology — violence transmuted directly into a domestic, celebratory substance (beer), blending savage wilderness imagery with homely craft in a way distinctly characteristic of trickster-adjacent folk magic."),
    ("Kontiot kowin eläwät;", "Kontiot kovin elävät;", "kontio, kovin, eletä", "bear, greatly, to be active/lively", "Bears are very lively;", ""),
    ("Koprin kuonoa kokoa,", "Koprin kuonoa kokoa,", "koura, kuono, koota", "claw/paw, snout, to gather", "Gather the foam from their snouts with your paw,", ""),
    ("Käsin waahtea waluta,", "Käsin vaahtea valuta,", "käsi, vaahti, valuttaa", "hand/paw, foam, to let drip", "Let the foam drip from your paw,", ""),
    ("Se kanna kawon kätehen,", "Se kanna kavon käteen,", "se, kantaa, kapo, käsi", "that, to carry, maiden, hand", "Carry that to the maiden's hand,", ""),
    ("Tuo olalle Osmottaren.\"", "Tuo olalle Osmottaren.\"", "tuoda, olka, Osmotar", "to bring, shoulder, Osmotar", "Bring it to Osmotar's shoulder.\"", ""),
    ("Jopa taisi näätä juosta,", "Jopa taisi näätä juosta,", "jo, taitaa, näätä, juosta", "already, to be able, marten, to run", "The marten indeed could run,", ""),
    ("Kultalintu liihätellä,", "Kultalintu liihätellä,", "kultalintu, liihätellä", "golden bird, to glide swiftly", "The golden bird to glide swiftly,", ""),
    ("Pian juoksi matkan pitkän,", "Pian juoksi matkan pitkän,", "pian, juosta, matka, pitkä", "soon, to run, journey, long", "Soon it ran a long journey,", ""),
    ("Wälehen wälit lyhyet,", "Välehen välit lyhyet,", "väleen, väli, lyhyt", "quickly, gap, short", "Quickly the short gaps,", ""),
    ("Joen poikki, toisen pitkin,", "Joen poikki, toisen pitkin,", "joki, poikki, toinen, pitkin", "river, across, second, along", "Across one river, along a second,", ""),
    ("Kolmannen wähän witahan,", "Kolmannen vähän vitahan,", "kolmas, vähän, vita", "third, a little, diagonally", "A little diagonally across a third,", ""),
    ("Kontion kiwikololle,", "Kontion kivikololle,", "kontio, kivikolo", "bear, stone-hollow", "To the bear's stone hollow,", ""),
    ("Karhun louhi kartanolla.", "Karhun louhikartanolla.", "karhu, louhikartano", "bear, rocky estate", "At the bear's rocky estate.", ""),
    ("Siellä karhut tappelewat,", "Siellä karhut tappelevat,", "siellä, karhu, tapella", "there, bear, to fight", "There bears are fighting,", ""),
    ("Kontiot kowin eläwät,", "Kontiot kovin elävät,", "kontio, kovin, eletä", "bear, greatly, to be active", "Bears are very lively,", ""),
    ("Rautasella kalliolla,", "Rautaisella kalliolla,", "rautainen, kallio", "iron, cliff/rock", "On an iron cliff,", ""),
    ("Wuorella teräksisellä.", "Vuorella teräksisellä.", "vuori, teräksinen", "mountain, steel", "On a steel mountain.", ""),
    ("Juoksi kuona karhun suusta,", "Juoksi kuona karhun suusta,", "juosta, kuona, karhu, suu", "to flow, slag/froth, bear, mouth", "Froth ran from the bear's mouth,", ""),
    ("Waahti kontion kiasta,", "Vaahti kontion kidasta,", "vaahti, kontio, kita", "foam, bear, maw", "Foam from the bear's jaw,", ""),
    ("Koprin kuonoa kokosi,", "Koprin kuonoa kokosi,", "koura, kuono, koota", "paw, snout, to gather", "It gathered the snout's foam with its paw,", ""),
    ("Käsin waahtea walutti,", "Käsin vaahtea valutti,", "käsi, vaahti, valuttaa", "paw, foam, to let drip", "Let the foam drip from its paw,", ""),
    ("Sen kanto kawon kätehen,", "Sen kantoi kavon käteen,", "se, kantaa, kapo, käsi", "that, to carry, maiden, hand", "Carried that to the maiden's hand,", ""),
    ("Hywän immen hyppysihin.", "Hyvän immen hyppysiin.", "hyvä, impi, hyppyset", "good, maiden, fingertips", "To the good maiden's fingertips.", ""),
    ("Osmotar oluehensa,", "Osmotar oluehensa,", "Osmotar, olut", "Osmotar, beer", "Osmotar into her beer,", ""),
    ("Kapo kaato kaljahansa;", "Kapo kaatoi kaljaansa;", "kapo, kaataa, kalja", "maiden, to pour, small beer", "The maiden poured (it) into her small beer;", ""),
    ("Ei ota olut hapata,", "Ei ota olut hapata,", "ei, ottaa, olut, hapata", "not, to take, beer, to ferment", "But the beer would not begin to ferment,", "The second attempt (bear-foam) also fails entirely, building the rule-of-three pattern toward its eventual successful resolution with the bee — escalating from a found object (cone) to violent wilderness foam to finally something genuinely sweet and otherworldly, a structured magical trial sequence."),
    ("Eikä nouse nuori juoma.", "Eikä nouse nuori juoma.", "ei, nousta, nuori, juoma", "not, to rise, young, drink", "Nor would the young drink rise.", ""),
    ("Arwelee, ajattelewi,", "Arvelee, ajattelee,", "arvella, ajatella", "to ponder, to think", "Ponders, thinks,", ""),
    ("Mitä tuohon tuotanehe", "Mitä tuohon tuotanehe", "mikä, tuoda", "what, to bring", "What might be brought to that", ""),
    ("Oluelle happameksi,", "Oluelle happameksi,", "olut, happama", "beer, fermenting agent", "As a fermenting agent for the beer,", ""),
    ("Kaljalle kohottimeksi.", "Kaljalle kohottimeksi.", "kalja, kohotin", "small beer, rising agent", "As a rising agent for the small beer.", ""),
    ("Hyw' on tyttö Pohjan neiti,", "Hyvä on tyttö Pohjan neiti,", "hyvä, tyttö, Pohja, neiti", "good, girl, Pohjola, maiden", "Good is the girl, the maiden of Pohjola,", ""),
    ("Aina kengältä kepiä,", "Aina kengältä kepeä,", "aina, kenkä, kepeä", "always, footstep, light", "Always light on her feet,", ""),
    ("Liikku sillan liitoksella,", "Liikkui sillan liitoksella,", "liikkua, silta, liitos", "to move, floor, joint", "She moved at the joint of the floor,", ""),
    ("Laaho keskilattialla,", "Laahoi keskilattialla,", "laahata, keskilattia", "to glide, middle of floor", "Glided across the middle of the floor,", ""),
    ("Yhtä toista toimitteli", "Yhtä toista toimitteli", "yksi, toinen, toimittaa", "one, another, to busy with", "Busied herself with this and that", ""),
    ("Kahen kattilan kesellä,", "Kahden kattilan keskellä,", "kaksi, kattila, keskellä", "two, cauldron, in the middle", "In the midst of two cauldrons,", ""),
    ("Näki lehen lattialla,", "Näki lehden lattialla,", "nähdä, lehti, lattia", "to see, leaf, floor", "She saw a leaf on the floor,", ""),
    ("Otti lehen lattialta.", "Otti lehden lattialta.", "ottaa, lehti, lattia", "to take, leaf, floor", "Took the leaf from the floor.", ""),
    ("Katselewi, kääntelewi:", "Katselee, kääntelee:", "katsella, kääntää", "to look, to turn", "Looks at it, turns it over:", ""),
    ("\"Mitä tuostakin tulisi", "\"Mitä tuostakin tulisi", "mikä, tuosta, tulla", "what, from that, to become", "\"What might come of that", ""),
    ("Kawon kaunihin käsissä,", "Kavon kaunihin käsissä,", "kapo, kaunis, käsi", "maiden, beautiful, hand", "In the beautiful maiden's hands,", ""),
    ("Hywän immen hyppysissä?\"", "Hyvän immen hyppysissä?\"", "hyvä, impi, hyppyset", "good, maiden, fingertips", "In the good maiden's fingertips?\"", ""),
    ("Jo kanto kawon kätehen,", "Jo kantoi kavon käteen,", "kantaa, kapo, käsi", "to carry, maiden, hand", "She carried it to the maiden's hand,", ""),
    ("Hywän immen hyppysihin.", "Hyvän immen hyppysiin.", "hyvä, impi, hyppyset", "good, maiden, fingertips", "To the good maiden's fingertips.", ""),
    ("Kapo kaksin kämmeninsä,", "Kapo kaksin kämmeninsä,", "kapo, kaksi, kämmen", "maiden, two, palm", "The maiden with her two palms,", ""),
    ("Hykersi molempinensa,", "Hykersi molemmin puolin,", "hykertää, molemmin", "to rub, both", "Rubbed with both,", ""),
    ("Molempihin reisihinsä;", "Molempiin reisiinsä;", "molemmin, reisi", "both, thigh", "Onto both her thighs;", ""),
    ("Synnyttäwi mehiläisen.", "Synnyttää mehiläisen.", "synnyttää, mehiläinen", "to give birth to, bee", "She gave birth to a bee.", ""),
    ("Niin se neuo lintuansa,", "Niin se neuvoi lintuaan,", "niin, neuvoa, lintu", "so, to instruct, bird", "So she instructed her bird,", ""),
    ("Mehiläistänsä opasti:", "Mehiläistänsä opasti:", "mehiläinen, opastaa", "bee, to guide", "Guided her bee:", ""),
    ("\"Mehiläinen lintuseni,", "\"Mehiläinen lintuseni,", "mehiläinen, lintunen", "bee, little bird", "\"Bee, my little bird,", ""),
    ("Orpolapseni omani!", "Orpolapseni omani!", "orpolapsi, oma", "orphan child, own", "My own orphan child!", ""),
    ("Lennä tuonne, kunne käsken,", "Lennä tuonne, kunne käsken,", "lentää, tuonne, käskeä", "to fly, there, to command", "Fly there, where I command,", ""),
    ("Kunne käsken ja kehotan,", "Kunne käsken ja kehotan,", "kunne, käskeä, kehottaa", "to where, to command, to urge", "Where I command and urge you,", ""),
    ("Ylitse meren yheksän,", "Ylitse meren yhdeksän,", "yli, meri, yhdeksän", "over, sea, nine", "Over nine seas,", ""),
    ("Meri puolen kymmenettä.", "Meri puolen kymmenettä.", "meri, puoli, kymmenes", "sea, half, tenth", "Half the tenth sea.", ""),
    ("Tuo simoa siiwissäsi,", "Tuo simaa siivissäsi,", "tuoda, sima, siipi", "to bring, mead, wing", "Bring mead in your wings,", ""),
    ("Kanna mettä kaapussasi,", "Kanna mettä kaavussasi,", "kantaa, mesi, kaapu", "to carry, honey, cloak", "Carry honey in your cloak,", ""),
    ("Helewästä heinän päästä,", "Helevästä heinän päästä,", "helevä, heinä, pää", "sweet/fine, grass, tip", "From the fine tip of the grass,", ""),
    ("Kukan kultasen nenästä;", "Kukan kultaisen nenästä;", "kukka, kultainen, nenä", "flower, golden, tip", "From the tip of the golden flower;", ""),
    ("Ne kanna kawon kätehen,", "Ne kanna kavon käteen,", "ne, kantaa, kapo, käsi", "those, to carry, maiden, hand", "Carry those to the maiden's hand,", ""),
    ("Tuo olalle Osmottaren.\"", "Tuo olalle Osmottaren.\"", "tuoda, olka, Osmotar", "to bring, shoulder, Osmotar", "Bring them to Osmotar's shoulder.\"", ""),
    ("Mehiläinen meiän lintu", "Mehiläinen meidän lintu", "mehiläinen, me, lintu", "bee, our, bird", "The bee, our bird,", ""),
    ("Jopa lenti, jotta joutu,", "Jopa lensi, jotta joutui,", "jo, lentää, joutua", "already, to fly, to hasten", "Already flew, hastening,", ""),
    ("Pian lenti matkan pitkän,", "Pian lensi matkan pitkän,", "pian, lentää, matka, pitkä", "soon, to fly, journey, long", "Soon flew a long journey,", ""),
    ("Wälehen wälit lyhyet,", "Välehen välit lyhyet,", "väleen, väli, lyhyt", "quickly, gap, short", "Quickly the short gaps,", ""),
    ("Meren poikki, toisen pitkin,", "Meren poikki, toisen pitkin,", "meri, poikki, toinen, pitkin", "sea, across, second, along", "Across one sea, along a second,", ""),
    ("Kolmannen wähän witahan,", "Kolmannen vähän vitahan,", "kolmas, vähän, vita", "third, a little, diagonally", "A little diagonally across a third,", ""),
    ("Ylitse meren yheksän,", "Ylitse meren yhdeksän,", "yli, meri, yhdeksän", "over, sea, nine", "Over nine seas,", ""),
    ("Meri puolen kymmenettä,", "Meri puolen kymmenettä,", "meri, puoli, kymmenes", "sea, half, tenth", "Half the tenth sea,", ""),
    ("Tuurin uutehen tupahan,", "Tuurin uuteen tupaan,", "Tuuri (place/figure), uusi, tupa", "Tuuri, new, cabin", "To Tuuri's new cabin,", ""),
    ("Palwosen laettomahan.", "Palvosen laettomaan.", "Palvonen, laeton", "Palvonen, roofless", "To Palvonen's roofless (place).", ""),
    ("Siellä on neiti nukkununna,", "Siellä on neiti nukkunut,", "siellä, neiti, nukkua", "there, maiden, to sleep", "There a maiden has fallen asleep,", "A sleeping enchanted maiden draped in gold and silver, lying amid magical honey-grass in a hidden roofless cabin, is a classic fairy-tale image of an enclosed, otherworldly source of power guarded by sleep and secrecy — the bee must cross nine and a half seas to reach this liminal, dreamlike realm, the same supernatural distance Lemminkäinen's mother once crossed to find healing substances near the moon and sun, linking this magical-source motif across multiple episodes of the epic."),
    ("Wyöwaski walahtununna,", "Vyövaski valahtunut,", "vyövaski, valahtaa", "bronze belt, to slip/sink", "Her bronze belt having slipped,", ""),
    ("Kupehill' on kultaheinä,", "Kupeilla on kultaheinä,", "kupe, kultaheinä", "side, golden grass", "At her sides is golden grass,", ""),
    ("Wyöllähän hopia heinä,", "Vyöllähän hopea heinä,", "vyö, hopea, heinä", "belt, silver, grass", "At her belt is silver grass,", ""),
    ("Siwulla simanen heinä,", "Sivulla simainen heinä,", "sivu, simainen, heinä", "side, mead-like, grass", "At her side is mead-grass,", ""),
    ("Mesiheinä helmassansa.", "Mesiheinä helmassansa.", "mesiheinä, helma", "honey-grass, lap/hem", "Honey-grass in her lap.", ""),
    ("Kasti siipensä simahan,", "Kasti siipensä simaan,", "kastaa, siipi, sima", "to dip, wing, mead", "It dipped its wings in mead,", ""),
    ("Toisen siipensä metehen,", "Toisen siipensä metehen,", "toinen, siipi, mesi", "second, wing, honey", "The other wing in honey,", ""),
    ("Helewähän heinän päähän,", "Helevähän heinän päähän,", "helevä, heinä, pää", "fine, grass, tip", "At the fine tip of the grass,", ""),
    ("Kukan kultasen nenähän.", "Kukan kultaisen nenähän.", "kukka, kultainen, nenä", "flower, golden, tip", "At the tip of the golden flower.", ""),
    ("Toi simoa siiwessänsä,", "Toi simaa siivessänsä,", "tuoda, sima, siipi", "to bring, mead, wing", "It brought mead in its wing,", ""),
    ("Kanto mettä kaapussansa,", "Kantoi mettä kaavussansa,", "kantaa, mesi, kaapu", "to carry, honey, cloak", "Carried honey in its cloak,", ""),
    ("Sen kanto kawon kätehen,", "Sen kantoi kavon käteen,", "se, kantaa, kapo, käsi", "that, to carry, maiden, hand", "Carried that to the maiden's hand,", ""),
    ("Hywän immen hyppysihin.", "Hyvän immen hyppysiin.", "hyvä, impi, hyppyset", "good, maiden, fingertips", "To the good maiden's fingertips.", ""),
    ("Osmotar oluehensa,", "Osmotar oluehensa,", "Osmotar, olut", "Osmotar, beer", "Osmotar into her beer,", ""),
    ("Kapo pisti kaljahansa,", "Kapo pisti kaljaansa,", "kapo, pistää, kalja", "maiden, to put, small beer", "The maiden put it into her small beer,", ""),
    ("Jo otti olut hapata,", "Jo otti olut hapata,", "jo, ottaa, olut, hapata", "now, to take/begin, beer, to ferment", "Now the beer began to ferment,", "Third time succeeds where the first two failed — the simple rule-of-three pattern resolves, and the modest, otherworldly sweetness of mead and honey (rather than violent foam or an inert pinecone) proves to be the magic ingredient, a gentle thematic resolution: true transformation comes from delicate natural sweetness rather than force."),
    ("Jopa nousi nuori juoma,", "Jopa nousi nuori juoma,", "jo, nousta, nuori, juoma", "now, to rise, young, drink", "Now the young drink rose,", ""),
    ("Puisen uuen uurtehessa,", "Puisen uuden uurtehessa,", "puinen, uusi, uurre", "wooden, new, vat", "In the new wooden vat,", ""),
    ("Korwon koiwusen sisässä.", "Korvon koivuisen sisässä.", "korvo, koivuinen", "wooden vessel, birchen", "Inside the birchen vessel.", ""),
    ("Kuohu korwien tasalle,", "Kuohui korvien tasalle,", "kuohua, korva, tasalle", "to foam/boil over, ear, level with", "It foamed level with the ears,", "The beer's dramatic, overflowing fermentation — foaming up to the brim, threatening to spill onto the floor — gives the brew an almost willful, animated character, as though the magic itself is straining for release, fitting the broader pattern of the epic's inanimate or half-animate objects (the bleeding comb, the singing hop-vine) acting with apparent agency."),
    ("Ärjy päälle äprähien,", "Ärjyi päälle äyräiden,", "ärjyä, äyräs", "to roar/surge, brim/edge", "Surged over the brim,", ""),
    ("Tahto maahan tyyräellä,", "Tahtoi maahan tyyrätä,", "tahtoa, maa, tyyrätä", "to want, ground, to spill/steer", "Wanted to spill onto the ground,", ""),
    ("Lattialle lainehella.", "Lattialle laineella.", "lattia, laine", "floor, wave", "Onto the floor in a wave.", ""),
    ("Pantihin olut punanen,", "Pantiin olut punainen,", "panna, olut, punainen", "to put, beer, red", "The red beer was put away,", ""),
    ("Kalja kaunis käytettihin,", "Kalja kaunis käytettiin,", "kalja, kaunis, käyttää", "small beer, beautiful, to use/ferment", "The beautiful small beer was fermented,", ""),
    ("Nassakkahan tammisehen,", "Nassakkaan tammiseen,", "nassakka, tammi", "small keg, oak", "Into an oaken small keg,", ""),
    ("Tynnyrihin pienosehen,", "Tynnyriin pienoiseen,", "tynnyri, pienoinen", "barrel, small", "Into a small barrel,", ""),
    ("Tapin waskisen warahan,", "Tapin vaskisen varahan,", "tappi, vaskinen, vara", "spigot, copper, in care of", "Under the care of a copper spigot,", ""),
    ("Kiwisehen kellarihin.", "Kiviseen kellariin.", "kivinen, kellari", "stone, cellar", "Into a stone cellar.", ""),
    ("Olut tykki tynnyrissä,", "Olut tykki tynnyrissä,", "olut, tykkiä, tynnyri", "beer, to thump/throb, barrel", "The beer thumped in the barrel,", "The beer itself speaks aloud, demanding a singer worthy of it and threatening to burst its own barrel if denied — yet another instance of an inanimate object given voice and will, as well as a darkly comic, almost petulant threat from the brew itself, echoing the trickster-tinged personification seen throughout this runo."),
    ("Kalja keikku kellarissa:", "Kalja keikkui kellarissa:", "kalja, keikkua, kellari", "small beer, to sway/rock, cellar", "The small beer swayed in the cellar:", ""),
    ("\"Kun nyt juojani tulisi,", "\"Kun nyt juojani tulisi,", "kun, nyt, juoja, tulla", "if, now, drinker, to come", "\"If now my drinker would come,", ""),
    ("Lakkiani laitteleisi,", "Lakkiani laittelisi,", "lakki, laitella", "cap/lid, to arrange", "Would arrange my lid,", ""),
    ("Kunnollinen kukkujani,", "Kunnollinen kukkujani,", "kunnollinen, kukkuja", "proper/worthy, cuckoo-caller/singer", "My proper, worthy singer,", ""),
    ("Laaullinen laulajani!\"", "Lauluullinen laulajani!\"", "laulullinen, laulaja", "song-filled, singer", "My song-filled singer!\"", ""),
    ("Etsittihin laulajoa,", "Etsittiin laulajaa,", "etsiä, laulaja", "to search, singer", "A singer was sought,", ""),
    ("Laaullista laulajoa,", "Lauluullista laulajaa,", "laulullinen, laulaja", "song-filled, singer", "A song-filled singer,", ""),
    ("Kunnollista kukkujoa,", "Kunnollista kukkujaa,", "kunnollinen, kukkuja", "worthy, singer", "A worthy singer,", ""),
    ("Kaunista karehtioa.", "Kaunista karehtijaa.", "kaunis, karehtija", "beautiful, singer/entertainer", "A beautiful entertainer.", ""),
    ("Lohi on tuotu laulajaksi,", "Lohi on tuotu laulajaksi,", "lohi, tuoda, laulaja", "salmon, to bring, singer", "A salmon was brought as singer,", "Comically absurd auditions — a salmon, a pike, and a small child are all tried out as the wedding singer before all three are dismissed as unsuitable (the fish for crooked jaws, the child for an unreliable voice) — an episode of escalating, almost slapstick failure before the final correct candidate, structurally mirroring the earlier failed fermentation attempts and reinforcing the rule-of-three trickster-tale pattern across the whole runo."),
    ("Hauki kunnon kukkujaksi;", "Hauki kunnon kukkujaksi;", "hauki, kunto, kukkuja", "pike, worth, singer", "A pike as the worthy singer;", ""),
    ("Ei lohessa laulajoa,", "Ei lohessa laulajaa,", "ei, lohi, laulaja", "not, salmon, singer", "There was no singer in the salmon,", ""),
    ("Kuonasuussa kukkujoa,", "Kuonosuussa kukkujaa,", "kuonosuu, kukkuja", "snout-mouth, singer", "No singer in the snout-mouth,", ""),
    ("Lohen on leuat lonkallahan,", "Lohen on leuat lonkallaan,", "lohi, leuka, lonkka", "salmon, jaw, askew", "The salmon's jaws are askew,", ""),
    ("Hauin hampahat hajalla.", "Hauin hampaat hajalla.", "hauki, hammas, hajalla", "pike, tooth, scattered/apart", "The pike's teeth are scattered apart.", ""),
    ("Etsitähän laulajoa,", "Etsitään laulajaa,", "etsiä, laulaja", "to search, singer", "A singer was sought,", ""),
    ("Laaullista laulajoa,", "Lauluullista laulajaa,", "laulullinen, laulaja", "song-filled, singer", "A song-filled singer,", ""),
    ("Kunnollista kukkujoa,", "Kunnollista kukkujaa,", "kunnollinen, kukkuja", "worthy, singer", "A worthy singer,", ""),
    ("Kaunista karehtioa.", "Kaunista karehtijaa.", "kaunis, karehtija", "beautiful, entertainer", "A beautiful entertainer.", ""),
    ("Laps' on tuotu laulajaksi,", "Lapsi on tuotu laulajaksi,", "lapsi, tuoda, laulaja", "child, to bring, singer", "A child was brought as singer,", ""),
    ("Poika kunnon kukkujaksi;", "Poika kunnon kukkujaksi;", "poika, kunto, kukkuja", "boy, worth, singer", "A boy as the worthy singer;", ""),
    ("Ei lapsessa laulajoa,", "Ei lapsessa laulajaa,", "ei, lapsi, laulaja", "not, child, singer", "There was no singer in the child,", ""),
    ("Kuolasuussa kukkujoa,", "Kuolasuussa kukkujaa,", "kuolasuu, kukkuja", "drool-mouth, singer", "No singer in the drooling mouth,", ""),
    ("Ääni on lapsen langennunna,", "Äänin on lapsen langennut,", "ääni, lapsi, langeta", "voice, child, to fail/fall", "The child's voice has failed,", ""),
    ("Puhet suuhun puuttununna.", "Puheet suuhun puuttunut.", "puhe, suu, puuttua", "speech, mouth, to be stuck", "The speech is stuck in his mouth.", ""),
    ("Niin sano olut punanen,", "Niin sanoi olut punainen,", "niin, sanoa, olut, punainen", "so, to say, beer, red", "So said the red beer,", ""),
    ("Noitueli nuori juoma,", "Noitueli nuori juoma,", "noituilla, nuori, juoma", "to mutter/curse, young, drink", "The young drink muttered as if cursing,", ""),
    ("Nassakassa tammisessa,", "Nassakassa tammisessa,", "nassakka, tammi", "keg, oak", "In the oaken keg,", ""),
    ("Tapin waskisen takana:", "Tapin vaskisen takana:", "tappi, vaskinen, takana", "spigot, copper, behind", "Behind the copper spigot:", ""),
    ("\"Kun ei tuoa laulajoa,", "\"Kun ei tuoda laulajaa,", "kun, ei, tuoda, laulaja", "if, not, to bring, singer", "\"If a singer is not brought,", "The beer's final, explicit threat to break its own hoops and pour itself out if not given a proper singer is the climax of its personified agency throughout the runo — an inanimate substance issuing an ultimatum is among the most overtly trickster-like, willful behaviors of any object in the text, demanding the correct ritual response or it will sabotage the entire feast."),
    ("Laaullista laulajoa,", "Lauluullista laulajaa,", "laulullinen, laulaja", "song-filled, singer", "A song-filled singer,", ""),
    ("Kunnollista kukkujoa,", "Kunnollista kukkujaa,", "kunnollinen, kukkuja", "worthy, singer", "A worthy singer,", ""),
    ("Kaunista karehtioa,", "Kaunista karehtijaa,", "kaunis, karehtija", "beautiful, entertainer", "A beautiful entertainer,", ""),
    ("Potkin poikki wanteheni,", "Potkin poikki vanteheni,", "potkia, poikki, vanne", "to kick, in two, hoop", "I will kick my hoops in two,", ""),
    ("Ulos pohjani porotan.\"", "Ulos pohjani porotan.\"", "ulos, pohja, porottaa", "out, bottom, to thrust/burst", "I will burst my bottom out.\"", ""),
    ("Sillon Pohjolan emäntä", "Silloin Pohjolan emäntä", "silloin, Pohjola, emäntä", "then, Pohjola, mistress", "Then the mistress of Pohjola", ""),
    ("Pani kutsut kulkemahan,", "Pani kutsut kulkemaan,", "panna, kutsu, kulkea", "to send, invitation, to travel", "Sent invitations out,", ""),
    ("Itse tuon sanoiksi wirkki:", "Itse tuon sanoiksi virkki:", "itse, tuo, sana, virkata", "herself, that, word, to utter", "Herself uttered these words:", ""),
    ("\"Ohoh piika pikkarainen,", "\"Ohoh piika pikkarainen,", "ohoh, piika, pikkarainen", "oh, maid, little", "\"Oh little maid,", ""),
    ("Orjani alinomanen.", "Orjani alinomainen.", "orja, alinomainen", "slave/servant, constant", "My ever-constant servant.", ""),
    ("Kutsu rahwasta kokohon,", "Kutsu rahvasta kokoon,", "kutsua, rahvas, koolle", "to invite, common folk, together", "Invite the common folk together,", ""),
    ("Miesten joukko juominkihin;", "Miesten joukko juomingeihin;", "mies, joukko, juominki", "man, crowd, drinking-feast", "A crowd of men to the drinking-feast;", ""),
    ("Kutsu köyhät, kutsu kurjat,", "Kutsu köyhät, kutsu kurjat,", "kutsua, köyhä, kurja", "to invite, poor, wretched", "Invite the poor, invite the wretched,", ""),
    ("Kutsu rujot, kutsu rammat,", "Kutsu rujot, kutsu rammat,", "kutsua, rujo, rampa", "to invite, crippled, lame", "Invite the crippled, invite the lame,", ""),
    ("Rujot rein reutuellos,", "Rujot rein reuhtoele,", "rujo, reki, reuhtoa", "crippled, sleigh, to haul along", "Haul the crippled along by sleigh,", ""),
    ("Rammat ratsahin ajellos,", "Rammat ratsahin ajele,", "rampa, ratsas, ajaa", "lame, riding-horse, to drive", "Drive the lame by riding-horse,", ""),
    ("Sokiat wenehin soua.", "Sokeat venehin soua.", "sokea, vene, soutaa", "blind, boat, to row", "Row the blind by boat.", "The mistress's instruction to deliberately exclude only Lemminkäinen — naming and warning against him specifically as a known troublemaker ('aina torassa' — always quarreling) — while inviting every other marginalized and disadvantaged person in the realm sets up the entire premise for the next conflict: the trickster figure pointedly excluded from a feast, a classic trigger for trickster-tale retaliation and chaos."),
    ("Kutsu wanha Wäinämöinen", "Kutsu vanha Väinämöinen", "kutsua, vanha, Väinämöinen", "to invite, old, Väinämöinen", "Invite old Väinämöinen", ""),
    ("Lailliseksi laulajaksi,", "Lailliseksi laulajaksi,", "laillinen, laulaja", "lawful/proper, singer", "As the proper singer,", ""),
    ("Elä kutsu Kaukomieltä,", "Älä kutsu Kaukomieltä,", "älä, kutsua, kaukomieli", "do not, to invite, far-mind", "Do not invite the Far-minded one,", ""),
    ("Elä lieto Lemminkäistä,", "Älä lieto Lemminkäistä,", "älä, lieto, Lemminkäinen", "do not, carefree, Lemminkäinen", "Do not invite carefree Lemminkäinen,", ""),
    ("Se on lieto Lemminkäinen", "Se on lieto Lemminkäinen", "se, lieto, Lemminkäinen", "he, carefree, Lemminkäinen", "That carefree Lemminkäinen", ""),
    ("Ahti ainaki torasa.\"", "Ahti ainaki torassa.\"", "Ahti, aina, tora", "Ahti (Lemminkäinen's other name), always, quarrel", "Ahti is always in a quarrel.\"", ""),
    ("Orja tuon sanoiksi wirkki,", "Orja tuon sanoiksi virkki,", "orja, tuo, sana, virkata", "servant, that, word, to utter", "The servant uttered these words,", ""),
    ("Kysytteli, lausutteli:", "Kysytteli, lausutteli:", "kysytellä, lausutella", "to keep asking, to keep saying", "Kept asking, kept saying:", ""),
    ("\"Mistä tunnen Kaukomielen,", "\"Mistä tunnen Kaukomielen,", "mistä, tuntea, kaukomieli", "from where, to recognize, far-mind", "\"From what do I recognize the Far-minded one,", ""),
    ("Kusta lieto Lemminkäisen?", "Kusta lieto Lemminkäisen?", "kusta, lieto, Lemminkäinen", "from where, carefree, Lemminkäinen", "From what carefree Lemminkäinen?", ""),
    ("En tieä Ahin kotia,", "En tiedä Ahin kotia,", "ei, tietää, Ahti, koti", "not, to know, Ahti, home", "I do not know Ahti's home,", ""),
    ("Kaukomielen kartanoa.\"", "Kaukomielen kartanoa.\"", "kaukomieli, kartano", "far-mind, estate", "The Far-minded one's estate.\"", ""),
    ("Sano Pohjolan emäntä:", "Sanoi Pohjolan emäntä:", "sanoa, Pohjola, emäntä", "to say, Pohjola, mistress", "Said the mistress of Pohjola:", ""),
    ("\"Hywin tunnet Kaukomielen;", "\"Hyvin tunnet Kaukomielen;", "hyvin, tuntea, kaukomieli", "well, to recognize, far-mind", "\"You will recognize the Far-minded one well;", "The mistress's detailed, almost mocking physical description of Lemminkäinen — a crooked eye, a long jaw, a slightly twisted mouth, a snub nose — reduces the trickster hero to a set of comic physical flaws, a verbal caricature that both identifies him and subtly belittles him even as she takes pains to exclude him from her feast."),
    ("Ahti saarella asuwi,", "Ahti saarella asuu,", "Ahti, saari, asua", "Ahti, island, to live", "Ahti lives on an island,", ""),
    ("Weitikkä wesien luona,", "Weitikka vesien luona,", "weitikka, vesi", "rascal, water", "The rascal by the waters,", ""),
    ("Laajimman lahen kohalla", "Laajimman lahden kohalla", "laajin, lahti, kohalla", "widest, bay, at the spot of", "At the spot of the widest bay,", ""),
    ("Kaukoniemen kainalossa.", "Kaukoniemen kainalossa.", "Kaukoniemi, kainalo", "Kaukoniemi (place), armpit/nook", "In the nook of Kaukoniemi.", ""),
    ("Kaukomielen silmä karsas,", "Kaukomielen silmä karsas,", "kaukomieli, silmä, karsas", "far-mind, eye, crooked/squinting", "The Far-minded one's eye is crooked,", ""),
    ("Leuka pitkä Lemminkäisen,", "Leuka pitkä Lemminkäisen,", "leuka, pitkä, Lemminkäinen", "jaw, long, Lemminkäinen", "Lemminkäinen's jaw is long,", ""),
    ("Ahin suu wähiten wäärä,", "Ahin suu vähäisen vääristynyt,", "Ahti, suu, vähäisen, vääristyä", "Ahti, mouth, slightly, to be crooked", "Ahti's mouth is slightly crooked,", ""),
    ("Nenä weitikän nykerä.\"", "Nenä weitikän nykerä.\"", "nenä, weitikka, nykerä", "nose, rascal, snub/stubby", "The rascal's nose is stubby.\"", ""),
    ("Tuopa piika pikkarainen,", "Tuopa piika pikkarainen,", "tuo, piika, pikkarainen", "that, maid, little", "That little maid,", ""),
    ("Raataja rahan alanen,", "Raataja rahan alainen,", "raataja, raha, alainen", "toiler/laborer, money, subject to", "The toiler subject to wages,", ""),
    ("Kutsu rahwahan kokohon,", "Kutsui rahvaan kokoon,", "kutsua, rahvas, koolle", "to invite, common folk, together", "Invited the common folk together,", ""),
    ("Miesten joukon juominkihin;", "Miesten joukon juomingeihin;", "mies, joukko, juominki", "man, crowd, drinking-feast", "A crowd of men to the drinking-feast;", ""),
    ("Kutsu kurjat, kutsu köyhät,", "Kutsui kurjat, kutsui köyhät,", "kutsua, kurja, köyhä", "to invite, wretched, poor", "Invited the wretched, invited the poor,", ""),
    ("Kutsu rujot, kutsu rammat,", "Kutsui rujot, kutsui rammat,", "kutsua, rujo, rampa", "to invite, crippled, lame", "Invited the crippled, invited the lame,", ""),
    ("Rujot rein reutueli,", "Rujot rein reuhtoeli,", "rujo, reki, reuhtoa", "crippled, sleigh, to haul along", "Hauled the crippled along by sleigh,", ""),
    ("Rammat ratsahin ajeli,", "Rammat ratsahin ajeli,", "rampa, ratsas, ajaa", "lame, riding-horse, to drive", "Drove the lame by riding-horse,", ""),
    ("Sokiat wenehin souti.", "Sokeat venehin souti.", "sokea, vene, soutaa", "blind, boat, to row", "Rowed the blind by boat.", ""),
    ("Kutsu wanhan Wäinämöisen,", "Kutsui vanhan Väinämöisen,", "kutsua, vanha, Väinämöinen", "to invite, old, Väinämöinen", "Invited old Väinämöinen,", ""),
    ("Laulajan iänikuisen;", "Laulajan iänikuisen;", "laulaja, iänikuinen", "singer, eternal", "The eternal singer;", ""),
    ("Se on kaunis Kaukomieli,", "Se on kaunis Kaukomieli,", "se, kaunis, kaukomieli", "he, beautiful, far-mind", "That handsome Far-minded one,", "The runo ends on a deliberate, pointed exclusion — the servant carries out her mistress's order to the letter, leaving out only the trickster Lemminkäinen by name. This calculated snub of the one guest most prone to mischief and quarreling is a classic trickster-tale setup: the excluded trickster figure now has every motive for the disruptive revenge his exclusion all but guarantees in the episodes that follow."),
    ("Senp' on heitti kutsumatta.", "Sen on heitti kutsumatta.", "se, jättää, kutsuma", "him, to leave, inviting", "Him she left without an invitation.", ""),
]

data_font = Font(name="Arial", size=10)
wrap_align = Alignment(wrap_text=True, vertical="top")
trickster_fill = PatternFill("solid", start_color="FFF2CC")

for row_idx, verse in enumerate(verses, 2):
    has_trickster = bool(verse[5])
    for col_idx, val in enumerate(verse, 1):
        cell = ws.cell(row=row_idx, column=col_idx, value=val)
        cell.font = data_font
        cell.alignment = wrap_align
        if has_trickster:
            cell.fill = trickster_fill

col_widths = [40, 40, 45, 55, 55, 75]
for col_idx, width in enumerate(col_widths, 1):
    ws.column_dimensions[get_column_letter(col_idx)].width = width

ws.row_dimensions[1].height = 30
ws.freeze_panes = "A2"

thin = Side(style='thin', color="CCCCCC")
border = Border(left=thin, right=thin, top=thin, bottom=thin)
for row in ws.iter_rows(min_row=1, max_row=len(verses)+1, min_col=1, max_col=6):
    for cell in row:
        cell.border = border

wb.save("/mnt/user-data/outputs/kalevala_wedding_brewing.xlsx")
print(f"Done. {len(verses)} verses processed.")
