from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

wb = Workbook()
ws = wb.active
ws.title = "Runo 10"

headers = ["A: Alkuperäinen säe", "B: Modernilla suomella", "C: Perusmuodot", "D: Käännökset (perusmuodot)", "E: Englanninkielinen käännös", "F: Trickster-huomioita"]
header_font = Font(name="Arial", bold=True, color="FFFFFF", size=11)
header_fill = PatternFill("solid", start_color="2E4057")
for col, h in enumerate(headers, 1):
    cell = ws.cell(row=1, column=col, value=h)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

verses = [
    ("Waka wanha Wäinämöinen,", "Vakaa vanha Väinämöinen,", "vakaa, vanha, Väinämöinen", "steady, old, Väinämöinen", "Steady old Väinämöinen,", ""),
    ("Kun ei saanunna sanoja", "Kun ei saanut sanoja", "kun, ei, saada, sana", "when, not, to get, word", "When he had not gotten words", ""),
    ("Tuolta Tuonelan koista,", "Tuolta Tuonelan kodista,", "tuolta, Tuonela, koti", "from there, Tuonela, home", "From there, from the home of Tuonela,", ""),
    ("Manalan ikimajasta,", "Manalan ikimajasta,", "Manala, ikimaja", "Manala, eternal dwelling", "From Manala's eternal dwelling,", ""),
    ("Ain' yhtä ajattelewi,", "Aina yhtä ajattelee,", "aina, yksi, ajatella", "always, one, to think", "Always thinks the same thing,", ""),
    ("Pitkin päätänsä pitäwi,", "Pitkin päätänsä pitää,", "pitkin, pää, pitää", "along, head, to hold/keep", "Keeps it running through his head,", ""),
    ("Mistäpä sanoja saisi,", "Mistäpä sanoja saisi,", "mistä, sana, saada", "from where, word, to get", "From where he might get words,", ""),
    ("Loisi lempiluottehia.", "Loisi lempiluotteja.", "luoda, lempi, luote", "to create, beloved, charm", "Might create beloved charms.", ""),
    ("Sanan wirkko, noin nimesi:", "Sanan virkko, noin nimesi:", "sana, virkata, niin, nimetä", "word, to utter, so, to name", "He uttered a word, named it so:", ""),
    ("\"Tuolla oisi sata sanoa,", "\"Tuolla olisi sata sanaa,", "tuolla, olla, sata, sana", "there, to be, hundred, word", "\"There would be a hundred words,", "Väinämöinen identifies a giant, Antero Vipunen, as the ultimate hoard of magic words — knowledge held in the body of an ancient, sleeping being. Seeking forbidden or hidden knowledge from a reluctant or dangerous source is a recurring trickster-quest motif."),
    ("Tuhat wirren tutkelmusta,", "Tuhat virren tutkelmusta,", "tuhat, virsi, tutkelmus", "thousand, hymn, fragment", "A thousand fragments of song,", ""),
    ("Suussa Antero Wipusen,", "Suussa Antero Vipusen,", "suu, Antero Vipunen", "mouth, Antero Vipunen", "In the mouth of Antero Vipunen,", ""),
    ("Watsassa wanhan Kalewan.", "Vatsassa vanhan Kalevan.", "vatsa, vanha, Kaleva", "stomach, old, Kaleva", "In the stomach of old Kaleva.", ""),
    ("Sinne on matka mentäwätä,", "Sinne on matka mentävää,", "sinne, matka, mennä", "there, journey, to go", "There is a journey to be made,", ""),
    ("Polku poimeteltawata,", "Polku poimeteltavaa,", "polku, poimetella", "path, to pick one's way along", "A path to pick one's way along,", ""),
    ("Seki matkoa pahinta;", "Sekin matkaa pahinta;", "se, matka, pahin", "that, journey, worst", "And that the worst of journeys;", ""),
    ("Yks on juoni juostakseni", "Yksi on juoni juostakseni", "yksi, juoni, juosta", "one, line/path, to run", "One is the line I must run", ""),
    ("Naisten neulojen neniä;", "Naisten neulojen neniä;", "naisten, neula, nenä", "women's, needle, tip/point", "The points of women's needles;", ""),
    ("Juoni toinen juostakseni", "Juoni toinen juostakseni", "juoni, toinen, juosta", "line, second, to run", "A second line I must run", ""),
    ("Miehen miekan tutkamia;", "Miehen miekan tutkamia;", "mies, miekka, tutkain", "man, sword, point/tip", "The points of men's swords;", ""),
    ("Kolmas juoni juostakseni", "Kolmas juoni juostakseni", "kolmas, juoni, juosta", "third, line, to run", "A third line I must run", ""),
    ("Uron tapparan teriä.\"", "Uron tapparan teriä.\"", "uros, tappara, terä", "hero, battle-axe, blade", "The blades of heroes' battle-axes.\"", ""),
    ("Lähteä luku tulewi,", "Lähteä luku tulee,", "lähteä, luku, tulla", "to leave, count/idea, to come", "The thought of leaving comes,", ""),
    ("Toinen käyä kelpoawi,", "Toinen käydä kelpaa,", "toinen, käydä, kelvata", "second, to go, to be fit/suitable", "And going there seems fitting,", ""),
    ("Kun on muienki kasakan", "Kun on muidenkin kasakan", "kun, muu, kasakka", "when, other, hired hand/servant", "Since others too, hired hands,", ""),
    ("Eli orjan palkollisen.", "Eli orjan palkollisen.", "eli, orja, palkollinen", "or, slave, servant/laborer", "Or a slave's laborer (would go).", ""),
    ("Meni sepponsa pajahan,", "Meni seppojensa pajaan,", "mennä, seppo, paja", "to go, smith, forge", "He went to his smith's forge,", ""),
    ("Sanowi sanalla tuolla:", "Sanoi sanalla tuolla:", "sanoa, sana, tuo", "to say, word, that", "Said with that word:", ""),
    ("\"Ohoh seppo Ilmarinen.", "\"Ohoh seppo Ilmarinen.", "ohoh, seppo, Ilmarinen", "oh, smith, Ilmarinen", "\"Oh smith Ilmarinen.", ""),
    ("Taos rautaset talukset,", "Taotko rautaiset talukset,", "taoa, rautainen, talus", "to forge, iron, footwear/shoe", "Forge iron footwear,", "Väinämöinen has himself fully armored in iron by the smith before his quest — a calculated, almost trickster-like preparation, arming himself with deception-proof protection before facing an unpredictable and dangerous source of knowledge."),
    ("Tao rauta rukkasetki,", "Tao rautaiset rukkasetkin,", "taoa, rautainen, rukkaset", "to forge, iron, mitten", "Forge iron mittens too,", ""),
    ("Paita rautanen rakenna,", "Paita rautainen rakenna,", "paita, rautainen, rakentaa", "shirt, iron, to build/make", "Build an iron shirt,", ""),
    ("Laai rautanen korento,", "Laadi rautainen korento,", "laatia, rautainen, korento", "to make, iron, pole/staff", "Make an iron staff,", ""),
    ("Teräksinen tienaellos,", "Teräksinen tienaa,", "teräksinen, tienata", "steel, to earn/forge (make)", "A steel one to forge for the journey,", ""),
    ("Tao syämehen teräkset,", "Tao sydämeen teräkset,", "taoa, sydän, teräs", "to forge, heart/core, steel", "Forge steel into its core,", ""),
    ("Weä päälle melto rauta;", "Vedä päälle pehmeä rauta;", "vetää, päälle, pehmeä, rauta", "to draw, over, soft, iron", "Draw soft iron over it;", ""),
    ("Lähen saamahan sanoja,", "Lähden saamaan sanoja,", "lähteä, saada, sana", "to leave, to get, word", "I am setting off to get words,", ""),
    ("Onkelmoita ottamahan,", "Onkelmoita ottamaan,", "onkelma, ottaa", "fishing-find, to take", "To take fishing-finds,", ""),
    ("Watsasta wanhan Kalewan,", "Vatsasta vanhan Kalevan,", "vatsa, vanha, Kaleva", "stomach, old, Kaleva", "From the stomach of old Kaleva,", ""),
    ("Suusta Antero Wipusen.\"", "Suusta Antero Vipusen.\"", "suu, Antero Vipunen", "mouth, Antero Vipunen", "From the mouth of Antero Vipunen.\"", ""),
    ("Sano seppo Ilmarinen", "Sanoi seppo Ilmarinen", "sanoa, seppo, Ilmarinen", "to say, smith, Ilmarinen", "Said smith Ilmarinen", ""),
    ("\"Wiikon on Wipunen kuollut,", "\"Viikon on Vipunen kuollut,", "viikko, Vipunen, kuolla", "week, Vipunen, to die", "\"Vipunen has been dead a week,", ""),
    ("Kalewa kaonnut kauan,", "Kaleva kadonnut kauan,", "Kaleva, kadota, kauan", "Kaleva, to disappear, long", "Kaleva has long since vanished,", ""),
    ("Wipunsa wirittämästä,", "Vipunsa virittämästä,", "vipu, virittää", "trap/snare, to set", "From setting his snare,", ""),
    ("Ahtamasta ansatiensä;", "Ahtamasta ansatiensä;", "ahtaa, ansatie", "to pack/cram, trap-path", "From packing his trap-path tight;", ""),
    ("Et sieltä sanoa saane,", "Et sieltä sanaa saa,", "ei, sieltä, sana, saada", "not, from there, word, to get", "You will not get a word from there,", ""),
    ("Et sanoa puoltakana.\"", "Et sanaa puoltakaan.\"", "ei, sana, puoli", "not, word, half", "Not even half a word.\"", ""),
    ("Waka wanha Wäinämöinen", "Vakaa vanha Väinämöinen", "vakaa, vanha, Väinämöinen", "steady, old, Väinämöinen", "Steady old Väinämöinen", ""),
    ("Toki läksi, ei totellut,", "Toki lähti, ei totellut,", "toki, lähteä, ei, totella", "yet, to leave, not, to obey", "Yet set off, did not heed the warning,", "Just as Lemminkäinen ignored his mother's warnings before, Väinämöinen ignores the smith's explicit warning that the quest is hopeless — a recurring pattern in the Kalevala of trickster-adjacent heroes disregarding sound advice in pursuit of their goal."),
    ("Astu päiwän helkytteli", "Astui päivän helkytteli", "astua, päivä, helkyttää", "to walk, day, to make ring/clink", "Walked a day, made (the needles) ring,", ""),
    ("Naisten neulojen neniä,", "Naisten neulojen neniä,", "naisten, neula, nenä", "women's, needle, point", "The points of women's needles,", ""),
    ("Astu toisen torkutteli", "Astui toisen torkutteli", "astua, toinen, torkutella", "to walk, second, to make nod/sway", "Walked a second, made (the swords) sway,", ""),
    ("Miesten miekan tutkamia,", "Miesten miekan tutkamia,", "miesten, miekka, tutkain", "men's, sword, point", "The points of men's swords,", ""),
    ("Kolmanenki keikutteli", "Kolmannenkin keikutteli", "kolmas, keikutella", "third, to make tilt/sway", "A third too, made (the axes) sway,", ""),
    ("Uron tapparan teriä.", "Uron tapparan teriä.", "uros, tappara, terä", "hero, battle-axe, blade", "The blades of heroes' battle-axes.", ""),
    ("Itse wirsikäs Wipunen", "Itse virsikäs Vipunen", "itse, virsikäs, Vipunen", "himself, song-filled, Vipunen", "Himself the song-filled Vipunen", ""),
    ("Jo oli wiikon maassa maannut,", "Jo oli viikon maassa maannut,", "jo, olla, viikko, maa, maata", "already, to be, week, ground, to lie", "Had already lain in the ground a week,", ""),
    ("Kauan lentossa lewännyt;", "Kauan lennossa levännyt;", "kauan, lento, levätä", "long, flight (of time), to rest", "Had long rested in passing time;", ""),
    ("Haapa kaswo hartioilta,", "Haapa kasvoi hartioilta,", "haapa, kasvaa, hartia", "aspen, to grow, shoulder", "An aspen grew from his shoulders,", "Vipunen has become so overgrown with trees that he is indistinguishable from the landscape — Väinämöinen literally chops down a forest growing on a sleeping giant before realizing what he has found, a darkly comic misrecognition typical of trickster-tale blunders."),
    ("Koiwu kulmilla yleni,", "Koivu kulmilla yleni,", "koivu, kulma, yletä", "birch, brow/temple, to rise", "A birch rose at his brow,", ""),
    ("Leppä leukaluun nenästä,", "Leppä leukaluun nenästä,", "leppä, leukaluu, nenä", "alder, jawbone, tip", "An alder from the tip of his jawbone,", ""),
    ("Pajupehko parran alta,", "Pajupensas parran alta,", "pajupensas, parta", "willow bush, beard", "A willow bush from under his beard,", ""),
    ("Otsasta orawikuusi,", "Otsasta oravikuusi,", "otsa, oravikuusi", "forehead, squirrel-spruce", "A squirrel-spruce from his forehead,", ""),
    ("Hawu honka hampahilta,", "Havu honka hampailta,", "havu, honka, hammas", "fir-needle, pine, tooth", "A needled pine from his teeth,", ""),
    ("Jaloilta jalo petäjä.", "Jaloilta jalo petäjä.", "jalka, jalo, petäjä", "foot/leg, noble, pine", "A noble pine from his feet.", ""),
    ("Jo tulewi Wäinämöinen,", "Jo tulee Väinämöinen,", "jo, tulla, Väinämöinen", "already, to come, Väinämöinen", "Now Väinämöinen comes,", ""),
    ("Kaato haawan hartioilta,", "Kaatoi haavan hartioilta,", "kaataa, haapa, hartia", "to fell, aspen, shoulder", "Felled the aspen from his shoulders,", ""),
    ("Koiwun kulmilta kukisti,", "Koivun kulmilta kukisti,", "koivu, kulma, kukistaa", "birch, brow, to topple", "Toppled the birch from his brow,", ""),
    ("Leuoilta lepän lewiän,", "Leuoilta lepän leveän,", "leuka, leppä, leveä", "jaw, alder, broad/wide", "The broad alder from his jaw,", ""),
    ("Pajupehkon parran alta,", "Pajupensaan parran alta,", "pajupensas, parta", "willow bush, beard", "The willow bush from under his beard,", ""),
    ("Hakko hongan hampahilta,", "Hakkasi hongan hampailta,", "hakata, honka, hammas", "to chop, pine, tooth", "Chopped the pine from his teeth,", ""),
    ("Kuusen otsalta kumosi,", "Kuusen otsalta kumosi,", "kuusi, otsa, kumota", "spruce, forehead, to topple", "Toppled the spruce from his forehead,", ""),
    ("Penko pensiän petäjän.", "Penkoi pensiän petäjän.", "penkoa, pensiä, petäjä", "to dig up/root out, bushy, pine", "Rooted out the bushy pine.", ""),
    ("Syöksi rautasen korennon", "Syöksi rautaisen korennon", "syöstä, rautainen, korento", "to thrust, iron, staff/pole", "He thrust the iron staff", ""),
    ("Ikenihin irjuwihin,", "Ikeniin irvistäviin,", "ikenet, irvistää", "gums, to grimace/gape", "Into the gaping gums,", ""),
    ("Leukohin lotisewihin.", "Leukoihin lotiseviin.", "leuka, lotista", "jaw, to flap/clatter", "Into the clattering jaws.", "Väinämöinen actively provokes Vipunen by jamming an iron pole into his mouth — an aggressive, almost taunting act of waking the sleeping giant, deliberately courting danger to extract knowledge by force."),
    ("Tuosta wirsikäs Wipunen", "Tuosta virsikäs Vipunen", "tuosta, virsikäs, Vipunen", "from that, song-filled, Vipunen", "From that the song-filled Vipunen", ""),
    ("Heti herkesi unesta,", "Heti heräsi unesta,", "heti, herätä, uni", "immediately, to wake, sleep", "Immediately woke from sleep,", ""),
    ("Tunsi koskewan kowasti,", "Tunsi koskevan kovasti,", "tuntea, koskea, kovasti", "to feel, to touch/hurt, hard", "Felt it hurting badly,", ""),
    ("Kipiästi kiusasewan.", "Kipeästi kiusaavan.", "kipeästi, kiusata", "painfully, to torment", "Painfully tormenting him.", ""),
    ("Puri päältä mellon rauan,", "Puri päältä pehmeän raudan,", "purra, päältä, pehmeä, rauta", "to bite, from on top, soft, iron", "He bit through the soft iron on top,", ""),
    ("Päältä rautasen korennon,", "Päältä rautaisen korennon,", "päältä, rautainen, korento", "from on top, iron, staff", "Through the top of the iron staff,", ""),
    ("Ei tiennyt terästä purra,", "Ei tiennyt terästä purra,", "ei, tietää, teräs, purra", "not, to know, steel, to bite", "But did not know to bite through the steel,", ""),
    ("Ei syöä rauan syäntä.", "Ei syödä rauan sydäntä.", "ei, syödä, rauta, sydän", "not, to eat, iron, core/heart", "Did not eat through the iron's core.", "The trick of forging a soft iron exterior over a steel core is the technical key to the whole episode — Vipunen bites through the outer layer but cannot penetrate the hidden steel, exactly as Väinämöinen and the smith planned. A literal trick weapon."),
    ("Auko suunsa suuremmaksi,", "Avasi suunsa suuremmaksi,", "avata, suu, suurempi", "to open, mouth, bigger", "He opened his mouth wider,", ""),
    ("Leukapielensä lewitti,", "Leukapielensä levitti,", "leukapieli, levittää", "jaw-corner, to spread", "Spread his jaw-corners,", ""),
    ("Nielläksensä Wäinämöistä.", "Nielläkseen Väinämöisen.", "nielläkseen, Väinämöinen", "to swallow, Väinämöinen", "To swallow Väinämöinen.", ""),
    ("Siitä wanha Wäinämöinen", "Siitä vanha Väinämöinen", "siitä, vanha, Väinämöinen", "from there, old, Väinämöinen", "Then old Väinämöinen", ""),
    ("Saip' on suuhun suuritieon,", "Sai on suuhun suuritiedon,", "saada, suu, suuritieto", "to get, mouth, great-knowledge (one)", "Got into the mouth of the great-knowing one,", "Far from resisting being swallowed, Väinämöinen seizes the opportunity, sliding directly into the giant's stomach — turning what looks like defeat (being eaten) into the very means of achieving his goal. This deliberate embrace of apparent catastrophe as a tactic is a hallmark trickster reversal."),
    ("Watsahan warawäkewän;", "Vatsaan varavoimakkaan;", "vatsa, varavoimakas", "stomach, powerfully-built", "Into the powerfully-built one's stomach;", ""),
    ("Wiikon kielellä wiruwi,", "Viikon kielellä viruu,", "viikko, kieli, virua", "week, tongue, to lie/rest", "He lies a week on the tongue,", ""),
    ("Keruksissa kellehtiwi,", "Keruksissa kellehtii,", "kerus, kellehtiä", "jaw/cheek-pouch, to roll/sway", "Rolls in the cheek-pouches,", ""),
    ("Siitä watsahan walahti.", "Siitä vatsaan valahti.", "siitä, vatsa, valahtaa", "from there, stomach, to slip/slide", "Then slid into the stomach.", ""),
    ("Pani paitansa pajaksi,", "Pani paitansa pajaksi,", "panna, paita, paja", "to put/turn, shirt, forge", "He turned his shirt into a forge,", "Inside the giant's belly, Väinämöinen builds an entire improvised smithy from his own clothing — shirt as forge, sleeves as bellows, trousers as chimney — and begins hammering, turning his own body and garments into tools of cunning craft. A wonderfully inventive, resourceful trickster transformation of ordinary objects into magical instruments."),
    ("Hiat paian palkeheksi,", "Hihat paidan palkeeksi,", "hiha, paita, palje", "sleeve, shirt, bellows", "His shirt sleeves into bellows,", ""),
    ("Turkkinsa tuhottimeksi,", "Turkkinsa tuhottimeksi,", "turkki, tuhotin", "fur coat, ash-rake/poker", "His fur coat into an ash-poker,", ""),
    ("Housut hormiksi rakenti,", "Housut hormiksi rakensi,", "housut, hormi, rakentaa", "trousers, chimney/flue, to build", "Built his trousers into a chimney flue,", ""),
    ("Sukat hormin suulliseksi,", "Sukat hormin suulliseksi,", "sukka, hormi, suullinen", "sock, flue, mouthpiece/opening", "His socks into the flue's opening,", ""),
    ("Polwensa alasimeksi,", "Polvensa alasimeksi,", "polvi, alasin", "knee, anvil", "His knee into an anvil,", ""),
    ("Wasaraksi kyynäspäänsä,", "Vasaraksi kyynärpäänsä,", "vasara, kyynärpää", "hammer, elbow", "His elbow into a hammer,", ""),
    ("Pikkusormensa pihiksi;", "Pikkusormensa pihdiksi;", "pikkusormi, pihti", "little finger, tongs/pliers", "His little finger into tongs;", ""),
    ("Takoa taputtelewi,", "Takoa taputtelee,", "takoa, taputella", "to forge, to tap/hammer", "He keeps on forging, hammering,", ""),
    ("Lyöä lynnähyttelewi,", "Lyödä lynnähyttelee,", "lyödä, lynnähyttää", "to strike, to clang/bang", "Striking, clanging,", ""),
    ("Watsassa warawäkewän,", "Vatsassa varavoimakkaan,", "vatsa, varavoimakas", "stomach, powerfully-built", "In the stomach of the powerfully-built one,", ""),
    ("Mahtipontisen powessa.", "Mahtipontisen povessa.", "mahtipontinen, povi", "mighty/grand, bosom/chest", "In the mighty one's chest/bosom.", ""),
    ("Sillon wirsikäs Wipunen", "Silloin virsikäs Vipunen", "silloin, virsikäs, Vipunen", "then, song-filled, Vipunen", "Then the song-filled Vipunen", ""),
    ("Itse tuon sanoiksi wirkki:", "Itse tuon sanoiksi virkki:", "itse, tuo, sana, virkata", "himself, that, word, to utter", "Himself uttered these words:", ""),
    ("\"Mi sie lienet miehiäsi,", "\"Mikä sinä lienet miehiäsi,", "mikä, sinä, lienee, mies", "what, you, might be, man", "\"What kind of man you might be,", ""),
    ("Jo kuka urohiasi;", "Jo kuka urohiasi;", "jo, kuka, uros", "indeed, who, hero", "Indeed who of heroes;", ""),
    ("Jo olen syönyt sa'an miestä,", "Jo olen syönyt sadan miestä,", "jo, olla, syödä, sata, mies", "already, to be, to eat, hundred, man", "I have already eaten a hundred men,", "Vipunen's monstrous boast of having devoured hundreds — and his suspicion of demonic or magical origin for this strange new intruder — frames the encounter as a battle between two powerful tricksters, each suspecting the other of supernatural deception."),
    ("Tuhonnut tuhan urosta,", "Tuhonnut tuhat urosta,", "tuhota, tuhat, uros", "to destroy, thousand, hero", "Destroyed a thousand heroes,", ""),
    ("En ole wielä mointa syönyt;", "En ole vielä moista syönyt;", "ei, olla, vielä, moinen, syödä", "not, to be, yet, such, to eat", "I have not yet eaten such a thing;", ""),
    ("Syet suuhuni tulewat,", "Syöt suuhuni tulevat,", "syte, suu, tulla", "ember, mouth, to come", "Embers come into my mouth,", ""),
    ("Kekälehet kielelleni,", "Kekäleet kielelleni,", "kekäle, kieli", "firebrand, tongue", "Firebrands onto my tongue,", ""),
    ("Rauan kuonat kulkkuhuni.", "Raudan kuonat kulkkuuni.", "rauta, kuona, kurkku", "iron, slag/dross, throat", "Iron slag down my throat.", ""),
    ("Mist' olet Hiisi hingannunna,", "Mistä olet Hiisi hinkannut,", "mistä, Hiisi, hinkata", "from where, Hiisi, to scrape/struggle", "From where have you, Hiisi, scraped yourself,", ""),
    ("Kusta juutas julkenunna,", "Kustako juudas julkenenut,", "kusta, juudas, julkeaa", "from where, devil/traitor, to dare", "From where have you, devil, dared,", ""),
    ("Perkele perehtynynnä?", "Perkele perehtynyt?", "perkele, perehtyä", "devil, to become acquainted/settled in", "Devil, settled yourself in?", ""),
    ("Kun olet tullut tunnotonna,", "Kun olet tullut tunnottomana,", "kun, tulla, tunnoton", "since, to come, senseless/unfeeling", "Since you have come unfeeling,", ""),
    ("Tawotonna taputellut,", "Tavotonna taputellut,", "tavoton, taputtella", "without manners, to tap/hammer", "Without manners, hammering away,", ""),
    ("Puremahan, jäytämähän,", "Puremaan, jäytämään,", "purra, jäytää", "to bite, to gnaw", "Biting, gnawing,", ""),
    ("Syömähän, kaluamahan.", "Syömään, kaluamaan.", "syödä, kalua", "to eat, to gnaw clean", "Eating, gnawing clean.", ""),
    ("Oletko tauti luojan luoma,", "Oletko tauti luojan luoma,", "olla, tauti, luoja, luoda", "to be, illness, creator, to create", "Are you an illness created by the creator,", ""),
    ("Surma säätämä jumalan,", "Surma säätämä jumalan,", "surma, säätää, jumala", "death, to ordain, god", "A death ordained by god,", ""),
    ("Wai olet pantu palkan eestä,", "Vai olet pantu palkan edestä,", "vai, panna, palkka, edestä", "or, to put/sent, wage/payment, for the sake of", "Or have you been sent for payment,", ""),
    ("Rakettu rahan nenästä?", "Rakettu rahan nenästä?", "rakentaa, raha, nenä", "to build/make, money, tip/account", "Made for the sake of money?", ""),
    ("Jos olet tauti luojan luoma,", "Jos olet tauti luojan luoma,", "jos, tauti, luoja, luoda", "if, illness, creator, to create", "If you are an illness created by the creator,", ""),
    ("Surma säätämä jumalan,", "Surma säätämä jumalan,", "surma, säätää, jumala", "death, to ordain, god", "A death ordained by god,", ""),
    ("Niin mä luomme luojahani,", "Niin minä luotan luojaani,", "niin, luottaa, luoja", "then, to trust, creator", "Then I trust in my creator,", ""),
    ("Heitämme jumalahani,", "Heitän jumalaani,", "heittää, jumala", "to cast/throw oneself, god", "I throw myself to my god,", ""),
    ("Ei herra hyweä heitä,", "Ei herra hyvää heitä,", "ei, herra, hyvä, heittää", "not, lord, good, to abandon", "The lord does not abandon the good,", ""),
    ("Luoja kaunista kaota.", "Luoja kaunista kadota.", "luoja, kaunis, kadottaa", "creator, beautiful, to let perish", "The creator does not let the fair perish.", ""),
    ("Jos olet pantu palkan eestä,", "Jos olet pantu palkan edestä,", "jos, panna, palkka, edestä", "if, to put/sent, wage, for the sake of", "If you have been sent for payment,", ""),
    ("Rakettu rahan nenästä,", "Rakettu rahan nenästä,", "rakentaa, raha, nenä", "to build, money, tip", "Made for the sake of money,", ""),
    ("Niin mä pannen palkatonta,", "Niin minä panen palkatonta,", "niin, panna, palkaton", "then, to put, unpaid/wageless", "Then I will set the unpaid one,", ""),
    ("rahatonta juoksemahan,", "Rahatonta juoksemaan,", "rahaton, juosta", "moneyless, to run", "The moneyless one running,", ""),
    ("Kullatonta kulkemahan.", "Kullatonta kulkemaan.", "kullaton, kulkea", "goldless, to wander", "The goldless one wandering.", ""),
    ("Tietähän sinun sukusi,", "Tiedänhän sinun sukusi,", "tietää, sinä, suku", "to know, you, kin/origin", "I do know your origin,", ""),
    ("Maan kawala kaswantosi;", "Maan kavala kasvantosi;", "maa, kavala, kasvanto", "earth, cunning/sly, growth/origin", "Your earthly, cunning origin;", "Vipunen attempts to identify and thereby gain power over the intruder by naming its origin — a classic shamanic identification ritual, similar to how naming a trickster's true nature can neutralize it."),
    ("Oletko kalma kalmistosta,", "Oletko kalma kalmistosta,", "olla, kalma, kalmisto", "to be, death/corpse, graveyard", "Are you death from the graveyard,", ""),
    ("Perkele pyhästä maasta,", "Perkele pyhästä maasta,", "perkele, pyhä, maa", "devil, holy, earth", "A devil from holy ground,", ""),
    ("Mullista muhajawista,", "Mullista muhajavista,", "multa, muhaista", "soil, crumbling/loose", "From crumbling soils,", ""),
    ("Maista liikuteltawista?", "Maista liikuteltavista?", "maa, liikuteltava", "earth, movable/shifting", "From shifting earths?", ""),
    ("Wai olet wieno weestä nossut,", "Vai olet vieno vedestä nousta,", "vai, vieno, vesi, nousta", "or, gentle, water, to rise", "Or are you gentle, risen from water,", ""),
    ("Ween waahesta walunut;", "Veden vaahdesta valunut;", "vesi, vaahti, valua", "water, foam, to flow", "Flowed from the water's foam;", ""),
    ("Wai olet tuulen tuuwittama,", "Vai olet tuulen tuuvittama,", "vai, tuuli, tuuvittaa", "or, wind, to cradle/rock", "Or are you rocked by the wind,", ""),
    ("Meren tyrskyn työnnättämä?", "Meren tyrskyn työnnättämä?", "meri, tyrsky, työntää", "sea, surf/breaker, to push", "Pushed by the sea's surf?", ""),
    ("Mist' olet pulma puuttununna,", "Mistä olet pulma puuttunut,", "mistä, pulma, puuttua", "from where, problem/trouble, to come/lack", "From where have you, trouble, come,", ""),
    ("Taikia tapahtununna?", "Taikina tapahtunut?", "taikina, tapahtua", "magic-thing/dough, to happen", "Magical thing, occurred?", ""),
    ("Kiwistäkö, kannoistako,", "Kivistäkö, kannoistako,", "kivi, kanto", "stone, stump", "From stones, or from stumps,", ""),
    ("Waiko wanhoista sioista,", "Vaiko vanhoista sioista,", "vai, vanha, sija", "or, old, place", "Or from old places,", ""),
    ("Waiko watturaunioista,", "Vaiko vattu-raunioista,", "vai, vattu, raunio", "or, raspberry, ruin/heap", "Or from raspberry-thicket ruins,", ""),
    ("Tietomiesten tienohilta,", "Tietomiesten tienohilta,", "tietomies, tienoo", "wise man, region/area", "From the regions of wise men,", ""),
    ("Lakkipäien lainehilta,", "Lakkipäiden laineilta,", "lakkipää, laine", "cloud-capped (mountain), wave", "From the waves of cloud-capped peaks,", ""),
    ("Noitien noronenistä,", "Noitien noronenistä,", "noita, noronen", "witch, little stream/source", "From the little streams of witches,", ""),
    ("Mäkipäistä möyrymiesten,", "Mäkipäistä möyrymiesten,", "mäkipää, möyrymies", "hilltop, rumbling/growling man", "From the hilltops of growling men,", ""),
    ("Lummetkoirain koista,", "Lumikoirain kodista,", "lumikoira, koti", "snow-dog, home", "From the homes of snow-dogs,", ""),
    ("Karhun kiljun kartanosta,", "Karhun kiljun kartanosta,", "karhu, kilju, kartano", "bear, growl/howl, estate", "From the estate of the bear's growl,", ""),
    ("Rewon rääyntäsialta,", "Revon rääyntäsijalta,", "repo, rääyntä, sija", "fox, screech/howl, place", "From the place of the fox's screech,", ""),
    ("Jäniksen jäwintämailta?\"", "Jäniksen jäpittämämailta?\"", "jänis, jäpittää, maa", "hare, to chase/frighten, land", "From the lands where the hare is chased?\"", ""),
    ("Lähe nyt kumma kulkemahan,", "Lähde nyt kumma kulkemaan,", "lähteä, nyt, kumma, kulkea", "to leave, now, strange thing, to wander", "Set off now, strange creature, to wander,", "The earliest part of Vipunen's banishing-curse against the unidentified being inside him — long before he realizes it is Väinämöinen — is the standard incantation form used elsewhere to expel evil spirits, illness, or curses. The structure of conjuring/expelling a malevolent presence echoes the same magical register tricksters often use offensively."),
    ("Maan paha pakenemahan,", "Maan paha pakenemaan,", "maa, paha, paeta", "earth, evil, to flee", "Evil of the earth, to flee,", ""),
    ("Ennen kun sanon emolle,", "Ennen kuin sanon emolle,", "ennen, kuin, sanoa, emo", "before, than, to say, mother", "Before I tell my mother,", ""),
    ("Wirkan wierin wanhemmalle.", "Virkan vierin vanhemmalle.", "virkkaa, vieri, vanhempi", "to utter, alongside, parent", "Speak alongside my parent.", ""),
    ("Kun minä etsin emosi,", "Kun minä etsin emosi,", "kun, minä, etsiä, emo", "if, I, to search, mother", "If I seek your mother,", ""),
    ("Haen waltawanhempasi,", "Haen valtavanhempasi,", "hakea, valtavanhempi", "to fetch, mighty parent", "Fetch your mighty parent,", ""),
    ("Wielä turmut tuskihisi,", "Vielä turmiot tuskiisi,", "turmio, tuska", "ruin/misfortune, pain/anguish", "Still more ruin upon your anguish,", ""),
    ("Haluisi halkielet;", "Haluisi halkeilet;", "haluta, halkeilla", "to want, to crack/split", "You would willingly crack apart;", ""),
    ("Halkiat paha kaheksi,", "Halkeaisit paha kahdeksi,", "haljeta, paha, kaksi", "to crack, evil one, two", "You would crack apart, evil one, in two,", ""),
    ("Konna kolmeksi muruksi.", "Konna kolmeksi muruksi.", "konna, kolme, muru", "wretch/villain, three, piece", "Wretch, into three pieces.", ""),
    ("Ei ennen minun isoni,", "Ei ennen minun isäni,", "ei, ennen, minä, isä", "not, before, my, father", "My father never before,", ""),
    ("Eikä waltawanhempani,", "Eikä valtavanhempani,", "eikä, valtavanhempi", "nor, mighty parent", "Nor my mighty parent,", ""),
    ("Nouatellut noian mieltä,", "Noudatellut noidan mieltä,", "noudattaa, noita, mieli", "to follow, witch, mind/will", "Followed a witch's will,", ""),
    ("Lahjotellut Lappalaista;", "Lahjoitellut lappalaista;", "lahjoittaa, lappalainen", "to give gifts to, Laplander", "Gave gifts to a Laplander;", ""),
    ("Sai se liiat liikkumahan,", "Sai se liiat liikkumaan,", "saada, liika, liikkua", "to make, excess/evil, to move", "Made the excess ones move off,", ""),
    ("Sai pahat pakenemahan.", "Sai pahat pakenemaan.", "saada, paha, paeta", "to make, evil, to flee", "Made the evil ones flee.", ""),
    ("Jos ei minussa miestä lienee", "Jos ei minussa miestä liene", "jos, ei, minä, mies, lienee", "if, not, I, man, might be", "If there be not man enough in me,", ""),
    ("Ukon pojassa urosta,", "Ukon pojassa urosta,", "Ukko, poika, uros", "Ukko (sky god), son, hero", "Heroism enough in Ukko's son,", ""),
    ("Ompa tuossa weikossani,", "Onpa tuossa veikossani,", "olla, veikko", "to be, brother", "There is yet in my brother,", ""),
    ("Joka pilwiä pitäwi,", "Joka pilviä pitää,", "joka, pilvi, pitää", "who, cloud, to hold", "Who holds the clouds,", ""),
    ("Hattaroita hallitsewi.", "Hattaroita hallitsee.", "hattara, hallita", "small cloud, to rule/control", "Who rules the small clouds.", ""),
    ("Tuolta ma anon apua,", "Tuolta minä anon apua,", "tuolta, minä, anoa, apu", "from there, I, to beg, help", "From there I beg for help,", "Vipunen invokes the sky-god Ukko for aid against the intruder — exactly the same divine figure that Lemminkäinen previously commanded as a tool in Runo 7. Both heroic and monstrous figures in the epic treat the gods as resources to be summoned and directed."),
    ("Tuolta huuan hoiwautan,", "Tuolta huudan hoivautan,", "tuolta, huutaa, hoivata", "from there, to call, to seek care", "From there I call, seek aid,", ""),
    ("Ylähältä taiwosesta,", "Ylhäältä taivaasta,", "ylhäältä, taivas", "from above, sky", "From above, from the sky,", ""),
    ("Alahalta maaemästä;", "Alhaalta maaemästä;", "alhaalta, maaemä", "from below, mother-earth", "From below, from mother earth;", ""),
    ("Huutelen hätäsen huuon,", "Huutelen hätäisen huudon,", "huudella, hätäinen, huuto", "to call out, urgent, cry", "I call out an urgent cry,", ""),
    ("Panen äänen pakkoisen,", "Panen äänen pakollisen,", "panna, ääni, pakollinen", "to send, voice, forceful", "Send a forceful voice,", ""),
    ("Läpi maan, läpi manuen,", "Läpi maan, läpi manuen,", "läpi, maa, manu", "through, earth, world", "Through the earth, through the world,", ""),
    ("Läpi kuuen kirjokannen,", "Läpi kuuden kirjokannen,", "läpi, kuusi, kirjokansi", "through, six, painted lid (sky)", "Through the six painted vaults (of sky),", ""),
    ("Läpi taiwahan yheksän.", "Läpi taivaan yhdeksän.", "läpi, taivas, yhdeksän", "through, sky, nine", "Through the nine heavens.", ""),
    ("Ukko taiwahan napanen,", "Ukko taivaan napainen,", "Ukko, taivas, napa", "Ukko, sky, navel", "Ukko, navel of the sky,", ""),
    ("Remupilwen reunahinen.", "Remupilven reunainen.", "remupilvi, reuna", "thundercloud, edge", "One at the edge of the thundercloud.", ""),
    ("Tuo tänne tulinen miekka,", "Tuo tänne tulinen miekka,", "tuoda, tänne, tulinen, miekka", "to bring, here, fiery, sword", "Bring here a fiery sword,", ""),
    ("Säkehinen säilä kanna,", "Säkeninen säilä kanna,", "säkeninen, säilä", "sparking, blade", "Carry a sparking blade,", ""),
    ("Jolla ma pahan pitelen,", "Jolla minä pahan pitelen,", "jolla, paha, pidellä", "with which, evil one, to hold/handle", "With which I will handle the evil one,", ""),
    ("Ilkiän iki asetan.", "Ilkeän iäksi asetan.", "ilkeä, ikä, asettaa", "nasty/evil, forever, to settle/fix", "Settle the nasty one forever.", ""),
    ("Nouse weestä ween emäntä,", "Nouse vedestä veden emäntä,", "nousta, vesi, emäntä", "to rise, water, mistress", "Rise from the water, mistress of the water,", "Vipunen invokes multiple cosmic and natural forces — the water-mistress, the forest, hundreds of armed men, ancient ancestors — escalating his summoned allies in a way structurally identical to Lemminkäinen's own escalating forest-incantation in Runo 7. This shared incantatory pattern shows the trickster's rhetorical toolkit is universal across characters in the epic."),
    ("Sinilakki lainehista,", "Sinilakki laineista,", "sinilakki, laine", "blue-cap, wave", "Blue-cap from the waves,", ""),
    ("Hienohelma hettehestä,", "Hienohelma hetteestä,", "hienohelma, hete", "fine-hemmed, spring/marsh-pool", "Fine-hemmed one from the spring,", ""),
    ("Puhasmuotonen murasta,", "Puhdasmuotoinen murusta,", "puhdasmuotoinen, muru", "pure-formed, crumb/fragment", "Pure-formed one from the depths,", ""),
    ("Awukseni, ainokseni,", "Avukseni, ainokseni,", "apu, ainoa", "help, only/sole", "As my help, my only one,", ""),
    ("Tuikseni, turwakseni,", "Tuekseni, turvakseni,", "tuki, turva", "support, protection", "As my support, my protection,", ""),
    ("Tässä työssä työlähässä,", "Tässä työssä työläässä,", "tämä, työ, työläs", "this, work, laborious", "In this laborious work,", ""),
    ("Tässä tuskassa kowassa.", "Tässä tuskassa kovassa.", "tämä, tuska, kova", "this, anguish, hard", "In this hard anguish.", ""),
    ("Nouse metsä miehinesi,", "Nouse metsä miehinesi,", "nousta, metsä, mies", "to rise, forest, man", "Rise, forest, with your men,", ""),
    ("Korpi kaikki kansoinesi,", "Korpi kaikki kansoinesi,", "korpi, kaikki, kansa", "wilderness, all, people", "Wilderness, with all your peoples,", ""),
    ("Perkele perehinesi,", "Perkele perheinesi,", "perkele, perhe", "devil, family", "Devil, with your family,", ""),
    ("Umpilampi lapsinesi;", "Umpilampi lapsinesi;", "umpilampi, lapsi", "sealed pond, child", "Sealed pond, with your children;", ""),
    ("Sata miestä miekallista,", "Sata miestä miekallista,", "sata, mies, miekallinen", "hundred, man, sword-bearing", "A hundred sword-bearing men,", ""),
    ("Tuhat rauaista urosta,", "Tuhat rautaista urosta,", "tuhat, rautainen, uros", "thousand, iron-clad, hero", "A thousand iron-clad heroes,", ""),
    ("Wäeksi wähän urohon,", "Väeksi vähän urohon,", "väki, vähä, uros", "force, little/small, hero", "As force against the small hero,", ""),
    ("Miehen pienen miehueksi.", "Miehen pienen miehueksi.", "mies, pieni, miehue", "man, small, band of men", "As a band of men against the small man.", ""),
    ("Kun ei tuosta kyllä liene,", "Kun ei tuosta kyllä liene,", "kun, ei, tuosta, kyllä, liene", "if, not, from that, enough, might be", "If that be not enough,", ""),
    ("Mistä mä anon apua?", "Mistä minä anon apua?", "mistä, minä, anoa, apu", "from where, I, to beg, help", "From where shall I beg help?", ""),
    ("Onko wanhoa wäkeä,", "Onko vanhaa väkeä,", "olla, vanha, väki", "to be, old, folk/force", "Is there old folk,", ""),
    ("Iän kaiken istunutta;", "Iän kaiken istunutta;", "ikä, kaikki, istua", "age, all, to sit", "Who have sat through all ages;", ""),
    ("Nouse maasta mannun eukko,", "Nouse maasta mannun eukko,", "nousta, maa, mannu, eukko", "to rise, earth, ground/world, old woman", "Rise from the earth, old woman of the ground,", ""),
    ("Pellosta periisäntä,", "Pellosta periisäntä,", "pelto, periisäntä", "field, original master", "From the field, original master,", ""),
    ("Kaikki maasta miekkamiehet,", "Kaikki maasta miekkamiehet,", "kaikki, maa, miekkamies", "all, earth, sword-man", "All sword-men from the earth,", ""),
    ("Hiekasta hewoisurohot,", "Hiekasta hevosurohot,", "hiekka, hevosuros", "sand, horse-hero", "Horse-heroes from the sand,", ""),
    ("Tämän pulmun purkajaksi,", "Tämän pulman purkajaksi,", "pulma, purkaa", "problem/trouble, to undo/resolve", "To resolve this problem,", ""),
    ("Tämän jakson jaksajaksi.", "Tämän jakson jaksajaksi.", "jakso, jaksaa", "section/ordeal, to manage/endure", "To handle this ordeal.", ""),
    ("Kawe eukko luonnon tytti,", "Kave eukko luonnon tyttö,", "Kave, eukko, luonto, tyttö", "Kave (mythical woman), old woman, nature, girl", "Kave, old woman, daughter of nature,", ""),
    ("Kawe kultanen korea!", "Kave kultainen korea!", "Kave, kultainen, korea", "Kave, golden, splendid", "Golden, splendid Kave!", ""),
    ("Joka ennen päästöt päästit,", "Joka ennen päästöt päästit,", "joka, ennen, päästö, päästää", "who, before, release, to release", "Who before released the releases,", ""),
    ("Joka ennen jaksot jaksoit,", "Joka ennen jaksot jaksoit,", "joka, ennen, jakso, jaksaa", "who, before, ordeal, to endure", "Who before endured the ordeals,", ""),
    ("Käy nyt päästö päästämähän,", "Käy nyt päästö päästämään,", "käydä, päästö, päästää", "to go, release, to release", "Come now to release this release,", ""),
    ("Tämä jakso jaksamahan.", "Tämä jakso jaksamaan.", "tämä, jakso, jaksaa", "this, ordeal, to endure", "To endure this ordeal.", ""),
    ("Kun ei wielä tuosta liene,", "Kun ei vielä tuosta liene,", "kun, ei, vielä, tuosta, liene", "if, not, yet, from that, might be", "If still that be not enough,", ""),
    ("Saakohon joku jumala,", "Saakoon joku jumala,", "saada, joku, jumala", "may get, some, god", "May some god come,", ""),
    ("Tuhatkunta perkeleitä,", "Tuhatkunta perkeleitä,", "tuhatkunta, perkele", "a thousand-fold, devil", "A thousand devils,", ""),
    ("Kaikki päästöt päästämähän,", "Kaikki päästöt päästämään,", "kaikki, päästö, päästää", "all, release, to release", "To release all the releases,", ""),
    ("Kaikki jaksot jaksamahan,", "Kaikki jaksot jaksamaan,", "kaikki, jakso, jaksaa", "all, ordeal, to endure", "To endure all the ordeals,", ""),
    ("Kaikki pulmut purkamahan.\"", "Kaikki pulmat purkamaan.\"", "kaikki, pulma, purkaa", "all, problem, to undo", "To undo all the problems.\"", ""),
    ("Lähe nyt kohusta konna,", "Lähde nyt kohusta konna,", "lähteä, kohtu, konna", "to leave, womb/belly, villain", "Leave now from the belly, villain,", ""),
    ("Maan kamala maksoistani,", "Maan kamala maksoistani,", "maa, kamala, maksa", "earth, horrid, liver", "Earth's horrid one, from my liver,", ""),
    ("Ei siellä sinun sioa", "Ei siellä sinun sijaa", "ei, siellä, sinä, sija", "not, there, your, place", "There is no place for you there", ""),
    ("Siankana tarpehella;", "Siankaan tarpeella;", "sika, tarve", "pig, need", "Not even as much as a pig needs;", ""),
    ("Muunne muutaos majasi,", "Muunne muuttaos majasi,", "muunne, muuttaa, maja", "elsewhere, to move, dwelling", "Move your dwelling elsewhere,", ""),
    ("Etemmä elosiasi.", "Etemmäksi elosijaasi.", "etemmäksi, elosija", "further, dwelling-place", "Further off your living-place.", ""),
    ("Minne nyt sinun manoan,", "Minne nyt sinun manaan,", "minne, sinä, manata", "where, you, to banish/conjure", "Where now shall I banish you,", "Vipunen's lengthy banishment incantation, attempting every conceivable origin and destination for the supposed evil spirit, is the single longest piece of magical speech in the text — a demonstration of the same expansive, rhetorical, exhaustive cataloguing technique Lemminkäinen used in his own forest-incantation, again linking the two figures' verbal craft."),
    ("Kunne käsken ja kehotan,", "Kunne käsken ja kehotan,", "kunne, käskeä, kehottaa", "to where, to command, to urge", "To where shall I command and urge you,", ""),
    ("Kun sa lienet nosto toisen,", "Kun sinä lienet nosto toisen,", "kun, sinä, lienee, nosto, toinen", "since, you, might be, lifted-thing, other's", "Since you might be lifted by another,", ""),
    ("Toisen nosto, toisen nuoli,", "Toisen nosto, toisen nuoli,", "toinen, nosto, nuoli", "other's, lifted-thing, other's arrow", "Another's lifting, another's arrow,", ""),
    ("Toki koitellos kotiisi,", "Toki koetelkos kotiisi,", "toki, koetella, koti", "yet, to try/test, home", "Yet try to go to your home,", ""),
    ("Tekiäsi tienohille,", "Tekijäsi tienoolle,", "tekijä, tienoo", "maker, region", "To the region of your maker,", ""),
    ("Paniasi parmohille.", "Panijasi parmoille.", "panija, parmo", "sender/placer, threshold/area", "To the area of your sender.", ""),
    ("Liiku kun lipiä koira,", "Liiku kuin lipeä koira,", "liikkua, kuin, lipeä, koira", "to move, as/like, supple/quick, dog", "Move like a quick dog,", ""),
    ("Tuika kun tulikipuna;", "Tuiki kuin tulikipuna;", "tuikkia, kuin, tulikipuna", "to flash, as/like, spark of fire", "Flash like a spark of fire;", ""),
    ("Lennä kukkona kujaan,", "Lennä kukkona kujaan,", "lentää, kukko, kuja", "to fly, rooster, lane", "Fly as a rooster into the lane,", "This same image — a rooster herded into the lane, a hen lassoed into the yard — appeared verbatim in Runo 6 when Lemminkäinen mocked the old woman of Pohjola. Vipunen reuses this exact insult-image, suggesting it is a stock formula for comic banishment within the trickster-adjacent verbal tradition of the epic."),
    ("Kanan lassa kartanolle;", "Kanan lassona kartanolle;", "kana, lasso, kartano", "hen, lasso/snare, estate/yard", "As a hen lassoed to the yard;", ""),
    ("Sorra soimelta hewonen,", "Sorru soimelta hevonen,", "sortua, soimi, hevonen", "to collapse/fall, manger, horse", "Fall from the manger, horse,", ""),
    ("Nawetasta sarwinauta,", "Navetasta sarvinauta,", "navetta, sarvinauta", "cow barn, horned cattle", "Horned cattle from the cow barn,", ""),
    ("Päähyt koukkuhun kowerra,", "Päähyt koukkuun kovera,", "pää, koukku, koveroida", "little head, hook, to curl/hollow", "Little head curled into a hook,", ""),
    ("Sarwet sontahan sowita,", "Sarvet sontaan sovita,", "sarvi, sonta, sovittaa", "horn, dung, to fit", "Horns fitted into the dung,", ""),
    ("Häntä laske lattialle.", "Häntä laske lattialle.", "häntä, laskea, lattia", "tail, to lower, floor", "Tail lowered to the floor.", ""),
    ("Sitte tullessa tupahan", "Sitten tullessa tupaan", "sitten, tulla, tupa", "then, to come, cabin", "Then when coming into the cabin", ""),
    ("Mene kynsin kynnyksessä,", "Mene kynsin kynnyksessä,", "mennä, kynsi, kynnys", "to go, claw, threshold", "Go clawing at the threshold,", ""),
    ("Polwin porstuan owissa,", "Polvin porstuan ovissa,", "polvi, porstua, ovi", "knee, porch/vestibule, door", "Kneeling at the porch doors,", ""),
    ("Saahen syrjin syyttömistä,", "Saaden syrjin syyttömistä,", "saada, syrjin, syytön", "to get, sideways, blameless/innocent", "Coming sideways from the innocent ones,", ""),
    ("Wieritse wiattomista,", "Vieritse viattomista,", "vieritse, viaton", "alongside, innocent", "Alongside the innocent ones,", ""),
    ("Käyös päälle käskiäsi,", "Käy päälle käskijäsi,", "käydä, käskijä", "to go, commander/sender", "Go upon your commander,", ""),
    ("Nouse päälle nostajasi,", "Nouse päälle nostajasi,", "nousta, nostaja", "to rise, lifter/raiser", "Rise upon your raiser,", ""),
    ("Ota kiinni kinterestä,", "Ota kiinni kinnerestä,", "ottaa, kinneri", "to take, hold, hock/heel-tendon", "Take hold of the heel-tendon,", ""),
    ("Takimmaisista jaloista,", "Takimmaisista jaloista,", "takimmainen, jalka", "hindmost, leg/foot", "Of the hindmost legs,", ""),
    ("Kaijimmista kantapäistä,", "Kaikkein kantapäistä,", "kaikkein, kantapää", "most of all, heel", "Of all the heels,", ""),
    ("Wasemmista warpahista;", "Vasemmista varpaista;", "vasen, varvas", "left, toe", "Of the left toes;", ""),
    ("Tunge perkelet tulehen,", "Tunge perkeleet tuleen,", "tunkea, perkele, tuli", "to push, devil, fire", "Push the devils into the fire,", ""),
    ("Isännät perisopesta,", "Isännät perisopesta,", "isäntä, perisoppi", "master, far/inner corner", "The masters from the inner corner,", ""),
    ("Emännät owisopesta,", "Emännät ovisopesta,", "emäntä, ovisoppi", "mistress, door corner", "The mistresses from the door corner,", ""),
    ("Lapset keskilattialta;", "Lapset keskilattialta;", "lapsi, keskilattia", "child, middle of the floor", "The children from the middle of the floor;", ""),
    ("Suin tulehen, päin tulehen,", "Suin tuleen, päin tuleen,", "suu, tuli, pää", "mouth, fire, head", "Mouth into the fire, head into the fire,", "This horrifically violent expulsion sequence — gouging eyes, scattering organs, boiling lungs — recalls the equally graphic curse Lemminkäinen made against the Lapp wizards in Runo 6. Both heroes deploy nearly identical extreme bodily-destruction imagery as their ultimate verbal weapon."),
    ("Takaraiwoin tanterehen;", "Takaraivoin tanterelle;", "takaraivo, tanner", "back of the head, ground", "Back of the head onto the ground;", ""),
    ("Silmät käännä kellellehen,", "Silmät käännä kellelleen,", "silmä, kääntää, kellellään", "eye, to turn, on its back/upside down", "Turn the eyes upside down,", ""),
    ("Niskat ruttoin rutase,", "Niskat ruttoon rutise,", "niska, rutto, rutista", "neck, plague, to crush/crackle", "Crush the necks in plague,", ""),
    ("Wello werta hartioissa,", "Velloa verta hartioissa,", "velloa, veri, hartia", "to churn/stir, blood, shoulder", "Churn blood in the shoulders,", ""),
    ("Sotke suolia sisässä,", "Sotke suolia sisässä,", "sotkea, suoli, sisässä", "to mix/mash, intestine, inside", "Mash the intestines inside,", ""),
    ("Keitä keuhkoja mahassa.", "Keitä keuhkoja mahassa.", "keittää, keuhko, maha", "to boil/cook, lung, stomach", "Boil the lungs in the stomach.", ""),
    ("Pane pää pärisemähän,", "Pane pää pärisemään,", "panna, pää, päristä", "to make, head, to whirr/buzz", "Make the head whirr,", ""),
    ("Pane luut lotisemahan,", "Pane luut lotisemaan,", "panna, luu, lotista", "to make, bone, to clatter", "Make the bones clatter,", ""),
    ("Henki huokumattomaksi.", "Henki huokumattomaksi.", "henki, huokumaton", "breath/spirit, breathless", "Breath into breathlessness.", ""),
    ("Waan en pannekan pahoille,", "Vaan en panekaan pahoille,", "vaan, ei, panna, paha", "but, not, to put, evil", "But I will not put (you) to evil things,", "After this terrifying curse, Vipunen abruptly softens and instead offers the intruder hospitality — sending it instead to a feast — a strange and sudden tonal reversal that recalls how tricksters often pivot unpredictably between menace and accommodation."),
    ("Warsin töille törkehille;", "Varsin töille törkeille;", "varsin, työ, törkeä", "quite, work/deed, outrageous", "Quite to outrageous deeds;", ""),
    ("Tuonne ma sinun manoan", "Tuonne minä sinun manaan", "tuonne, minä, sinä, manata", "there, I, you, to banish/send", "There I will send you", ""),
    ("Isäntäsi iltaselle,", "Isäntäsi iltaiselle,", "isäntä, iltainen", "master, evening meal", "To your master's evening meal,", ""),
    ("Emäntäsi einehelle,", "Emäntäsi einehelle,", "emäntä, eine", "mistress, meal", "To your mistress's meal,", ""),
    ("Muorisi muna paloille,", "Muorisi munapaloille,", "muori, munapala", "old woman, egg-piece", "To your old woman's egg-pieces,", ""),
    ("Muun perehen murkkinalle;", "Muun perheen murkkinalle;", "muu, perhe, murkkina", "other, family, supper", "To the rest of the family's supper;", ""),
    ("Siellä itkewi isosi,", "Siellä itkee isäsi,", "siellä, itkeä, isä", "there, to cry, father", "There your father cries,", ""),
    ("Walittawi wanhempasi,", "Valittaa vanhempasi,", "valittaa, vanhempi", "to lament, parent", "Your parent laments,", ""),
    ("Weljesi wesin waluwi,", "Veljesi vesin valuu,", "veli, vesi, valua", "brother, tears/water, to flow", "Your brother's tears flow,", ""),
    ("Muorisi murehtelewi.", "Muorisi murehtelee.", "muori, murehtia", "old woman, to grieve", "Your old woman grieves.", ""),
    ("Ota Hiieltä kypärä,", "Ota Hiieltä kypärä,", "ottaa, Hiisi, kypärä", "to take, Hiisi, helmet", "Take a helmet from Hiisi,", "Vipunen now offers practical magical equipment for the journey — Hiisi's helmet, magic skis, a horse — exactly the kind of borrowed or stolen supernatural tools that Lemminkäinen used (Hiisi's own skis) in Runo 7. The motif of using the enemy's/devil's equipment against them recurs across multiple characters."),
    ("Lakki laajan perkelehen,", "Lakki laajan perkeleen,", "lakki, laaja, perkele", "cap, wide/great, devil", "A cap from the great devil,", ""),
    ("Yli meret mennäksesi,", "Yli meret mennäksesi,", "yli, meri, mennä", "over, sea, to go", "To go over the seas,", ""),
    ("Lammit luikutellaksesi;", "Lammit luikutellaksesi;", "lampi, luikutella", "pond, to slip/glide quickly", "To glide quickly over the ponds;", ""),
    ("Saaos Hiien hiihtoneuot,", "Saa Hiien hiihtoneuvot,", "saada, Hiisi, hiihtoneuvo", "to get, Hiisi, ski equipment", "Get Hiisi's ski equipment,", ""),
    ("Lemmon leppäset siwakat,", "Lemmon leppäiset sivakat,", "Lempo, leppä, sivakka", "Lempo (devil), alder, ski", "Lempo's alder skis,", ""),
    ("Pahan miehen paksu sana,", "Pahan miehen paksu sana,", "paha, mies, paksu, sana", "evil, man, thick/strong, word", "The evil man's strong word,", ""),
    ("Joilla hiihat hiien maita,", "Joilla hiihdät hiien maita,", "jolla, hiihtää, hiisi, maa", "with which, to ski, hiisi, land", "With which you ski Hiisi's lands,", ""),
    ("Lemmon lehtoja samoat.", "Lemmon lehtoja samoat.", "Lempo, lehto, samota", "Lempo, grove, to travel", "Travel Lempo's groves.", ""),
    ("Waan jos kyytiä kysynet,", "Vaan jos kyytiä kysyt,", "vaan, jos, kyyti, kysyä", "but, if, ride, to ask", "But if you ask for a ride,", ""),
    ("Anonet ajohewoista;", "Anot ajohevosta;", "anoa, ajohevonen", "to beg, riding horse", "Beg for a riding horse;", ""),
    ("Ota Hiiestä hewonen,", "Ota Hiiestä hevonen,", "ottaa, Hiisi, hevonen", "to take, Hiisi, horse", "Take a horse from Hiisi,", ""),
    ("Wuoresta walitse warsa,", "Vuoresta valitse varsa,", "vuori, valita, varsa", "mountain, to choose, foal", "From the mountain choose a foal,", ""),
    ("Hiiess' on hywä hewonen,", "Hiiessä on hyvä hevonen,", "Hiisi, hyvä, hevonen", "Hiisi, good, horse", "In Hiisi there is a good horse,", ""),
    ("Punatukka tunturissa,", "Punatukka tunturissa,", "punatukka, tunturi", "red-haired, fell/mountain", "Red-maned in the fell,", ""),
    ("Hywälle hypittäjälle,", "Hyvälle hypittäjälle,", "hyvä, hypittäjä", "good, one who makes (it) leap", "For a good leaper-maker,", ""),
    ("Ajajalle ankaralle,", "Ajajalle ankaralle,", "ajaja, ankara", "driver, harsh/strict", "For a harsh driver,", ""),
    ("Jonka tukka tulta tuiski,", "Jonka tukka tulta tuiskasi,", "tukka, tuli, tuiskahtaa", "hair, fire, to flash", "Whose hair flashed fire,", ""),
    ("Nenä warsin walkiata;", "Nenä varsin valkeata;", "nenä, varsin, valkea", "nose, quite, fire/bright", "Whose nose was quite fiery;", ""),
    ("Joll' on rautaset kapiot,", "Jolla on rautaiset kapiot,", "jolla, rautainen, kapio", "which has, iron, hoof", "Which has iron hooves,", ""),
    ("Teräksiset temmottimet;", "Teräksiset temmottimet;", "teräksinen, temmotin", "steel, rein/tether", "Steel reins;", ""),
    ("Jonk' ei kynnet kilpistele,", "Jonka kynnet ei kilpistele,", "kynsi, kilpistyä", "claw/hoof, to slip/buckle", "Whose hooves do not slip,", ""),
    ("Eikä kalpistu kapiot,", "Eikä kalpene kapiot,", "ei, kalveta, kapio", "not, to pale/weaken, hoof", "Nor do the hooves pale,", ""),
    ("Ilmankana iljanella,", "Ilmankaan iljanteella,", "ilmankaan, iljanne", "even, slippery ice", "Even on slippery ice,", ""),
    ("Kalmankana kaljamalla.", "Kalmankaan kaljamalla.", "kalma, kaljama", "death/corpse-place, bare/frosty patch", "Even on a frosty death-patch.", ""),
    ("Jos ei wielä siitä liene,", "Jos ei vielä siitä liene,", "jos, ei, vielä, siitä, liene", "if, not, yet, from that, might be", "If still that be not enough,", ""),
    ("Niin ota sukusi sukset,", "Niin ota sukusi sukset,", "niin, ottaa, suku, suksi", "then, to take, kin, ski", "Then take your kin's skis,", ""),
    ("Heimokuntasi hewoset,", "Heimokuntasi hevoset,", "heimokunta, hevonen", "tribe/kin-group, horse", "Your kin-group's horses,", ""),
    ("Weljesi weno punanen,", "Veljesi veno punainen,", "veli, vene, punainen", "brother, boat, red", "Your brother's red boat,", ""),
    ("Kulkiaksesi kotihin,", "Kulkiaksesi kotiin,", "kulkea, koti", "to travel, home", "To travel home,", ""),
    ("Wenehellä wettä myöten,", "Veneellä vettä myöten,", "vene, vesi, myöten", "boat, water, along", "By boat along the water,", ""),
    ("Hewosella tietä myöten,", "Hevosella tietä myöten,", "hevonen, tie, myöten", "horse, road, along", "By horse along the road,", ""),
    ("Suksilla mäkiä myöten.", "Suksilla mäkiä myöten.", "suksi, mäki, myöten", "ski, hill, along", "By skis along the hills.", ""),
    ("Ollet kalma kalmistosta,", "Olletkin kalma kalmistosta,", "olla, kalma, kalmisto", "to be, death/corpse, graveyard", "Should you be death from the graveyard,", ""),
    ("Perkele pyhästä maasta;", "Perkele pyhästä maasta;", "perkele, pyhä, maa", "devil, holy, earth", "A devil from holy ground;", ""),
    ("Niin tuonne sinun manoan,", "Niin tuonne sinun manaan,", "niin, tuonne, sinä, manata", "then, there, you, to banish", "Then there I will send you,", ""),
    ("Tuonne käsken ja kehotan,", "Tuonne käsken ja kehotan,", "tuonne, käskeä, kehottaa", "there, to command, to urge", "There I command and urge you,", ""),
    ("Multihin muhajawihin,", "Multiin muhajaviin,", "multa, muhaista", "soil, crumbling", "Into the crumbling soils,", ""),
    ("Maihin liikuteltawihin,", "Maihin liikuteltaviin,", "maa, liikuteltava", "earth, shifting", "Into the shifting earths,", ""),
    ("Johon on kansa kaatununna,", "Johon on kansa kaatunut,", "johon, kansa, kaatua", "into which, people, to fall", "Into which people have fallen,", ""),
    ("Wäki wahwa wääntynynnä.", "Väki vahva vääntynyt.", "väki, vahva, vääntyä", "folk, strong, to twist/writhe", "Strong folk have writhed.", ""),
    ("Ollet wieno weestä nossut,", "Olletkin vieno vedestä nousta,", "olla, vieno, vesi, nousta", "to be, gentle, water, to rise", "Should you be gentle, risen from water,", ""),
    ("Ween waahesta walunut;", "Veden vaahdesta valunut;", "vesi, vaahti, valua", "water, foam, to flow", "Flowed from the water's foam;", ""),
    ("Niin tuonne sinun manoan,", "Niin tuonne sinun manaan,", "niin, tuonne, sinä, manata", "then, there, you, to banish", "Then there I will send you,", ""),
    ("Tuonne käsken ja kehotan,", "Tuonne käsken ja kehotan,", "tuonne, käskeä, kehottaa", "there, to command, to urge", "There I command and urge you,", ""),
    ("Suurelle meren selälle,", "Suurelle meren selälle,", "suuri, meri, selkä", "great, sea, open water", "To the great open sea,", ""),
    ("Ulapalle aukialle,", "Ulapalle aukealle,", "ulappa, aukea", "open sea, open", "To the open expanse,", ""),
    ("Pohjan pitkähän perähän;", "Pohjan pitkään perään;", "pohja, pitkä, perä", "north, long, far end", "To the long far end of the north;", ""),
    ("Siellä tuulen tuuwitella,", "Siellä tuulen tuuvitella,", "siellä, tuuli, tuuvitella", "there, wind, to be rocked", "There to be rocked by the wind,", ""),
    ("Ween wienon wilkutella,", "Veden vienon vilkutella,", "vesi, vieno, vilkutella", "water, gentle, to sway", "Swayed by the gentle water,", ""),
    ("Ween synkän sylkytellä.", "Veden synkän sylkytellä.", "vesi, synkkä, sylkytellä", "water, dark, to shake/toss", "Tossed by the dark water.", ""),
    ("Ollet tuulen tuuwittama,", "Olletkin tuulen tuuvittama,", "olla, tuuli, tuuvittaa", "to be, wind, to rock", "Should you be one rocked by the wind,", ""),
    ("Ilman tyrskyn tyyräelmä,", "Ilman tyrskyn tyyräelmä,", "ilma, tyrsky, tyyräelmä", "air, surf, steered/driven thing", "Driven by the air's surf,", ""),
    ("Mennös tuulen tietä myöten,", "Menköön tuulen tietä myöten,", "mennä, tuuli, tie, myöten", "to go, wind, road, along", "Go along the wind's road,", ""),
    ("Ahawan ratoa myöten;", "Ahavan rataa myöten;", "ahava, rata", "bitter wind, track/path", "Along the bitter wind's track;", ""),
    ("Liiku kun lipiä koira,", "Liiku kuin lipeä koira,", "liikkua, kuin, lipeä, koira", "to move, as, quick, dog", "Move like a quick dog,", ""),
    ("Siiry kun sininen nuoli,", "Siirry kuin sininen nuoli,", "siirtyä, kuin, sininen, nuoli", "to move, as, blue, arrow", "Move like a blue arrow,", ""),
    ("Tuika kun tulikipuna.", "Tuiki kuin tulikipuna.", "tuikkia, kuin, tulikipuna", "to flash, as, spark of fire", "Flash like a spark of fire.", ""),
    ("Ja tuonne ma sinun manoan", "Ja tuonne minä sinun manaan", "ja, tuonne, minä, sinä, manata", "and, there, I, you, to banish", "And there I will banish you", "The catalogue of wild beast lairs (elk's ski-paths, hare's grounds, fox's wailing-place, bear's rock-den) as possible banishment destinations is an exhaustive taxonomic listing technique seen elsewhere in Lemminkäinen's similarly catalog-heavy hunting incantation in Runo 7 — both heroes share this love of enumerative, list-based magical rhetoric."),
    ("Hirwen hiihtokankahille,", "Hirven hiihtokankahille,", "hirvi, hiihtokangas", "elk, ski-heath", "To the elk's ski-heath,", ""),
    ("Jäniksen jäpimämaille,", "Jäniksen jäpimämaille,", "jänis, jäpimämaa", "hare, frightened-land", "To the hare's frightened lands,", ""),
    ("Rewon rääkymäsioille,", "Revon rääkymäsijoille,", "repo, rääkymä, sija", "fox, screeching, place", "To the fox's screeching places,", ""),
    ("Kontion kiwikolohon,", "Kontion kivikoloon,", "kontio, kivikolo", "bear, stone-hollow", "To the bear's stone hollow,", ""),
    ("Karhun louhikamarihin,", "Karhun louhikamariin,", "karhu, louhikamari", "bear, rocky chamber", "To the bear's rocky chamber,", ""),
    ("Notkoille noroperille,", "Notkoille noroperille,", "notko, noropera", "hollow/dip, stream-bottom", "To the hollow stream-bottoms,", ""),
    ("Soille räykynettömille,", "Soille räykynettömille,", "suo, räykynetön", "swamp, without screeching/cry", "To the swamps without a cry,", ""),
    ("Herehisin hettehisin,", "Herehisiin hetteisiin,", "herehinen, hete", "soft/marshy, spring-pool", "Into soft marshy springs,", ""),
    ("Läilymihin lähtehisin,", "Läilymiin lähteisiin,", "läilyvä, lähde", "wavering/quivering, spring/source", "Into wavering springs,", ""),
    ("Jost' et kuulu kuuna pänä,", "Josta et kuulu kuuna päivänä,", "josta, ei, kuulua, kuu, päivä", "from where, not, to be heard, moon, day", "From where you will not be heard ever again,", ""),
    ("Selwiä sinä ikänä.", "Selviä sinä ikänä.", "selvitä, ikä", "to get clear/escape, ever", "Never escape that place.", ""),
    ("Jo tuonne ma sinun manoan", "Jo tuonne minä sinun manaan", "jo, tuonne, minä, sinä, manata", "already, there, I, you, to banish", "Now there I banish you", "The final destination of banishment — Rutja's fierce rapids where trees fall headfirst — recycles, almost verbatim, the same description Lemminkäinen used in Runo 6 for the place he would magically banish the Lapp wizards. This is the third or fourth recurrence of nearly identical incantation formulae across different speakers, suggesting these are traditional, reusable magical 'spell templates' within the oral epic tradition — a key insight into how trickster-style verbal magic functions structurally in the Kalevala."),
    ("Tuonne kuolletten kotihin,", "Tuonne kuolleitten kotiin,", "tuonne, kuollut, koti", "there, dead, home", "There to the home of the dead,", ""),
    ("Ikimennetten majahan,", "Ikimenneitten majaan,", "ikimennyt, maja", "eternally gone, dwelling", "To the dwelling of the eternally departed,", ""),
    ("Waipunetten waattehille.", "Vaipuneitten vaatteille.", "vaipunut, vaate", "sunken/perished, clothing", "To the clothing of the perished.", ""),
    ("Pohjan pitkähän perähän,", "Pohjan pitkään perään,", "pohja, pitkä, perä", "north, long, far end", "To the long far end of the north,", ""),
    ("Lapin laajahan salohon,", "Lapin laajaan saloon,", "Lappi, laaja, salo", "Lapland, wide, wilderness", "To the wide wilderness of Lapland,", ""),
    ("Rutjan koskehen kowahan,", "Rutjan koskeen kovaan,", "Rutja, koski, kova", "Rutja, rapids, fierce", "To the fierce rapids of Rutja,", ""),
    ("Palawahan pyörtehesen,", "Palavaan pyörteeseen,", "palava, pyörre", "burning, whirlpool", "To the burning whirlpool,", ""),
    ("Johon puut päin putoowat,", "Johon puut päin putoavat,", "johon, puu, pudota", "into which, tree, to fall", "Into which trees fall headfirst,", ""),
    ("Perin wieriwät petäjät,", "Perin vierivät petäjät,", "perin, vierähtää, petäjä", "completely, to roll, pine", "Pine trees roll away entirely,", ""),
    ("Hongat latwoin lankiawat;", "Hongat latvoin lankeavat;", "honka, latva, langeta", "old pine, treetop, to fall", "Old pines fall with their tops;", ""),
    ("Kokonansa kokkahongat,", "Kokonansa kokkahongat,", "kokonansa, kokkahonka", "entirely, hook-pine", "Entirely the hook-pines,", ""),
    ("Tywin syösten suuret hongat,", "Tyvin syösten suuret hongat,", "tyvi, syöstä, suuri, honka", "trunk-base, to thrust, great, pine", "Great pines thrust from the base,", ""),
    ("Latwoin laikkapäät petäjät.", "Latvoin laikkapäät petäjät.", "latva, laikkapää, petäjä", "treetop, patch-headed, pine", "Patch-headed pines from the top.", ""),
    ("Jos et tuostakan totelle,", "Jos et tuostakaan tottele,", "jos, ei, tuostakaan, totella", "if, not, even from that, to obey", "If you do not obey even that,", "When even the most elaborate banishment fails, Vipunen threatens to physically seize the intruder with claws taken from birds of prey — a final escalation from words to threatened violent action, showing the limits of even the most extensive verbal magic."),
    ("Otan hyiset kintahani,", "Otan hyiset kintaani,", "ottaa, hyinen, kinnas", "to take, icy, mitten", "I will take icy mittens,", ""),
    ("Maan matoset wanttuhuni,", "Maan matoset vanttuihini,", "maa, mato, vantuu", "earth, worm, glove", "Earth's worms into my gloves,", ""),
    ("Wielä saan kokolta koprat,", "Vielä saan kokolta koprat,", "vielä, saada, kokko, koura", "still, to get, eagle, claw", "I will still get claws from the eagle,", ""),
    ("Weren juojalta wekarat,", "Veren juojalta wekarat,", "veri, juoja, wekara", "blood, drinker, talon", "Talons from the blood-drinker,", ""),
    ("Linnulta lihan pitimet,", "Linnulta lihan pitimet,", "lintu, liha, pidin", "bird, flesh, grip/holder", "Flesh-grips from the bird,", ""),
    ("Hawukalta haarottimet,", "Haukalta haarottimet,", "haukka, haarotin", "hawk, spreader/fork", "Spreaders from the hawk,", ""),
    ("Joilla konnan kopristelen,", "Joilla konnan kopristelen,", "jolla, konna, kopristella", "with which, villain, to grip/clutch", "With which I will clutch the villain,", ""),
    ("Ilkiän iki asetan.", "Ilkeän iäksi asetan.", "ilkeä, ikä, asettaa", "evil one, forever, to settle", "Settle the evil one forever.", ""),
    ("Jo nyt on liitto liikkuasi,", "Jo nyt on liitto liikkuasi,", "jo, nyt, liitto, liikkua", "already, now, agreement, to move", "Now there is agreement for you to move,", ""),
    ("Saanut hetki heitteäsi,", "Saanut hetki heittäytyäsi,", "saada, hetki, heittäytyä", "to get, moment, to cast oneself", "The moment has come for you to cast off,", ""),
    ("Lähtöaika lähteäsi,", "Lähtöaika lähteäsi,", "lähtöaika, lähteä", "departure time, to leave", "The time has come for you to leave,", ""),
    ("Tehtyä teloamasta,", "Tehtyä teloamasta,", "tehty, teloa", "done, to flail/struggle", "Having been done with struggling,", ""),
    ("Hengellistä hieromasta;", "Hengellistä hieromasta;", "hengellinen, hieroa", "spiritual/breath-related, to rub/grind", "Done with the spiritual grinding;", ""),
    ("Lähe nyt liika liikkumahan,", "Lähde nyt liika liikkumaan,", "lähteä, liika, liikkua", "to leave, excess, to move", "Set off now, excess one, to move,", ""),
    ("Mies paha pakenemahan,", "Mies paha pakenemaan,", "mies, paha, paeta", "man, evil, to flee", "Evil man, to flee,", ""),
    ("Ennen päiwän nousemista,", "Ennen päivän nousemista,", "ennen, päivä, nousta", "before, day/sun, to rise", "Before the sun rises,", ""),
    ("Koi jumalan koittamista,", "Koi jumalan koittamista,", "koi, jumala, koittaa", "dawn, god, to break/dawn", "Before god's dawn breaks,", ""),
    ("Auringon ylenemistä;", "Auringon ylenemistä;", "aurinko, yletä", "sun, to rise", "Before the sun ascends;", ""),
    ("Ennen kun sanani saapi,", "Ennen kuin sanani saapi,", "ennen, kuin, sana, saapua", "before, than, word, to arrive", "Before my word arrives,", ""),
    ("Tahi mieli juohtunewi.", "Tahi mieli juohtuu.", "tahi, mieli, juohtua", "or, mind, to occur/come to mind", "Or my mind changes.", ""),
    ("Tulkohon jumalan tunti,", "Tulkoon jumalan tunti,", "tulla, jumala, tunti", "to come, god, hour", "May god's hour come,", "Vipunen's final apocalyptic flourish, describing the earth shaking and mountains trembling at the coming of god's power, escalates the rhetoric to cosmic scale — bombastic overstatement is itself a comic trickster trait, especially when it ultimately fails to expel a guest who has already decided to stay and negotiate instead."),
    ("Apu herran auetkohon.", "Apu herran auetkoon.", "apu, herra, aueta", "help, lord, to open", "May the lord's help open up.", ""),
    ("Sillon wuoret woina wuoti,", "Silloin vuoret voina vuoti,", "silloin, vuori, voi, vuotaa", "then, mountain, butter, to flow", "Then the mountains flowed like butter,", ""),
    ("Kalliot sian lihana,", "Kalliot sian lihana,", "kallio, sika, liha", "cliff/rock, pig, meat/flesh", "The cliffs like pig's flesh,", ""),
    ("Lapohina umpilammit,", "Lappoina umpilammit,", "lappo, umpilampi", "flat slab, sealed pond", "Sealed ponds like flat slabs,", ""),
    ("Ylähäiset maat aleni,", "Ylähäiset maat aleni,", "ylähäinen, maa, aletä", "upper, land, to lower", "The upper lands lowered,", ""),
    ("Alahaiset maat yleni,", "Alahaiset maat yleni,", "alahainen, maa, yletä", "lower, land, to rise", "The lower lands rose,", ""),
    ("Linnat liikku, järkky järwet,", "Linnat liikkui, järkkyi järvet,", "linna, liikkua, järkkyä, järvi", "castle, to move, to shake, lake", "Castles moved, lakes shook,", ""),
    ("Wuoret waskiset wapisi,", "Vuoret vaskiset vapisi,", "vuori, vaskinen, vapista", "mountain, copper/bronze, to tremble", "Bronze mountains trembled,", ""),
    ("Tornit linnan torkahteli,", "Tornit linnan torkahteli,", "torni, linna, torkahdella", "tower, castle, to sway/nod", "The castle's towers swayed,", ""),
    ("Tullessa jumalan tunnin,", "Tullessa jumalan tunnin,", "tulla, jumala, tunti", "to come, god, hour", "As god's hour came,", ""),
    ("Awun herran auetessa.", "Avun herran auetessa.", "apu, herra, aueta", "help, lord, to open", "As the lord's help opened.", ""),
    ("Niin sinäin liika liiku,", "Niin sinäkin liika liiku,", "niin, sinä, liika, liikkua", "so, you too, excess, to move", "So you too, excess one, move,", ""),
    ("Niin sinäi paha pakene,", "Niin sinäkin paha pakene,", "niin, sinä, paha, paeta", "so, you too, evil, to flee", "So you too, evil one, flee,", ""),
    ("Liiku liikuteltaessa,", "Liiku liikuteltaessa,", "liikkua, liikutella", "to move, to be moved", "Move when being moved,", ""),
    ("Järky järkyteltäessä.\"", "Järky järkyteltäessä.\"", "järkkyä, järkytellä", "to shake, to be shaken", "Shake when being shaken.\"", ""),
    ("Sillon wanha Wäinämöinen", "Silloin vanha Väinämöinen", "silloin, vanha, Väinämöinen", "then, old, Väinämöinen", "Then old Väinämöinen", ""),
    ("Itse tuon sanoiksi wirkki:", "Itse tuon sanoiksi virkki:", "itse, tuo, sana, virkata", "himself, that, word, to utter", "Himself uttered these words:", ""),
    ("\"Hywä täällä on ollakseni,", "\"Hyvä täällä on ollakseni,", "hyvä, täällä, olla", "good, here, to be", "\"It is good for me to be here,", "Väinämöinen's defiant, almost mocking refusal to leave despite Vipunen's terrifying curses — declaring the giant's organs delicious and that he plans to stay indefinitely — is a brilliantly trickster-like response: turning the threat back into a joke, refusing to be intimidated by even cosmic-scale magical violence, and using calm wit to outlast brute supernatural force."),
    ("Armas aikaellakseni;", "Armas aikaellakseni;", "armas, aikailla", "dear/pleasant, to pass time", "Pleasant for me to pass the time;", ""),
    ("Maksat maistawi hywältä,", "Maksat maistuvat hyvältä,", "maksa, maistua, hyvä", "liver, to taste, good", "The liver tastes good,", ""),
    ("Keuhkot käypi keitokseksi,", "Keuhkot käy keitokseksi,", "keuhko, käydä, keitos", "lung, to serve as, stew", "The lungs serve as a stew,", ""),
    ("Raswat ruuaksi pätöwi.", "Rasvat ruuaksi pätee.", "rasva, ruoka, pätee", "fat, food, to suffice/work", "The fat works well as food.", ""),
    ("Enkä lähe luonnenkana,", "Enkä lähde luonnenkaan,", "ei, lähteä, luonnenkaan", "not, to leave, by nature/at all", "Nor will I leave at all,", ""),
    ("Eriä sinä ikänä,", "Eroa sinä ikänä,", "erota, ikä", "to depart, ever", "Never depart, ever,", ""),
    ("Kun en saa sanoja kuulla,", "Kun en saa sanoja kuulla,", "kun, ei, saada, sana, kuulla", "until, not, to get, word, to hear", "Until I get to hear the words,", ""),
    ("Luoa lempiluottehia,", "Luoda lempiluotteja,", "luoda, lempi, luote", "to create, beloved, charm", "Create beloved charms,", ""),
    ("Kuulla kyllältä sanoja,", "Kuulla kyllältä sanoja,", "kuulla, kyllä, sana", "to hear, enough, word", "Hear enough words,", ""),
    ("Tuhansia tutkelmoita.\"", "Tuhansia tutkelmoita.\"", "tuhat, tutkelma", "thousand, fragment of verse", "Thousands of verse-fragments.\"", ""),
    ("Sillon wirsikäs Wipunen,", "Silloin virsikäs Vipunen,", "silloin, virsikäs, Vipunen", "then, song-filled, Vipunen", "Then the song-filled Vipunen,", ""),
    ("Jonk' oli suussa suuri tieto,", "Jonka oli suussa suuri tieto,", "jonka, suu, suuri, tieto", "whose, mouth, great, knowledge", "Whose mouth held great knowledge,", "Realizing that violence and threats have failed, Vipunen abruptly shifts strategy and gives Väinämöinen exactly what he wants — singing endless magical knowledge until the captive guest is satisfied. The negotiation succeeds where coercion failed: a battle of wills resolved through the trickster's preferred tool, persistence and clever positioning, rather than force."),
    ("Mahti ponneton powessa,", "Mahti ponneton povessa,", "mahti, ponneton, povi", "power, vast/boundless, chest/bosom", "Boundless power in his chest,", ""),
    ("Watsassa warat wäkewät,", "Vatsassa varat väkevät,", "vatsa, vara, väkevä", "stomach, resource, mighty", "Mighty resources in his stomach,", ""),
    ("Aukasi sanasen arkun,", "Avasi sanaisen arkun,", "avata, sanainen, arkku", "to open, word-filled, chest/box", "Opened the word-filled chest,", ""),
    ("Wirsilipponsa wiritti,", "Virsilippaansa viritti,", "virsilippas, virittää", "song-box, to set/tune", "Tuned his song-box,", ""),
    ("Lauloaksensa hywiä,", "Laulaakseen hyviä,", "laulaa, hyvä", "to sing, good", "To sing good ones,", ""),
    ("Parahin pannaksensa.", "Parhain pannakseen.", "paras, panna", "best, to put forth", "To put forth the very best.", ""),
    ("Ei sanat sanoihin puutu,", "Ei sanat sanoihin puutu,", "ei, sana, puuttua", "not, word, to run short", "The words do not run short of words,", ""),
    ("Wirret weisaten wähene,", "Virret veisaten vähene,", "virsi, veisata, vähentyä", "hymn, to sing, to diminish", "The hymns do not diminish in singing,", ""),
    ("Ennen kalliot kiwiä,", "Ennen kalliot kiviä,", "ennen, kallio, kivi", "sooner, cliff, stone", "Sooner cliffs run short of stones,", ""),
    ("Wirrat wienoja wesiä,", "Virrat vienoja vesiä,", "virta, vieno, vesi", "stream, gentle, water", "Streams of their gentle waters,", ""),
    ("Umpilammit ahwenia,", "Umpilammit ahvenia,", "umpilampi, ahven", "sealed pond, perch", "Sealed ponds of their perch,", ""),
    ("Aaltoja Aluen järwi.", "Aaltoja Aluen järvi.", "aalto, Alue, järvi", "wave, Alue (mythic lake), lake", "Lake Alue of its waves.", ""),
    ("Laulo päiwät pääksytysten,", "Lauloi päivät pääksytysten,", "laulaa, päivä, pääksytysten", "to sing, day, one after another", "He sang days one after another,", ""),
    ("Yhytysten yöt saneli", "Yhdytysten yöt saneli", "laulaa, yhdytysten, yö, sanella", "to sing, in succession, night, to recite", "Recited the nights in succession", ""),
    ("Ennen saatuja sanoja,", "Ennen saatuja sanoja,", "ennen, saatu, sana", "previously, gotten, word", "Words gotten before,", ""),
    ("Opituita ongelmoita,", "Opittuja ongelmoita,", "opittu, ongelma", "learned, riddle/mystery", "Learned mysteries,", ""),
    ("Wipunsa wirittämillä,", "Vipunsa virittämillä,", "vipu, virittää", "trap, to set", "From his own set traps,", ""),
    ("Ahtamilla ansatiensä.", "Ahtamillaan ansatiensä.", "ahtaa, ansatie", "to pack, trap-path", "From his packed trap-paths.", ""),
    ("Laulo synnyt syitä myöten,", "Lauloi synnyt syitä myöten,", "laulaa, synty, syy", "to sing, origin, cause", "He sang the origins by their causes,", ""),
    ("Luottehet lomia myöten;", "Luotteet lomia myöten;", "luote, loma", "charm, gap/interval", "Charms through their intervals;", ""),
    ("Pääty päiwä kuulemahan,", "Päätyi päivä kuulemaan,", "päätyä, päivä, kuulla", "to end up, sun/day, to hear", "The sun ended up listening,", ""),
    ("Pääty kuu tähyämähän,", "Päätyi kuu tähyämään,", "päätyä, kuu, tähyätä", "to end up, moon, to gaze", "The moon ended up gazing,", ""),
    ("Otawainen oppimahan,", "Otavainen oppimaan,", "Otavainen, oppia", "Great Bear (constellation), to learn", "The Great Bear ended up learning,", ""),
    ("Aallot seisottu selällä,", "Aallot seisahtui selällä,", "aalto, seisahtua, selkä", "wave, to stop, open water", "The waves stopped on the open water,", ""),
    ("Lainehet lahen perillä,", "Laineet lahen perillä,", "laine, lahti, perä", "wave, bay, far end", "The waves at the far end of the bay,", ""),
    ("Puuttu wirrat wieremästä,", "Puuttui virrat vieremästä,", "puuttua, virta, vierähtää", "to stop, stream, to flow", "The streams stopped flowing,", ""),
    ("Rutjan koski kuohumasta,", "Rutjan koski kuohumasta,", "Rutja, koski, kuohua", "Rutja, rapids, to foam/surge", "Rutja's rapids stopped surging,", ""),
    ("Wuotamasta juoksen koski,", "Vuotamasta juoksun koski,", "vuotaa, juoksu, koski", "to flow, running, rapids", "The rapids stopped their running flow,", ""),
    ("Joki Joortanan pysähty.", "Joki Joortanan pysähtyi.", "joki, Joortana, pysähtyä", "river, Jordan, to stop", "The river Jordan stopped.", "The cosmic scale of nature itself pausing to listen — sun, moon, stars, rivers, even the biblical Jordan halting — to hear Vipunen's song is a grandiose, almost comically excessive image of the power of words, fitting the trickster theme of language as the ultimate, world-altering tool."),
    ("Waka wanha Wäinämöinen", "Vakaa vanha Väinämöinen", "vakaa, vanha, Väinämöinen", "steady, old, Väinämöinen", "Steady old Väinämöinen", ""),
    ("Siitä sai sanoja kuulla,", "Siitä sai sanoja kuulla,", "siitä, saada, sana, kuulla", "from that, to get, word, to hear", "From that got to hear words,", ""),
    ("Luoa lempi luottehia;", "Luoda lempiluotteja;", "luoda, lempi, luote", "to create, beloved, charm", "To create beloved charms;", ""),
    ("Sai saoin sanoja kuulla,", "Sai satoin sanoja kuulla,", "saada, sata, sana, kuulla", "to get, hundred, word, to hear", "Got to hear words by the hundreds,", ""),
    ("Tuhansia tutkelmoita,", "Tuhansia tutkelmoita,", "tuhat, tutkelma", "thousand, fragment of verse", "Thousands of verse-fragments,", ""),
    ("Suusta Antero Wipusen,", "Suusta Antero Vipusen,", "suu, Antero Vipunen", "mouth, Antero Vipunen", "From the mouth of Antero Vipunen,", ""),
    ("Mahtipontisen powesta,", "Mahtipontisen povesta,", "mahtipontinen, povi", "mighty, chest/bosom", "From the mighty one's chest,", ""),
    ("Watsasta warawäkewän.", "Vatsasta varavoimakkaan.", "vatsa, varavoimakas", "stomach, powerfully-built", "From the powerfully-built one's stomach.", ""),
    ("Siitä wirsikäs Wipunen", "Siitä virsikäs Vipunen", "siitä, virsikäs, Vipunen", "from there, song-filled, Vipunen", "Then the song-filled Vipunen", "Having finally given Väinämöinen everything he wanted, Vipunen simply spits him back out — an almost comically anticlimactic, undignified ending to the long ordeal, a final deflating touch typical of trickster-tale conclusions where grand adventures end in mundane, even slightly absurd dismissals."),
    ("Sylkeä tomahtelewi", "Sylkeä tomahtelee", "sylkeä, tomahdella", "to spit, to puff/spurt out", "Spits him out with a puff", ""),
    ("Ulos wanhan Wäinämöisen.", "Ulos vanhan Väinämöisen.", "ulos, vanha, Väinämöinen", "out, old, Väinämöinen", "Old Väinämöinen out.", ""),
    ("Itse wanha Wäinämöinen", "Itse vanha Väinämöinen", "itse, vanha, Väinämöinen", "himself, old, Väinämöinen", "Himself old Väinämöinen", ""),
    ("Läksi suusta suuritieon,", "Lähti suusta suuritiedon,", "lähteä, suu, suuritieto", "to leave, mouth, great-knowledge (one)", "Left from the mouth of the great-knowing one,", ""),
    ("Mahtipontisen powesta,", "Mahtipontisen povesta,", "mahtipontinen, povi", "mighty, chest", "From the mighty one's chest,", ""),
    ("Watsasta warawäkewän,", "Vatsasta varavoimakkaan,", "vatsa, varavoimakas", "stomach, powerfully-built", "From the powerfully-built one's stomach,", ""),
    ("Tuli sepponsa pajahan.", "Tuli seppojensa pajaan.", "tulla, seppo, paja", "to come, smith, forge", "Came to his smith's forge.", ""),
    ("Sano seppo Ilmarinen:", "Sanoi seppo Ilmarinen:", "sanoa, seppo, Ilmarinen", "to say, smith, Ilmarinen", "Said smith Ilmarinen:", ""),
    ("\"Joko sait sanoja kuulla,", "\"Joko sait sanoja kuulla,", "jo, saada, sana, kuulla", "already, to get, word, to hear", "\"Did you get to hear the words,", ""),
    ("Luoa lempi luottehia,", "Luoda lempiluotteja,", "luoda, lempi, luote", "to create, beloved, charm", "To create beloved charms,", ""),
    ("Miten laita lasketahan,", "Miten laita lasketaan,", "miten, laita, laskea", "how, side/rail, to lower/set", "How the side rail is to be set,", ""),
    ("Perilaita liitetähän,", "Perilaita liitetään,", "perilaita, liittää", "stern rail, to join", "The stern rail joined,", ""),
    ("Kokkapuut kohennetahan?\"", "Kokkapuut kohennetaan?\"", "kokkapuu, kohentaa", "prow timber, to fit/adjust", "The prow timbers fitted?\"", ""),
    ("Sano wanha Wäinämöinen:", "Sanoi vanha Väinämöinen:", "sanoa, vanha, Väinämöinen", "to say, old, Väinämöinen", "Said old Väinämöinen:", ""),
    ("\"Jo ma sain sanoja kuulla,", "\"Jo minä sain sanoja kuulla,", "jo, minä, saada, sana, kuulla", "already, I, to get, word, to hear", "\"I have already gotten to hear the words,", ""),
    ("Luoa lempi luottehia;", "Luoda lempiluotteja;", "luoda, lempi, luote", "to create, beloved, charm", "To create beloved charms;", ""),
    ("Sain saoin sanoja kuulla,", "Sain satoin sanoja kuulla,", "saada, sata, sana, kuulla", "to get, hundred, word, to hear", "I got to hear words by the hundreds,", ""),
    ("Tuhansia tutkelmoita.\"", "Tuhansia tutkelmoita.\"", "tuhat, tutkelma", "thousand, fragment of verse", "Thousands of verse-fragments.\"", ""),
    ("Niin meni wenosen luoksi,", "Niin meni venosen luokse,", "niin, mennä, venonen, luokse", "so, to go, little boat, to/near", "So he went to the little boat,", "The episode ends with the practical, almost deflating payoff: the entire harrowing ordeal of being swallowed by a giant served only to finish a boat-building project — grand cosmic adventure in service of a mundane carpentry task, a wry undercutting typical of trickster narratives where epic effort yields modest, earthbound results."),
    ("Sai wenonen walmihiksi,", "Sai venonen valmiiksi,", "saada, venonen, valmis", "to get, little boat, ready", "Got the little boat ready,", ""),
    ("Laatineksi puinen pursi;", "Laadittu puinen pursi;", "laatia, puinen, pursi", "to construct, wooden, vessel", "The wooden vessel constructed;", ""),
    ("Heitti wenonsa teloille,", "Heitti venonsa teloille,", "heittää, vene, telat", "to throw/set, boat, rollers", "Set his boat onto the rollers,", ""),
    ("Uuen laiwan lastuillensa.", "Uuden laivan lastuillensa.", "uusi, laiva, lastu", "new, ship, wood-chip/shaving", "His new ship onto its wood-chips.", ""),
]

data_font = Font(name="Arial", size=10)
wrap_align = Alignment(wrap_text=True, vertical="top")
trickster_fill = PatternFill("solid", start_color="FFF2CC")

for row_idx, verse in enumerate(verses, 2):
    has_trickster = bool(verse[5])
    for col_idx, val in enumerate(verse, 1):
        cell = ws.cell(row=row_idx, column=col_idx, value=val)
        cell.font = data_font
        cell.alignment = wrap_align
        if has_trickster:
            cell.fill = trickster_fill

col_widths = [40, 40, 45, 55, 55, 75]
for col_idx, width in enumerate(col_widths, 1):
    ws.column_dimensions[get_column_letter(col_idx)].width = width

ws.row_dimensions[1].height = 30
ws.freeze_panes = "A2"

thin = Side(style='thin', color="CCCCCC")
border = Border(left=thin, right=thin, top=thin, bottom=thin)
for row in ws.iter_rows(min_row=1, max_row=len(verses)+1, min_col=1, max_col=6):
    for cell in row:
        cell.border = border

wb.save("/mnt/user-data/outputs/kalevala_runo10.xlsx")
print(f"Done. {len(verses)} verses processed.")
