from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

wb = Workbook()
ws = wb.active
ws.title = "Runo XXV"

headers = ["A: Alkuperäinen säe", "B: Nykysuomi", "C: Perusmuodot", "D: Käännökset (EN)", "E: Trickster-huomioita"]
header_fill = PatternFill("solid", start_color="2E4057")
header_font = Font(bold=True, color="FFFFFF", name="Arial", size=11)
for col, h in enumerate(headers, 1):
    cell = ws.cell(row=1, column=col, value=h)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

verses = [
    ("Jopa viikon vuoteltihin,", "Jo viikon vuoteltihin,", "jo, viikko, vuottaa", "already, week, to wait", ""),
    ("vuoteltihin, katseltihin", "vuoteltihin, katseltihin", "vuottaa, katsella", "to wait, to look around", ""),
    ("neion nuotehet tulevan", "neidon saapumista", "neito, saapuminen", "maiden's, arrival", ""),
    ("seppo Ilmarin kotihin:", "seppä Ilmarin kotiin:", "seppä, Ilmarinen, koti", "smith, Ilmarinen's, home", ""),
    ("silmät vanhoilta valuvi", "silmät vanhoilta valuvat", "silmä, vanha, valua", "eyes, old ones', to flow/run", ""),
    ("ikkunoissa istuessa,", "ikkunoissa istuessa,", "ikkuna, istua", "windows, while sitting", ""),
    ("polvet nuorilta nojuvi", "polvet nuorilta nojuvat", "polvi, nuori, nojua", "knees, young ones', to lean", ""),
    ("veräjillä vuottaessa,", "veräjillä vuottaessa,", "veräjä, vuottaa", "gates, while waiting", ""),
    ("lasten jalkoja paleli", "lasten jalkoja paleli", "lapsi, jalka, palella", "children's, feet, to freeze/be cold", ""),
    ("seinuksilla seisoessa,", "seinuksilla seisoessa,", "seinä, seistä", "walls, while standing", ""),
    ("kului kengät kesk'-iältä", "kului kengät keski-iältä", "kulua, kenkä, keski-ikä", "to wear out, shoes, middle-age", ""),
    ("rantasilla raittaessa.", "rannoilla raittaessa.", "ranta, raitti", "shores, on the road/path", ""),
    ("Niin huomenna muutamana,", "Niin eräänä huomenna,", "niin, eräänä, huominen", "so, one, next morning", ""),
    ("päivänä moniahana", "päivänä moniahana", "päivä, moninainen", "day, many/various", ""),
    ("kumu kuuluvi salolta,", "kumu kuuluu salolta,", "kumu, kuulua, salo", "rumble, to be heard, wilderness", ""),
    ("reen kapina kankahalta.", "reen kapina kankaalta.", "reki, kapina, kangas", "sled's, rattle/noise, heath/plain", ""),
    ("Lokka, luopuisa emäntä,", "Lokka, luopuisa emäntä,", "Lokka, luopuisa, emäntä", "Lokka (name), yielding/giving, mistress", ""),
    ("Kalevatar, kaunis vaimo,", "Kalevalatar, kaunis vaimo,", "Kalevalatar, kaunis, vaimo", "Kalevalatar (name), beautiful, woman/wife", ""),
    ("sanan virkkoi, noin nimesi:", "sanan virkkoi, noin nimitti:", "sana, virkkoa, nimittää", "word, to say, to name/call", ""),
    ("\"Se on poikani rekonen!", "\"Se on poikani rekonen!", "se, olla, poika, reki", "that, to be, son's, sled", ""),
    ("Jo tulevi Pohjolasta", "Jo tulee Pohjolasta", "jo, tulla, Pohjola", "already, to come, Northland", ""),
    ("nuoren neitonsa keralla!", "nuoren neitonsa kanssa!", "nuori, neito, kanssa", "young, maiden's, with", ""),
    ("\"Lähes nyt kohti näitä maita,", "\"Lähes nyt kohti näitä maita,", "lähestyä, nyt, kohti, tämä, maa", "to approach, now, toward, these, lands", "Lokka's welcome — 'come toward these lands, toward these estates, to the father's gotten cottages, the elder's prepared ones' — is Ilmarinen's mother performing the ideal welcoming mother-in-law, the counter-image to Louhi."),
    ("kohin näitä kartanoita,", "kohti näitä kartanoita,", "kohti, tämä, kartano", "toward, these, estates/yards", ""),
    ("ison saamille tuville,", "isän saamille tuville,", "isä, saada, tupa", "father's, gotten, cottages/halls", ""),
    ("vanhemman varustamille!\"", "vanhemman varustamille!\"", "vanhempi, varustaa", "elder's/parent's, prepared", ""),
    ("Se on seppo Ilmarinen", "Se on seppä Ilmarinen", "se, seppä, Ilmarinen", "that, smith, Ilmarinen", ""),
    ("jo kohta kotihin saapi,", "jo kohta kotiin saapuu,", "jo, kohta, koti, saapua", "already, soon, home, to arrive", ""),
    ("ison saamille pihoille,", "isän saamille pihoille,", "isä, saada, piha", "father's, gotten, yards", ""),
    ("vanhemman varustamille.", "vanhemman varustamille.", "vanhempi, varustaa", "elder's/parent's, prepared", ""),
    ("Pyyhyet vihertelevät", "Pyyhyet vihertelevät", "pyyhe, vihertää", "streamers/tassels, to be green/flutter", ""),
    ("vesaisilla vempelillä,", "vesaisilla vempelillä,", "vesainen, vempele", "sapling-made, swingletree", ""),
    ("käkyet kukahtelevat", "käet kukahtelevat", "käki, kukahtaa", "cuckoos, to cuckoo-call/ring out", ""),
    ("korjan kirjavan kokalla,", "korjan kirjavan kokalla,", "korja, kirjava, kokka", "decorated sleigh's, patterned, bow/front", ""),
    ("oravat samoelevat", "oravat samoelevat", "orava, samoilla", "squirrels, to wander/roam", ""),
    ("päällä aisan vaahterisen.", "päällä aisan vaahterisen.", "päällä, aisa, vaahtera", "over, shaft, maple", ""),
    ("Lokka, luopuisa emäntä,", "Lokka, luopuisa emäntä,", "Lokka, luopuisa, emäntä", "Lokka, yielding/giving, mistress", ""),
    ("Kalevatar, vaimo kaunis,", "Kalevalatar, vaimo kaunis,", "Kalevalatar, vaimo, kaunis", "Kalevalatar, woman/wife, beautiful", ""),
    ("tuossa tuon sanoiksi virkki,", "tuossa tuon sanoiksi sanoi,", "tuossa, tuo, sana, virkkoa", "there, those, words, to say", ""),
    ("itse lausui, noin nimesi:", "itse lausui, noin nimitti:", "itse, lausua, nimittää", "herself, to utter, to name/call", ""),
    ("\"Kylä vuotti uutta kuuta,", "\"Kylä vuotti uutta kuuta,", "kylä, vuottaa, uusi, kuu", "village, to wait, new, moon", ""),
    ("nuoret päivän nousentoa,", "nuoret päivän nousua,", "nuori, päivä, nousu", "young ones', sun's, rising", ""),
    ("lapset maata mansikkaista,", "lapset maata mansikkaista,", "lapsi, maa, mansikka", "children, land, strawberry", ""),
    ("vesi tervaista venettä;", "vesi tervaista venettä;", "vesi, tervainen, vene", "water, tarred, boat", ""),
    ("mie en kuuta puolinkana,", "minä en kuuta puolinkaan,", "minä, ei, kuu, puolinkaan", "I, not, moon, not even half", ""),
    ("päiveä mokominkana:", "päivää moisinkaan:", "päivä, moinen", "sun/day, such a", ""),
    ("minä vuotin veijoani,", "minä vuotin veljeäni,", "minä, vuottaa, veli", "I, to wait, brother", ""),
    ("veijoani, minjoani.", "veljeäni, miniääni.", "veli, miniä", "my brother, my daughter-in-law", ""),
    ("Katsoin aamun, katsoin illan,", "Katsoin aamun, katsoin illan,", "katsoa, aamu, ilta", "to look, morning, evening", ""),
    ("en tiennyt, mihin katosi,", "en tiennyt, minne katosi,", "ei, tietää, minne, kadota", "not, to know, where, to disappear", ""),
    ("tokko pientä kasvatteli", "tokko pientä kasvatteli", "tokko, pieni, kasvattaa", "perhaps, small one, to raise/grow", ""),
    ("vaiko laihoa lihoitti,", "vaiko laihoa lihoitti,", "vai, laiha, lihottaa", "or, thin/lean, to fatten", ""),
    ("kun ei tullut kuitenkana,", "kun ei tullut kuitenkaan,", "kun, ei, tulla, kuitenkaan", "when, not, to come, however", ""),
    ("vaikka varsinki lupasi", "vaikka varsinkin lupasi", "vaikka, varsinkin, luvata", "even though, especially, to promise", ""),
    ("tulla jälen tuntuessa,", "tulla jälen tuntuessa,", "tulla, jälki, tuntua", "to come, track, while feeling", ""),
    ("saa'a jälen jäähtymättä.", "saapua jälen jäähtymättä.", "saapua, jälki, jäähtyä", "to arrive, track, without cooling", ""),
    ("\"Aina katsoin aamusilla,", "\"Aina katsoin aamuisin,", "aina, katsoa, aamu", "always, to look, mornings", ""),
    ("päivät päässäni pitelin,", "päivät päässäni pidin,", "päivä, pää, pitää", "days, head, to keep/hold", ""),
    ("kun ei vieri veijon saani,", "kun ei vieriyt veikon saani,", "kun, ei, vierähtää, veikko, saani", "when, not, to glide, brother's, sled", ""),
    ("ei kolaja veijon korja,", "ei kolanut veikon korja,", "ei, kolata, veikko, korja", "not, to rattle, brother's, sleigh", ""),
    ("näille pienille pihoille,", "näille pienille pihoille,", "tämä, pieni, piha", "these, small, yards", ""),
    ("kape'ille kartanoille.", "kapeille kartanoille.", "kapea, kartano", "narrow, estates/yards", ""),
    ("Oisko olkinen oronen,", "Olisiko olkinen oriinen,", "olla, olkinen, ori", "to be, straw-made, stallion", ""),
    ("reki kaksikaplahinen,", "reki kaksikaplaisinen,", "reki, kaksikaplanen", "sled, two-runnered", ""),
    ("senki saaniksi sanoisin,", "senkin saaniksi sanoisin,", "sekin, saani, sanoa", "that too, as a sled, to say", ""),
    ("korjaksi korotteleisin,", "korjaksi korotteleisi,", "korja, korotella", "as a sleigh, to praise/elevate", ""),
    ("jos se veijoni vetäisi,", "jos se veljeäni vetäisi,", "jos, se, veli, vetää", "if, that, brother, to pull", ""),
    ("toisi kaunoni kotihin.", "toisi kaunoni kotiin.", "tuoda, kaunoinen, koti", "to bring, beautiful one, home", ""),
    ("\"Niinpä toivoin tuon ikäni,", "\"Niinpä toivoin tuon ikäni,", "niin, toivoa, tuo, ikä", "so, to hope/wish, that, lifetime", ""),
    ("katsoin kaiken päiväkauen;", "katsoin kaiken päiväkauen;", "katsoa, kaikki, päiväkausi", "to look, all, day-season", ""),
    ("pääni katsoin kallellehen,", "päätäni katsoin kallellehen,", "pää, katsoa, kallelleen", "head, to look, tilted", ""),
    ("sykeröni syrjällehen,", "sykeröni syrjällehen,", "sykerö, syrjä", "my curly-head, to the side", ""),
    ("silmät suorat suikulaksi:", "silmät suorat suikulaksi:", "silmä, suora, suikula", "eyes, straight, into slits", ""),
    ("toivoin veijoni tulevan", "toivoin veljeäni tulevan", "toivoa, veli, tulla", "to hope/wish, brother, coming", ""),
    ("näille pienille pihoille,", "näille pienille pihoille,", "tämä, pieni, piha", "these, small, yards", ""),
    ("kape'ille kartanoille.", "kapeille kartanoille.", "kapea, kartano", "narrow, estates/yards", ""),
    ("Jo tuo viimeinki tulevi,", "Jo tuo viimeinkin tulee,", "jo, tuo, viimein, tulla", "already, that, finally, to come", ""),
    ("toki kerran kerkiävi,", "toki kerran kerkeää,", "toki, kerta, kerkiää", "however, once, to be in time/manage", ""),
    ("vierellä verevä", "vierellä verevä", "vieri, verevä", "beside, ruddy/fresh", ""),
    ("muoto, punaposki puolellansa!", "muoto, punaposki puolellansa!", "muoto, punaposki, puoli", "form/looks, red-cheeked, side", ""),
    ("\"Sulho, viljon veljyeni!", "\"Sulho, viljan veljyeni!", "sulho, vilja, veli", "groom/suitor, dear/abundant, brother", ""),
    ("Lasketapa laukkiotsa,", "Laske laukkiasi,", "laskea, laukki", "to lower/release, steed", ""),
    ("vietätä hyvä hevonen", "vie hyvä hevonen", "viedä, hyvä, hevonen", "to take, good, horse", ""),
    ("entisille heinillensä,", "entisille heinilleen,", "entinen, heinä", "former, hay", ""),
    ("taanoisille kauroillensa!", "taanoisille kauroilleen!", "tanoinen, kaura", "former, oats", ""),
    ("Laai meille terveyttä,", "Laita meille terveyttä,", "laittaa, me, terveys", "to make, us, health/greeting", ""),
    ("laai meille, laai muille,", "laita meille, laita muille,", "laittaa, me, muu", "to make, us, others", ""),
    ("laai kaikelle kylälle!", "laita kaikelle kylälle!", "laittaa, kaikki, kylä", "to make, all, village", ""),
    ("\"Tehtyäsi tervehyiset", "\"Tehtyäsi tervehdykset", "tehdä, tervehdys", "having made, greetings", ""),
    ("sanele tarinojasi:", "sanele tarinoitasi:", "sanella, tarina", "to recite/tell, stories", ""),
    ("matkasitko mainehitta,", "matkasitko mainehitta,", "matkustaa, maine", "to travel, reputation/honour", ""),
    ("kävit tiesi tervehenä,", "kävit tiesi terveenä,", "käydä, tie, terve", "to go, road, healthy/whole", ""),
    ("kun läksit anopin luoksi,", "kun läksit anopin luokse,", "kun, lähteä, anoppi, luokse", "when, to set out, mother-in-law's, near", ""),
    ("apen ainoan kotihin?", "apen ainoan kotiin?", "appi, ainoinen, koti", "father-in-law's, only, home", ""),
    ("Saitko neien, voitit vallan,", "Saitko neidon, voitit vallan,", "saada, neito, voittaa, valta", "to get, maiden, to win, power", ""),
    ("sorritko sotiveräjän,", "sorritko sotiveräjän,", "sortaa, sota, veräjä", "to topple, war's, gate", ""),
    ("levititkö neien linnan,", "levititkö neidon linnan,", "levittää, neito, linna", "to spread/open, maiden's, castle/hall", ""),
    ("pirotitko pystyn seinän,", "pirotitko pystyn seinän,", "pirottaa, pysty, seinä", "to scatter/topple, upright, wall", ""),
    ("astuitko anopin sillan,", "astuitko anopin sillan,", "astua, anoppi, silta", "to stride, mother-in-law's, bridge/floor", ""),
    ("istuitko isännän lautsan?", "istuitko isännän lautsan?", "istua, isäntä, lavitsa", "to sit, master's, bench", ""),
    ("\"Jo tuon näen kyselemättä,", "\"Jo tuon näen kysymättä,", "jo, nähdä, tuo, kysymättä", "already, to see, that, without asking", ""),
    ("arvoan anelematta:", "arvaan anelematta:", "arvata, anella", "to guess/know, without begging", ""),
    ("kävipä tiensä tervehenä,", "kävipä tiensä terveenä,", "käydä, tie, terve", "to go, road, healthy/whole", ""),
    ("matkansa imantehena;", "matkansa imartehena;", "matka, imarteinen", "journey, fine/admirable", ""),
    ("toip' on hanhen, voitti vallan,", "toi hanhen, voitti vallan,", "tuoda, hanhi, voittaa, valta", "to bring, goose, to win, power", ""),
    ("sortipa sotiveräjän,", "sortipa sotiveräjän,", "sortaa, sota, veräjä", "to topple, war's, gate", ""),
    ("langettipa lautalinnan,", "langettipa lautalinnan,", "langettaa, lauta, linna", "to cause to fall, plank, castle/hall", ""),
    ("levitteli lehmusseinän", "levitteli lehmusseinän", "levitellä, lehmus, seinä", "to spread/open, linden-wood, wall", ""),
    ("käyessä anopin luona,", "käydessä anopin luona,", "käydä, anoppi, luona", "while going, mother-in-law's, near", ""),
    ("apen ainoan ko'issa.", "apen ainoan kotona.", "appi, ainoinen, koti", "father-in-law's, only, home", ""),
    ("Onp' on sotka suojassansa,", "On sotka suojassansa,", "olla, sotka, suoja", "to be, diving duck, shelter/protection", ""),
    ("kana kainaloisessansa,", "kana kainalossansa,", "kana, kainalos", "hen/girl, armpit/embrace", ""),
    ("puhas neiti puolellansa,", "puhdas neiti puolellansa,", "puhdas, neito, puoli", "pure/clean, maiden, side", ""),
    ("valkeainen valloissansa.", "valkeainen vallassansa.", "valkea, valta", "white/bright one, in his keeping", ""),
    ("\"Kenpä toi tämän valehen,", "\"Kenpä toi tämän valheen,", "kuka, tuoda, tämä, valhe", "who, to bring, this, lie/falsehood", ""),
    ("ken pani pahan sanoman,", "ken pani pahan sanoman,", "kuka, panna, paha, sanoma", "who, to put, bad, message/news", ""),
    ("sulhon tyhjin tulleheksi,", "sulhon tyhjin tulleeksi,", "sulho, tyhjin, tulla", "groom/suitor, emptily, to have come", ""),
    ("oron jouten juosneheksi?", "orin jouten juosseeksi?", "ori, jouten, juosta", "stallion's, idly, to have run", ""),
    ("Eipä sulho tyhjin tullut,", "Eipä sulho tyhjin tullut,", "ei, sulho, tyhjin, tulla", "not, groom/suitor, emptily, to come", ""),
    ("ei oronen jouten juosnut:", "ei oriinen jouten juosnut:", "ei, ori, jouten, juosta", "not, stallion, idly, to run", ""),
    ("on mitä oron veteä,", "on mitä orin vetää,", "olla, mitä, ori, vetää", "to be, what/something, stallion, to pull", ""),
    ("liinaharjan liikutella!", "liinaharjan liikutella!", "liina, harja, liikuttaa", "linen, mane, to move", ""),
    ("Hiessäpä hyvä hevonen,", "Hiessä hyvä hevonen,", "hiki, hyvä, hevonen", "in sweat, good, horse", ""),
    ("vaahessa valittu varsa", "vaahessa valittu varsa", "vaahto, valittu, varsa", "in foam, chosen, foal", ""),
    ("tuvun tänne tuotuansa,", "tuvun tänne tuotuansa,", "tupa, tänne, tuoda", "cottage/hall, here, having brought", ""),
    ("verevän ve'ettyänsä.", "verevän vedettyänsä.", "verevä, vetää", "ruddy/fresh one, having pulled/drawn", ""),
    ("\"Nouse nyt korjasta, korea,", "\"Nouse nyt korjasta, korea,", "nousta, nyt, korja, korea", "to rise, now, sleigh, beautiful/fine", ""),
    ("hyvä lahja, laitiosta!", "hyvä lahja, laidasta!", "hyvä, lahja, laita", "good, gift, side/edge", ""),
    ("Nouse ilman nostamatta,", "Nouse ilman nostamatta,", "nousta, ilman, nostaa", "to rise, without, raising", ""),
    ("ylene ylentämättä,", "ylene ylentämättä,", "yletä, ylentää", "to rise, without lifting", ""),
    ("jos on nuori nostajasi,", "jos on nuori nostajasi,", "jos, olla, nuori, nostaja", "if, to be, young, raiser", ""),
    ("ylpeä ylentäjäsi!", "ylpeä ylentäjäsi!", "ylpeä, ylentäjä", "proud, lifter", ""),
    ("\"Korjasta kohottuasi,", "\"Korjasta kohottuasi,", "korja, kohota", "sleigh, having risen", ""),
    ("reen perästä päästyäsi", "reen perästä päästyäsi", "reki, perä, päästä", "sled's, back/stern, having gotten free", ""),
    ("astu tietä temminkäistä,", "astu tietä temminkäistä,", "astua, tie, temminkäinen", "to stride, road, worn-down", ""),
    ("maata maksankarvallista,", "maata maksankarvallista,", "maa, maksa, karvainen", "land, liver-coloured", ""),
    ("sikojen silittämäistä,", "sikojen silittämistä,", "sika, silittää", "pigs', stroked/worn smooth", ""),
    ("porsahien polkemaista,", "porsaiden polkemaa,", "porsas, polkea", "piglets', trampled", ""),
    ("lampahan latsottamaista,", "lampaan latsomaa,", "lammas, latsoa", "sheep's, trodden flat", ""),
    ("hevon harjan hieromaista!", "hevosen harjan hieromaista!", "hevonen, harja, hieroa", "horse's, mane, rubbed/worn", ""),
    ("\"Astu hanhen askelilla,", "\"Astu hanhen askelilla,", "astua, hanhi, askel", "to stride, goose's, steps", ""),
    ("taputa tavin jaloilla", "taputa tavin jaloilla", "taputella, tavi, jalka", "to pat/step, teal's, feet", ""),
    ("näitä pestyjä", "näitä pestyjä", "nämä, pestä", "these, washed", ""),
    ("pihoja, tasaisia tanteria,", "pihoja, tasaisia tanteria,", "piha, tasainen, tanner", "yards, even/flat, ground/field", ""),
    ("apen saamia pihoja,", "apen saamia pihoja,", "appi, saada, piha", "father-in-law's, gotten, yards", ""),
    ("anopin asettamia,", "anopin asettamia,", "anoppi, asettaa", "mother-in-law's, set/prepared", ""),
    ("veljen veistopenkeriä,", "veljen veistopenkeriä,", "veli, veisto, penkereen", "brother's, carved, embankments", ""),
    ("sisaren siniketoja!", "sisaren siniketoja!", "sisar, sininen, keto", "sister's, blue, meadow/field", ""),
    ("Pole jalka portahalle,", "Pole jalka portaalle,", "polkea, jalka, porras", "to stamp/step, foot, step/stair", ""),
    ("siirrä sintsin siltaselle,", "siirrä eteisen sillalle,", "siirtää, eteinen, silta", "to move, entrance hall's, bridge/floor", ""),
    ("astu sintsiä simaista;", "astu eteistä simaista;", "astua, eteinen, simainen", "to stride, entrance hall, honey/mead-like", ""),
    ("siitä siirräite sisähän,", "siitä siirry sisään,", "siitä, siirtyä, sisään", "from that, to move, inside", ""),
    ("alle kuulun kurkihirren,", "alle kuulun kurkihirren,", "alla, kuulu, kurkihirsi", "under, renowned, ridgepole/main beam", ""),
    ("alle kaunihin katoksen!", "alle kauniin katoksen!", "alla, kaunis, katos", "under, beautiful, roof/shelter", ""),
    ("\"Jo täällä tämänki talven,", "\"Jo täällä tänäkin talvena,", "jo, täällä, tänäkin, talvi", "already, here, this too, winter", "Lokka's catalogue of the house longing for the daughter-in-law — 'this whole winter and last summer the duck-bone bridge rang for one who stood on it, the golden roof boomed for one who walked under it, the windows rejoiced for one who sat in them' — is the trickster-mother's poetic claim that the house itself has been waiting."),
    ("jopa mennehen kesosen", "jo menneen kesän", "jo, mennyt, kesä", "already, past, summer", ""),
    ("silta soitti sorsanluinen", "silta soitti sorsanluinen", "silta, soittaa, sorsa, luu", "bridge/floor, to sound, duck's, bone", ""),
    ("sillallista seisojaista,", "sillallista seisojaista,", "silta, seisoja", "bridge/floor's, stander/one who stands", ""),
    ("laki kultainen kumisi", "laki kultainen kumisi", "laki, kultainen, kumista", "roof/ceiling, golden, to boom/resound", ""),
    ("laen alla astujaista,", "laen alla astujaista,", "laki, alla, astuja", "roof/ceiling, under, walker/one who walks", ""),
    ("ikkunat iloittelihe", "ikkunat iloittelihe", "ikkuna, iloitella", "windows, to rejoice", ""),
    ("ikkunaisten istujaista.", "ikkunaisten istujaista.", "ikkuna, istuja", "windows', sitter/one who sits", ""),
    ("\"Jo täällä tämänki talven,", "\"Jo täällä tänäkin talvena,", "jo, täällä, tänäkin, talvi", "already, here, this too, winter", ""),
    ("jopa mennehen kesosen", "jo menneen kesän", "jo, mennyt, kesä", "already, past, summer", ""),
    ("kääkäset käkertelihe", "kääkäset käkertelihe", "kääkänen, käkertellä", "old crones/hinges, to chatter/creak", ""),
    ("sormuskättä sulkijaista,", "sormuskättä sulkijaista,", "sormuskas, sulkija", "ring-handed, closer/one who closes", ""),
    ("kynnykset kykertelihe", "kynnykset kykertelihe", "kynnys, kykertellä", "thresholds, to creak/groan", ""),
    ("hienohelman hempujaista,", "hienohelman hempujaista,", "hienohelma, hempuja", "fine-hemmed, gentle-stepper", ""),
    ("ovet aina aukieli", "ovet aina aukeni", "ovi, aina, aueta", "doors, always, to open", ""),
    ("ovellista aukojaista.", "ovellista aukojaista.", "ovi, aukoja", "door's, opener/one who opens", ""),
    ("\"Jo täällä tämänki talven,", "\"Jo täällä tänäkin talvena,", "jo, täällä, tänäkin, talvi", "already, here, this too, winter", ""),
    ("jopa mennehen kesosen", "jo menneen kesän", "jo, mennyt, kesä", "already, past, summer", ""),
    ("perin pirtti pyörähteli", "perin pirtti pyörähteli", "perin, pirtti, pyörähtää", "thoroughly, cottage, to spin/turn", ""),
    ("pirtillistä pyyhkijäistä,", "pirtillistä pyyhkijäistä,", "pirtti, pyyhkijä", "cottage's, sweeper/one who sweeps", ""),
    ("sintsinen sijoittelihe", "sintsinen sijoittelihe", "eteinen, sijoitella", "entrance hall, to settle/place", ""),
    ("sintsillistä siivojaista,", "sintsillistä siivojaista,", "eteinen, siivooja", "entrance hall's, cleaner/one who cleans", ""),
    ("vajaset vasertelihe", "vajaset vasertelihe", "vaja, vasertella", "sheds, to rustle/stir", ""),
    ("vajallista vastakättä.", "vajallista vastakättä.", "vaja, vastakäsi", "shed's, other-hand/helper", ""),
    ("\"Jo täällä tämänki talven,", "\"Jo täällä tänäkin talvena,", "jo, täällä, tänäkin, talvi", "already, here, this too, winter", ""),
    ("jopa mennehen kesosen", "jo menneen kesän", "jo, mennyt, kesä", "already, past, summer", ""),
    ("piha piilten kääntelihe", "piha piilten käänteli", "piha, piilten, käännellä", "yard, secretly, to turn", ""),
    ("lastun pitkän poimijaista,", "lastun pitkän poimijaista,", "lastu, pitkä, poimija", "long chip/splinter, picker/one who picks", ""),
    ("aittaset alentelihe", "aittaset alentelihe", "aitta, alennella", "storehouses, to lower/descend", ""),
    ("aitallista astujaista,", "aitallista astujaista,", "aitta, astuja", "storehouse's, walker/one who walks", ""),
    ("orret notkui, parret painui", "orret notkui, parret painui", "orsi, notkua, parsi, painua", "rafters, to bend/sag, beams, to sink", ""),
    ("nuoren vaimon vaattehia.", "nuoren vaimon vaatteita.", "nuori, vaimo, vaate", "young, woman's/wife's, clothes", ""),
    ("\"Jo täällä tämänki talven,", "\"Jo täällä tänäkin talvena,", "jo, täällä, tänäkin, talvi", "already, here, this too, winter", ""),
    ("jopa mennehen kesosen", "jo menneen kesän", "jo, mennyt, kesä", "already, past, summer", ""),
    ("kujaset kukertelihe", "kujaset kukertelihe", "kuja, kukertella", "lanes, to hum/bend", ""),
    ("kujallista kulkijaista,", "kujallista kulkijaista,", "kuja, kulkija", "lane's, traveller/one who travels", ""),
    ("lääväset lähentelihe", "lääväset lähentelihe", "läävä, lähennellä", "barns, to approach/come near", ""),
    ("läävällistä läänijäistä,", "läävällistä läänijäistä,", "läävä, läänijä", "barn's, tending one/one who tends", ""),
    ("tanhuaiset taantelihe", "tanhuaiset taantelihe", "tarha, taantua", "yards/pens, to draw back", ""),
    ("tanhuallista tavia.", "tanhuallista tavia.", "tarha, tapa", "yard's/pen's, custom/habit", ""),
    ("\"Jo täällä tämänki päivän,", "\"Jo täällä tänäkin päivänä,", "jo, täällä, tänäkin, päivä", "already, here, this too, day", ""),
    ("jopa päivän eilisenki", "jo eilisen päivän", "jo, eilen, päivä", "already, yesterday's, day", ""),
    ("aioin ammoi aikalehmä", "juuri ammoi ikuinen lehmä", "juuri, ammua, ikuinen, lehmä", "just, to moo, eternal, cow", ""),
    ("aamuvihkon antajaista,", "aamuvihkon antajaista,", "aamu, vihko, antaja", "morning's, bundle, giver/one who gives", ""),
    ("hevoisvarsa hirnakoitsi", "hevoisvarsa hirnakoitsi", "hevonen, varsa, hirnua", "horse's, foal, to neigh", ""),
    ("heinävihkon heittäjäistä,", "heinävihkon heittäjäistä,", "heinä, vihko, heittäjä", "hay's, bundle, thrower/one who throws", ""),
    ("kaikerti kevätkaritsa", "kaikerti kevätkaritsa", "kaiverta, kevät, karitsa", "to gnaw/bleat, spring's, lamb", ""),
    ("palasen parantajaista.", "palasen parantajaista.", "pala, parantaja", "piece/morsel, improver/one who improves", ""),
    ("\"Jo täällä tämänki päivän,", "\"Jo täällä tänäkin päivänä,", "jo, täällä, tänäkin, päivä", "already, here, this too, day", ""),
    ("jopa päivän eilisenki", "jo eilisen päivän", "jo, eilen, päivä", "already, yesterday's, day", ""),
    ("vanhat istui ikkunoissa,", "vanhat istuivat ikkunoissa,", "vanha, istua, ikkuna", "old ones, to sit, windows", ""),
    ("lapset raittoi rantasilla,", "lapset raiteilla rannoilla,", "lapsi, raitti, ranta", "children, roads/paths, shores", ""),
    ("naiset seisoi seinuksilla,", "naiset seisoivat seinuksilla,", "nainen, seistä, seinä", "women, to stand, walls", ""),
    ("pojat porstuan ovilla", "pojat porstuan ovilla", "poika, porstua, ovi", "boys, porch's, doors", ""),
    ("nuoren vaimon varronnassa,", "nuoren vaimon varronnassa,", "nuori, vaimo, varoa", "young, woman's/wife's, watching/waiting", ""),
    ("morsiamen vuotannassa.", "morsiamen vuotannassa.", "morsian, vuottaa", "bride's, waiting for", ""),
    ("\"Terve nyt, piha täysinesi,", "\"Terve nyt, piha täysinesi,", "terve, nyt, piha, täynnä", "greetings, now, yard, full", ""),
    ("ulkoinen urohinesi,", "ulkoinen urohinesi,", "ulkoinen, uros", "outer/external, with your heroes/men", ""),
    ("terve, vaja täysinesi,", "terve, vaja täysinesi,", "terve, vaja, täynnä", "greetings, shed, full", ""),
    ("vaja vierahaisinesi,", "vaja vierahaisinesi,", "vaja, vieras", "shed, with your strangers/guests", ""),
    ("terve, sintsi täysinesi,", "terve, eteinen täysinesi,", "terve, eteinen, täynnä", "greetings, entrance hall, full", ""),
    ("tuohikatto kansoinesi,", "tuohikatto kansoinesi,", "tuohi, katto, kansa", "birch-bark, roof, with your people", ""),
    ("terve, pirtti täysinesi,", "terve, pirtti täysinesi,", "terve, pirtti, täynnä", "greetings, cottage, full", ""),
    ("satalauta lapsinesi,", "satalauta lapsinesi,", "sata, lauta, lapsi", "hundred-planked, with your children", ""),
    ("terve, kuu, terve, kuningas,", "terve, kuu, terve, kuningas,", "terve, kuu, kuningas", "greetings, moon, greetings, king", ""),
    ("terve nuori nuoekansa!", "terve nuori nuoekansa!", "terve, nuori, nuori, kansa", "greetings, young, young, people/folk", ""),
    ("Ei ole tässä ennen ollut,", "Ei ole tässä ennen ollut,", "ei, olla, tässä, ennen, olla", "not, to have been, here, before", ""),
    ("eipä ennen eikä eilen", "eipä ennen eikä eilen", "ei, ennen, eikä, eilen", "not, before, nor, yesterday", ""),
    ("tämän joukon juoleutta,", "tämän joukon juoleutta,", "tämä, joukko, juoleus", "this, crowd's, elegance/fineness", ""),
    ("tämän kansan kauneutta.", "tämän kansan kauneutta.", "tämä, kansa, kauneus", "this, people's, beauty", ""),
    ("\"Sulho, viljon veljyeni!", "\"Sulho, viljan veljyeni!", "sulho, vilja, veli", "groom/suitor, dear/abundant, brother", ""),
    ("Pura pois punaiset paikat,", "Pura pois punaiset paikat,", "purkaa, pois, punainen, paikka", "to undo, away, red, places/spots", ""),
    ("sivalluta silkkiverhot!", "sivalluta silkkiverhot!", "sivaltaa, silkki, verho", "to slash/draw aside, silk, curtains", ""),
    ("Näytä tuota näätäistäsi,", "Näytä tuota näätäistäsi,", "näyttää, tuo, näätäinen", "to show, that, little marten", ""),
    ("viisin vuosin käytyäsi,", "viisin vuosin käytyäsi,", "viisi, vuosi, käydä", "five, years, having been/gone", ""),
    ("kaheksin katseltuasi!", "kahdeksin katseltuasi!", "kahdeksan, katsella", "eight, having looked", ""),
    ("\"Tokko toit, kenen käkesit?", "\"Tokko toit, kenen käit hakemaan?", "tokko, tuoda, kuka, käydä, hakea", "perhaps, to bring, whom, to go, to fetch", ""),
    ("Käkesit käkösen tuoa,", "Käit käkösen hakemaan,", "käydä, käki, hakea", "to go, cuckoo, to fetch", ""),
    ("maalta valkean valita,", "maalta valkean valita,", "maa, valkea, valita", "land, white/bright one, to choose", ""),
    ("vesiltä verevän saa'a.", "vesiltä verevän saada.", "vesi, verevä, saada", "waters, ruddy/fresh one, to get", ""),
    ("\"Jo tuon näen kyselemättä,", "\"Jo tuon näen kysymättä,", "jo, nähdä, tuo, kysymättä", "already, to see, that, without asking", ""),
    ("arvoan anelematta:", "arvaan anelematta:", "arvata, anella", "to guess/know, without begging", ""),
    ("toit käkösen tullessasi,", "toit käkösen tullessasi,", "tuoda, käki, tulla", "to bring, cuckoo, while coming", ""),
    ("sinisotkan suojassasi,", "sinisotkan suojassasi,", "sininen, sotka, suoja", "blue, diving duck, shelter/protection", ""),
    ("vihannimman virven latvan", "vihannimman virven latvan", "vihanta, virpi, latva", "greenest, twig/young branch, crown/top", ""),
    ("vihannasta virviköstä,", "vihannasta virviköstä,", "vihanta, virvikko", "green, twig-thicket", ""),
    ("tuorehimman tuomen lehvän", "tuoreimman tuomen lehvän", "tuore, tuomi, lehvä", "freshest, bird-cherry's, branch/frond", ""),
    ("tuorehesta tuomikosta.\"", "tuoreesta tuomikosta.\"", "tuore, tuomikko", "fresh, bird-cherry grove", ""),
    ("Olipa lapsi lattialla.", "Olipa lapsi lattialla.", "olla, lapsi, lattia", "to be, child, floor", ""),
    ("Lausui lapsi lattialta:", "Lausui lapsi lattialta:", "lausua, lapsi, lattia", "to utter, child, floor", ""),
    ("\"Voi veikko, mitä vetelet!", "\"Voi veikko, mitä vetelet!", "voi, veikko, mitä, vetää", "woe, brother, what, to pull/drag", ""),
    ("Tervaskannon kauneutta,", "Tervaskannon kauneutta,", "tervaskangas, kauneus", "tarry-stump's, beauty", ""),
    ("tervapuolikon pituutta,", "tervapuolikon pituutta,", "terva, puolikko, pituus", "tar, half-keg's, length", ""),
    ("kerinkannan korkeutta!", "kerinkannan korkeutta!", "keri, kanta, korkeus", "winding-stick's, heel, height", "The child on the floor's mock critique of the bride — 'the beauty of a tarry stump, the length of a tar half-keg, the height of a ball-winder's heel!' — is the trickster-child's counter-voice to Lokka's elaborate praise-catalogue, the comic deflation of the entire ceremonial welcome."),
    ("\"Kutti, kutti, sulho rukka!", "\"Kutti, kutti, sulho rukka!", "kutti, sulho, rukka", "hush/chick-call, groom/suitor, poor", ""),
    ("Tuota toivotit ikäsi,", "Tuota toivotit ikäsi,", "tuo, toivoa, ikä", "that, to hope/wish, lifetime", ""),
    ("sanoit saavasi sataisen,", "sanoit saavasi sataisen,", "sanoa, saada, satainen", "to say, to get, hundredfold", ""),
    ("tuovasi tuhannen neien.", "tuovasi tuhannen neidon.", "tuoda, tuhat, neito", "to bring, thousand, maiden", ""),
    ("Jo saitki hyvän sataisen:", "Jo saitkin hyvän sataisen:", "jo, saada, hyvä, satainen", "already, to get, good, hundredfold", ""),
    ("- tuon tuhannen tuppeloisen!", "- tuon tuhannen tuppeloisen!", "tuo, tuhat, tuppelo", "that, thousand, clumsy/fat one", ""),
    ("Sait kuin suolta suovariksen,", "Sait kuin suolta suovariksen,", "saada, kuin, suo, suovaris", "to get, like, swamp, swamp-crow", ""),
    ("aialta ajoharakan,", "aialta ajoharakan,", "aita, ajoharakka", "fence's, driving-magpie", ""),
    ("pellolta pelotuslinnun,", "pellolta pelotuslinnun,", "pelto, pelotuslint", "field's, scare-bird/scarecrow-bird", ""),
    ("mustan linnun mullokselta!", "mustan linnun mullokselta!", "musta, lintu, mullos", "black, bird, ploughed earth", ""),
    ("\"Mitä lie ikänsä tehnyt,", "\"Mitä lie ikänsä tehnyt,", "mitä, lieneä, ikä, tehdä", "what, perhaps, lifetime, to do", ""),
    ("kuta mennehen kesosen,", "mitä menneen kesän,", "mitä, mennyt, kesä", "what, past, summer", ""),
    ("kun ei kinnasta kutonut,", "kun ei kinnasta kutonut,", "kun, ei, kinnas, kutoa", "when, not, mitten, to knit", ""),
    ("saanut sukkoa su'unki?", "saanut sukkoa sukankaan?", "saada, sukka, sukka", "to get, stocking, stocking", ""),
    ("Tyhjänä tuli tupahan,", "Tyhjänä tuli tupaan,", "tyhjä, tulla, tupa", "empty, to come, cottage/hall", ""),
    ("annitoinna appelahan:", "annittoina appelaan:", "anniton, appi", "empty-handed, father-in-law's", ""),
    ("hiiret kopsassa kopasi,", "hiiret kopsassa kopasivat,", "hiiri, kopsa, kopata", "mice, bag/basket, to scramble/rustle", ""),
    ("hörppäkorvat lippahassa!\"", "hörppäkorvat lippahassa!\"", "hörppäkorva, lippas", "floppy-ears (mice), in the chest/box", ""),
    ("Lokka, luopuisa emäntä,", "Lokka, luopuisa emäntä,", "Lokka, luopuisa, emäntä", "Lokka, yielding/giving, mistress", ""),
    ("Kalevatar, vaimo kaunis,", "Kalevalatar, vaimo kaunis,", "Kalevalatar, vaimo, kaunis", "Kalevalatar, woman/wife, beautiful", ""),
    ("kuuli kummaisen tarinan.", "kuuli kummaisen tarinan.", "kuulla, kummainen, tarina", "to hear, wondrous/strange, story", ""),
    ("Sanan virkkoi, noin nimesi:", "Sanan virkkoi, noin nimitti:", "sana, virkkoa, nimittää", "word, to say, to name/call", ""),
    ("\"Mitä lausuit, lapsi kurja,", "\"Mitä lausuit, lapsi kurja,", "mitä, lausua, lapsi, kurja", "what, to utter, child, wretched", ""),
    ("kuta, kunnotoin, latelit?", "kuta, kunnoton, latelit?", "kuta, kunnoton, latella", "what, without honour/good, to recite/babble", ""),
    ("Muista kummat kuulukohon,", "Muista kuumat kuuluisivat,", "muistaa, kumma, kuulua", "to remember, wondrous, to be heard", ""),
    ("häväistykset häälyköhön,", "häväistykset häälyisivät,", "häväistys, häälyä", "disgraces/shames, to waver/float", ""),
    ("eipä tästä neitosesta,", "eipä tästä neitosesta,", "ei, tästä, neito", "not, from this, maiden", ""),
    ("ei tämän talon väestä!", "ei tämän talon väestä!", "ei, tämä, talo, väki", "not, this, house's, folk/people", ""),
    ("\"Jo sanoit pahan sanasen,", "\"Jo sanoit pahan sanasen,", "jo, sanoa, paha, sanen", "already, to say, bad, little word", ""),
    ("sanan kehnon kertaelit", "sanan kehnon kertaeli", "sana, kehno, kertaella", "word, poor/bad, to repeat", ""),
    ("suusta yötisen vasikan,", "suusta yöllisen vasikan,", "suu, yöllinen, vasikka", "mouth, nocturnal, calf", ""),
    ("päästä pennun päiväkunnan!", "päästä pennun päiväkunnan!", "pää, pentu, päiväkunta", "head, pup, day-folk (worthless one)", "Lokka scolding the child — 'you spoke from the mouth of a night-calf, from the head of a day-pup' — is the trickster-mother defending her son's bride with the same force she once used to welcome her."),
    ("Hyvän on sulho neien saanut,", "Hyvän on sulho neidon saanut,", "hyvä, sulho, neito, saada", "good, groom/suitor, maiden, to get", ""),
    ("tuonut maalta maan parahan:", "tuonut maalta maan parhaan:", "tuoda, maa, maa, paras", "to bring, land, land's, best", ""),
    ("on kuin puola puolikypsi,", "on kuin puola puolikypsi,", "olla, kuin, puola, puolikypsi", "to be, like, lingonberry, half-ripe", ""),
    ("kuin on mansikka mäellä,", "kuin on mansikka mäellä,", "kuin, olla, mansikka, mäki", "like, to be, strawberry, hill", ""),
    ("tahi kuin käkönen puussa,", "tahi kuin käkönen puussa,", "tahi, kuin, käki, puu", "or, like, cuckoo, tree", ""),
    ("pieni lintu pihlajassa,", "pieni lintu pihlajassa,", "pieni, lintu, pihlaja", "small, bird, rowan-tree", ""),
    ("koivussa koreasulka,", "koivussa koreasulka,", "koivu, korea, sulka", "birch, beautiful/fine, feather", ""),
    ("valorinta vaahteressa.", "valorinta vaahterassa.", "valo, rinta, vaahtera", "light/bright, breast, maple", ""),
    ("\"Oisi ei saanut Saksastana,", "\"Ei olisi saanut Saksasta,", "ei, olla, saada, Saksa", "not, to have been, to get, Germany/foreign", ""),
    ("tavannut Viron takoa", "tavannut Viron takaa", "tavata, Viro, taka", "to find/meet, Estonia, behind", ""),
    ("tämän neitosen soreutta,", "tämän neitosen soreutta,", "tämä, neito, soreus", "this, maiden's, gracefulness", ""),
    ("tämän allin armautta,", "tämän allin armautta,", "tämä, alli, armaus", "this, long-tailed duck's, grace/dearness", ""),
    ("tämän kasvon kauneutta,", "tämän kasvon kauneutta,", "tämä, kasvot, kauneus", "this, face's, beauty", ""),
    ("tämän muo'on muhkeutta,", "tämän muodon muhkeutta,", "tämä, muoto, muhkeus", "this, form/looks', magnificence", ""),
    ("käsivarren valkeutta,", "käsivarren valkeutta,", "käsivarsi, valkeus", "forearm's, whiteness", ""),
    ("kaulan hoikan kaarevuutta.", "kaulan hoikan kaarevuutta.", "kaula, hoikka, kaare", "neck's, slim, curve", ""),
    ("\"Eikä neiti tyhjin tullut:", "\"Eikä neiti tyhjin tullut:", "ei, neito, tyhjin, tulla", "not, maiden, emptily, to come", ""),
    ("oli turkit tuotavana,", "oli turkit tuotavana,", "olla, turkki, tuotava", "to be, fur coats, to be brought", ""),
    ("vaipat vasta saatavana", "vaipat vasta saatavana", "vaippa, vasta, saatava", "cloaks, just, to be gotten", ""),
    ("ja verat ve'ettävänä.", "ja verot vedettävänä.", "ja, verka, vetää", "and, broadcloth, to be drawn/brought", ""),
    ("\"Paljo on tällä neitosella", "\"Paljon on tällä neitosella", "paljon, tällä, neito", "much, this, maiden's", ""),
    ("oman värttinän väkeä,", "oman värttinän väkeä,", "oma, värttinä, väki", "own, spindle's, force/strength", ""),
    ("oman kehrän kiertämätä,", "oman kehrän kiertämätä,", "oma, kehrä, kiertää", "own, spinning-wheel's, spinning", ""),
    ("oman hyppisen hyveä,", "oman hyppisen hyvyyttä,", "oma, hyppynen, hyvyys", "own, fingertip's, goodness", ""),
    ("vaattehia valkehia,", "vaatteita valkeita,", "vaate, valkea", "clothes, white/bright", ""),
    ("talvisotkun suorimia,", "talvisotkan suorimia,", "talvi, sotka, suoria", "winter's, diving duck, straightened", ""),
    ("kevätpäivän valkomia,", "kevätpäivän valkomia,", "kevät, päivä, valkoa", "spring's, day's, whitened", ""),
    ("kesäkuien kuivomia:", "kesäkuiden kuivomia:", "kesä, kuu, kuivaa", "summer's, months', dried", ""),
    ("hyvät hurstit huilahukset,", "hyvät hurstit huilahukset,", "hyvä, hursti, huilahdus", "good, rough-cloths, whirling", ""),
    ("päänalaiset pällähykset,", "päänalaiset pällähykset,", "päänalainen, pällähys", "pillows, puffed-up/billowing", ""),
    ("sivallukset silkkihuivit,", "sivallukset silkkihuivit,", "sivallus, silkki, huivi", "waving, silk, scarves", ""),
    ("vilahukset villavaipat.", "vilahukset villavaipat.", "vilahdus, villa, vaippa", "flashing/waving, wool, cloaks", ""),
    ("\"Hyvä mutso, kaunis mutso,", "\"Hyvä mutso, kaunis mutso,", "hyvä, mutso, kaunis", "good, young wife/daughter-in-law, beautiful", ""),
    ("mutso valkeanverevä!", "mutso valkeaverevä!", "mutso, valkea, verevä", "young wife, white/bright, ruddy/fresh", ""),
    ("Hyvinpä ko'issa kuuluit,", "Hyvinpä kotona kuuluit,", "hyvin, koti, kuulua", "well, home, to be heard/known", ""),
    ("tyttönä ison ko'issa;", "tyttönä isän kotona;", "tyttö, isä, koti", "as a girl, father's, home", ""),
    ("hyvin kuulu kuun ikäsi", "hyvin kuulu kuun ikäsi", "hyvin, kuulua, kuu, ikä", "well, to be heard/known, moon's, age/time", ""),
    ("miniänä miehelässä!", "miniänä miehellä!", "miniä, mies", "as daughter-in-law, man's", ""),
    ("\"Elä huolelle rupea,", "\"Älä huolelle rupea,", "älä, huoli, ruveta", "don't, worry, to begin", ""),
    ("elä huoli huolehtia!", "älä huoli huolehtia!", "älä, huoli, huolehtia", "don't, worry, to worry", ""),
    ("Ei sinua suolle viety,", "Ei sinua suolle viety,", "ei, sinä, suo, viedä", "not, you, swamp, to take", ""),
    ("ojavarrelle otettu:", "ojavarrelle otettu:", "ojavarsi, ottaa", "ditch-side, to take", ""),
    ("viety on viljamättähältä,", "viety on viljamättähältä,", "viedä, vilja, mätäs", "taken, grain/fertile, mound", ""),
    ("viety vielä viljemmälle,", "viety vielä hedelmällisemmälle,", "viedä, vielä, hedelmällinen", "taken, still, more fertile", ""),
    ("otettu oluttuvilta,", "otettu oluttuvista,", "ottaa, olut, tupa", "taken, ale-house/cottage", ""),
    ("oluemmille otettu.", "oluempiin otettu.", "olla, oluinen", "taken, to more ale/beer-like (better)", ""),
    ("\"Hyvä neito, kaunis mutso!", "\"Hyvä neito, kaunis mutso!", "hyvä, neito, kaunis, mutso", "good, maiden, beautiful, young wife", ""),
    ("Tuotapa kysyn sinulta:", "Tuotapa kysyn sinulta:", "tuo, kysyä, sinä", "that, to ask, you", ""),
    ("näitkö tänne tullessasi", "näitkö tänne tullessasi", "nähdä, tänne, tulla", "to see, here, while coming", ""),
    ("kekoja keräperiä,", "kekoja keräperiä,", "keko, keräperä", "haystacks/stacks, round-bottomed", ""),
    ("näsäpäitä närttehiä?", "näsäpäitä närtäisiä?", "näsäpää, närtäinen", "snub-nosed ones, grumpy ones", ""),
    ("Ne kaikki tämän talosen,", "Ne kaikki tämän talon,", "ne, kaikki, tämä, talo", "those, all, this, house's", ""),
    ("tämän sulhon kyntämiä,", "tämän sulhon kyntämiä,", "tämä, sulho, kyntää", "this, groom's/suitor's, ploughed", ""),
    ("kyntämiä, kylvämiä.", "kyntämiä, kylvämiä.", "kyntää, kylvää", "ploughed, sown", ""),
    ("\"Neitokainen, nuorukainen!", "\"Neitokainen, nuorukainen!", "neito, nuori", "little maiden, little young one", ""),
    ("Tuota nyt sanon sinulle:", "Tuota nyt sanon sinulle:", "tuo, nyt, sanoa, sinä", "that, now, to say, you", ""),
    ("kun tunsit talohon tulla,", "kun tunsit taloon tulla,", "kun, tuntea, talo, tulla", "when, to feel/recognise, house, to come", ""),
    ("niin tunne talossa olla!", "niin tunne talossa olla!", "niin, tuntea, talo, olla", "so, to feel/recognise, house, to be", ""),
    ("Hyvä tääll' on mutson olla,", "Hyvä täällä on mutson olla,", "hyvä, täällä, olla, mutso", "good, here, to be, young wife", ""),
    ("kaunis kasvoa miniän,", "kaunis kasvaa miniänä,", "kaunis, kasvaa, miniä", "beautiful, to grow/thrive, daughter-in-law", ""),
    ("piossasi piimäpytty,", "käsissäsi piimäpytty,", "käsi, piimä, pytty", "in your hands, buttermilk, tub", ""),
    ("voivatinen vallassasi.", "voivatinen vallassasi.", "voi, vatinen, valta", "butter, bowl, in your keeping", ""),
    ("\"Hyvä täss' on neien olla,", "\"Hyvä täällä on neidon olla,", "hyvä, täällä, neito, olla", "good, here, maiden, to be", ""),
    ("kaunis kasvoa kanasen.", "kaunis kasvaa kanasen.", "kaunis, kasvaa, kanainen", "beautiful, to grow/thrive, little hen/girl", ""),
    ("Täss' on laajat saunan lauat", "Täällä on laajat saunan laudat", "täällä, laaja, sauna, lauta", "here, wide, sauna's, planks", ""),
    ("ja leveät pirtin lautsat,", "ja leveät pirtin lavitsat,", "ja, leveä, pirtti, lavitsa", "and, wide, cottage's, benches", ""),
    ("isännät isosi verrat,", "isännät isosi verrat,", "isäntä, isä, verta", "masters, father's, equals", ""),
    ("emännät emosi verrat,", "emännät äitisi verrat,", "emäntä, äiti, verta", "mistresses, mother's, equals", ""),
    ("pojat onpi veikon verrat,", "pojat ovat veikon verrat,", "poika, olla, veli, verta", "boys, to be, brother's, equals", ""),
    ("tyttäret sisaren verrat.", "tyttäret sisaren verrat.", "tytär, sisar, verta", "daughters, sister's, equals", "Lokka's welcome address to the bride — 'the masters here are your father's equals, the mistresses your mother's equals, the boys your brother's equals, the girls your sister's equals' — is the trickster-mother's most generous fiction: the claim that the new household will replace the old one."),
    ("\"Kun sinun himo tulevi,", "\"Kun sinun himo tulee,", "kun, sinä, himo, tulla", "when, your, desire/craving, to come", ""),
    ("noita mielesi tekevi", "noita mielesi tekee", "tuo, mieli, tehdä", "those, mind/will, to do/make", ""),
    ("ison saamia kaloja,", "isän saamia kaloja,", "isä, saada, kala", "father's, gotten, fish", ""),
    ("veljen pyitä pyytämiä,", "veljen pyytämiä pyitä,", "veli, pyytää, pyy", "brother's, caught, hazel-grouse", ""),
    ("niin elä kysy ky'yltä", "niin älä kysy kyyttäniskalta", "niin, älä, kysyä, kyyttäniska", "so, don't, to ask, crook-neck", ""),
    ("eläkä ano apelta!", "äläkä ano apelta!", "älä, anella, appi", "don't, to beg/ask for, father-in-law", ""),
    ("Kysy suorin sulholtasi,", "Kysy suoraan sulholtasi,", "kysyä, suoraan, sulho", "to ask, directly, groom/suitor", ""),
    ("toimittele tuojaltasi!", "toimittele tuojaltasi!", "toimittaa, tuoja", "to manage/arrange, bringer", ""),
    ("Ei ole sitä metsässä", "Ei ole sitä metsässä", "ei, olla, se, metsä", "not, to be, that, forest", ""),
    ("jalan neljän juoksijata", "neljäjalkaisena juoksijaa", "neljä, jalka, juoksija", "four, feet, runner", ""),
    ("eikä ilman lintusia,", "eikä ilman lintusta,", "ei, ilma, lintu", "not, sky's, bird", ""),
    ("kahen siiven siukovia,", "kahden siiven siukovia,", "kaksi, siipi, siukoa", "two, wings', whirring/rushing", ""),
    ("ei vielä ve'essäkänä", "ei vielä vesissäkään", "ei, vielä, vesi", "not, still, waters", ""),
    ("kalaparvea parasta,", "kalaparvea parasta,", "kala, parvi, paras", "fish, school/flock, best", ""),
    ("kuta sinun ei saaja saane,", "jota sinulle ei saaja saane,", "jota, sinä, ei, saaja, saada", "that, you, not, getter, to get", ""),
    ("saaja saane, tuoja tuone.", "saaja saane, tuoja tuone.", "saaja, saada, tuoja, tuoda", "getter, to get, bringer, to bring", ""),
    ("\"Hyvä täss' on neien olla,", "\"Hyvä täällä on neidon olla,", "hyvä, täällä, neito, olla", "good, here, maiden, to be", ""),
    ("kaunis kasvoa kanasen.", "kaunis kasvaa kanasen.", "kaunis, kasvaa, kanainen", "beautiful, to grow/thrive, little hen/girl", ""),
    ("Ei ole kiirettä kivelle", "Ei ole kiirettä kivelle", "ei, olla, kiire, kivi", "not, to be, hurry, stone", ""),
    ("eikä huolta huhmarelle:", "eikä huolta huhmarelle:", "ei, huoli, huhmare", "not, worry, mortar", ""),
    ("vesi tässä vehnät jauhoi,", "vesi täällä vehnät jauhoi,", "vesi, täällä, vehnä, jauhaa", "water, here, wheat, to grind", ""),
    ("koski kuohutti rukihit,", "koski kuohutti rukiit,", "koski, kuohuttaa, ruis", "rapids, to churn, rye", ""),
    ("aalto astiat pesevi,", "aalto astiat pesee,", "aalto, astia, pestä", "wave, dishes, to wash", ""),
    ("meren vaahti valkaisevi.", "meren vaahti valkaisee.", "meri, vaahto, valkaista", "sea's, foam, to bleach/whiten", ""),
    ("\"Ohoh kullaista kyläistä,", "\"Ohoh kullaista kyläistä,", "oi, kultainen, kyläinen", "oh, golden, village-one", ""),
    ("maan parasta paikaistani!", "maan parasta paikkaa!", "maa, paras, paikka", "land's, best, place", ""),
    ("Nurmet alla, pellot päällä,", "Nurmet alla, pellot päällä,", "nurmi, alla, pelto, päällä", "meadows, below, fields, above", ""),
    ("keskellä kylä välillä;", "keskellä kylä välillä;", "keski, kylä, väli", "middle, village, between", ""),
    ("kylän alla armas ranta,", "kylän alla armas ranta,", "kylä, alla, armas, ranta", "village, below, dear, shore", ""),
    ("rannassa rakas vetonen:", "rannassa rakas vetonen:", "ranta, rakas, vesi", "shore, dear, water", ""),
    ("se sopivi sorsan uia,", "se sopii sorsan uia,", "se, sopia, sorsa, uida", "that, to suit, duck, to swim", ""),
    ("vesilinnun vieretellä.\"", "vesilinnun vieretellä.\"", "vesilintu, vierätellä", "water-bird, to manoeuvre/drift", ""),
    ("Siitä joukko juotettihin,", "Siitä joukko juotettiin,", "siitä, joukko, juottaa", "from that, crowd, to give drink", ""),
    ("syötettihin, juotettihin", "syötettiin, juotettiin", "syöttää, juottaa", "to feed, to give drink", ""),
    ("liioilla lihamuruilla,", "liialla lihalla,", "liika, liha", "excess, meat/flesh", ""),
    ("kaunihilla kakkaroilla,", "kauniilla kakkaroilla,", "kaunis, kakkara", "beautiful, round-loaves/balls", ""),
    ("olu'illa ohraisilla,", "oluilla ohraisilla,", "olut, ohrainen", "beers/ales, barley", ""),
    ("viertehillä vehnäisillä.", "kiertevillä vehnäisillä.", "kiertää, vehnäinen", "rolling/circling, wheat-made", ""),
    ("Olipa kystä kyllin syöä,", "Olipa kyllin syödä,", "olla, kyllin, syödä", "to be, enough, to eat", ""),
    ("kyllin syöä, kyllin juoa", "kyllin syödä, kyllin juoda", "kyllin, syödä, kyllin, juoda", "enough, to eat, enough, to drink", ""),
    ("punaisissa purtiloissa,", "punaisissa purtiloissa,", "punainen, purtilo", "red, trough/vessel", ""),
    ("kaunoisissa kaukaloissa:", "kauniissa kaukaloissa:", "kaunis, kaukalo", "beautiful, trough/container", ""),
    ("pirotella piirahia,", "pirotella piirakkaita,", "pirotella, piirakka", "to sprinkle/spread, pies/pastries", ""),
    ("murotella voimuruja,", "murotella voimuruja,", "murotella, voi, muru", "to crumble, butter, crumbs", ""),
    ("sirotella siikasia,", "sirotella siikasia,", "sirotella, siika", "to scatter/spread, whitefish", ""),
    ("lohkota lohikaloja", "lohkoa lohikaloja", "lohkoa, lohi, kala", "to split/carve, salmon, fish", ""),
    ("veitsellä hope'isella,", "veitsellä hopeisella,", "veitsi, hopea", "knife, silver", ""),
    ("kuraksella kultaisella.", "kuraksella kultaisella.", "kurake, kultainen", "fork/carving-tool, golden", ""),
    ("Olut juoksi ostamatoin,", "Olut juoksi ostamatoin,", "olut, juosta, ostamaton", "beer/ale, to run/flow, unbought", ""),
    ("mesi markoin maksamatoin,", "mesi markoin maksamatoin,", "mesi, markka, maksaa", "honey/mead, marks, unpaid for", ""),
    ("oluoinen orren päästä,", "olut orren päästä,", "olut, orsi, pää", "beer/ale, rafter's, end/head", ""),
    ("sima vaarnojen sisästä,", "sima vaarnojen sisästä,", "sima, vaarnas, sisä", "honey/mead, plough-handles, inside", ""),
    ("olut huulten huuhtimeksi,", "olut huulten huuhtimeksi,", "olut, huuli, huuhtoa", "beer/ale, lips', rinsing", ""),
    ("mesi mielten kääntimeksi.", "mesi mielten kääntimeksi.", "mesi, mieli, kääntää", "honey/mead, minds', turning", ""),
    ("Kukapa tuossa kukkujaksi,", "Kuka tuossa kukkujaksi,", "kuka, tuossa, kukku", "who, there, crower/caller", ""),
    ("lailliseksi laulajaksi?", "lailliseksi laulajaksi?", "laillinen, laulaja", "lawful/proper, singer", ""),
    ("Vaka vanha Väinämöinen,", "Vakaa vanha Väinämöinen,", "vakaa, vanha, Väinämöinen", "steady/wise, old, Väinämöinen", ""),
    ("laulaja iän-ikuinen,", "laulaja iän-ikuinen,", "laulaja, ikuinen", "singer, age-eternal", ""),
    ("itse laululle rupesi,", "itse lauluun rupesi,", "itse, laulu, ruveta", "himself, song, to begin", ""),
    ("töille virtten työntelihe.", "laulutöihin työnsi itsensä.", "laulutyö, työntää", "singing-work, to push", ""),
    ("Sanovi sanalla tuolla,", "Sanoi sanalla tuolla,", "sanoa, sana, tuo", "to say, word, that", ""),
    ("lausui tuolla lausehella:", "lausui tuolla lauseella:", "lausua, tuo, lause", "to utter, that, sentence", ""),
    ("\"Veli kullat, veitoseni,", "\"Veli kullat, veitoseni,", "veli, kulta, veito", "brother golds, dear brothers", ""),
    ("suulliset sanalliseni,", "suulliset sanalliseni,", "suullinen, sanallinen", "mouthed ones, worded ones", ""),
    ("kielelliset kumppalini!", "kielelliset kumppalini!", "kielellinen, kumppani", "tongued ones, companions", ""),
    ("Kuulkottenpa, kuin sanelen!", "Kuulkaa, kun sanelen!", "kuulla, kun, sanella", "to hear, when, to recite/tell", ""),
    ("Harvoin on hanhet suutasusten,", "Harvoin on hanhet suutasusten,", "harvoin, hanhi, suutasusten", "seldom, geese, beak to beak", ""),
    ("sisarukset silmätysten,", "sisarukset silmätysten,", "sisarus, silmätysten", "siblings, eye to eye", ""),
    ("harvoin veikot vieretysten,", "harvoin veljet vieretysten,", "harvoin, veli, vieretysten", "seldom, brothers, side by side", ""),
    ("emon lapset laiatusten", "äidin lapset laiatusten", "äiti, lapsi, laiatusten", "mother's, children, side by side", ""),
    ("näillä raukoilla rajoilla,", "näillä raukoilla rajoilla,", "tämä, raukka, raja", "these, poor/wretched, borders/regions", ""),
    ("poloisilla Pohjan mailla.", "poloisilla Pohjan mailla.", "poloinen, Pohja, maa", "wretched, North's, lands", "Väinämöinen's feast-song opening — 'seldom do geese meet beak to beak, siblings eye to eye, brothers side by side, a mother's children together on these poor borders of the North' — is the trickster-shaman's characteristic opening gambit: praise through scarcity."),
    ("\"Niin joko laululle lähemme,", "\"Niin joko lauluun lähemme,", "niin, jo, laulu, lähteä", "so, already, song, to set out", ""),
    ("töille virtten työnteleimme?", "laulutöihin työntelemme?", "laulutyö, työntää", "singing-work, to push", ""),
    ("Laulanta runoilla töitä,", "Laulanta runoilla töitä,", "laulanta, runo, työ", "singing, runes, work", ""),
    ("kukunta kevätkäellä,", "kukunta kevätkäellä,", "kukunta, kevät, käki", "cuckoo-calling, spring's, cuckoo", ""),
    ("painanta sinettärillä,", "painanta sinettärillä,", "painanta, sinettäri", "pressing, blue-bird", ""),
    ("kuonta kankahattarilla.", "kuonta kankahattarilla.", "kuonta, kankahatar", "weaving, heath-maiden", ""),
    ("\"Laulavat Lapinki lapset,", "\"Laulavat Lapinkin lapset,", "laulaa, Lappi, lapsi", "to sing, Lapland's, children", ""),
    ("heinäkengät heittelevät", "heinäkengät heittelevät", "heinä, kenkä, heitellä", "hay-shoes, to throw/toss", ""),
    ("hirven harvoilta lihoilta,", "hirven harvoilta lihoilta,", "hirvi, harva, liha", "elk's, sparse, flesh/meat", ""),
    ("peuran pienen pallehilta;", "peuran pienen pallehilta;", "peura, pieni, palle", "deer's, small, ribs", ""),
    ("niin miks' en minäki laula,", "niin miksi en minäkään laula,", "niin, miksi, ei, minä, laulaa", "so, why, not, I, to sing", ""),
    ("miks' ei laula meiän lapset", "miksi ei laula meidän lapset", "miksi, ei, laulaa, me, lapsi", "why, not, to sing, our, children", ""),
    ("ruoalta rukihiselta,", "ruoalta rukiiselta,", "ruoka, rukiinen", "food, rye-made", ""),
    ("suulta suurukselliselta?", "suulta suurukselliselta?", "suu, suuruksellinen", "mouth, porridge-filled", ""),
    ("\"Laulavat Lapinki lapset,", "\"Laulavat Lapinkin lapset,", "laulaa, Lappi, lapsi", "to sing, Lapland's, children", ""),
    ("heläjävät heinäkengät", "heläjävät heinäkengät", "helätä, heinä, kenkä", "to resound/ring, hay-shoes", ""),
    ("vesimaljan juotuansa,", "vesimaljan juotuansa,", "vesi, malja, juoda", "water's, cup/goblet, having drunk", ""),
    ("petäjäisen purtuansa;", "petäjäisen purtuansa;", "petäjäinen, purra", "pine's, having bitten/gnawed", ""),
    ("niin miks' en minäki laula,", "niin miksi en minäkään laula,", "niin, miksi, ei, minä, laulaa", "so, why, not, I, to sing", ""),
    ("miks' ei laula meiän lapset", "miksi ei laula meidän lapset", "miksi, ei, laulaa, me, lapsi", "why, not, to sing, our, children", ""),
    ("juomilta jyvällisiltä,", "juomilta jyvällisiltä,", "juoma, jyvällinen", "drinks, grain-filled", ""),
    ("olu'ilta ohraisilta?", "oluita ohraisilta?", "olut, ohrainen", "beers/ales, barley", ""),
    ("\"Laulavat Lapinki lapset,", "\"Laulavat Lapinkin lapset,", "laulaa, Lappi, lapsi", "to sing, Lapland's, children", ""),
    ("heläjävät heinäkengät", "heläjävät heinäkengät", "helätä, heinä, kenkä", "to resound/ring, hay-shoes", ""),
    ("nokisilta nuotioilta,", "nokisilta nuotioilta,", "nokinen, nuotio", "sooty, campfires/hearths", ""),
    ("hiilisiltä hiertimiltä;", "hiilisiltä hiertimiltä;", "hiilinen, hierrin", "coal-covered, rubbing-stones", ""),
    ("niin miks' en minäki laula,", "niin miksi en minäkään laula,", "niin, miksi, ei, minä, laulaa", "so, why, not, I, to sing", ""),
    ("miks' ei laula meiän lapset", "miksi ei laula meidän lapset", "miksi, ei, laulaa, me, lapsi", "why, not, to sing, our, children", ""),
    ("alta kuulun kurkihirren,", "alta kuulun kurkihirren,", "alta, kuulu, kurkihirsi", "under, renowned, ridgepole/main beam", ""),
    ("alta kaunihin katoksen?", "alta kauniin katoksen?", "alta, kaunis, katos", "under, beautiful, roof/shelter", ""),
    ("\"Hyväpä täss' on miesten olla,", "\"Hyvä täällä on miesten olla,", "hyvä, täällä, mies, olla", "good, here, men's, to be", ""),
    ("armas naistenki asua", "armas naistenkin asua", "armas, nainen, asua", "dear, women's, to live/dwell", ""),
    ("olutpuolikon povella,", "olutpuolikon povella,", "olut, puolikko, povi", "beer-half-keg's, bosom/side", ""),
    ("mesitiinun tienohilla,", "mesitiinun tienohilla,", "mesi, tiinu, tienoo", "honey/mead-tub's, vicinity/side", ""),
    ("sivullamme siikasalmet,", "sivullamme siikasalmet,", "sivu, siika, salmi", "beside us, whitefish, straits", ""),
    ("luonamme lohiapajat,", "luonamme lohiapajat,", "luona, lohi, apaja", "near us, salmon, fishing-place", ""),
    ("joist' ei syöen syömät puutu,", "joista ei syödessä syömät puutu,", "josta, ei, syödä, syöminen, puuttua", "from which, not, while eating, eatings, to run out", ""),
    ("juoen juomiset vähene.", "juodessa juomiset vähene.", "juoda, juominen, vähentyä", "while drinking, drinkings, to diminish", ""),
    ("\"Hyväpä täss' on miesten olla,", "\"Hyvä täällä on miesten olla,", "hyvä, täällä, mies, olla", "good, here, men's, to be", ""),
    ("armas naistenki elellä.", "armas naistenkin elellä.", "armas, nainen, elellä", "dear, women's, to live along", ""),
    ("Ei tässä surulla syöä,", "Ei täällä surulla syödä,", "ei, täällä, suru, syödä", "not, here, grief, to eat", ""),
    ("ei eletä huolen kanssa;", "ei eletä huolen kanssa;", "ei, elää, huoli, kanssa", "not, to live, worry, with", ""),
    ("tässä syöähän surutta,", "täällä syödään surutta,", "täällä, syödä, surutta", "here, to eat, without grief", ""),
    ("eletähän huoletoinna", "eletään huoletoinna", "elää, huoleton", "to live, carefree", ""),
    ("iällä tämän isännän,", "iällä tämän isännän,", "ikä, tämä, isäntä", "lifetime, this, master", ""),
    ("elinajalla emännän.", "elinajalla emännän.", "elinaika, emäntä", "lifetime, mistress", ""),
    ("\"Kumman tässä ensin kiitän,", "\"Kumman täällä ensin kiitän,", "kumpi, täällä, ensin, kiittää", "which of the two, here, first, to thank/praise", ""),
    ("isännänkö vai emännän?", "isännänkö vai emännän?", "isäntä, vai, emäntä", "master's, or, mistress's", ""),
    ("Ainap' entiset urohot", "Aina entiset urohot", "aina, entinen, uros", "always, former, heroes/men", ""),
    ("ensin kiittivät isännän,", "ensin kiittivät isännän,", "ensin, kiittää, isäntä", "first, to thank/praise, master", ""),
    ("ku on suolta suojan saanut,", "joka on suolta suojan saanut,", "joka, suo, suoja, saada", "who, swamp, shelter/protection, to get", ""),
    ("ko'in korvesta kokenut:", "kotinsa korvesta kokenut:", "koti, korpi, kokea", "home, wilderness, to experience", ""),
    ("tyvin tuonut tyyskät männyt,", "tyvineen tuonut tyyskät männyt,", "tyvi, tuoda, tyyskä, mänty", "by the base, to bring, storm-blasted, pines", ""),
    ("latvoin lansatut petäjät,", "latvoineen kaadetut petäjät,", "latva, kaataa, petäjä", "with their tops, felled, pines", ""),
    ("pannut paikalle hyvälle,", "pannut paikalle hyvälle,", "panna, paikka, hyvä", "to put, place, good", ""),
    ("asettanut ankaralle", "asettanut ankaralle", "asettaa, ankara", "to set, strict/firm", ""),
    ("suuriksi sukutuviksi,", "suuriksi sukutuviksi,", "suuri, suku, tupa", "great, lineage, cottages/halls", ""),
    ("kaunihiksi kartanoiksi;", "kauniiksi kartanoiksi;", "kaunis, kartano", "beautiful, estates/yards", ""),
    ("salvannut salosta seinät,", "salvannut salosta seinät,", "salvata, salo, seinä", "to log/build, wilderness, walls", ""),
    ("hirret hirmulta mäeltä,", "hirret hirmulta mäeltä,", "hirsi, hirmu, mäki", "logs, terrible/stormy, hill", ""),
    ("ruotehet rome'ikolta,", "ruotehet romeilta,", "ruode, rome", "thin-poles, loose-rocks", ""),
    ("malat marjakankahalta,", "malat marjakankahalta,", "mala, marja, kangas", "roof-poles, berry, heath/plain", ""),
    ("tuohet tuomivaaran päältä,", "tuohet tuomivaaran päältä,", "tuohi, tuomi, vaara", "birch-bark, bird-cherry, hill/fell", ""),
    ("sammalet sulilta soilta.", "sammalet sulilta soilta.", "sammal, sula, suo", "mosses, thawed, swamps", ""),
    ("\"Tupa on tehty tesmällensä,", "\"Tupa on tehty tesmällensä,", "tupa, tehdä, tesmä", "cottage/hall, made, for its purpose", ""),
    ("suoja pantu paikallensa.", "suoja pantu paikallensa.", "suoja, panna, paikka", "shelter, put, in its place", ""),
    ("Sata oli miestä salvaimella,", "Sata oli miestä salvaimella,", "sata, olla, mies, salvaimen", "hundred, to be, men, on the log-work", ""),
    ("tuhat oli tuvan katolla", "tuhat oli tuvan katolla", "tuhat, olla, tupa, katto", "thousand, to be, cottage's/hall's, roof", ""),
    ("tehessä tätä tupoa,", "tehdessä tätä tupaa,", "tehdä, tämä, tupa", "while making, this, cottage/hall", ""),
    ("laaittaissa lattiata.", "laitettaessa lattiaa.", "laittaa, lattia", "while making, floor", ""),
    ("\"Jopa vaan tämän isännän", "\"Jo vaan tämän isännän", "jo, vaan, tämä, isäntä", "already, but, this, master", ""),
    ("saaessa tätä tupoa", "saadessa tätä tupaa", "saada, tämä, tupa", "while getting, this, cottage/hall", ""),
    ("mont' on tukka tuulta nähnyt,", "monta on tukka tuulta nähnyt,", "monta, tukka, tuuli, nähdä", "many, hair, wind, to see", ""),
    ("hivus säätä hirveätä.", "hius säätä hirveätä.", "hius, sää, hirveä", "hair, weather, terrible", "Väinämöinen's praise of the master — who built this hall from storm-blasted pines, hired a hundred men on the log-work and a thousand on the roof, whose hair has seen many winds and terrible weather — is the trickster-singer deploying praise as social magic: the host is gratified into generosity."),
    ("Use'in hyvän isännän", "Usein hyvän isännän", "usein, hyvä, isäntä", "often, good, master", ""),
    ("jäänyt on kinnasta kivelle,", "jäänyt on kinnas kivelle,", "jäädä, kinnas, kivi", "to remain, mitten, stone", ""),
    ("hattua havun selälle,", "hattua havun selälle,", "hattu, havu, selkä", "hat, spruce-branch, back", ""),
    ("suohon sukkoa vajonnut.", "suohon sukka vajonnut.", "suo, sukka, vaipua", "swamp, stocking, to sink", ""),
    ("\"Use'in hyvä isäntä", "\"Usein hyvä isäntä", "usein, hyvä, isäntä", "often, good, master", ""),
    ("aivan aika-huomenessa", "aivan aika-aamuisena", "aivan, aika, aamu", "quite, time, morning", ""),
    ("ennen muien nousematta,", "ennen muiden nousematta,", "ennen, muu, nousta", "before, others', rising", ""),
    ("kyläkunnan kuulematta", "kyläkunnan kuulematta", "kylä, kunta, kuulla", "village, community, hearing", ""),
    ("nousnut on nuotiotulelta,", "noussut on nuotiotulelta,", "nousta, nuotio, tuli", "to rise, campfire, fire", ""),
    ("havannut havumajoilta,", "havannut havumajoilta,", "havata, havu, maja", "to spring up, spruce-branch, dwelling", ""),
    ("havu päänsä harjaellut,", "havu päänsä harjaellut,", "havu, pää, harjailla", "spruce-branch, head, to brush/comb", ""),
    ("kaste pesnyt sirkut silmät.", "kaste pessyt kirkkaat silmät.", "kaste, pestä, kirkas, silmä", "dew, to wash, clear/bright, eyes", ""),
    ("\"Siitäpä hyvä isäntä", "\"Siitäpä hyvä isäntä", "siitä, hyvä, isäntä", "from that, good, master", ""),
    ("saapi tuttua tupahan,", "saa tuttua tupaan,", "saada, tuttu, tupa", "to get, familiar ones, cottage/hall", ""),
    ("lautsantäyen laulajoita,", "lavitsan täyden laulajia,", "lavitsa, täysi, laulaja", "bench's, full, singers", ""),
    ("ikkunat iloitsijoita,", "ikkunat iloitsijoita,", "ikkuna, iloita", "windows, rejoicers", ""),
    ("siltalauat lausujoita,", "siltalauat lausujia,", "silta, lauta, lausuja", "bridge-planks, utterers/reciters", ""),
    ("karsinat karehtijoita,", "karsinat karehtijoita,", "karsina, karehtija", "stalls/pens, merry-makers", ""),
    ("seinävieret seisojia,", "seinävieret seisojia,", "seinä, vieri, seisoja", "wall-sides, standers", ""),
    ("aitovieret astujia,", "aitovieret astujia,", "aita, vieri, astuja", "fence-sides, walkers", ""),
    ("pihat pitkin kulkijoita,", "pihat pitkin kulkijoita,", "piha, pitkin, kulkija", "yards, along, travellers", ""),
    ("maat ristin matelijoita.", "maat ristin matelijoita.", "maa, risti, matelijoita", "lands, crosswise, crawlers", ""),
    ("\"Isännän esinnä kiitin,", "\"Isännän ensin kiitin,", "isäntä, ensin, kiittää", "master, first, to thank/praise", ""),
    ("siitä ehtoisen emännän", "siitä ehtoisen emännän", "siitä, ehtoinen, emäntä", "from that, prosperous/noble, mistress", ""),
    ("ruokien rakentamasta,", "ruokien rakentamasta,", "ruoka, rakentaa", "food's, building/constructing", ""),
    ("pitkän pöyän täyttämästä.", "pitkän pöydän täyttämästä.", "pitkä, pöytä, täyttää", "long, table, filling", ""),
    ("\"Hänpä leipoi leivät paksut,", "\"Hänpä leipoi leivät paksut,", "hän, leipoa, leipä, paksu", "she, to bake, breads, thick", ""),
    ("suuret talkkunat taputti", "suuret talkkunat taputti", "suuri, talkkuna, taputtaa", "great, ground grain mixture, to pat/knead", ""),
    ("käpe'illä kämmenillä,", "käpeillä kämmenillä,", "käpinen, kämmen", "nimble, palms", ""),
    ("kyperillä kymmenillä;", "kyperillä kymmenillä;", "kypärä, kymmenen", "curved, tens (fingers)", ""),
    ("nosti leivät leppeästi,", "nosti leivät leppeästi,", "nostaa, leipä, leppeä", "to lift, breads, gently/evenly", ""),
    ("syötti vierahat välehen", "syötti vieraat välehen", "syöttää, vieras, välillä", "to feed, guests/strangers, meanwhile", ""),
    ("liioilla sianlihoilla,", "liialla sianlihalla,", "liika, sianliha", "excess, pork", ""),
    ("kohokuori-kokkaroilla", "kohokuori-kokkaroilla", "kohokuori, kakkara", "risen-crust, round-loaves/balls", ""),
    ("- terät vieri veitsistämme,", "- terät vierähti veitsistämme,", "terä, vierähtää, veitsi", "blades, to roll/fly off, knives", ""),
    ("päät putosi puukoistamme", "päät putosi puukoistamme", "pää, pudota, puukko", "heads, to fall, knives", ""),
    ("lohen päitä lohkoessa,", "lohen päitä lohkoessa,", "lohi, pää, lohkoa", "salmon's, heads, while splitting", ""),
    ("hauin päitä halkoessa.", "hauen päitä halkoessa.", "hauki, pää, halkoa", "pike's, heads, while splitting", ""),
    ("\"Use'in hyvä emäntä,", "\"Usein hyvä emäntä,", "usein, hyvä, emäntä", "often, good, mistress", ""),
    ("tuo tarkka taloinen vaimo,", "tuo tarkka taloinen vaimo,", "tuo, tarkka, taloinen, vaimo", "that, precise, householder's, woman/wife", ""),
    ("kuullut on kukotta nousta,", "kuullut on kukotta nousta,", "kuulla, kukko, nousta", "to have heard, without rooster, to rise", ""),
    ("kanan lapsetta karata", "kanan lapsetta karata", "kana, lapsi, karata", "hen's, without child, to flee/dart", ""),
    ("näitä häitä hankittaissa,", "näitä häitä hankittaessa,", "nämä, häät, hankkia", "these, wedding, while preparing", ""),
    ("teoksia tehtäessä,", "teoksia tehtäessä,", "teos, tehdä", "works/deeds, while doing", ""),
    ("hiivoja rakettaessa,", "hiivoja rakettaessa,", "hiiva, rakentaa", "yeast, while preparing/building", ""),
    ("olosia pantaessa.", "oluita pantaessa.", "olut, panna", "beers/ales, while making/putting", ""),
    ("\"Hyvin on hyvä emäntä,", "\"Hyvin on hyvä emäntä,", "hyvin, hyvä, emäntä", "well, good, mistress", ""),
    ("tuo tarkka taloinen vaimo,", "tuo tarkka taloinen vaimo,", "tuo, tarkka, taloinen, vaimo", "that, precise, householder's, woman/wife", ""),
    ("osannut oluet panna,", "osannut oluet panna,", "osata, olut, panna", "to know how, beers/ales, to make/put", ""),
    ("makujuoman juoksutella", "makujuoman juoksutella", "makujuoma, juoksuttaa", "flavour-drink, to make run/flow", ""),
    ("iuista imeltyneistä,", "idusta imeltyneistä,", "itu, imeltyä", "sprout/seed, sweetened/malted", ""),
    ("make'ista maltahista,", "makeista maltaista,", "makea, mallas", "sweet, malts", ""),
    ("joit' ei puulla puuhaellut,", "joita ei puulla puuhaellut,", "jota, ei, puu, puuhata", "that, not, wood/stick, to bustle", ""),
    ("korennolla koukkaellut,", "korennolla koukkaellut,", "korento, koukata", "carrying-yoke, to hook/bend", ""),
    ("vaanpa kourilla kohenti,", "vaan kourilla kohenti,", "vaan, koura, kohentaa", "but, fists, to adjust/stir", ""),
    ("käsivarsin käännytteli", "käsivarsin käännytteli", "käsivarsi, kääntää", "forearms, to turn", ""),
    ("saunassa savuttomassa,", "saunassa savuttomassa,", "sauna, savuton", "sauna, without smoke", ""),
    ("la'aistuilla lautehilla.", "laitetuilla lauteilla.", "laittaa, laude", "prepared, sauna benches", ""),
    ("\"Eipä tuo hyvä emäntä,", "\"Eipä tuo hyvä emäntä,", "ei, tuo, hyvä, emäntä", "not, that, good, mistress", ""),
    ("tuo tarkka taloinen vaimo,", "tuo tarkka taloinen vaimo,", "tuo, tarkka, taloinen, vaimo", "that, precise, householder's, woman/wife", ""),
    ("laske iskulle ituja,", "laske iskulle ituja,", "laskea, isku, itu", "to let, strike/blow, sprout/seed", ""),
    ("päästä maalle maltahia;", "päästä maalle maltaita;", "päästää, maa, mallas", "to let go, ground, malts", ""),
    ("käypi saunassa use'in", "käy saunassa usein", "käydä, sauna, usein", "to go, sauna, often", ""),
    ("syänyöllä yksinänsä,", "sydänyöllä yksinänsä,", "sydänyö, yksin", "midnight, alone", ""),
    ("ei huoli susia surra,", "ei huoli susia surra,", "ei, huolia, susi, surra", "not, to care, wolves, to grieve/fear", ""),
    ("pelätä metsän petoja.", "pelätä metsän petoja.", "pelätä, metsä, peto", "to fear, forest's, beasts", ""),
    ("\"Jopa nyt emännän kiitin;", "\"Jo nyt emännän kiitin;", "jo, nyt, emäntä, kiittää", "already, now, mistress, to thank/praise", ""),
    ("vuotas kiitän patvaskani!", "hetkinen kiitän patvaskani!", "hetkinen, kiittää, patvanen", "a moment, to thank/praise, best man", ""),
    ("Ken on pantu patvaskaksi,", "Ken on pantu patvaskaksi,", "ken, olla, panna, patvanen", "who, to be, put, best man", ""),
    ("ken otettu oppahaksi?", "ken otettu oppahaksi?", "ken, ottaa, opas", "who, taken, guide", ""),
    ("Kylän paras patvaskana,", "Kylän paras patvaskana,", "kylä, paras, patvanen", "village's, best, best man", ""),
    ("kylän onni oppahana.", "kylän onni oppahana.", "kylä, onni, opas", "village's, luck/fortune, guide", ""),
    ("\"Onpa meiän patvaskalla", "\"Onpa meiän patvaskalla", "olla, me, patvanen", "to be, our, best man", ""),
    ("päällä haahen haljakkainen;", "päällä haahden haljakkainen;", "päällä, haahti, haljaka", "over, vessel's, pale-blue/bright", ""),
    ("se on kaita kainalosta,", "se on kaita kainalosta,", "se, kaita, kainalos", "that, narrow/slim, armpit", ""),
    ("soma suolien kohasta.", "soma suolien kohdasta.", "soma, suoli, kohta", "lovely, intestines', place/area", ""),
    ("\"Onpa meiän patvaskalla,", "\"Onpa meiän patvaskalla,", "olla, me, patvanen", "to be, our, best man", ""),
    ("onpa kauhtana kapoinen:", "onpa kauhtana kapoinen:", "olla, kauhtana, kapea", "to be, overcoat, narrow/slender", ""),
    ("helmat hietoa vetävi,", "helmat hietoa vetää,", "helma, hiekka, vetää", "hems, sand, to pull", ""),
    ("takapuolet tanteria.", "takapuolet tanteria.", "takapuoli, tanner", "back-parts, ground/field", ""),
    ("\"Vähän paitoa näkyvi,", "\"Vähän paitaa näkyy,", "vähän, paita, näkyä", "a little, shirt, to be seen", ""),
    ("pikkaraisen pilkottavi:", "pikkaraisen pilkottaa:", "pikkuinen, pilkottaa", "tiny, to peek/show", ""),
    ("on kuin Kuuttaren kutoma,", "on kuin Kuuttaren kutoma,", "olla, kuin, Kuutar, kutoa", "to be, like, Moon-maiden's, woven", ""),
    ("tinarinnan riukuttama.", "tinarinnan riukuttama.", "tinarinta, riukuttaa", "tin-breasted, rattled/shaken (made)", ""),
    ("\"Onpa meiän patvaskalla", "\"Onpa meiän patvaskalla", "olla, me, patvanen", "to be, our, best man", ""),
    ("vyöllä ussakka utuinen,", "vyöllä ussakka utuinen,", "vyö, ussakka, utuinen", "belt, bushy/fuzzy, misty", ""),
    ("päivän tyttären kutoma,", "päivän tyttären kutoma,", "päivä, tytär, kutoa", "sun's/day's, daughter's, woven", ""),
    ("kirjokynnen kirjoittama", "kirjokynnen kirjoittama", "kirjo, kynsi, kirjoittaa", "patterned, claw/nail, written/inscribed", ""),
    ("ajalla tulettomalla,", "ajalla tulettomalla,", "aika, tulaton", "time, fireless", ""),
    ("tulen tietämättömällä.", "tulen tietämättömällä.", "tuli, tietää", "fire, without knowing", "Väinämöinen's extended praise of the best man — his coat, his shirt woven by the Moon-maiden, his belt woven by the Sun's daughter, his silk stockings, his fine boots, his golden curls and golden beard, his tall helmet piercing the clouds — is the trickster-singer's lavish flattery deployed as social bonding."),
    ("\"Onpa meiän patvaskalla", "\"Onpa meiän patvaskalla", "olla, me, patvanen", "to be, our, best man", ""),
    ("silkkiset sukat jalassa,", "silkkiset sukat jalassa,", "silkki, sukka, jalka", "silk, stockings, foot", ""),
    ("silkkiset sukan sitehet,", "silkkiset sukan sitehet,", "silkki, sukka, side", "silk, stocking's, ties/garters", ""),
    ("säteriset säärinauhat,", "säteriset säärinauhat,", "säteri, sääri, nauha", "fine-cloth, shin's, ribbons/garters", ""),
    ("jotk' on kullalla ku'ottu,", "jotka on kullalla kudottu,", "jotka, olla, kulta, kutoa", "which, to have been, gold, woven", ""),
    ("hopealla huoliteltu.", "hopealla huoliteltu.", "hopea, huolitella", "silver, finished/trimmed carefully", ""),
    ("\"Onpa meiän patvaskalla", "\"Onpa meiän patvaskalla", "olla, me, patvanen", "to be, our, best man", ""),
    ("Saksan kengät kelvolliset,", "Saksan kengät kelvolliset,", "Saksa, kenkä, kelvollinen", "Germany's/foreign, shoes, worthy/proper", ""),
    ("kuni joutsenet joella,", "kuin joutsenet joella,", "kuin, joutsen, joki", "like, swans, river", ""),
    ("vesiteiret vieremillä", "vesiteiret vieremillä", "vesitiiri, vieremi", "sea-terns, rolling/gliding surfaces", ""),
    ("tahi hanhuet havulla,", "tahi hanhet havulla,", "tahi, hanhi, havu", "or, geese, spruce-branch", ""),
    ("muuttolinnut murrikolla.", "muuttolinnut murrikolla.", "muuttolintu, murrikko", "migratory birds, murky/foggy weather", ""),
    ("\"Onpa meiän patvaskalla", "\"Onpa meiän patvaskalla", "olla, me, patvanen", "to be, our, best man", ""),
    ("kutrit kullansuortuvaiset,", "kutrit kullansuortuvaiset,", "kutri, kulta, suortu", "curls/locks, gold, stranded", ""),
    ("parta kullanpalmikkoinen;", "parta kullanpalmikkoinen;", "parta, kulta, palmikko", "beard, gold, braid", ""),
    ("päässä pystyinen kypäri,", "päässä pystyinen kypäri,", "pää, pystyinen, kypärä", "head, upright/tall, helmet", ""),
    ("puhki pilvien puhuja,", "puhki pilvien puhuja,", "puhki, pilvi, puhua", "through, clouds, blowing/speaking", ""),
    ("läpi metsän läiköttäjä,", "läpi metsän läiköttäjä,", "läpi, metsä, läiköttää", "through, forest, to glitter/shine", ""),
    ("jot' ei saatane sataisin,", "jota ei saatane sadoilla,", "jota, ei, saada, sata", "that, not, to get, hundred", ""),
    ("tuotane tuhansin markoin.", "tuoda tuhansin markoin.", "tuoda, tuhat, markka", "to bring, thousand, marks", ""),
    ("\"Jo nyt kiitin patvaskani;", "\"Jo nyt kiitin patvaskani;", "jo, nyt, kiittää, patvanen", "already, now, to thank/praise, best man", ""),
    ("vuotas kiitän saajanaisen!", "hetkinen kiitän saajanaisen!", "hetkinen, kiittää, saajanainen", "a moment, to thank/praise, bridesmaid", ""),
    ("Mist' on saatu saajanainen,", "Mistä on saatu saajanainen,", "mistä, saada, saajanainen", "from where, gotten, bridesmaid", ""),
    ("kust' otettu onnellinen?", "mistä otettu onnellinen?", "mistä, ottaa, onnellinen", "from where, taken, lucky/fortunate one", ""),
    ("\"Tuolt' on saatu saajanainen,", "\"Tuolta on saatu saajanainen,", "tuolta, saada, saajanainen", "from there, gotten, bridesmaid", ""),
    ("tuolt' otettu onnellinen", "tuolta otettu onnellinen", "tuolta, ottaa, onnellinen", "from there, taken, lucky/fortunate one", ""),
    ("takoa Tanikan linnan,", "takaa Tanikan linnan,", "taka, Tanikka, linna", "behind, Tanikka's (place), castle/hall", ""),
    ("uuen linnan ulkopuolta.", "uuden linnan ulkopuolelta.", "uusi, linna, ulkopuoli", "new, castle's/hall's, outside", ""),
    ("\"Eipä vielä sieltäkänä,", "\"Eipä vielä sieltäkään,", "ei, vielä, sieltä", "not, still, from there", ""),
    ("ei perän pereäkänä!", "ei perään pereäkään!", "ei, perä, perä", "not, back/stern, back/stern", ""),
    ("Tuolt' on saatu saajanainen,", "Tuolta on saatu saajanainen,", "tuolta, saada, saajanainen", "from there, gotten, bridesmaid", ""),
    ("tuolt' otettu onnellinen", "tuolta otettu onnellinen", "tuolta, ottaa, onnellinen", "from there, taken, lucky/fortunate one", ""),
    ("Vienan pääliltä vesiltä,", "Vienan päälisiltä vesiltä,", "Viena, päällinen, vesi", "Viena's (White Sea), upper, waters", ""),
    ("ulapoilta auke'ilta.", "ulapoilta avoimelta.", "ulappa, avoin", "open sea, open/wide", ""),
    ("\"Eipä vielä sieltäkänä,", "\"Eipä vielä sieltäkään,", "ei, vielä, sieltä", "not, still, from there", ""),
    ("ei perän pereäkänä!", "ei perään pereäkään!", "ei, perä, perä", "not, back/stern, back/stern", ""),
    ("Kasvoi maalla mansimarja,", "Kasvoi maalla mansikka,", "kasvaa, maa, mansikka", "to grow, land, strawberry", ""),
    ("punapuola kankahalla,", "punapuola kankaalla,", "punainen, puola, kangas", "red, lingonberry, heath/plain", ""),
    ("pellolla heleä heinä,", "pellolla heleä heinä,", "pelto, heleä, heinä", "field, radiant, hay/grass", ""),
    ("kukka kultainen aholla:", "kukka kultainen aholla:", "kukka, kultainen, aho", "flower, golden, clearing", ""),
    ("siit' on saatu saajanainen,", "siitä on saatu saajanainen,", "siitä, saada, saajanainen", "from that, gotten, bridesmaid", ""),
    ("siit' otettu onnellinen.", "siitä otettu onnellinen.", "siitä, ottaa, onnellinen", "from that, taken, lucky/fortunate one", ""),
    ("\"Saajanaisen suu somainen", "\"Saajanaisen suu somainen", "saajanainen, suu, soma", "bridesmaid's, mouth, lovely", ""),
    ("kuni Suomen sukkulainen;", "kuin Suomen sukkulainen;", "kuin, Suomi, sukkula", "like, Finland's, shuttle", ""),
    ("saajanaisen sirkut silmät", "saajanaisen kirkkaat silmät", "saajanainen, kirkas, silmä", "bridesmaid's, clear/bright, eyes", ""),
    ("kuni tähet taivahalla;", "kuin tähdet taivaalla;", "kuin, tähti, taivas", "like, stars, sky", ""),
    ("saajanaisen kuulut kulmat", "saajanaisen kuulut kulmat", "saajanainen, kuulu, kulma", "bridesmaid's, renowned, brows", ""),
    ("kuni kuu meren-ylinen.", "kuin kuu merenpäällinen.", "kuin, kuu, meri, päällinen", "like, moon, sea, over", ""),
    ("\"Onpa meiän saajanaisen", "\"Onpa meiän saajanaisen", "olla, me, saajanainen", "to be, our, bridesmaid's", ""),
    ("kaula kullankiehkuroissa,", "kaula kullankiehkuroissa,", "kaula, kulta, kiehkura", "neck, gold, coil/wreath", ""),
    ("pää kullanvipalehissa,", "pää kultavipaleissa,", "pää, kulta, vipale", "head, gold, slice/splint", ""),
    ("käet kullankäärilöissä,", "kädet kultakääreissä,", "käsi, kulta, kääre", "hands, gold, wrappings", ""),
    ("sormet kullansormuksissa,", "sormet kultasormuksissa,", "sormi, kulta, sormus", "fingers, gold, rings", ""),
    ("korvat kullanhelmilöissä,", "korvat kultahelmissä,", "korva, kulta, helmi", "ears, gold, beads/pearls", ""),
    ("kulmat kullansolmuloissa,", "kulmat kultasolmuissa,", "kulma, kulta, solmu", "brows, gold, knots/ornaments", ""),
    ("silmäripset simpsukoissa.", "silmäripset simpsukoissa.", "silmäripsi, simpsukka", "eyelashes, fringe/lash ornaments", ""),
    ("\"Luulin kuun kumottavaksi,", "\"Luulin kuun kumottavaksi,", "luulla, kuu, kumottaa", "to think/suppose, moon, to gleam/reflect", ""),
    ("kuu kumotti kultasolki;", "kuu kumotti kultasolki;", "kuu, kumottaa, kulta, solki", "moon, to gleam, gold, brooch", ""),
    ("luulin päivän paistavaksi,", "luulin päivän paistavaksi,", "luulla, päivä, paistaa", "to think/suppose, sun/day, to shine", ""),
    ("kun sen paistoi paian kaulus;", "kun sen paistoi paidan kaulus;", "kun, se, paistaa, paita, kaulus", "when, that, to shine, shirt's, collar", ""),
    ("luulin laivan läikkyväksi,", "luulin laivan läikkyväksi,", "luulla, laiva, läikkyä", "to think/suppose, ship, to glitter/flash", ""),
    ("kun sen läikkyi lakki päässä.", "kun se läikkyi lakki päässä.", "kun, se, läikkyä, lakki, pää", "when, that, to glitter, cap, head", ""),
    ("\"Jopa kiitin saajanaisen;", "\"Jo kiitin saajanaisen;", "jo, kiittää, saajanainen", "already, to thank/praise, bridesmaid", ""),
    ("annas katson kaiken kansan,", "annas katson kaiken kansan,", "antaa, katsoa, kaikki, kansa", "to let, to look at, all, people/folk", ""),
    ("onko kansa kaunihina,", "onko kansa kauniina,", "onko, kansa, kaunis", "is, people/folk, beautiful", ""),
    ("väki vanha vänkeänä", "väki vanha vänkeänä", "väki, vanha, vänkiä", "folk/people, old, vigorous/robust", ""),
    ("sekä nuoriso somana,", "sekä nuoriso somana,", "sekä, nuoriso, soma", "and, youth, lovely", ""),
    ("koko joukko juoleana!", "koko joukko juoleana!", "koko, joukko, juoleus", "whole, crowd, elegant/fine", ""),
    ("\"Jopa katsoin kaiken kansan,", "\"Jo katsoin kaiken kansan,", "jo, katsoa, kaikki, kansa", "already, to look at, all, people/folk", ""),
    ("ehkä tiesin ennoltaki:", "vaikka tiesin ennaltakin:", "vaikka, tietää, ennen", "even though, to know, before", ""),
    ("eip' ole tässä ennen ollut", "ei ole täällä ennen ollut", "ei, olla, täällä, ennen, olla", "not, to have been, here, before", ""),
    ("eikä varsin vasta liene", "eikä varsin juuri liene", "ei, varsin, juuri, lieneä", "not, quite, just, perhaps", ""),
    ("tämän joukon juoleutta,", "tämän joukon juoleutta,", "tämä, joukko, juoleus", "this, crowd's, elegance/fineness", ""),
    ("tämän kansan kauneutta,", "tämän kansan kauneutta,", "tämä, kansa, kauneus", "this, people's, beauty", ""),
    ("väen vanhan vänkeyttä,", "väen vanhan vänkeyttä,", "väki, vanha, vänkiä", "folk's, old, vigour/robustness", ""),
    ("väen nuorison somuutta.", "väen nuorison somiutta.", "väki, nuoriso, soma", "folk's, youth's, loveliness", ""),
    ("Kaikk' on kansa haljakassa", "Kaikki kansa haljakassa", "kaikki, kansa, haljaka", "all, people/folk, pale-blue/bright", ""),
    ("kuni metsä huutehessa:", "kuin metsä huutehessa:", "kuin, metsä, huute", "like, forest, in spring-flood", ""),
    ("alta on kuin aamurusko,", "alta on kuin aamurusko,", "alta, olla, kuin, aamurusko", "from below, to be, like, morning glow", ""),
    ("päältä on kuin päivänkoite.", "päältä on kuin päivänkoite.", "päältä, olla, kuin, päivänkoite", "from above, to be, like, sunrise", ""),
    ("\"Huokeat oli hopeat,", "\"Huokeat oli hopeat,", "huokea, olla, hopea", "light/cheap, to be, silvers", ""),
    ("löyhät kullat kutsuloilla,", "löyhät kullat kutsuilla,", "löyhä, kulta, kutsu", "loose/light, golds, invitations", ""),
    ("rahataskut tanterilla,", "rahataskut tanterilla,", "raha, tasku, tanner", "money, purses, on the ground", ""),
    ("rahakukkarot kujilla", "rahakukkarot kujilla", "raha, kukkaro, kuja", "money, purses, on the lanes", ""),
    ("näillä kutsuvierahilla", "näillä kutsuvierailla", "tämä, kutsuvieras", "these, invited-guests'", ""),
    ("kutsuloille kunniaksi.\"", "kutsuille kunniaksi.\"", "kutsu, kunnia", "invitations', honour", "Väinämöinen's closing toast — 'silver was light, gold loose on these guests' hands, money-purses on the ground, purses in the lanes of these invited guests, as an honour to the invitations' — is the trickster-shaman's most ironic praise: the guests were so rich their money fell about them."),
    ("Vaka vanha Väinämöinen,", "Vakaa vanha Väinämöinen,", "vakaa, vanha, Väinämöinen", "steady/wise, old, Väinämöinen", ""),
    ("virren ponsi polvu'inen,", "virren ponsi polvinen,", "virsi, ponsi, polvinen", "rune's, pedal/spring, generational", ""),
    ("siitä siirtihe rekehen,", "siitä siirtyi rekeen,", "siitä, siirtyä, reki", "from that, to move, sled", ""),
    ("lähtevi kohin kotia;", "lähtee kohti kotia;", "lähteä, kohti, koti", "to set out, toward, home", ""),
    ("laulelevi virsissänsä,", "laulelevi virsissänsä,", "laulella, virsi", "to sing softly, runes", ""),
    ("laulelevi, taitelevi.", "laulelevi, taitelevi.", "laulella, taitella", "to sing softly, to perform/play", ""),
    ("Lauloi virren, lauloi toisen", "Lauloi virren, lauloi toisen", "laulaa, virsi, toinen", "to sing, rune, second", ""),
    ("- virrelläpä kolmannella", "- virrelläpä kolmannella", "virsi, kolmas", "rune, third", ""),
    ("kilahti jalas kivehen,", "kilahti jalas kiveen,", "kilahti, jalas, kivi", "to ring/clang, sled-runner, stone", ""),
    ("tarttui kapla kannon päähän:", "tarttui kapla kannon päähän:", "tarttua, kapla, kanto, pää", "to catch/stick, swingletree-pin, stump, end/head", ""),
    ("rikkoihe reki runolta,", "rikkoutui reki runolta,", "rikkoutua, reki, runo", "to break, sled, rune", "Väinämöinen's sled breaking on the third rune — the runner striking a stone, the pin catching a stump — is the trickster's characteristic third-time reversal: the perfect singer-feast ends in a broken sled, demanding a new journey to the realm of the dead."),
    ("jalas taittui laulajalta,", "jalas taittui laulajalta,", "jalas, taittua, laulaja", "sled-runner, to snap, singer", ""),
    ("kapla poikki paukahutti,", "kapla poikki paukahutti,", "kapla, poikki, paukahtaa", "swingletree-pin, across, to bang/crack", ""),
    ("laiat irti loskahutti.", "laiat irti loskahutti.", "laita, irti, loskahtaa", "sides, loose, to splash/crash", ""),
    ("Sanoi vanha Väinämöinen,", "Sanoi vanha Väinämöinen,", "sanoa, vanha, Väinämöinen", "to say, old, Väinämöinen", ""),
    ("itse virkkoi, noin nimesi:", "itse virkkoi, noin nimitti:", "itse, virkata, nimittää", "himself, to say, to name/call", ""),
    ("\"Onko tässä nuorisossa,", "\"Onko täällä nuorisossa,", "onko, täällä, nuoriso", "is, here, youth", ""),
    ("kansassa kasuavassa,", "kansassa kasvavassa,", "kansa, kasvaa", "people/folk, growing", ""),
    ("vaiko tässä vanhalassa,", "vaiko täällä vanhalassa,", "vai, täällä, vanha", "or, here, old", ""),
    ("väessä vähenevässä,", "väessä vähenevässä,", "väki, vähentyä", "folk/people, diminishing", ""),
    ("kenpä Tuonelle kävisi,", "kenpä Tuonelle kävisi,", "kuka, Tuonela, käydä", "who, Tuonela's (realm of dead), to go", ""),
    ("lähtisi Manan majoille,", "lähtisi Manan majoille,", "lähteä, Manala, maja", "to set out, Manala's (realm of dead), dwellings", ""),
    ("toisi Tuonelta orasen,", "toisi Tuonelta orasen,", "tuoda, Tuonela, oranen", "to bring, Tuonela, sapling", ""),
    ("vääntiän Manan väeltä", "vääntiän Manan väeltä", "vääntiä, Manala, väki", "bending-piece/orb, Manala's, folk/people", ""),
    ("reki uusi laatiani,", "reki uusi laatiakseni,", "reki, uusi, laattia", "sled, new, to make", ""),
    ("korjanen kohentoani?\"", "korjanen kohentamakseni?\"", "korja, kohentaa", "sleigh, to adjust/repair", "Väinämöinen asking the crowd — young or old — who will go to Tuonela for a sapling and bending-piece to make a new sled, and the crowd refusing unanimously — is the trickster's characteristic pattern: no one else can do what he does, so he must go himself."),
    ("Sekä nuoremmat sanovi,", "Sekä nuoremmat sanoivat,", "sekä, nuorempi, sanoa", "and, younger, to say", ""),
    ("jotta vanhat vastoavi:", "jotta vanhat vastasivat:", "jotta, vanha, vastata", "that, old, to answer", ""),
    ("\"Ei ole tässä nuorisossa", "\"Ei ole täällä nuorisossa", "ei, olla, täällä, nuoriso", "not, to be, here, youth", ""),
    ("eikä varsin vanhastossa,", "eikä varsin vanhastossa,", "ei, varsin, vanha", "not, quite, old", ""),
    ("koko suuressa su'ussa", "koko suuressa suvussa", "koko, suuri, suku", "whole, great, lineage/kin", ""),
    ("niin urosta urheata,", "niin urosta urheata,", "niin, uros, urhea", "so, hero/man, brave/bold", ""),
    ("jotta Tuonelle menisi,", "että Tuonelle menisi,", "että, Tuonela, mennä", "that, Tuonela's, to go", ""),
    ("lähtisi Manan majoille,", "lähtisi Manan majoille,", "lähteä, Manala, maja", "to set out, Manala's, dwellings", ""),
    ("toisi Tuonelta orasen,", "toisi Tuonelta orasen,", "tuoda, Tuonela, oranen", "to bring, Tuonela, sapling", ""),
    ("vääntiän Manan majoilta", "vääntiän Manan majoilta", "vääntiä, Manala, maja", "bending-piece/orb, Manala's, dwellings", ""),
    ("reki uusi laatiasi,", "reki uusi laatiaksesi,", "reki, uusi, laattia", "sled, new, to make", ""),
    ("korjanen kohentoasi.\"", "korjanen kohentamaksesi.\"", "korja, kohentaa", "sleigh, to adjust/repair", ""),
    ("Silloin vanha Väinämöinen,", "Silloin vanha Väinämöinen,", "silloin, vanha, Väinämöinen", "then, old, Väinämöinen", ""),
    ("laulaja iän-ikuinen,", "laulaja iän-ikuinen,", "laulaja, ikuinen", "singer, age-eternal", ""),
    ("läksi toiste Tuonelahan,", "läksi toiste Tuonelaan,", "lähteä, toiste, Tuonela", "to set out, again, Tuonela", ""),
    ("matkasi Manan majoille.", "matkasi Manan majoille.", "matkustaa, Manala, maja", "to travel, Manala's, dwellings", ""),
    ("Toi orasen Tuonelasta,", "Toi orasen Tuonelasta,", "tuoda, oranen, Tuonela", "to bring, sapling, Tuonela", ""),
    ("vääntiän Manan majoilta.", "vääntiän Manan majoilta.", "vääntiä, Manala, maja", "bending-piece/orb, Manala's, dwellings", ""),
    ("Siitä vanha Väinämöinen", "Siitä vanha Väinämöinen", "siitä, vanha, Väinämöinen", "from that, old, Väinämöinen", ""),
    ("laulavi salon sinisen,", "laulaa salon sinisen,", "laulaa, salo, sininen", "to sing, wilderness, blue", ""),
    ("salohon tasaisen tammen", "saloon tasaisen tammen", "salo, tasainen, tammi", "wilderness, even/flat, oak", ""),
    ("sekä pihlajan pätevän;", "sekä pihlajan pätevän;", "sekä, pihlaja, pätevä", "and, rowan-tree, capable/sufficient", ""),
    ("ne kohenti korjaksensa,", "ne kohenti korjaksensa,", "kohentaa, korja", "to adjust/shape, as sleigh", ""),
    ("painalti jalaksiksensa,", "painalti jalaksiksensa,", "painaltaa, jalas", "to press, as runners", ""),
    ("niistä katsoi kaplaksia", "niistä katsoi kaplaksia", "niistä, katsoa, kapla", "from those, to look for, swingletree-pins", ""),
    ("sekä väänti vempeleitä:", "sekä väänti vempeleitä:", "sekä, vääntää, vempele", "and, to twist, swingletrees", ""),
    ("sai korjan kohennetuksi,", "sai korjan kohennetuksi,", "saada, korja, kohentaa", "to get, sleigh, adjusted/shaped", ""),
    ("re'en uuen laaituksi.", "reen uuden laitetuksi.", "reki, uusi, laittaa", "sled, new, made/prepared", ""),
    ("Pisti varsan valjahisin,", "Pisti varsan valjaisihin,", "pistää, varsa, valjaat", "to put, foal, harness", ""),
    ("ruskean re'en etehen,", "ruskean reen eteen,", "ruskea, reki, eteen", "brown/russet, sled, in front of", ""),
    ("itse istuihe rekehen,", "itse istui rekeen,", "itse, istua, reki", "himself, to sit, sled", ""),
    ("laskettihe laitiohon.", "laskeutui laitaan.", "laskeutua, laita", "to settle, side/edge", ""),
    ("Vitsattaki virkku juoksi,", "Vitsattakin virkku juoksi,", "vitsa, virkku, juosta", "switch/whip, lively one, to run", ""),
    ("helmin lyömättä hevonen", "helmin lyömättä hevonen", "helmi, lyödä, hevonen", "bells, without striking, horse", ""),
    ("entisille appehille,", "entisille reille,", "entinen, reitti", "former, routes/paths", ""),
    ("taanoisille suuruksille;", "taanoisille retkille;", "tanoinen, retki", "former, journeys/trips", ""),
    ("saattoi vanhan Väinämöisen,", "saattoi vanhan Väinämöisen,", "saattaa, vanha, Väinämöinen", "to escort/bring, old, Väinämöinen", ""),
    ("laulajan iän-ikuisen,", "laulajan iän-ikuisen,", "laulaja, ikuinen", "singer's, age-eternal", ""),
    ("oman uksen aukomille,", "oman uksen aukomille,", "oma, ovi, avata", "own, door's, opening", ""),
    ("oman kynnyksen etehen.", "oman kynnyksen eteen.", "oma, kynnys, eteen", "own, threshold, in front of", "Väinämöinen going to Tuonela alone, fetching the sapling and bending-piece, singing an oak and rowan from the blue wilderness, fashioning a new sled without asking anyone's help, and being brought home to his own threshold by his horse without a whip — is the eternal trickster's final act in this section: self-sufficient, unremarkable, solitary, returning to his own door as if death's realm were just another errand."),
]

thin_border = Border(
    left=Side(style='thin', color='CCCCCC'),
    right=Side(style='thin', color='CCCCCC'),
    top=Side(style='thin', color='CCCCCC'),
    bottom=Side(style='thin', color='CCCCCC')
)
fill_even = PatternFill("solid", start_color="F7F3E9")
fill_odd  = PatternFill("solid", start_color="FFFFFF")
fill_trickster = PatternFill("solid", start_color="FFF3CD")
normal_font    = Font(name="Arial", size=10)
trickster_font = Font(name="Arial", size=10, italic=True, color="7B5E00")

for i, (orig, modern, basic, trans, trick) in enumerate(verses, start=2):
    row_fill = fill_even if i % 2 == 0 else fill_odd
    for col, val in enumerate([orig, modern, basic, trans, trick], start=1):
        cell = ws.cell(row=i, column=col, value=val)
        cell.font = trickster_font if (col == 5 and trick) else normal_font
        cell.fill = fill_trickster if (col == 5 and trick) else row_fill
        cell.border = thin_border
        cell.alignment = Alignment(wrap_text=True, vertical="top")

ws.column_dimensions['A'].width = 32
ws.column_dimensions['B'].width = 32
ws.column_dimensions['C'].width = 30
ws.column_dimensions['D'].width = 32
ws.column_dimensions['E'].width = 55
ws.freeze_panes = "A2"
ws.row_dimensions[1].height = 30
for r in range(2, len(verses)+2):
    ws.row_dimensions[r].height = 30

out = "Kalevala_Runo_25_Analysis.xlsx"
wb.save(out)
print("Saved:", out, "–", len(verses), "verses")
