from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

wb = Workbook()
ws = wb.active
ws.title = "Runo 41"

headers = ["A: Alkuperäinen säe", "B: Nykysuomi", "C: Perusmuodot", "D: Käännös (EN)", "E: Trickster-huomiot"]
for col, h in enumerate(headers, 1):
    cell = ws.cell(row=1, column=col, value=h)
    cell.font = Font(bold=True, name="Arial", size=11, color="FFFFFF")
    cell.fill = PatternFill("solid", start_color="2E4057")
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

verses = [
    ("Vaka vanha Väinämöinen,","Vankka vanha Väinämöinen,","vakaa, vanha, Väinämöinen","steady, old, Väinämöinen",""),
    ("laulaja iän-ikuinen,","laulaja iän-ikuinen,","laulaja, ikä, ikuinen","singer, age, eternal",""),
    ("sormiansa suorittavi,","sormiaan suorittaa,","sormi, suorittaa","finger, to prepare/straighten",""),
    ("peukaloitansa pesevi.","peukaloitaan pesee.","peukalo, pestä","thumb, to wash","Väinämöinen washes and prepares his fingers before playing — the trickster-shaman performing ritual preparation before a magical act."),
    ("Istuiksen ilokivelle,","Istuutuu ilokivelle,","istuutua, ilokivi","to sit down, joy-stone",""),
    ("laulupaaelle paneikse","laulupaaelle paneutuu","laulupaa, paneutua","song-rock, to settle/lie down",""),
    ("hope'iselle mäelle,","hopeiselle mäelle,","hopea, mäki","silver, hill",""),
    ("kultaiselle kunnahalle.","kultaiselle kunnaalle.","kultainen, kunnas","golden, hillock",""),
    ("Otti soiton sormillensa,","Otti soiton sormillensa,","ottaa, soitto, sormi","to take, instrument, finger",""),
    ("käänti käyrän polvillensa,","käänsi käyrän polvilleen,","kääntää, käyrä, polvi","to turn, curved/arching, knee",""),
    ("kantelen kätensä alle.","kantelen käsiensä alle.","kantele, käsi, alle","kantele, hand, under/beneath",""),
    ("Sanan virkkoi, noin nimesi:","Sanan sanoi, noin nimesi:","sana, virkkoa, noin, nimetä","word, to say, thus, to name",""),
    ('"Tulkohonpa kuulemahan,','"Tulkoon kuulemaan,',"tulla, kuulla","to come, to hear",""),
    ("ku ei liene ennen kuullut","joka ei liene ennen kuullut","joka, ei, olla, ennen, kuulla","who, not, to be, before, to hear",""),
    ("iloa ikirunojen,","iloa ikirunojen,","ilo, ikiruno","joy, eternal-song/rune",""),
    ('kajahusta kanteloisen!"','kajahusta kanteleisen!"',"kajahdus, kantele","resounding/echo, kantele",""),
    ("Siitä vanha Väinämöinen","Siitä vanha Väinämöinen","siitä, vanha, Väinämöinen","then, old, Väinämöinen",""),
    ("alkoi soittoa somasti","alkoi soittoa somasti","alkaa, soitto, somasti","to begin, playing/music, finely/beautifully",""),
    ("hauinruotaista romua,","hauinruotoista romua,","hauinruoto, romu","pike-boned, junk/scrap","The kantele again called 'bony junk' even as its music enchants the world — the trickster's power is hidden in humble appearances."),
    ("kalanluista kanteletta.","kalanluista kanteletta.","kalanluu, kantele","fish bone, kantele",""),
    ("Sormet nousi notkeasti,","Sormet nousivat notkeasti,","sormi, nousta, notkea","finger, to rise, supple/nimble",""),
    ("peukalo ylös keveni.","peukalo ylös keveni.","peukalo, ylös, keveys","thumb, upward, lightness",""),
    ("Jo kävi ilo ilolle,","Jo kävi ilo ilolle,","jo, käydä, ilo","already/now, to go, joy",""),
    ("riemu riemulle remahti,","riemu riemulle remahti,","riemu, remahtaa","rejoicing/delight, to burst into joy",""),
    ("tuntui soitto soitannalle,","tuntui soitto soitannalle,","tuntua, soitto, soitanto","to feel/seem, music, playing",""),
    ("laulu laululle tehosi.","laulu laululle tehosi.","laulu, tehota","song, to take effect/resonate",""),
    ("Helähteli hauin hammas,","Helähteli hauen hammas,","helähtää, hauki, hammas","to ring/clang, pike, tooth",""),
    ("kalan pursto purkaeli,","kalan pursto purkaeli,","kala, pursto, purkaella","fish, tail, to resound/crack",""),
    ("ulvosi upehen jouhet,","ulvoi upean jouhet,","ulvoa, upea, jouhi","to howl/wail, splendid, horsehair",""),
    ("jouhet ratsun raikkahuivat.","jouhet ratsun raikkahuivat.","jouhi, ratsu, raikkahtaa","horsehair, steed/horse, to ring out clearly",""),
    ("Soitti vanha Väinämöinen.","Soitti vanha Väinämöinen.","soittaa, vanha, Väinämöinen","to play, old, Väinämöinen",""),
    ("Ei ollut sitä metsässä","Ei ollut sitä metsässä","ei, olla, se, metsä","not, to be, it/that, forest",""),
    ("jalan neljän juoksevata,","neljäjalkaisena juoksevaa,","jalka, neljä, juosta","leg, four, to run",""),
    ("koivin koikkelehtavata,","koivin koikkelehtavaa,","koivu, koikkelehta","birch tree, to leap/frisk",""),
    ("ku ei tullut kuulemahan,","joka ei tullut kuulemaan,","joka, ei, tulla, kuulla","who, not, to come, to hear",""),
    ("iloa imehtimähän.","iloa ihmettelemään.","ilo, ihmetellä","joy, to wonder at/marvel",""),
    ("Oravat ojentelihe","Oravat ojentautuivat","orava, ojentautua","squirrel, to stretch/lean",""),
    ("lehväseltä lehväselle;","lehvältä lehvälle;","lehvä","from branch to branch",""),
    ("tuohon kärpät kääntelihe,","tuohon soppelit kääntyivät,","soppeli, kääntyä","marten/sable, to turn",""),
    ("aioillen asettelihe.","aisoille asettuivat.","aisa, asettua","shaft/pole, to settle/sit",""),
    ("Hirvet hyppi kankahilla,","Hirvet hyppivät kankahilla,","hirvi, hyppiä, kangas","elk/moose, to jump, heath/plain",""),
    ("ilvekset piti iloa.","ilvekset pitivät iloa.","ilves, pitää, ilo","lynx, to keep/hold, joy",""),
    ("Heräsi susiki suolta,","Heräsi susikin suolta,","herätä, susi, suo","to wake, wolf, swamp/marsh",""),
    ("nousi karhu kankahalta","nousi karhu kankaalta","nousta, karhu, kangas","to rise, bear, heath",""),
    ("petäjäisestä pesästä,","petäjäisestä pesästä,","petäjä, pesä","pine-tree, nest/lair",""),
    ("kutiskosta kuusisesta.","kutiskosta kuusisesta.","kutisko, kuusi","thicket, spruce",""),
    ("Susi juoksi suuret matkat,","Susi juoksi suuret matkat,","susi, juosta, suuri, matka","wolf, to run, great, distance/journey",""),
    ("karhu kankahat samosi;","karhu kankaat samosi;","karhu, kangas, samoilla","bear, heath, to roam/wander",""),
    ("viimein aiallen asettui,","viimein aioille asettui,","viimein, aisa, asettua","finally, shaft/pole, to settle",""),
    ("veräjälle vieretäikse:","veräjälle vierähti:","veräjä, vierähtää","gate, to roll/tumble",""),
    ("aita kaatui kalliolle,","aita kaatui kalliolle,","aita, kaatua, kallio","fence, to fall, cliff/rock",""),
    ("veräjä aholle vieri.","veräjä aholle vieri.","veräjä, aho, vieristä","gate, open field, to roll",""),
    ("Siitä kuusehen kuvahti,","Siitä kuuseen kuvahti,","siitä, kuusi, kuvahtaa","then, spruce, to press/lean against",""),
    ("petäjähän pyörähytti","petäjähän pyörähti","petäjä, pyörähtää","pine tree, to spin/turn",""),
    ("soitantoa kuulemahan,","soitantoa kuulemaan,","soitanto, kuulla","playing/music, to hear",""),
    ("iloa imehtimähän.","iloa ihmettelemään.","ilo, ihmetellä","joy, to wonder at/marvel",""),
    ("Tapiolan tarkka ukko,","Tapiolan tarkka ukko,","Tapiola, tarkka, ukko","Tapiola (forest realm), watchful/precise, old man",""),
    ("itse Metsolan isäntä,","itse Metsolan isäntä,","itse, Metsola, isäntä","himself, Metsola (forest realm), master/lord",""),
    ("ja kaikki Tapion kansa,","ja kaikki Tapion kansa,","ja, kaikki, Tapio, kansa","and, all, Tapio (forest god), people/folk",""),
    ("sekä piiat jotta poiat,","sekä piiat että pojat,","sekä, piika, poika","and/both, maid, boy/son",""),
    ("kulki vuoren kukkulalle","kulki vuoren kukkulalle","kulkea, vuori, kukkula","to go/travel, mountain, peak/summit",""),
    ("soittoa tajuamahan.","soittoa tajuamaan.","soitto, tajuta","music, to perceive/grasp",""),
    ("Itseki metsän emäntä,","Itsekkin metsän emäntä,","itse, metsä, emäntä","herself, forest, mistress",""),
    ("Tapiolan tarkka vaimo,","Tapiolan tarkka vaimo,","Tapiola, tarkka, vaimo","Tapiola, watchful, woman/wife",""),
    ("sinisukkahan siroikse,","sinisukkaansa siistii,","sinisukka, siistiä","blue stocking, to tidy/neaten",""),
    ("punapaulahan paneikse;","punanauhaansa panemaan;","punanauha, panna","red ribbon, to put on",""),
    ("loihe koivun konkelolle,","kävi koivun konkelolle,","käydä, koivu, konkelo","to go, birch, leaning trunk/branch",""),
    ("lepän lengolle levahti","lepän lengolle levähti","lepän lengo, levätä","alder branch, to settle/rest",""),
    ("kanteloista kuulemahan,","kanteletta kuulemaan,","kantele, kuulla","kantele, to hear",""),
    ("soittoa tajuamahan.","soittoa tajuamaan.","soitto, tajuta","music, to perceive",""),
    ("Mi oli ilman lintujaki,","Mitä oli ilman lintuja,","mikä, ilma, lintu","what, air, bird",""),
    ("kahen siiven sirkovia,","kahden siiven sirkuttajia,","kaksi, siipi, sirkuttaa","two, wing, to twitter/chirp",""),
    ("ne tulivat tuiskutellen,","ne tulivat tuiskutellen,","ne, tulla, tuiskuttaa","they, to come, to rush/flutter",""),
    ("kiiätellen kiirehtivät","kiitellen kiirehtivät","kiitää, kiirehtiä","to rush/dart, to hasten",""),
    ("kunnioa kuulemahan,","kunniaa kuulemaan,","kunnia, kuulla","honour/glory, to hear",""),
    ("iloa imehtimähän.","iloa ihmettelemään.","ilo, ihmetellä","joy, to wonder at/marvel",""),
    ("Kokko kun kotona kuuli","Kokko kun kotona kuuli","kokko, kun, koti, kuulla","eagle, when, home, to hear",""),
    ("sen sorean Suomen soiton,","sen sorean Suomen soiton,","se, sorea, Suomi, soitto","that, graceful/fine, Finland, music",""),
    ("heitti pentunsa pesähän;","heitti pentunsa pesähän;","heittää, pentu, pesä","to put/leave, young/pup, nest",""),
    ("itse loihe lentämähän","itse ryhtyi lentämään","itse, ryhtyä, lentää","himself, to begin, to fly",""),
    ("soittohon sulan urohon,","soittoon sulan urohon,","soitto, sula, uros","music, fluent/smooth, hero/man",""),
    ("Väinämöisen vääntelöhön.","Väinämöisen vääntelöihin.","Väinämöinen, vääntelö","Väinämöinen, playing/turning",""),
    ("Korkealta kokko lenti,","Korkealta kokko lensi,","korkea, kokko, lentää","from high, eagle, to fly",""),
    ("halki pilvien havukka,","halki pilvien havukka,","halki, pilvi, havukka","through, cloud, hawk/eagle",""),
    ("allit aalloilta syviltä,","allit aalloilta syviltä,","alli, aalto, syvä","long-tailed duck, wave, deep",""),
    ("joutsenet sulilta soilta.","joutsenet sulilta soilta.","joutsen, sula, suo","swan, thawed/open, swamp/marsh",""),
    ("Pieniäki peiposia,","Pieniäkin peiposia,","pieni, peippo","small, chaffinch",""),
    ("lintuja livertäviä,","lintuja livertäviä,","lintu, livertää","bird, to warble/trill",""),
    ("sirkkuja satalukuisin,","sirkkuja satalukuisin,","sirkku, sata, luku","bunting/sparrow, hundred, number",""),
    ("leivoja liki tuhatta","leivoja liki tuhatta","leivo, liki, tuhat","lark, nearly, thousand",""),
    ("ilmassa ihastelivat,","ilmassa ihastelivat,","ilma, ihastella","air, to delight/admire",""),
    ("hartioilla haastelivat,","hartioilla haastelivat,","hartia, haastella","shoulder, to chatter/converse",""),
    ("tehessä isän iloa,","tehdessä isän iloa,","tehdä, isä, ilo","to make, father, joy",""),
    ("soitellessa Väinämöisen.","soitellessa Väinämöisen.","soitella, Väinämöinen","to play/perform, Väinämöinen",""),
    ("Itse ilman luonnottaret,","Itse ilman luonnottaret,","itse, ilma, luonnotar","themselves, air, nature spirit (female)",""),
    ("ilman impyet ihanat,","ilman ihastuttavat impyet,","ilma, ihana, impi","air, wonderful/lovely, maiden","Nature spirits come to listen — the trickster-shaman's music reaches even the supernatural world."),
    ("iloa imehtelivät,","iloa ihmettelivät,","ilo, ihmetellä","joy, to wonder at/marvel",""),
    ("kanteloista kuuntelivat;","kanteletta kuuntelivat;","kantele, kuunnella","kantele, to listen",""),
    ("mikä ilman vempelellä,","mikä ilman harsolla,","mikä, ilma, vempele","which/who, air, veil/gauze",""),
    ("taivon kaarella kajotti,","taivaan kaarella kajotti,","taivas, kaari, kajottaa","sky/heaven, arc, to gleam/shimmer",""),
    ("mikä pienen pilven päällä,","mikä pienen pilven päällä,","mikä, pieni, pilvi, päällä","which/who, small, cloud, on top of",""),
    ("rusoreunalla rehotti.","rusoreunalla rehotti.","rusoinen, reuna, rehottaa","rosy-edged, edge, to revel/flourish",""),
    ("Tuo Kuutar, korea impi,","Tuo Kuutar, korea impi,","Kuutar, korea, impi","Kuutar (Moon maiden), beautiful/fine, maiden",""),
    ("neiti Päivätär pätevä","neiti Päivätär pätevä","Päivätär, pätevä","Päivätär (Sun maiden), capable/worthy",""),
    ("pitelivät pirtojansa,","pitelivät pirtojaan,","pitellä, pirta","to hold, weaving reed/heddle",""),
    ("niisiänsä nostelivat,","niisiään nostelivat,","nostella, niisi","to lift, heddle (weaving)",""),
    ("kultakangasta kutoivat,","kultakangasta kutoivat,","kulta, kangas, kutoa","gold, cloth, to weave",""),
    ("hope'ista helskyttivät","hopeista helskyttivät","hopea, helskyttää","silver, to jingle/clatter",""),
    ("äärellä punaisen pilven,","äärellä punaisen pilven,","ääri, punainen, pilvi","edge/rim, red, cloud",""),
    ("pitkän kaaren kannikalla.","pitkän kaaren kannikalla.","pitkä, kaari, kannikka","long, arc, bridge/span",""),
    ("Kunpa saivat kuullaksensa","Kun saivat kuullakseen","kun, saada, kuulla","when, to get, to hear",""),
    ("tuon sorean soiton äänen,","tuon sorean soiton äänen,","tuo, sorea, soitto, ääni","that, graceful/fine, music, sound",""),
    ("jo pääsi piosta pirta,","jo pääsi piosta pirta,","jo, päästä, pio, pirta","already/now, to escape, grasp, weaving reed","Even the Moon and Sun maidens drop their weaving tools — Väinämöinen's music disrupts the cosmic order, a divine trickster power."),
    ("suistui sukkula käestä,","suistui sukkula kädestä,","suistua, sukkula, käsi","to slip/fall, shuttle, hand",""),
    ("katkesihe kultarihmat,","katkesivat kultarihmat,","kateta, kulta, rihma","to break, gold, thread",""),
    ("helkähti hopeaniiet.","helkähti hopeaniiet.","helkähtää, hopea, niisi","to clang/ring, silver, heddle",""),
    ("Ei sitä oloista ollut,","Ei sitä oloista ollut,","ei, se, oloinen, olla","not, it, kind/sort, to be",""),
    ("ei ollut ve'essäkänä","ei ollut vedessäkään","ei, olla, vesi","not, to be, water",""),
    ("evän kuuen kulkevata,","eväkuutta kulkevaa,","evä, kuusi, kulkea","fin, six, to travel",""),
    ("kalaparvea parasta,","kalaparvea parasta,","kalaparvi, paras","school of fish, best/finest",""),
    ("ku ei tullut kuulemahan,","joka ei tullut kuulemaan,","joka, ei, tulla, kuulla","who, not, to come, to hear",""),
    ("iloa imehtimähän.","iloa ihmettelemään.","ilo, ihmetellä","joy, to wonder at/marvel",""),
    ("Uipi hauit hangotellen,","Uivat hauit hangotellen,","uida, hauki, hangotella","to swim, pike, to glide/push forward",""),
    ("ve'en koirat vengotellen,","veden koirat vengotellen,","vesi, koira, vengotella","water, dog, to stretch/crane",""),
    ("lohet luo'oilta samosi,","lohet luodoilta samosi,","lohi, luoto, samoilla","salmon, skerry/reef, to wander/roam",""),
    ("siikaset syväntehiltä.","siikaset syväntehiltä.","siika, syvänne","whitefish, deep (place)",""),
    ("Säret pienet, ahvenetki,","Särkiset pienet, ahvenetkin,","särki, ahven","roach, perch",""),
    ("mujehetki, muut kalatki","mujehetkin, muut kalalkin","mujekka, muu, kala","vendace/bleak, other, fish",""),
    ("rinnoin ruokohon ajaikse,","rinnoin ruokohon ajoivat,","rinnoin, ruoko, ajaa","abreast/side by side, reed, to drive",""),
    ("rantahan rakenteleikse","rantaan rakenteleikse","ranta, rakentela","shore, to gather/build up",""),
    ("virttä Väinön kuulemahan,","virttä Väinön kuulemaan,","virsi, Väinö, kuulla","hymn/song, Väinö (Väinämöinen), to hear",""),
    ("soittoa tajuamahan.","soittoa tajuamaan.","soitto, tajuta","music, to perceive/grasp",""),
    ("Ahto, aaltojen kuningas,","Ahto, aaltojen kuningas,","Ahto, aalto, kuningas","Ahto (sea god), wave, king",""),
    ("ve'en ukko ruohoparta,","veden ukko ruohoparta,","vesi, ukko, ruoho, parta","water, old man, grass/reed, beard",""),
    ("ve'en kalvolle veäikse,","veden kalvolle vetäytyi,","vesi, kalvo, vetäytyä","water, film/surface, to draw/pull",""),
    ("luikahaikse lumpehelle;","luikahti lumpehelle;","luikahtaa, lumme","to glide, water lily",""),
    ("siinä kuunteli iloa.","siinä kuunteli iloa.","siinä, kuunnella, ilo","there/then, to listen, joy",""),
    ("Itse tuon sanoiksi virkki:","Itse tuon sanoiksi sanoi:","itse, tuo, sana, virkkoa","himself, that, word, to say",""),
    ('"En ole mointa ennen kuullut','"En ole moista ennen kuullut',"ei, olla, moinen, ennen, kuulla","not, to be, such/like that, before, to hear",""),
    ("sinä ilmoisna ikänä,","sinä ihmoisena ikänä,","se, ihmoinen, ikä","that, in all one's life, age",""),
    ("soitantoa Väinämöisen,","soitantoa Väinämöisen,","soitanto, Väinämöinen","playing/music, Väinämöinen",""),
    ('soittoa ikirunojan!"','soittoa ikirunojan!"',"soitto, ikiruno","music, eternal-song/rune","Even the sea king Ahto openly declares he has never heard anything like it — the trickster-artist's triumph confirmed by supernatural authority."),
    ("Sisarekset sotkottaret,","Sisarekset sotkottaret,","sisar, sotka","sisters, eider duck",""),
    ("rannan ruokoiset kälykset,","rannan ruokoiset kälykset,","ranta, ruokoinen, käly","shore, reedy, sister-in-law",""),
    ("hiipoivat hivuksiansa,","hipoivat hiuksiaan,","hipoa, hius","to comb/stroke, hair",""),
    ("hapsiansa harjasivat","hiuksiaan harjasivat","hius, harjata","hair, to brush/comb",""),
    ("harjalla hopeapäällä,","harjalla hopeapäällä,","harja, hopea, pää","brush, silver, head",""),
    ("sukimella kultaisella.","sukimella kultaisella.","sukia, kultainen","comb, golden",""),
    ("Saivat kuulla äänen ouon,","Saivat kuulla äänen oudon,","saada, kuulla, ääni, outo","to get, to hear, sound, strange/eerie",""),
    ("tuon on soitannan sorean:","tuon soitannan sorean:","tuo, soitanto, sorea","that, playing/music, graceful/fine",""),
    ("sulkahti suka vetehen,","sulkahti suka veteen,","sulahtaa, suka, vesi","to slip/sink, comb, water",""),
    ("haihtui harja lainehesen.","haihtui harja laineheen.","haihtua, harja, laine","to vanish/dissolve, brush, wave",""),
    ("Jäi hivukset hiipomatta,","Jäi hiukset hipomatta,","jäädä, hius, hipoa","to remain, hair, to comb",""),
    ("tukat kesken suorimatta.","tukat kesken suorimatta.","tukka, kesken, suorittaa","hair, unfinished/half-done, to straighten",""),
    ("Itseki ve'en emäntä,","Itsekkin veden emäntä,","itse, vesi, emäntä","herself, water, mistress",""),
    ("ve'en eukko ruokorinta,","veden eukko ruokorinta,","vesi, eukko, ruoko, rinta","water, old woman, reed, chest/breast",""),
    ("jopa nousevi merestä","jopa nousee merestä","jo, nousta, meri","already/now, to rise, sea",""),
    ("ja lapaikse lainehesta;","ja lapautuu lainehesta;","lapautua, laine","to flatten/slip, wave",""),
    ("ruokorintahan rivahti,","ruokorintahan rivahti,","ruokorinta, rivahtaa","reed-breasted one, to dart/rush",""),
    ("väännäikse vesikarille","väännäytyi vesikarille","vääntyä, vesikari","to twist/turn, water reef/rock",""),
    ("tuota ääntä kuulemahan,","tuota ääntä kuulemaan,","tuo, ääni, kuulla","that, sound, to hear",""),
    ("soitantoa Väinämöisen,","soitantoa Väinämöisen,","soitanto, Väinämöinen","playing/music, Väinämöinen",""),
    ("kun oli ääni kummanlainen,","kun oli ääni kummanlainen,","kun, olla, ääni, kummallinen","when, to be, sound, strange/wondrous",""),
    ("soitanto ylen sorea.","soitanto ylen sorea.","soitanto, ylen, sorea","playing/music, very/exceedingly, graceful/fine",""),
    ("Se siihen sike'in nukkui,","Se siihen sikeästi nukkui,","se, siinä, sikeästi, nukkua","she/it, there, deeply, to sleep","The water mistress falls into enchanted sleep — the music has the power to bespell even supernatural beings; a shamanic/trickster power."),
    ("vaipui maata vatsallehen","vaipui maata vatsallaan","vaipua, maata, vatsa","to sink/fall, to lie, belly",""),
    ("kirjavan kiven selälle,","kirjavan kiven selälle,","kirjava, kivi, selkä","speckled/multicoloured, stone, back/top",""),
    ("paaen paksun pallealle.","paaen paksun pallealle.","paasi, paksu, pallea","flat rock, thick, belly/dome",""),
    ("Siinä vanha Väinämöinen","Siinä vanha Väinämöinen","siinä, vanha, Väinämöinen","there/then, old, Väinämöinen",""),
    ("soitti päivän, soitti toisen.","soitti päivän, soitti toisen.","soittaa, päivä, toinen","to play, day, second/another",""),
    ("Ei ollut sitä urosta","Ei ollut sitä urosta","ei, olla, se, uros","not, to be, that, hero/man",""),
    ("eikä miestä urheata,","eikä miestä urheata,","eikä, mies, urheata","nor, man, brave/bold",""),
    ("ollut ei miestä eikä naista","ei ollut miestä eikä naista","ei, olla, mies, nainen","not, to be, man, woman",""),
    ("eikä kassan kantajata,","eikä kassan kantajaa,","eikä, kassa, kantaja","nor, hair-braid/lap, bearer/carrier",""),
    ("kellen ei itkuksi käynyt,","jolle ei itkuksi käynyt,","jolle, ei, itku, käydä","for whom, not, weeping, to go",""),
    ("kenen syäntä ei sulannut.","kenen sydäntä ei sulanut.","kenen, sydän, sulaa","whose, heart, to melt",""),
    ("Itki nuoret, itki vanhat,","Itki nuoret, itki vanhat,","itkeä, nuori, vanha","to weep, young, old",""),
    ("itki miehet naimattomat,","itki miehet naimattomat,","itkeä, mies, naimaton","to weep, man, unmarried",""),
    ("itki nainehet urohot,","itki nainehet urohot,","itkeä, nainut, uros","to weep, married, hero/man",""),
    ("itki pojat puol'-ikäiset,","itki pojat puoli-ikäiset,","itkeä, poika, puoli-ikäinen","to weep, boy, middle-aged",""),
    ("sekä pojat jotta neiet,","sekä pojat että neidot,","sekä, poika, neito","and/both, boy, maiden",""),
    ("jotta pienet piikasetki,","että pienet piiatkin,","että, pieni, piika","and/that, small, maidservant/girl",""),
    ("kun oli ääni kummanlainen,","kun oli ääni kummanlainen,","kun, olla, ääni, kummallinen","when, to be, sound, strange/wondrous",""),
    ("ukon soitanto suloinen.","ukon soitanto suloinen.","ukko, soitanto, suloinen","old man, playing/music, sweet/lovely",""),
    ("Itsensäki Väinämöisen","Itsekkin Väinämöisen","itse, Väinämöinen","himself, Väinämöinen",""),
    ("kyynel vieri kyykähteli.","kyynel vieri kyykähteli.","kyynel, vieristä, kyykähtää","tear, to roll, to trickle down","Väinämöinen weeps at his own playing — the trickster-shaman is moved by his own creation; the creator unmade by his art."),
    ("Tippui tilkat silmistänsä,","Tippui tilkat silmistään,","tippua, tilkka, silmä","to drip, drop, eye",""),
    ("vierivät vesipisarat,","vierivät vesipisarat,","vieristä, vesipisara","to roll, water drop",""),
    ("karkeammat karpaloita,","karkeammat karpaloita,","karkea, karpalo","coarser/larger, cranberry",""),
    ("herkeämmät hernehiä,","herkeämmät herneitä,","herkäinen, herne","rounder/smoother, pea",""),
    ("pyöreämmät pyyn munia,","pyöreämmät pyyn munia,","pyöreä, pyy, muna","rounder, hazel grouse, egg",""),
    ("päreämmät päitä pääskyn.","päreämmät pääskysen päitä.","päreä, pääskynen, pää","broader/flatter, swallow, head",""),
    ("Ve'et vieri silmästänsä,","Vedet vierivät silmästään,","vesi, vieristä, silmä","water/tears, to roll, eye",""),
    ("toiset toisesta noruvi.","toiset toisesta norui.","toinen, norua","one after another, to trickle",""),
    ("Putosivat poskipäille,","Putosivat poskipäille,","pudota, poski","to fall, cheek",""),
    ("kaunihille kasvoillensa,","kauniille kasvoilleen,","kaunis, kasvot","beautiful, face",""),
    ("kaunihilta kasvoiltansa","kauniilta kasvoiltaan","kaunis, kasvot","beautiful, face",""),
    ("leve'ille leuoillensa,","leville leuvuillaan,","leveä, leuka","wide, jaw/chin",""),
    ("leve'iltä leuoiltansa","leviltä leuvuiltaan","leveä, leuka","wide, jaw/chin",""),
    ("rehe'ille rinnoillensa,","reheille rinnoilleen,","reheä, rinta","broad/fine, chest/breast",""),
    ("rehe'iltä rinnoiltansa","reheiltä rinnoiltaan","reheä, rinta","broad/fine, chest/breast",""),
    ("päteville polvillensa,","pätevillä polvillaan,","pätevä, polvi","capable/sturdy, knee",""),
    ("päteviltä polviltansa","pätevilä polvilta","pätevä, polvi","capable/sturdy, knee",""),
    ("jalkapöyille jaloille,","jalkapöydille jaloille,","jalkapöytä, jalka","instep, foot/leg",""),
    ("jalkapöyiltä jaloilta","jalkapöydiltä jaloilta","jalkapöytä, jalka","instep, foot/leg",""),
    ("maahan alle jalkojensa","maahan alle jalkojensa","maa, alle, jalka","ground, under, foot",""),
    ("läpi viien villavaipan,","läpi viiden villavaipan,","läpi, viisi, villa, vaippa","through, five, wool, cloak/mantle",""),
    ("kautta kuuen kultavyönsä,","kautta kuuden kultavyönsä,","kautta, kuusi, kulta, vyö","through, six, gold, belt",""),
    ("seitsemän sinihamosen,","seitsemän sinisen hameen,","seitsemän, sininen, hame","seven, blue, skirt/dress",""),
    ("sarkakauhtanan kaheksan.","sarkakauhtanan kahdeksan.","sarka, kauhtana, kahdeksan","coarse cloth, coat, eight","The tears fall through seven garments — hyperbolic, almost comic excess; the trickster-shaman's emotions are as outsized as his magic."),
    ("Vierivät vesipisarat","Vierivät vesipisarat","vieristä, vesipisara","to roll, water drop",""),
    ("luota vanhan Väinämöisen","luota vanhan Väinämöisen","luota, vanha, Väinämöinen","from beside, old, Väinämöinen",""),
    ("rannalle meren sinisen,","rannalle meren sinisen,","ranta, meri, sininen","shore, sea, blue",""),
    ("rannalta meren sinisen","rannalta meren sinisen","ranta, meri, sininen","shore, sea, blue",""),
    ("alle selvien vesien,","alle selvien vesien,","alle, selvä, vesi","under, clear/open, water",""),
    ("päälle mustien murien.","päälle mustien murien.","päälle, musta, murea","on top of, black, dark sand/gravel",""),
    ("Siitä vanha Väinämöinen","Siitä vanha Väinämöinen","siitä, vanha, Väinämöinen","then, old, Väinämöinen",""),
    ("itse tuon sanoiksi virkki:","itse tuon sanoiksi sanoi:","itse, tuo, sana, virkkoa","himself, that, word, to say",""),
    ('"Onko tässä nuorisossa,','"Onko tässä nuorisossa,',"olla, tässä, nuoriso","to be, here/in this, youth",""),
    ("nuorisossa kaunoisessa,","nuorisossa kauniissa,","nuoriso, kaunis","youth, beautiful",""),
    ("tässä suuressa su'ussa,","tässä suuressa suvussa,","tässä, suuri, suku","in this, great, kin/tribe",""),
    ("isossa isän alassa","isossa isän alassa","iso, isä, ala","large, father, domain/realm",""),
    ("kyyneleni poimijata","kyyneleni poimijaa","kyynel, poimija","tear, gatherer/picker","Väinämöinen asks who will retrieve his tears from the sea — the trickster uses others to complete what he cannot do alone."),
    ('alta selvien vesien?"','alta selvien vesien?"',"alta, selvä, vesi","from under, clear, water",""),
    ("Nuoret tuossa noin sanovi","Nuoret tuossa noin sanoivat","nuori, tuossa, noin, sanoa","young, there/then, thus, to say",""),
    ("sekä vanhat vastoavi:","sekä vanhat vastasivat:","sekä, vanha, vastata","and/both, old, to answer",""),
    ('"Ei ole tässä nuorisossa,','"Ei ole tässä nuorisossa,',"ei, olla, tässä, nuoriso","not, to be, here, youth",""),
    ("nuorisossa kaunoisessa,","nuorisossa kauniissa,","nuoriso, kaunis","youth, beautiful",""),
    ("tässä suuressa su'ussa,","tässä suuressa suvussa,","tässä, suuri, suku","in this, great, kin/tribe",""),
    ("isossa isän alassa","isossa isän alassa","iso, isä, ala","large, father, domain/realm",""),
    ("kyynelesi poimijata","kyynelesi poimijaa","kyynel, poimija","tear, gatherer/picker",""),
    ('alta selvien vesien."','alta selvien vesien."',"alta, selvä, vesi","from under, clear, water",""),
    ("Sanoi vanha Väinämöinen,","Sanoi vanha Väinämöinen,","sanoa, vanha, Väinämöinen","to say, old, Väinämöinen",""),
    ("itse virkki, noin nimesi:","itse sanoi, noin nimesi:","itse, virkkoa, noin, nimetä","himself, to say, thus, to name",""),
    ('"Kenpä toisi kyyneleni,','"Kuka toisi kyyneleni,',"kuka, tuoda, kyynel","who, to bring, tear",""),
    ("poimisi vesipisarat","poimisi vesipisarat","poimia, vesipisara","to pick/gather, water drop",""),
    ("alta selvien vesien,","alta selvien vesien,","alta, selvä, vesi","from under, clear, water",""),
    ('saisi multa sulkaturkin."','saisi minulta sulkaturkin."',"saada, minulta, sulkaturkki","to get, from me, feather coat","Väinämöinen offers a feather coat as reward — trickster negotiates and bargains rather than commanding."),
    ("Tuli korppi koikotellen.","Tuli korppi koikotellen.","tulla, korppi, koikotella","to come, raven, to strut/hop",""),
    ("Sanoi vanha Väinämöinen:","Sanoi vanha Väinämöinen:","sanoa, vanha, Väinämöinen","to say, old, Väinämöinen",""),
    ('"Käyös, korppi, kyyneleni','"Käy, korppi, kyyneleni',"käydä, korppi, kyynel","to go, raven, tear","Väinämöinen tries the raven first — but the raven, often a trickster bird itself, fails at the task."),
    ("alta selvien vesien!","alta selvien vesien!","alta, selvä, vesi","from under, clear, water",""),
    ('Annan sulle sulkaturkin."','Annan sinulle sulkaturkin."',"antaa, sinulle, sulkaturkki","to give, to you, feather coat",""),
    ("Eipä korppi saanutkana.","Eipä korppi saanutkaan.","ei, korppi, saada","not, raven, to get/manage",""),
    ("Kuuli tuon sininen sotka,","Kuuli tuon sininen sotka,","kuulla, tuo, sininen, sotka","to hear, that, blue, eider duck",""),
    ("niin tuli sininen sotka.","niin tuli sininen sotka.","niin, tulla, sininen, sotka","so/then, to come, blue, eider duck",""),
    ("Sanoi vanha Väinämöinen:","Sanoi vanha Väinämöinen:","sanoa, vanha, Väinämöinen","to say, old, Väinämöinen",""),
    ('"Use\'in, sininen sotka,','"Usein, sininen sotka,',"usein, sininen, sotka","often, blue, eider duck",""),
    ("suullasi sukelteleihet,","suullasi sukelteleihet,","suu, sukeltaa","mouth, to dive",""),
    ("ve'essä vilotteleihet:","vedessä vilotteleihet:","vesi, vilotella","water, to plunge/bathe",""),
    ("käypä, poimi kyyneleni","käy, poimi kyyneleni","käydä, poimia, kyynel","to go, to pick/gather, tear",""),
    ("alta selvien vesien!","alta selvien vesien!","alta, selvä, vesi","from under, clear, water",""),
    ("Saat sinä parahan palkan:","Saat sinä parhaan palkan:","saada, sinä, paras, palkka","to get, you, best, reward",""),
    ('annan sulle sulkaturkin."','annan sinulle sulkaturkin."',"antaa, sinulle, sulkaturkki","to give, to you, feather coat",""),
    ("Kävi sotka poimimahan","Kävi sotka poimimaan","käydä, sotka, poimia","to go, eider duck, to pick/gather",""),
    ("Väinämöisen kyyneleitä","Väinämöisen kyyneleitä","Väinämöinen, kyynel","Väinämöinen, tear",""),
    ("alta selvien vesien,","alta selvien vesien,","alta, selvä, vesi","from under, clear, water",""),
    ("päältä mustien murien.","päältä mustien murien.","päältä, musta, murea","from on top of, black, dark gravel",""),
    ("Poimi kyynelet merestä,","Poimi kyynelet merestä,","poimia, kyynel, meri","to gather, tear, sea",""),
    ("kantoi Väinölle kätehen:","kantoi Väinölle käteen:","kantaa, Väinö, käsi","to carry, Väinö (Väinämöinen), hand",""),
    ("jo oli muiksi muuttunehet,","jo olivat muiksi muuttuneet,","jo, olla, muu, muuttua","already, to be, other/different, to change","The tears have transformed into pearls — transformation is the essence of trickster creation; grief becomes treasure."),
    ("kasvanehet kaunoisiksi,","kasvanehet kaunoisiksi,","kasvaa, kaunis","grown, beautiful",""),
    ("helmiksi heristynehet,","helmiksi heristynehet,","helmi, herätä","pearls, to arise/emerge",""),
    ("simpsukoiksi siintynehet,","simpukoiksi siintynehet,","simpukka, siintyä","clam/mussel, to become/turn into",""),
    ("kuningasten kunnioiksi,","kuningasten kunnioiksi,","kuningas, kunnia","king, honour/glory",""),
    ("valtojen iki-iloiksi.","valtojen iki-iloiksi.","valta, ikuinen, ilo","power/realm, eternal, joy","Väinämöinen's tears become eternal treasures of kings — the trickster's sorrow transmuted into the world's beauty."),
]

thin = Side(style="thin", color="CCCCCC")
border = Border(left=thin, right=thin, top=thin, bottom=thin)
trickster_fill = PatternFill("solid", start_color="FFF3CD")
alt_fill = PatternFill("solid", start_color="F8F9FA")

for row_idx, (a, b, c, d, e) in enumerate(verses, start=2):
    ws.cell(row=row_idx, column=1, value=a)
    ws.cell(row=row_idx, column=2, value=b)
    ws.cell(row=row_idx, column=3, value=c)
    ws.cell(row=row_idx, column=4, value=d)
    ws.cell(row=row_idx, column=5, value=e)

for row in ws.iter_rows(min_row=2, max_row=ws.max_row, min_col=1, max_col=5):
    row_num = row[0].row
    has_trickster = bool(row[4].value)
    for cell in row:
        cell.font = Font(name="Arial", size=10)
        cell.alignment = Alignment(wrap_text=True, vertical="top")
        cell.border = border
        if has_trickster:
            cell.fill = trickster_fill
        elif row_num % 2 == 0:
            cell.fill = alt_fill

ws.column_dimensions["A"].width = 35
ws.column_dimensions["B"].width = 35
ws.column_dimensions["C"].width = 30
ws.column_dimensions["D"].width = 35
ws.column_dimensions["E"].width = 55

ws.row_dimensions[1].height = 35
for row_num in range(2, ws.max_row + 1):
    ws.row_dimensions[row_num].height = 30

ws.freeze_panes = "A2"

legend_row = ws.max_row + 2
cell = ws.cell(row=legend_row, column=1, value="Väri/Color: Keltainen / Yellow = säe liittyy trickster-teemaan / verse connected to trickster theme")
cell.font = Font(name="Arial", size=9, italic=True, color="7B6E00")
cell.fill = PatternFill("solid", start_color="FFF3CD")

wb.save("kalevala_runo41.xlsx")
print(f"Done! {ws.max_row - 2} verses written.")
