from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

wb = Workbook()
ws = wb.active
ws.title = "Runo XXIII Part 3"

headers = ["A: Alkuperäinen säe", "B: Nykysuomi", "C: Perusmuodot", "D: Käännökset (EN)", "E: Trickster-huomioita"]
header_fill = PatternFill("solid", start_color="2E4057")
header_font = Font(bold=True, color="FFFFFF", name="Arial", size=11)
for col, h in enumerate(headers, 1):
    cell = ws.cell(row=1, column=col, value=h)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

verses = [
    ("Olipa akka lattialla,", "Olipa akka lattialla,", "olla, akka, lattia", "to be, old woman, floor", ""),
    ("akka vanha, vaippa päällä,", "akka vanha, vaippa päällä,", "akka, vanha, vaippa, päälle", "old woman, old, cloak/wrap, over", ""),
    ("kylän kynnysten kävijä,", "kylän kynnysten kävijä,", "kylä, kynnys, käyjä", "village's, thresholds, walker", ""),
    ("mieron teien tietelijä.", "mieron teiden tietelijä.", "miero, tie, tietelijä", "wanderer's, roads, knower", ""),
    ("Hänpä tuon sanoiksi virkki,", "Hänpä tuon sanoiksi sanoi,", "hän, tuo, sana, virkkoa", "she, those, words, to say", ""),
    ("itse lausui ja lateli:", "itse lausui ja lateli:", "itse, lausua, latella", "herself, to utter, to recite/spread out", ""),
    ("\"Kukko lauloi kullallensa,", "\"Kukko lauloi kullallensa,", "kukko, laulaa, kulta", "rooster, to sing/crow, for his golden one", ""),
    ("kanan lapsi kaunollensa,", "kanan lapsi kaunollensa,", "kana, lapsi, kaunoinen", "hen's, chick, for his beautiful one", ""),
    ("varis lauloi vaahtokuulla,", "varis lauloi vaahtoisen kuun aikaan,", "varis, laulaa, vaahtoinen, kuu", "crow, to sing, foamy/whitish, moon", ""),
    ("kevätkuulla keikutteli.", "kevätkuulla keikutteli.", "kevät, kuu, keikuttaa", "spring's, moon, to rock/sway", ""),
    ("Minun lauloa pitäisi,", "Minun laulaa pitäisi,", "minä, laulaa, pitää", "my, to sing, should", ""),
    ("heiän olla laulamatta:", "heidän olla laulamatta:", "he, olla, laulamatta", "their, to be, without singing", ""),
    ("heill' on kultansa kotona,", "heillä on kultansa kotona,", "heidän, kulta, koti", "their, golden one, home", ""),
    ("aina luona armahansa;", "aina luona armaansa;", "aina, luona, armas", "always, near, dear one", ""),
    ("minä kullatoin, ko'itoin,", "minä kullatoin, kodaton,", "minä, kultaton, kodaton", "I, without golden one, homeless", ""),
    ("ajan kaiken armahatoin.", "ajan kaiken armahatoin.", "aika, kaikki, armahatoin", "time, all, without a dear one", ""),
    ("\"Kuules, sisko, kuin sanelen!", "\"Kuules, sisko, kun sanelen!", "kuulla, sisko, kun, sanella", "to hear, sister, when, to recite/tell", ""),
    ("Kun menetki miehelähän,", "Kun menetkin miehelle,", "kun, mennä, mies", "when, to go, man's", ""),
    ("elä noua miehen mieltä,", "älä noukkaa miehen mieltä,", "älä, noukita, mies, mieli", "don't, to pick at, man's, mind/will", ""),
    ("kuin minä poloinen nouin", "kuin minä poloinen noukin", "kuin, minä, poloinen, noukita", "like, I, wretched, picked at", ""),
    ("miehen mieltä, kiurun kieltä,", "miehen mieltä, kiurun kieltä,", "mies, mieli, kiuru, kieli", "man's, mind/will, skylark's, tongue", ""),
    ("suuren sulhoni syäntä!", "suuren sulhoni sydäntä!", "suuri, sulho, sydän", "great, my groom's/suitor's, heart", "The old vagrant woman's counter-song — 'the rooster sings for his golden one, but I have no golden one, I am homeless; don't try to please your man as I did, picking at his mind like a skylark's tongue' — is the trickster-crone's autobiography of failure used as negative example. Her life is the warning."),
    ("\"Olin kukka ollessani,", "\"Olin kukka ollessani,", "olla, kukka, olla", "to be, flower, while being", ""),
    ("kasvaessani kanerva,", "kasvaessani kanerva,", "kasvaa, kanerva", "while growing, heather", ""),
    ("vesa nuori noustessani,", "vesa nuori noustessani,", "vesa, nuori, nousta", "sapling, young, while rising", ""),
    ("ympynen yletessäni,", "ympynen yletessäni,", "ympynen, yletä", "round/full one, while rising", ""),
    ("mesimarja mainittaissa,", "mesimarja mainittaessa,", "mesimarja, mainita", "honey-berry/cloudberry, while being mentioned", ""),
    ("kulta kuiskuteltaessa,", "kulta kuiskuteltaessa,", "kulta, kuiskutella", "golden one, while being whispered about", ""),
    ("tavi taattoni pihoilla,", "tavi isäni pihoilla,", "tavi, isä, piha", "teal, father's, yards", ""),
    ("lakla maammon lattioilla,", "lakla äitini lattioilla,", "lakla, äiti, lattia", "paddle/spatula-bird, mother's, floors", ""),
    ("vesilintu veikon luona,", "vesilintu veikon luona,", "vesilintu, veikko, luona", "water-bird, brother's, near", ""),
    ("sirkkunen sisaren luona.", "sirkkunen sisaren luona.", "sirkkunen, sisar, luona", "little cricket, sister's, near", ""),
    ("Kävin kukkana kujilla,", "Kävin kukkana kujilla,", "käydä, kukka, kuja", "to go, flower, lanes", ""),
    ("vaapukkana vainiolla,", "vaapukkana vainiolla,", "vaapukka, vainio", "raspberry, open field", ""),
    ("hersuin hiekkarantasilla,", "hersuin hiekkarannoilla,", "hersuilla, hiekkaranta", "jingling/trilling, sandy shores", ""),
    ("keikuin kukkakunnahilla;", "keikuin kukkakunnahilla;", "keikkua, kukka, kunnas", "to sway/rock, flower, hill", ""),
    ("laulelin jokaisen lakson,", "laulelin jokaisen laakson,", "laulella, jokainen, laakso", "to sing, every, valley", ""),
    ("joka kummun kukkuelin,", "joka kummulle kukkuelin,", "joka, kumpu, kukua", "every, mound, to cuckoo-call", ""),
    ("lehot leikkiä pitelin,", "lehot leikissä pidin,", "lehto, leikki, pitää", "groves, play, to keep/hold", ""),
    ("ahot ainoista iloa.", "ahot ainoistaan iloa.", "aho, ainoa, ilo", "clearings, only, joy", ""),
    ("\"Suu veti revon ritahan,", "\"Suu veti repon ritaan,", "suu, vetää, repo, rita", "mouth, to pull, fox's, trap/snare", ""),
    ("kieli kärpän lautasehen,", "kieli kärpän lautaseen,", "kieli, kärppä, lauta", "tongue, stoat's, plank/board", ""),
    ("mieli neien miehelähän,", "mieli neidon miehelle,", "mieli, neito, mies", "mind/will, maiden's, man's", ""),
    ("tapa toisehen talohon.", "tapa toiseen taloon.", "tapa, toinen, talo", "custom/habit, other, house", ""),
    ("Niinpä neiti luotunaki,", "Niinpä neiti luotunakin,", "niin, neito, luotu", "so, maiden, created", ""),
    ("tytär tuuiteltunaki", "tytär tuuditeltunakin", "tytär, tuudittaa", "daughter, rocked/lulled", ""),
    ("- miniäksi miehelähän,", "- miniäksi miehelle,", "miniä, mies", "daughter-in-law, man's", ""),
    ("orjaksi anoppelahan.", "orjaksi anopin.", "orja, anoppi", "slave, mother-in-law's", ""),
    ("\"Jou'uin, marja, muille maille,", "\"Jouduin, marja, muille maille,", "joutua, marja, muu, maa", "to end up, berry, other, lands", ""),
    ("tuomi, toisille vesille,", "tuomi, toisille vesille,", "tuomi, toinen, vesi", "bird-cherry, other, waters", ""),
    ("jou'uin, puola, purtavaksi,", "jouduin, puola, purtavaksi,", "joutua, puola, purra", "to end up, lingonberry, to be bitten/chewed", ""),
    ("mansikka, manattavaksi.", "mansikka, manattavaksi.", "mansikka, manata", "strawberry, to be cursed/sworn at", ""),
    ("Joka puu puri minua,", "Joka puu puri minua,", "joka, puu, purra", "every, tree, to bite", ""),
    ("joka leppä leikkaeli,", "joka leppä leikkeli,", "joka, leppä, leikata", "every, alder, to cut", ""),
    ("joka koivu koiskaeli,", "joka koivu koiski,", "joka, koivu, koiskia", "every, birch, to knock/strike", ""),
    ("joka haapa haukkaeli.", "joka haapa haukkeli.", "joka, haapa, haukata", "every, aspen, to bite/grab at", ""),
    ("\"Naitihin ma miehelähän,", "\"Naitihin minä miehelle,", "naida, minä, mies", "to marry, I, man's", ""),
    ("vietihin anoppelahan.", "vietihin anopille.", "viedä, anoppi", "to be taken, mother-in-law's", ""),
    ("Sanottihin siell' olevan,", "Sanottihin siellä olevan,", "sanoa, siellä, olla", "to say, there, to be", ""),
    ("neittä sinne naitaessa,", "neittä sinne naittaessa,", "naittaa, neito, sinne", "while marrying maiden, there", ""),
    ("kuusi kuusista tupoa,", "kuusi kuusisia tupaa,", "kuusi, kuusinen, tupa", "six, spruce-wood, cottages/halls", ""),
    ("kaksin kerroin kammaria,", "kaksin kerroin kammaria,", "kaksi, kerros, kammari", "two, floors, rooms/chambers", ""),
    ("ahovieret aittamaina,", "ahovieret aittamaina,", "aho, vieri, aitta", "clearing-sides, storehouses", ""),
    ("kujavieret kukkamaina,", "kujavieret kukkamaina,", "kuja, vieri, kukka", "lane-sides, flower-lands", ""),
    ("ojavieret ohramaina,", "ojavieret ohramaina,", "oja, vieri, ohramaa", "ditch-sides, barley-land", ""),
    ("kangasvieret kauramaina,", "kangasvieret kauramaina,", "kangas, vieri, kauramaa", "heath-sides, oat-land", ""),
    ("purnut puitua eloa,", "purnut puitua eloa,", "purnu, puitu, elo", "barrels/tubs, threshed, grain/livelihood", ""),
    ("toiset purnut puitavia,", "toiset purnut puitavia,", "toinen, purnu, puitava", "other, barrels, to be threshed", ""),
    ("sata saatuja rahoja,", "sata saatuja rahoja,", "sata, saada, raha", "hundred, gotten, money", ""),
    ("sata toinen saatavia.", "sata toinen saatavia.", "sata, toinen, saatava", "hundred, second, to be gotten", ""),
    ("\"Sainpa, tuhma, tulleheksi,", "\"Sainpa, tuhma, tulleeksi,", "saada, tuhma, tulla", "to get, stupid/dull, to have come", "The vagrant woman's account of what she was promised — six spruce-houses, double chambers, clearing-side storehouses, a hundred moneys — and what she found: a hall on six poles, clearings full of worthlessness, groves full of unaffection, lanes of her worries, a hundred words instead of money — is the trickster-crone's defining story of deception."),
    ("kälkö, kättä lyöneheksi:", "kälkö, kättä lyöneksi:", "kälkö, käsi, lyödä", "loud-noise/fool, hand, to have struck (made a deal)", ""),
    ("tupa oli kuuella tuella,", "tupa oli kuudella tuella,", "tupa, olla, kuusi, tuki", "cottage/hall, to be, six, support/post", ""),
    ("seitsemällä seipähällä,", "seitsemällä seipäällä,", "seitsemän, seiväs", "seven, poles/stakes", ""),
    ("ahot täynnä armotuutta,", "ahot täynnä armotuutta,", "aho, täynnä, armoton", "clearings, full of, without grace/loveless", ""),
    ("lehot täynnä lemmetyyttä,", "lehot täynnä lemmetöntä,", "lehto, täynnä, lemmitön", "groves, full of, without love/affection", ""),
    ("kujat, kurjan, huoliani,", "kujat, kurjan, huoliani,", "kuja, kurja, huoli", "lanes, wretched, my worries", ""),
    ("metsät mieliä pahoja,", "metsät mieliä pahoja,", "metsä, mieli, paha", "forests, moods/spirits, bad", ""),
    ("purnut puitua vihoa,", "purnut puitua vihaa,", "purnu, puitu, viha", "barrels, threshed, anger/hate", ""),
    ("toiset purnut puimatointa,", "toiset purnut puimatonta,", "toinen, purnu, puimaton", "other, barrels, unthreshed/empty", ""),
    ("sata saatuja sanoja,", "sata saatuja sanoja,", "sata, saada, sana", "hundred, gotten, words", ""),
    ("sata toinen saatavia.", "sata toinen saatavia.", "sata, toinen, saatava", "hundred, second, to be gotten", ""),
    ("\"En mä tuostana totellut,", "\"En minä tuostakaan totellut,", "ei, minä, tuosta, totella", "not, I, from that, to obey", ""),
    ("ko'in kuuluna asua.", "koitin kuuluna asua.", "koittaa, kuulu, asua", "to try, renowned/proper, to live/dwell", ""),
    ("Tuolla toivoin kunniata,", "Tuolla toivoin kunniaa,", "tuolla, toivoa, kunnia", "there, to hope/wish, honour", ""),
    ("tuolla lempeä tavoitin,", "tuolla lempeä tavoitin,", "tuolla, lempi, tavoittaa", "there, love/affection, to reach/get", ""),
    ("tulen tuomalla tupahan,", "tulen tuomalla tupaan,", "tuli, tuoda, tupa", "fire, by bringing, cottage/hall", ""),
    ("pään päretten poimennalla", "pään päretten poimennalla", "pää, päre, poimia", "head, chip-torch, by picking up", ""),
    ("- pieksin otsani ovehen,", "- pieksin otsani oveen,", "piestä, otsa, ovi", "to beat, forehead, door", ""),
    ("pääni pihtipuolisehen:", "pääni pihtipuoliseen:", "pää, pihtipuoli", "head, door-post", ""),
    ("oven suuss' on ouot silmät,", "oven suussa oikeat silmät,", "ovi, suu, outo, silmä", "door's, opening, strange, eyes", ""),
    ("kaihat silmät karsinassa,", "kaihat silmät karsinassa,", "kaiha, silmä, karsina", "squinting, eyes, stall/pen", ""),
    ("kierot keskilattialla,", "kierot keskilattialla,", "kiero, keski, lattia", "crooked, middle, floor", ""),
    ("perässä perivihaiset;", "perässä perinpohjaisen vihaiset;", "perässä, perinpohjainen, vihainen", "behind, thorough, angry", ""),
    ("tuli suusta tuikahuvi,", "tuli suusta tuikahtui,", "tuli, suu, tuikahtaa", "fire, mouth, to flash/spark", ""),
    ("kekälehet kielen alta,", "kekäleet kielen alta,", "kekäle, kieli, alta", "embers, tongue, from under", ""),
    ("ilkeän isännän suusta,", "ilkeän isännän suusta,", "ilkeä, isäntä, suu", "evil/ugly, master's, mouth", ""),
    ("alta kielen armottoman.", "armottoman kielen alta.", "armoton, kieli, alta", "merciless, tongue, from under", ""),
    ("\"En mä tuostana totellut,", "\"En minä tuostakaan totellut,", "ei, minä, tuosta, totella", "not, I, from that, to obey", ""),
    ("ko'in kuitenkin eleä,", "koitin kuitenkin elää,", "koittaa, kuitenkin, elää", "to try, however, to live", ""),
    ("olla aina alla armon", "olla aina alla armon", "olla, aina, alla, armo", "to be, always, under, grace/mercy", ""),
    ("sekä nöyrä neuvottava;", "sekä nöyrä neuvottava;", "sekä, nöyrä, neuvottava", "and, humble, to be advised", ""),
    ("hyppäsin jänön jaloilla,", "hyppäsin jänöksen jaloilla,", "hypätä, jänis, jalka", "to jump, hare's, feet", ""),
    ("kävin kärpän kämmenillä,", "kävin näätäsen kämmenihin,", "käydä, näätä, kämmen", "to go, marten's, palms", ""),
    ("panin turkan myöhän maata,", "panin turkan myöhään maata,", "panna, turkki, myöhään, maata", "to put, fur coat, late, to lie/sleep", ""),
    ("nousin vaivaisen varahin.", "nousin vaivaisena varhain.", "nousta, vaivainen, varhainen", "to rise, wretched, early", ""),
    ("Saanut en, kurja, kunniata,", "En saanut, kurja, kunniaa,", "ei, saada, kurja, kunnia", "not, to get, wretched, honour", ""),
    ("leino, lempeä tavannut,", "leino, lempeä tavannut,", "leino, lempi, tavata", "poor wretch, love/affection, to find", ""),
    ("vaikka vuoret vierettäisin,", "vaikka vuoret vierettäisin,", "vaikka, vuori, vierittää", "even if, mountains, to roll", ""),
    ("kalliot kaha panisin.", "kalliot kahaksi panisin.", "kallio, kaksi, panna", "cliffs/rocks, in two, to put", ""),
    ("\"Suotta survoin suuret jauhot,", "\"Turhaan survoin suuret jauhot,", "turhaan, survoa, suuri, jauho", "in vain, to pound, great, flours", ""),
    ("kiusan karkeat karistin", "kiusan karkeat karistin", "kiusa, karkea, karistaa", "for torment, coarse, to shake off", ""),
    ("syöä ankaran anopin,", "syödä ankaran anopin,", "syödä, ankara, anoppi", "to eat, strict/harsh, mother-in-law's", ""),
    ("tulikulkun kuiskaella", "tulikulkun kuiskaisemiseksi", "tulikulkku, kuiskailla", "fire-throat's, for whispering", ""),
    ("päässä pitkän pintapöyän", "pään päässä pitkän pintapöydän", "pää, pitkä, pintapöytä", "at the head, long, top-table", ""),
    ("kultalaiasta kupista.", "kultareunaisen kupin.", "kultainen, reuna, kuppi", "golden-edged, cup", ""),
    ("Itse söin, miniä raukka,", "Itse söin, miniä raukka,", "itse, syödä, miniä, raukka", "myself, to eat, daughter-in-law, poor wretch", ""),
    ("apoin jauhoja kiveltä,", "appeni jauhoja kiveltä,", "appi, jauho, kivi", "father-in-law's, flours, from stone", ""),
    ("liesipankko pöytänäni,", "liesipankko pöytänäni,", "liesi, pankko, pöytä", "hearth-shelf, table", ""),
    ("kapusta lusikkanani.", "kapusta lusikkanani.", "kapusta, lusikka", "ladle, as my spoon", ""),
    ("\"Use'in minä utuinen", "\"Usein minä utuinen", "usein, minä, utuinen", "often, I, misty/poor", ""),
    ("miniänä miehelässä", "miniänä miehellä", "miniä, mies", "daughter-in-law, man's", ""),
    ("kannoin suolta sammalia,", "kannoin suolta sammalia,", "kantaa, suo, sammal", "to carry, swamp, mosses", ""),
    ("noita leivoin leiväkseni,", "noita leivoin leiväkseni,", "tuo, leipoa, leipä", "those, to bake, as my bread", ""),
    ("vettä kaivosta kapalla,", "vettä kaivosta kapalla,", "vesi, kaivo, kappa", "water, well, with a measure/scoop", ""),
    ("tuota ryypin ryypykseni.", "tuota ryypin ryypykseni.", "tuo, ryypätä, ryypy", "that, to sip, as my sip/drink", ""),
    ("Sini söin kaloja, kalki,", "Siinä söin kaloja, kalki,", "siinä, syödä, kala, kalki", "there, to eat, fish, as a wretch", ""),
    ("sini, koito, kuorehia,", "siinä, koito, kuoreita,", "siinä, koito, kuore", "there, wretch, small fish (vendace)", ""),
    ("kuni notkuin nuottapuilla,", "kun notkusin nuottapuilla,", "kun, notkuilla, nuottapuu", "when, to bob/bend, seine-net pole", ""),
    ("keikuin keskellä venettä;", "keikuin keskellä venettä;", "keikkua, keski, vene", "to rock/sway, middle, boat", ""),
    ("en saanut sitä kaloa", "en saanut sitä kaloa", "ei, saada, se, kala", "not, to get, that, fish", ""),
    ("anoppini antamasta,", "anoppini antamasta,", "anoppi, antaa", "mother-in-law's, giving", ""),
    ("joka päiväksi päteisi,", "joka päivä päteisi,", "joka, päivä, päteä", "every, day, to be sufficient", ""),
    ("kerraksensa kelpoaisi.", "kerrakseen kelpoaisi.", "kerta, kelvata", "for once, to be fit/worthy", ""),
    ("\"Kesät kontuja keräsin,", "\"Kesät kontuja keräsin,", "kesä, konttu, kerätä", "summers, stalks/plants, to gather", ""),
    ("talvet väännin taikon vartta,", "talvet väänsin taikonvartta,", "talvi, vääntää, taiko, varsi", "winters, to twist, magic-beam/handle", ""),
    ("niinkuin muinenki kasakka", "niinkuin muinenkin kasakka", "niinkuin, muinen, kasakka", "like, former/old, cossack/worker", ""),
    ("eli orja, palkkalainen.", "eli orja, palkkalainen.", "eli, orja, palkkainen", "or, slave, hired servant", ""),
    ("Ainapa anoppelassa", "Aina anopissa", "aina, anoppi", "always, mother-in-law's", ""),
    ("tuo minulle työnnettihin", "tuo minulle työnnettihin", "tuo, minä, työntää", "that, me, to be pushed/given", ""),
    ("riihestä rive'in riusa,", "riihestä riveän riusa,", "riihi, riveä, riusa", "barn, vigorous/rough, yoke", ""),
    ("saunasta jyke'in loukku,", "saunasta jykevän loukku,", "sauna, jykevä, loukku", "sauna, heavy, club/mallet", ""),
    ("rannasta rave'in karttu,", "rannasta ravean kartun,", "ranta, ravea, karttu", "shore, vigorous, washing-club", ""),
    ("suurin taikko tanhuasta.", "suurimman taikon tarhasta.", "suuri, taiko, tarha", "greatest, magic-beam/handle, yard/pen", ""),
    ("Ei uskottu uupuvani,", "Ei uskottu uupuvani,", "ei, uskoa, uupua", "not, to believe, to tire/exhaust", ""),
    ("ei varattu vaipuvani,", "ei varattu vaipuvani,", "ei, varata, vaipua", "not, to prepare, to sink/fall", ""),
    ("vaikka uupuivat urohot,", "vaikka uupuivat urohot,", "vaikka, uupua, uros", "even though, to tire/exhaust, heroes/men", ""),
    ("vaipuivat hevosen varsat.", "vaipuivat hevosen varsat.", "vaipua, hevonen, varsa", "to sink/fall, horse's, foals", ""),
    ("\"Niin minä, piloinen piika,", "\"Niin minä, piloinen piika,", "niin, minä, pilo, piika", "so, I, tricky/difficult, maid", ""),
    ("te'in työtä työn ajalla,", "tein työtä työn ajalla,", "tehdä, työ, työ, aika", "to do, work, work, time", ""),
    ("väännin hartion väellä.", "väänsin hartialla väellä.", "vääntää, hartia, väki", "to twist, shoulder, force/strength", ""),
    ("Annas tulla toisen aian:", "Annas tulla toisen ajan:", "antaa, tulla, toinen, aika", "to let, to come, second/other, time", ""),
    ("jo tulehen tuomittihin,", "jo tuleen tuomittihin,", "jo, tuli, tuomita", "already, fire, to condemn/send", ""),
    ("sen kätehen käskettihin.", "sen käteen käskettihin.", "se, käsi, käskeä", "that, hand, to order", ""),
    ("\"Suotta soimat nostettihin,", "\"Turhaan soimaukset nostettiin,", "turhaan, soimaus, nostaa", "in vain, blame/reproach, to raise", ""),
    ("kiusan kielet kannettihin", "kiusan kielet kannettihin", "kiusa, kieli, kantaa", "torment's, tongues, to carry", ""),
    ("päälle mun hyvän tapani,", "päälle minun hyvän tapani,", "päälle, minä, hyvä, tapa", "over, my, good, custom/manner", ""),
    ("päälle kuulun kunniani;", "päälle kuulun kunniasi;", "päälle, kuulu, kunnia", "over, renowned, honour", ""),
    ("sanat päälleni satoivat,", "sanat päälleni satoivat,", "sana, päälle, sataa", "words, over me, to rain/fall", ""),
    ("puhe'et putoelivat", "puheet putoelivat", "puhe, pudota", "speeches, to fall", ""),
    ("kuin tuimat tulikipunat", "kuin tuimat tulikipunat", "kuin, tuima, tulikipuna", "like, fierce, fire-sparks", ""),
    ("tahi rautaiset rakehet.", "tahi rautaiset rakeet.", "tahi, rautainen, rae", "or, iron, hailstones", ""),
    ("\"En mä tuostana epäillyt,", "\"En minä tuostakaan epäillyt,", "ei, minä, tuosta, epäillä", "not, I, from that, to doubt", ""),
    ("oisin eeskipäin elellyt", "olisin eteenpäin elellyt", "olla, eteenpäin, elellä", "to have, forward, to live along", ""),
    ("akan ankaran apuna,", "naisen ankaran apuna,", "nainen, ankara, apu", "woman's, strict/harsh, helper", ""),
    ("tulikulkun kumppalina;", "tulikulkun kumppanina;", "tulikulkku, kumppani", "fire-throat's, companion", ""),
    ("vaan sepä paha panihe,", "vaan se paha pani,", "vaan, se, paha, panna", "but, that, evil, to put", ""),
    ("sepä suurenti suruni,", "se suurensi suruni,", "se, suurentaa, suru", "that, to enlarge, grief", ""),
    ("kun sulho sueksi muuttui,", "kun sulho sudeksi muuttui,", "kun, sulho, susi, muuttua", "when, groom/suitor, wolf, to change", ""),
    ("kauno karhuksi rupesi,", "kauno karhuksi rupesi,", "kaunoinen, karhu, ruveta", "beautiful one, bear, to become", ""),
    ("kylin söi, selin makasi,", "kyljellään söi, selällään makasi,", "kylki, syödä, selkä, maata", "on his side, to eat, on his back, to lie", ""),
    ("selin työnsä toimitteli.", "selällään työnsä toimitteli.", "selkä, työ, toimittaa", "on his back, work, to perform/do", ""),
    ("\"Tuota itkin itsekseni,", "\"Tuota itkin itsekseni,", "tuo, itkeä, itse", "that, to cry, myself", ""),
    ("ajattelin aitassani.", "ajattelin aitassani.", "ajatella, aitta", "to think, storehouse", ""),
    ("Muistin muita päiviäni,", "Muistin muita päiviäni,", "muistaa, muu, päivä", "to remember, other, days", ""),
    ("entistä elantoani", "entistä elantoani", "entinen, elanto", "former, livelihood/life", ""),
    ("ison pitkillä pihoilla,", "isän pitkillä pihoilla,", "isä, pitkä, piha", "father's, long, yards", ""),
    ("emon kaunon kartanolla.", "äidin kaunon kartanolla.", "äiti, kauno, kartano", "mother's, beautiful, estate/yard", ""),
    ("\"Sain tuosta sanelemahan,", "\"Sain tuosta sanelemaan,", "saada, tuosta, sanella", "to get, from that, to recite/tell", ""),
    ("itse virkin, vierettelin:", "itse virkin, vieritelin:", "itse, virkata, vierittää", "myself, to say, to roll/tell", ""),
    ("'Osasi minun emoni,", "'Osasi minun äitini,", "osata, minä, äiti", "to know how, my, mother", ""),
    ("osasi omenan saa'a,", "osasi omenan saada,", "osata, omena, saada", "to know how, apple, to get", ""),
    ("taisi taimen kasvatella,", "taisi taimen kasvattaa,", "taitaa, taimi, kasvattaa", "to manage, seedling, to raise", ""),
    ("ei osannut istutella:", "ei osannut istuttaa:", "ei, osata, istuttaa", "not, to know how, to plant", ""),
    ("istutti ihanan taimen", "istutti ihanan taimen", "istuttaa, ihana, taimi", "to plant, wonderful, seedling", ""),
    ("ilke'ille istumille,", "ilkeille istumille,", "ilkeä, istuma", "evil/ugly, sitting-places", ""),
    ("pani paikoille pahoille,", "pani paikoille pahoille,", "panna, paikka, paha", "to put, places, bad", ""),
    ("koivun juurille koville,", "koivun juurille koville,", "koivu, juuri, kova", "birch's, roots, hard", ""),
    ("iäksensä itkemähän,", "iäkseen itkemään,", "ikä, itkeä", "for a lifetime, to cry", ""),
    ("kuuksensa kujertamahan.", "kuukseen kujertamaan.", "kuukausi, kujertaa", "for a month, to twitter/lament", ""),
    ("'Oisipa minussa ollut", "'Olisipa minussa ollut", "olla, minä, olla", "to be, in me, to have been", ""),
    ("paikoille paremmillenki,", "paikoille paremmillekin,", "paikka, parempi", "places, better", ""),
    ("pitemmillenki pihoille,", "pidemmillekin pihoille,", "piha, pitkä", "yards, longer", ""),
    ("laajemmille lattioille,", "laajemmille lattioille,", "laaja, lattia", "wider, floors", ""),
    ("paremmanki varren vasta,", "paremmankin varren vasta,", "parempi, varsi, vasta", "better, body's, birch-whisk (match)", ""),
    ("verevämmän miehen verta.", "verevämmän miehen verta.", "verevä, mies, veri", "more ruddy/fresh, man's, blood (equal)", ""),
    ("Puutuin tuohon pulluksehen,", "Puutuin tuohon pallukkaan,", "puuttua, tuo, pallukka", "to fall into, that, big ball/lump", ""),
    ("tartuin tuohon talluksehen:", "tartuin tuohon tallukseen:", "tarttua, tuo, tallus", "to grab, that, oaf/clumsy one", ""),
    ("varikselt' on varren saanut,", "varikselta on varren saanut,", "varis, varsi, saada", "from crow, body, gotten", ""),
    ("korpilta nenän kopannut,", "korpilta nenän kopannut,", "korppi, nenä, kopata", "from raven, nose, to grab/snatch", ""),
    ("suunsa syövältä suelta,", "suunsa syövältä sudelta,", "suu, syövä, susi", "mouth, devouring, wolf", ""),
    ("koko muo'on kontiolta.", "koko muodon kontiolta.", "koko, muoto, kontio", "whole, form/looks, bear", ""),
    ("'Oisinpa mokoman saanut", "'Olisinpa mokomaisen saanut", "olla, moinen, saada", "to have been, such a, gotten", ""),
    ("mäellenki mentyäni:", "mäellekin mentyäni:", "mäki, mennä", "hill, having gone to", ""),
    ("saanut tieltä tervaskannon,", "saanut tieltä tervaskannon,", "saada, tie, tervaskangas", "gotten, road, tarry-stump", ""),
    ("leppäpökkelön lehosta,", "leppäpökkelön lehdosta,", "leppä, pökkele, lehto", "alder, gnarled stump, grove", ""),
    ("pannut turvan turpehesta,", "pannut turvan turpeesta,", "panna, turpa, turve", "to put, face/muzzle, peat/turf", ""),
    ("parran naavoista pahoista,", "parran naavoista pahoista,", "parta, naava, paha", "beard, lichen/beard-moss, bad", ""),
    ("suun kivestä, pään savesta,", "suun kivestä, pään savesta,", "suu, kivi, pää, savi", "mouth, stone, head, clay", ""),
    ("silmät kuumista sysistä,", "silmät kuumista sysistä,", "silmä, kuuma, sysi", "eyes, hot, charcoal", ""),
    ("koivun pahkat korviksensa,", "koivun pahkat korvikseen,", "koivu, pahka, korva", "birch's, burl/knot, as ears", ""),
    ("raian haarukan jaloiksi.'", "raian haarukan jaloiksi.'", "raia, haarukka, jalka", "branch/ragged one, fork, as feet", "The vagrant woman's savage comic reflection: 'I'd have been as well served married to a tarry stump, a peat face, lichen beard, stone mouth, clay head, coal eyes, birch burls for ears, forked branch for feet' — her husband was worse than an inanimate object. The bitterest comedy in the Kalevala."),
    ("\"Senpä lauloin laitoissani,", "\"Senpä lauloin laitoissani,", "se, laulaa, laita", "that, to sing, sides/edges", ""),
    ("huokaelin huolissani.", "huokaelin huolissani.", "huokailla, huoli", "to sigh, worries", ""),
    ("Sattui kauno kuulemahan,", "Sattui kaunoinen kuulemaan,", "sattua, kaunoinen, kuulla", "to happen, beautiful one, to hear", ""),
    ("seinuksella seisomahan!", "seinuksella seisomaan!", "seinä, seistä", "wall, to stand", ""),
    ("Niin kun tuo tulevi tuolta,", "Niin kun tuo tulee tuolta,", "niin, kun, tuo, tulla, tuolta", "so, when, that, to come, from there", ""),
    ("astui aitan portahalle,", "astui aitan portaalle,", "astua, aitta, porras", "to stride, storehouse's, step", ""),
    ("jo ma tuon tulosta tunsin,", "jo minä tuon tulosta tunsin,", "jo, minä, tuo, tulo, tuntea", "already, I, that, coming, to recognise", ""),
    ("astunnasta arvaelin:", "astumistavasta arvaelin:", "astumistapa, arvella", "from the way of stepping, to consider", ""),
    ("tukka tuiski tuulettaki,", "tukka tuiski tuuletakin,", "tukka, tuiskua, tuulla", "hair, to rush/whip, even in wind", ""),
    ("hivus viskoi viimattaki;", "hius viskoi viimastakin;", "hius, viskata, viima", "hair, to fling, even in storm", ""),
    ("ikenet oli irvellänsä,", "ikenet oli irvellänsä,", "ien, irvis", "gums, bared/grinning", ""),
    ("silmät kiljan kaljallansa,", "silmät kiljan kaljallansa,", "silmä, kilju, kalja", "eyes, piercing-cry, beer/ale (bloodshot)", ""),
    ("väätty pihlaja piossa,", "käännetty pihlaja kädessä,", "kääntää, pihlaja, käsi", "twisted, rowan-branch, hand", ""),
    ("käätty karttu kainalossa,", "käännetty karttu kainalossa,", "kääntää, karttu, kainalos", "twisted, washing-bat, armpit", ""),
    ("jolla lyöä lykkeävi,", "jolla lyödä lykkäilee,", "jolla, lyödä, lykätä", "with which, to strike, to push/beat", ""),
    ("kohti päätä kolkkoavi.", "kohti päätä kolkkoaa.", "kohti, pää, kolkata", "toward, head, to hit/bang", ""),
    ("\"Annas siitä illan tulla!", "\"Annas siitä illan tulla!", "antaa, siitä, ilta, tulla", "to let, from that, evening, to come", ""),
    ("Kun meni makoamahan,", "Kun meni makoamaan,", "kun, mennä, maata", "when, to go, to lie/sleep", ""),
    ("otti vitsan vierehensä,", "otti vitsan vierensä,", "ottaa, vitsa, vieri", "to take, switch/whip, beside", ""),
    ("nahkaruoskan naulaltansa,", "nahkaruoskan naulaltansa,", "nahka, ruoska, naula", "leather, whip, from nail", ""),
    ("ei ketänä muuta vasten,", "ei ketään muuta vasten,", "ei, kukaan, muu, vasten", "not, anyone, other, against", ""),
    ("vasten vaivaista minua.", "vasten vaivaista minua.", "vasten, vaivainen, minä", "against, wretched, me", "The vagrant woman's account of her husband taking switch and leather whip to bed — not against anyone else, against wretched me — is the nakedly brutal reality behind the wedding ceremony's beauty. This is what Osmotar's idealised instructions do not mention."),
    ("\"Nousin kylmältä kyleltä,", "\"Nousin kylmältä kyleltä,", "nousta, kylmä, kylki", "to rise, cold, side/flank", ""),
    ("viluiselta vuotehelta.", "viluiselta vuoteelta.", "viluinen, vuode", "cold, bed", ""),
    ("Sulho suorihe jälestä,", "Sulho suoriutui jälestä,", "sulho, suoriutua, jälestä", "groom/suitor, to be done/ready, from behind", ""),
    ("ulos uksesta uhitti!", "ulos ovesta uhitti!", "ulos, ovi, uhmata/kiitää", "out, door, to rush/dash", ""),
    ("Käsi käypi tukkahani,", "Käsi käy tukkahani,", "käsi, käydä, tukka", "hand, to go, hair", ""),
    ("haparoivi hapsihini,", "hapuilee hiuksiini,", "hapuilla, hius", "to grope, hair", ""),
    ("tukat tuulelle jakeli,", "tukat tuulelle jakeli,", "tukka, tuuli, jakaa", "hair, wind, to divide/scatter", ""),
    ("ahavalle anneksivi...", "ahavalle anneksii...", "ahava, antaa", "east wind, to give/hand over", ""),
    ("\"Mikäs neuvoksi minulle,", "\"Mikäs neuvoksi minulle,", "mikä, neuvo, minä", "what, advice, me", ""),
    ("mikä neuvon antajaksi?", "mikä neuvon antajaksi?", "mikä, neuvo, antaja", "what, advice, giver", ""),
    ("Teräksestä kengät teetin,", "Teräksestä kengät teetin,", "teräs, kenkä, teettää", "steel, shoes, to have made", ""),
    ("paulat vaskesta panetin,", "paulat vaskesta panetin,", "paula, vaski, panna", "strings/straps, copper/bronze, to put/make", ""),
    ("joilla seisoin seinävieret,", "joilla seisoin seinävieret,", "joilla, seistä, seinä, vieri", "with which, to stand, wall, side", ""),
    ("kuuntelin kujan perukset,", "kuuntelin kujien perukan,", "kuunnella, kuja, peräkulmaus", "to listen, lanes, back-corner", ""),
    ("kunnes viihtyisi vihainen,", "kunnes viihdyttäisi vihainen,", "kunnes, viihtyä, vihainen", "until, to be content/calm, angry one", ""),
    ("asettuisi ankarainen.", "asettuisi ankara.", "asettua, ankara", "to settle, strict/harsh", ""),
    ("Eikä viihy viimeinkänä,", "Eikä viihtynyt viimeksikään,", "ei, viihtyä, viimeksi", "not, to be content/calm, even last", ""),
    ("ei asetu aioinkana!", "ei asetu aikoinakaan!", "ei, asettua, aikoinaan", "not, to settle, ever", ""),
    ("\"Vilu viimeinki tulevi", "\"Vilu viimeinkin tulee", "vilu, viimein, tulla", "cold, finally, to come", ""),
    ("vihattuna vierressäni,", "vihattuna vieressäni,", "vihattu, vieri", "hated, beside", ""),
    ("seinävieret seistessäni,", "seinävieret seistessäni,", "seinä, vieri, seistä", "wall-sides, while standing", ""),
    ("ollessa oven takana.", "ollessa oven takana.", "olla, ovi, taka", "while being, door, behind", ""),
    ("Arvelin, ajattelime:", "Arvelin, ajattelime:", "arvella, ajatella", "to consider, to think", ""),
    ("ei minusta lienekänä", "ei minusta lieneekään", "ei, minä, lieneä", "not, from me, perhaps", ""),
    ("viikoista vihanpitoa,", "viikottaista vihanpitoa,", "viikko, viha, pito", "weekly, hatred, keeping", ""),
    ("kaukaista ylenkatsetta", "kaukaista ylenkatse", "kauka, ylenkatse", "far-reaching, disdain", ""),
    ("tässä lemmon leisiossa,", "tässä Lemmon leisiossa,", "tässä, Lemmo, leisio", "in this, Lemmo's (demon's), hiding place", ""),
    ("pirujen pesäsijassa.", "pirujen pesäsijassa.", "piru, pesä, sija", "devil's, nest, place", ""),
    ("\"Heitin hempeät tupaset,", "\"Heitin hempeät tupaset,", "heittää, hempeä, tupa", "to throw away, gentle/soft, cottages/halls", ""),
    ("armahat asuinmajani,", "rakkaat asuinmajani,", "rakas, asuinmaja", "dear, dwelling", ""),
    ("läksin, vieno, vieremähän.", "lähdin, vieno, vieremään.", "lähteä, vieno, vierähtää", "to set out, gentle, to roll/glide away", ""),
    ("Vierin soita, vierin maita,", "Viersin soita, viersin maita,", "vierähtää, suo, maa", "to roll/glide, swamps, lands", ""),
    ("vierin ventoja vesiä;", "viersin outoja vesiä;", "vierähtää, outo, vesi", "to roll/glide, strange, waters", ""),
    ("vierin veikon pellon päähän", "viersin veikon pellon päähän", "vierähtää, veikko, pelto, pää", "to roll/glide, brother's, field's, end/head", ""),
    ("siinä kukkui kuivat kuuset,", "siinä kukkuivat kuivat kuuset,", "siinä, kukua, kuiva, kuusi", "there, to cuckoo-call, dry, spruces", ""),
    ("lauloi lakkapäät petäjät,", "lauloivat lakkapäät petäjät,", "laulaa, lakkapää, petäjä", "to sing, flat-topped, pines", ""),
    ("kaikki vaakkuivat varikset,", "kaikki vaakkuivat varikset,", "kaikki, vaakkua, varis", "all, to caw, crows", ""),
    ("harakat hakahtelivat:", "harakat hakahtelivat:", "harakka, hakahtaa", "magpies, to chatter/crack", ""),
    ("'Ei täällä sinun kotisi", "'Ei täällä sinun kotisi", "ei, täällä, sinä, koti", "not, here, your, home", ""),
    ("eikä synnyntäsijasi!'", "eikä synnyntäsijasi!'", "ei, synnyntä, sija", "not, birth, place", ""),
    ("\"En mä tuotana totellut,", "\"En minä tuotakaan totellut,", "ei, minä, tuo, totella", "not, I, that, to obey", ""),
    ("vierin veikkoni piha'an.", "viersin veikkoni pihaan.", "vierähtää, veikko, piha", "to roll/glide, brother's, yard", ""),
    ("Jo mulle veräjät virkki,", "Jo minulle portit virkkivät,", "jo, minä, portti, virkata", "already, me, gates, to say", ""),
    ("kaikki vainiot valitti:", "kaikki pellot valittivat:", "kaikki, pelto, valittaa", "all, fields, to lament/complain", ""),
    ("'Mitäpä tulet kotihin,", "'Mitäpä tulet kotiin,", "mitä, tulla, koti", "what, to come, home", ""),
    ("kuta, kurja, kuulemahan?", "kuta, kurja, kuulemaan?", "kuta, kurja, kuulla", "what, wretched, to hear", ""),
    ("Jo ammoin isosi kuoli,", "Jo kauan isäsi kuoli,", "jo, kauan, isä, kuolla", "already, long ago, father, to die", ""),
    ("kaatui kaunis kantajasi;", "kaatui kaunis kantajasi;", "kaatua, kaunis, kantaja", "to fall, beautiful, bearer/carrier", ""),
    ("veikko sull' on ventovieras,", "veikko sinulle on täysvieras,", "veikko, sinä, täysvieras", "brother, you, complete stranger", ""),
    ("veikon nainen kuin venakko.'", "veikon nainen kuin vieras.'", "veikko, nainen, vieras", "brother's, woman/wife, like stranger", ""),
    ("\"En mä tuotana totellut,", "\"En minä tuotakaan totellut,", "ei, minä, tuo, totella", "not, I, from that, to obey", ""),
    ("menin mie toki tupahan.", "menin minä kuitenkin tupaan.", "mennä, minä, kuitenkin, tupa", "to go, I, however, cottage/hall", ""),
    ("Annoin kättä kääkäselle:", "Annoin kättä kääkäselle:", "antaa, käsi, kääkänen", "to give, hand, old hag/crone", ""),
    ("kylmä kääkä kättä vasten.", "kylmä kääkä kättä vasten.", "kylmä, kääkänen, käsi, vasten", "cold, old hag, hand, against", ""),
    ("\"Tultua tupahan tuosta", "\"Tultua tupaan tuosta", "tulla, tupa, tuosta", "having come, cottage/hall, from that", ""),
    ("oven suuhun seisotaime.", "oven suuhun seisoin.", "oven, suu, seistä", "door's, opening, to stand", ""),
    ("Korea kotoinen nainen:", "Korea kotoinen nainen:", "korea, kotoinen, nainen", "beautiful/fine, homely, woman", ""),
    ("ei tule likistämähän,", "ei tule likistämään,", "ei, tulla, likistää", "not, to come, to press/embrace", ""),
    ("käy ei kättä antamahan;", "ei käy kättä antamaan;", "ei, käydä, käsi, antaa", "not, to go, hand, to give", ""),
    ("korea minä itseki:", "korea minä itsekin:", "korea, minä, itsekkin", "beautiful/fine, I, myself too", ""),
    ("en mene likistämähän,", "en mene likistämään,", "ei, mennä, likistää", "not, to go, to press/embrace", ""),
    ("käy en kättä antamahan.", "en käy kättä antamaan.", "ei, käydä, käsi, antaa", "not, to go, hand, to give", ""),
    ("Pistän kättä kiukahalle:", "Pistän kättä kiukaalle:", "pistää, käsi, kiuas", "to put, hand, sauna stove", ""),
    ("kivet kylmät kiukahassa;", "kivet kylmät kiukaassa;", "kivi, kylmä, kiuas", "stones, cold, sauna stove", ""),
    ("käännän kättä hiilokselle:", "käännän kättä hiilokselle:", "kääntää, käsi, hiillos", "to turn, hand, embers", ""),
    ("hiilet kylmät hiiloksessa.", "hiilet kylmät hiiilloksessa.", "hiili, kylmä, hiillos", "coals, cold, embers", ""),
    ("\"Veikko lautsalla lamovi,", "\"Veikko lavitsalla lamoo,", "veikko, lavitsa, lamata", "brother, bench, to lie flat/idle", ""),
    ("päässä pankon pöllöttävi,", "päässä penkillä pöllöttää,", "pää, penkki, pöllöttää", "at the end, bench, to stare blankly", ""),
    ("syli syttä hartioilla,", "sylillinen syttä hartioilla,", "syli, sysi, hartia", "fathom/lap, charcoal, shoulders", ""),
    ("vaaksa muulla vartalolla,", "vaaksa muulla vartalolla,", "vaaksa, muu, vartalo", "span, other, body", ""),
    ("kyynärä kyventä päässä,", "kyynärä nokea päässä,", "kyynärä, noki, pää", "forearm-length, soot, head", ""),
    ("kortteli kovaa nokea.", "kortteli kovaa nokea.", "kortteli, kova, noki", "quarter-span, hard, soot", ""),
    ("\"Kysyi veikko vierahalta,", "\"Kysyi veikko vieraalta,", "kysyä, veikko, vieras", "to ask, brother, stranger", ""),
    ("tutkaeli tullehelta:", "tutkaeli tulleelta:", "tutkella, tullut", "to question/examine, one who had come", ""),
    ("'Mistä vieras veen takoa?'", "'Mistä vieras tulee?'", "mistä, vieras, tulla", "from where, stranger, to come", ""),
    ("Minä vainen vastaelin:", "Minä vainen vastaelin:", "minä, vainen, vastata", "I, poor/dear, to answer", ""),
    ("'Etkö tunne siskoasi,", "'Etkö tunne siskoasi,", "ei, tuntea, sisko", "not, to know, sister", ""),
    ("entistä emosi lasta?", "entistä äitisi lasta?", "entinen, äiti, lapsi", "former, mother's, child", ""),
    ("Me yhen emosen lapset,", "Me yhden äidin lapset,", "me, yksi, äiti, lapsi", "we, one, mother's, children", ""),
    ("yhen linnun liekuttamat,", "yhden linnun liekuttamat,", "yksi, lintu, liekuttaa", "one, bird's, rocked/swung", ""),
    ("yhen hanhen hautelemat,", "yhden hanhen hautelemat,", "yksi, hanhi, haudata", "one, goose, brooded over", ""),
    ("yhen pyyn pesästä saamat!'", "yhden pyyn pesästä saamat!'", "yksi, pyy, pesä, saada", "one, hazel-grouse, nest, gotten from", ""),
    ("Tuosta veikko itkemähän,", "Tuosta veikko itkemähän,", "tuosta, veikko, itkeä", "from that, brother, to cry", ""),
    ("silmät vettä vieremähän...", "silmät vettä vieremähän...", "silmä, vesi, vierähtää", "eyes, water, to roll", ""),
    ("\"Virkkoi veikko naisellensa,", "\"Virkkoi veikko vaimollensa,", "virkata, veikko, vaimo", "to say, brother, wife", ""),
    ("kuiskaeli kullallensa:", "kuiskaeli kullallensa:", "kuiskailla, kulta", "to whisper, golden one", ""),
    ("'Hanki syöä siskolleni!'", "'Hanki syödä siskolleni!'", "hankkia, syödä, sisar", "to get, to eat, sister's", ""),
    ("Veikon nainen naljasilmä", "Veikon nainen naljasilmä", "veikko, nainen, naljasilmä", "brother's, woman/wife, sly-eyed", ""),
    ("kantoi kaalia koasta,", "kantoi kaalia koasta,", "kantaa, kaali, kosta", "to carry, cabbage, tub/vessel", ""),
    ("jost' oli rakki rasvan syönyt,", "josta oli rakki rasvan syönyt,", "josta, olla, rakki, rasva, syödä", "from which, to be, mongrel, fat, to eat", ""),
    ("koira suolan koitellunna,", "koira suolan koitellut,", "koira, suola, koitella", "dog, salt, to have tested/tasted", ""),
    ("Musti murkinan pitännä.", "Musti murkinan pitänyt.", "Musti (dog name), murkina, pitää", "Musti (dog), meal, to have had", "The vagrant woman returning to her brother's house — greeted coldly, fed cabbage from which the dog had eaten the fat, given water instead of beer (sisters' eye-water, sisters-in-law's cuckoo-nest-water) — is the trickster-crone's most devastating portrait of social exclusion after failed marriage."),
    ("\"Virkkoi veikko naisellensa,", "\"Virkkoi veikko vaimollensa,", "virkata, veikko, vaimo", "to say, brother, wife", ""),
    ("kuiskaeli kullallensa:", "kuiskaeli kullallensa:", "kuiskailla, kulta", "to whisper, golden one", ""),
    ("'Tuo olutta vierahalle!'", "'Tuo olutta vieraalle!'", "tuoda, olut, vieras", "to bring, beer/ale, guest/stranger", ""),
    ("Veikon nainen naljasilmä", "Veikon nainen naljasilmä", "veikko, nainen, naljasilmä", "brother's, woman/wife, sly-eyed", ""),
    ("toip' on vettä vierahalle,", "toi vettä vieraalle,", "tuoda, vesi, vieras", "to bring, water, guest/stranger", ""),
    ("ei sitänä siivon vettä:", "ei sitäkään sievää vettä:", "ei, siivo, vesi", "not, decent/clean, water", ""),
    ("sisaresten silmivettä,", "sisaresten silmivettä,", "sisar, silmivesi", "sisters', eye-water/tears", ""),
    ("kälysten käenpesintä.", "kälysten käenpesintää.", "käly, käkipesä", "sisters-in-law's, cuckoo-nest-water", ""),
    ("\"Vierin jälle veikon luota,", "\"Viersin taas veikon luota,", "vierähtää, taas, veikko, luota", "to roll/glide, again, brother's, from near", ""),
    ("siirryin synnyntäsijalta.", "siirryin synnyntäsijalta.", "siirtyä, synnyntä, sija", "to move, birth, place", ""),
    ("Jou'uin, kurja, kulkemahan,", "Jouduin, kurja, kulkemaan,", "joutua, kurja, kulkea", "to end up, wretched, to go/travel", ""),
    ("sain, kurja, samoamahan,", "sain, kurja, samoamaan,", "saada, kurja, samota", "to get, wretched, to wade/wander", ""),
    ("raukka, rannat kiertämähän,", "raukka, rannat kiertämään,", "raukka, ranta, kiertää", "poor wretch, shores, to circle/wander", ""),
    ("vaivainen, vaeltamahan", "vaivainen, vaeltamaan", "vaivainen, vaeltaa", "wretched, to wander", ""),
    ("aina ouoillen oville,", "aina outoihin oviin,", "aina, outo, ovi", "always, strange, doors", ""),
    ("veräjille vierahille,", "portille vieraille,", "portti, vieras", "gate, strange", ""),
    ("lapset raukan rannikolle,", "lapset raukan rannikolle,", "lapsi, raukka, rannikko", "children, poor wretch's, coast/shore", ""),
    ("vaivaiset kylän varahan...", "vaivaiset kylän varaahan...", "vaivainen, kylä, varaa", "wretched ones, village's, provision/reserve", ""),
    ("\"Moni nyt minulla onpi,", "\"Moni nyt minulla on,", "moni, nyt, minä, olla", "many, now, me, to be", ""),
    ("usea olettelevi", "usea olettelee", "usea, olettaa", "many/frequent, to suppose/assume", ""),
    ("virkkaja vihaisen äänen,", "virkkaja vihaisen äänen,", "virkkaja, vihainen, ääni", "sayer, angry, voice", ""),
    ("äänen tuiman tuikuttaja;", "äänen tuiman tuikuttaja;", "ääni, tuima, tuikuttaa", "voice, fierce, shouter/crier", ""),
    ("ei ole minulla monta", "ei ole minulla monta", "ei, olla, minä, monta", "not, to be, me, many", ""),
    ("sanan armon antajata,", "sanan armon antajaa,", "sana, armo, antaja", "word's, grace/mercy, giver", ""),
    ("suin sulin puhelijata,", "suin sulin puhelijaa,", "suin sulin, puhelija", "full-mouthed/earnestly, speaker", ""),
    ("kiukahalle käskijätä", "kiukaalle käskijätä", "kiuas, käskijä", "sauna stove's, inviter", ""),
    ("satehesta saatuani,", "sateesta saatuani,", "sade, saada", "rain, having gotten from", ""),
    ("kylmästä kyhättyäni", "kylmästä kyhättyäni", "kylmä, kyhätä", "cold, having been assembled/made", ""),
    ("hallassa hamehen helmat,", "hallassa hameen helmat,", "halla, hame, helma", "frost, skirt/dress, hems", ""),
    ("turkin helmat tuppurissa.", "turkin helmat tuppurissa.", "turkki, helma, tuppu", "fur coat's, hems, all bunched up", ""),
    ("\"Enpä ennen nuorempana,", "\"Enkä ennen nuorempana,", "ei, ennen, nuori", "not, before, younger", ""),
    ("en mä uskonut olisi,", "en minä olisi uskonut,", "ei, minä, olla, uskoa", "not, I, to have been, to believe", ""),
    ("jos oisi sata sanonut,", "jos olisi sata sanonut,", "jos, olla, sata, sanoa", "if, to have been, hundred, to say", ""),
    ("tuhat kieltä kertaellut", "tuhat kieltä kertaellut", "tuhat, kieli, kertata", "thousand, tongues, to repeat", ""),
    ("näille juonin joutuvani,", "näille juonille joutuvan,", "tämä, juoni, joutua", "these, schemes/tracks, to end up", ""),
    ("näille päivin pääseväni,", "näille päiville pääseväni,", "tämä, päivä, päästä", "these, days, getting to", ""),
    ("jotk' on päivät päälle pääsnyt,", "jotka päivät päälle päässyt,", "jotka, päivä, päälle, päästä", "which, days, over, gotten", ""),
    ("juonet joutunna kätehen.\"", "juonet joutunut käteen.\"", "juoni, joutua, käsi", "schemes/tracks, ended up, hand", "The vagrant woman's final lines — 'I would never have believed, even if a hundred told me, a thousand tongues repeated it, that I would end up in these schemes, reach these days, these days that have come over me, these tracks that have fallen into my hand' — is the trickster-crone's closing self-knowledge: the most bitter wisdom in the Kalevala."),
]

thin_border = Border(
    left=Side(style='thin', color='CCCCCC'),
    right=Side(style='thin', color='CCCCCC'),
    top=Side(style='thin', color='CCCCCC'),
    bottom=Side(style='thin', color='CCCCCC')
)
fill_even = PatternFill("solid", start_color="F7F3E9")
fill_odd  = PatternFill("solid", start_color="FFFFFF")
fill_trickster = PatternFill("solid", start_color="FFF3CD")
normal_font    = Font(name="Arial", size=10)
trickster_font = Font(name="Arial", size=10, italic=True, color="7B5E00")

for i, (orig, modern, basic, trans, trick) in enumerate(verses, start=2):
    row_fill = fill_even if i % 2 == 0 else fill_odd
    for col, val in enumerate([orig, modern, basic, trans, trick], start=1):
        cell = ws.cell(row=i, column=col, value=val)
        cell.font = trickster_font if (col == 5 and trick) else normal_font
        cell.fill = fill_trickster if (col == 5 and trick) else row_fill
        cell.border = thin_border
        cell.alignment = Alignment(wrap_text=True, vertical="top")

ws.column_dimensions['A'].width = 32
ws.column_dimensions['B'].width = 32
ws.column_dimensions['C'].width = 30
ws.column_dimensions['D'].width = 32
ws.column_dimensions['E'].width = 55
ws.freeze_panes = "A2"
ws.row_dimensions[1].height = 30
for r in range(2, len(verses)+2):
    ws.row_dimensions[r].height = 30

out = "Kalevala_Runo_XXIII_Part3_Analysis.xlsx"
wb.save(out)
print("Saved:", out, "–", len(verses), "verses")
