from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

wb = Workbook()
ws = wb.active
ws.title = "Runo XXIV"

headers = ["A: Alkuperäinen säe", "B: Nykysuomi", "C: Perusmuodot", "D: Käännökset (EN)", "E: Trickster-huomioita"]
header_fill = PatternFill("solid", start_color="2E4057")
header_font = Font(bold=True, color="FFFFFF", name="Arial", size=11)
for col, h in enumerate(headers, 1):
    cell = ws.cell(row=1, column=col, value=h)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

verses = [
    ("Jo nyt on neiti neuvottuna,", "Jo nyt on neiti neuvottuna,", "jo, nyt, neito, neuvoa", "already, now, maiden, advised", ""),
    ("morsian opastettuna.", "morsian opastettuna.", "morsian, opastaa", "bride, instructed", ""),
    ("Vielä virkin veijolleni,", "Vielä sanoin veijolleni,", "vielä, virkata, veijo", "still, to say, dear brother", ""),
    ("sulholleni suin puhelen:", "sulholleni suoraan puhelen:", "sulho, suu, puhua", "groom/suitor, mouth, to speak", ""),
    ("\"Sulho, viljon veikkoseni,", "\"Sulho, viljan veikkoseni,", "sulho, vilja, veikko", "groom/suitor, dear/abundant, brother", ""),
    ("vielä veikkoa parempi,", "vielä veikkoa parempi,", "vielä, veikko, parempi", "still, brother, better", ""),
    ("emon lasta armahampi,", "äidin lasta armahampi,", "äiti, lapsi, armas", "mother's, child, dearer", ""),
    ("ison lasta lauhkeampi!", "isän lasta lauhkeampi!", "isä, lapsi, lauhkea", "father's, child, gentler/milder", ""),
    ("Kuulesta, ma kuin sanelen,", "Kuules, kun sanelen,", "kuulla, kun, sanella", "to hear, when, to recite/tell", ""),
    ("kuin sanelen, kuin puhelen", "kun sanelen, kun puhelen", "kun, sanella, kun, puhua", "when, to recite/tell, when, to speak", ""),
    ("tästä liinalinnustasi,", "tästä liinalinnustasi,", "tästä, liinalintu", "from this, linen-bird (bride)", ""),
    ("saamaisestasi kanasta!", "saamaisestasi kanasta!", "saada, kana", "your gotten, hen/girl", ""),
    ("\"Kiitä, sulho, onneasi", "\"Kiitä, sulho, onneasi", "kiittää, sulho, onni", "to thank/praise, groom, luck/fortune", ""),
    ("hyvän saaman saamastasi!", "hyvän saaman saamastasi!", "hyvä, saama, saada", "good, gotten, from getting", ""),
    ("Kun kiität, hyvinki kiitä!", "Kun kiität, hyvinkin kiitä!", "kun, kiittää, hyvin", "when, to thank/praise, well", ""),
    ("Hyvän sait, hyvän tapasit,", "Hyvän sait, hyvän tapasit,", "hyvä, saada, tavata", "good, to get, to find/meet", ""),
    ("hyvän Luojasi lupasi,", "hyvän Luojasi lupasi,", "hyvä, Luoja, luvata", "good, Creator, to promise", ""),
    ("hyvän antoi armollinen.", "hyvän antoi armollinen.", "hyvä, antaa, armollinen", "good, to give, gracious/merciful", ""),
    ("Lue kiitokset isolle,", "Lue kiitokset isälle,", "lukea, kiitos, isä", "to recite/count, thanks, father", ""),
    ("emoselle viel' enemmin,", "äidille vielä enemmän,", "äiti, vielä, enemmän", "mother, still, more", ""),
    ("ku tuuti tytön mokoman,", "joka tuuditti tytön mokoman,", "joka, tuudittaa, tyttö, moinen", "who, to rock/lull, girl, such a", ""),
    ("niin mokoman morsiamen!", "niin mokomaisen morsiamen!", "niin, moinen, morsian", "so, such a, bride", ""),
    ("\"Puhas on neiti puolellasi,", "\"Puhdas on neiti puolellasi,", "puhdas, neito, puoli", "pure/clean, maiden, side", "The bridal praise catalogue — pure beside you, bright in betrothal, white in your keeping, graceful in your shelter, a sturdy daughter, ruddy beside you — is the singer-trickster's performance of ideal wifely description, the male gaze as social obligation."),
    ("neiti kirkas kihloissasi,", "neiti kirkas kihloissasi,", "neito, kirkas, kihla", "maiden, bright/clear, betrothal", ""),
    ("valkeainen vallassasi,", "valkeainen vallassasi,", "valkea, valta", "white/bright one, in your keeping", ""),
    ("soreainen suojassasi,", "soreainen suojassasi,", "sorea, suoja", "graceful one, in your shelter", ""),
    ("tytär riski rinnallasi,", "tytär riski rinnallasi,", "tytär, riski, rinta", "daughter, sturdy/vigorous, at your breast", ""),
    ("vereväinen vieressäsi,", "vereväinen vieressäsi,", "verevä, vieri", "ruddy/fresh one, beside you", ""),
    ("tytär riski, riihenpuija,", "tytär riski, riihenpuija,", "tytär, riski, riihi, puija", "daughter, sturdy, barn-flail-wielder", ""),
    ("hempulainen heinänlyöjä,", "hempulainen heinänlyöjä,", "hempulainen, heinä, lyödä", "nimble/graceful one, hay-striker", ""),
    ("pulski poukkujen pesijä,", "pulski poukkujen pesijä,", "pulski, poukku, pestä", "brisk/plump, bundles, washer", ""),
    ("varski vaatevalkaisija,", "varski vaatevalkaisija,", "varski, vaate, valkaista", "lively, clothes, bleacher", ""),
    ("kensti rihman kehreäjä,", "kensti rihman kehreäjä,", "kensti, rihma, kehrätä", "nimble, thread, spinner", ""),
    ("karski kankahan kutoja.", "karski kankahan kutoja.", "karski, kangas, kutoa", "vigorous, cloth, weaver", ""),
    ("\"Niin sen piukki pirran ääni,", "\"Niin piukki pirran ääni,", "niin, piukata, pirta, ääni", "so, to twang/crack, reed's, sound", ""),
    ("kuin käki mäellä kukkui;", "kuin käki mäellä kukkui;", "kuin, käki, mäki, kukua", "like, cuckoo, hill, to cuckoo-call", ""),
    ("niin sen suihki sukkulainen,", "niin suihki sukkulainen,", "niin, suihahtaa, sukkula", "so, to dart/rush, shuttle", ""),
    ("kuin on portimo pinossa;", "kuin on portimo pinossa;", "kuin, portimo, pino", "like, weaver's-pin, pile/stack", ""),
    ("niin sen käämi käännähteli,", "niin käämi käännähteli,", "niin, käämi, kääntyä", "so, bobbin/spool, to turn", ""),
    ("kuin käpy oravan suussa.", "kuin käpy oravan suussa.", "kuin, käpy, orava, suu", "like, cone, squirrel's, mouth", ""),
    ("Ei kylä sike'in maannut,", "Ei kylä sikeästi maannut,", "ei, kylä, sikeästi, maata", "not, village, soundly, to sleep", ""),
    ("linnakunta uinaellut", "linnakunta uinaellut", "linnakunta, uinahtaa", "castle-folk/community, to doze", ""),
    ("neien pirran pirkeheltä,", "neidon pirran pirskeheltä,", "neito, pirta, pirske", "maiden's, reed's, whirring/humming", ""),
    ("sukkulan surinehelta.", "sukkulan surinasta.", "sukkula, surina", "shuttle's, buzzing/humming", ""),
    ("\"Sulhokainen, nuorukainen,", "\"Sulhokainen, nuorukainen,", "sulho, nuori", "little groom, little young one", ""),
    ("miehen kanta kaunokainen!", "miehen kanta kaunokainen!", "mies, kanta, kaunoinen", "man's, support/heel, beautiful one", ""),
    ("Tao viikate terävä,", "Tao viikate terävä,", "takoa, viikate, terävä", "to forge, scythe, sharp", ""),
    ("vaali vartehen hyvähän,", "vaali vartehen hyvään,", "vaalia, varsi, hyvä", "to tend/choose, handle, good", ""),
    ("veistele veräjän suussa,", "veistele veräjän suussa,", "veistää, veräjä, suu", "to carve/trim, gate's, opening", ""),
    ("kannon päässä kalkuttele!", "kannon päässä kalkuttele!", "kanto, pää, kalkuttaa", "stump, end/head, to hammer", ""),
    ("Kun tulevi päiväpaiste,", "Kun tulee päivänpaiste,", "kun, tulla, päivänpaiste", "when, to come, sunshine", ""),
    ("viepä neiti nurmen päälle:", "vie neiti nurmen päälle:", "viedä, neito, nurmi, päälle", "to take, maiden, meadow, over", ""),
    ("näet, kuin heinä herskähtävi,", "näet, kuinka heinä herskähtää,", "nähdä, kuinka, heinä, herskähtää", "to see, how, hay, to swoosh/swish", ""),
    ("kova heinä korskahtavi,", "kova heinä korskahtaa,", "kova, heinä, korskahtaa", "hard, hay, to rustle/crackle", ""),
    ("vihviläinen viuskahtavi,", "vihviläinen viuskahtaa,", "vihvilä, viuskahtaa", "rush/reed-grass, to swish", ""),
    ("suolaheinä suiskahtavi,", "suolaheinä suiskahtaa,", "suolaheinä, suiskahtaa", "sorrel-grass, to swish", ""),
    ("mätäs myötähän menevi,", "mätäs myötään menee,", "mätäs, myötään, mennä", "tussock, along/with, to go", ""),
    ("vesan kanta katkeavi.", "vesan kanta katkeaa.", "vesa, kanta, katketa", "sapling's, base/root, to snap", "The instruction to take the bride to the meadow and show her mowing — watch how hay swooshes, hard grass crackles, rushes swish — is the singer-trickster's practical catalogue of agricultural skills as courtship praise."),
    ("\"Kun tulevi toinen päivä,", "\"Kun tulee toinen päivä,", "kun, tulla, toinen, päivä", "when, to come, second, day", ""),
    ("hanki suora sukkulainen,", "hanki suora sukkulainen,", "hankkia, suora, sukkula", "to get, straight, shuttle", ""),
    ("pirran-päällinen pätevä,", "pirran-päällinen pätevä,", "pirta, päällinen, pätevä", "reed-cover, capable/sufficient", ""),
    ("käärinlauta laaullinen,", "käärinlauta lauluisa,", "käärinlauta, laulullinen", "roll-board, musical/tuneful", ""),
    ("vuoli suksekset soreat,", "vuoli suksekset soreat,", "vuolla, suksi, sorea", "to carve, skis, graceful/fine", ""),
    ("hanki kaikki kangasneuvot!", "hanki kaikki kangasneuvot!", "hankkia, kaikki, kangas, neuvo", "to get, all, cloth, tools/implements", ""),
    ("Laita neiti kangaspuille,", "Laita neiti kangaspuille,", "laittaa, neito, kangaspuu", "to put, maiden, loom", ""),
    ("pirran-päällinen piohon:", "pirran-päällinen käteen:", "pirta, päällinen, käsi", "reed-cover, into hand", ""),
    ("äsken pirta piukkoavi,", "äsken pirta piukkoaa,", "äsken, pirta, piukata", "only then, reed, to twang/crack", ""),
    ("kangaspuut kamahtelevi,", "kangaspuut kamahtelee,", "kangaspuu, kamahtaa", "loom, to boom/clatter", ""),
    ("kuuluvi kylähän kalske,", "kuuluu kylään kalske,", "kuulua, kylä, kalske", "to be heard, village, clattering", ""),
    ("pirran pirske loitommalle.", "pirran pirske kauemmas.", "pirta, pirske, kauemmas", "reed's, whirring/humming, further away", ""),
    ("Akat tuosta arvelevat,", "Naiset tuosta arvelevat,", "nainen, tuosta, arvella", "women, from that, to consider", ""),
    ("kysyvät kyläiset naiset:", "kysyvät kyläiset naiset:", "kysyä, kyläinen, nainen", "to ask, village, women", ""),
    ("'Kuka kangasta kutovi?'", "'Kuka kangasta kutoo?'", "kuka, kangas, kutoa", "who, cloth, to weave", ""),
    ("Sinun vastata sopivi:", "Sinun vastata sopii:", "sinä, vastata, sopia", "your, to answer, to suit/fit", ""),
    ("'Oma kultani kutovi,", "'Oma kultani kutoo,", "oma, kulta, kutoa", "own, golden one, to weave", ""),
    ("herttaiseni helskyttävi.", "herttaiseni helskyttää.", "herttainen, helskyttää", "my dear one, to jingle/clatter", ""),
    ("Laskiko lapoja kangas,", "Laskiko lapoja kangas,", "laskea, lapo, kangas", "to shed, shed-sticks, cloth", ""),
    ("päästi pirta piitämiä?'", "päästi pirta piitämiä?'", "päästää, pirta, piit", "to let go, reed, prongs/spikes", ""),
    ("'Ei laske lapoja kangas,", "'Ei laske lapoja kangas,", "ei, laskea, lapo, kangas", "not, to shed, shed-sticks, cloth", ""),
    ("päästä ei pirta piitämiä:", "päästä ei pirta piitämiä:", "ei, päästää, pirta, piit", "not, to let go, reed, prongs/spikes", ""),
    ("on kuin Kuuttaren kutoma,", "on kuin Kuuttaren kutoma,", "olla, kuin, Kuutar, kutoa", "to be, like, Moon-maiden's, woven", ""),
    ("Päivättären kehreämä,", "Päivättären kehreämä,", "Päivätär, kehrätä", "Sun-maiden's, spun", ""),
    ("Otavattaren osaama,", "Otavattaren osaama,", "Otavatar, osata", "Great-Bear-maiden's, known how to do", ""),
    ("Tähettären täyttelemä.'", "Tähettären täyttelemä.'", "Tähettär, täytellä", "Star-maiden's, completed/filled", "The praise formula attributing the bride's weaving to Moon-maiden, Sun-maiden, Great-Bear-maiden, Star-maiden — is the trickster-singer elevating domestic skill to cosmic level. The loom-work is so perfect it must be divine."),
    ("\"Sulhokainen, nuorukainen,", "\"Sulhokainen, nuorukainen,", "sulho, nuori", "little groom, little young one", ""),
    ("miehen kanta kaunokainen!", "miehen kanta kaunokainen!", "mies, kanta, kaunoinen", "man's, support/heel, beautiful one", ""),
    ("Kun nyt lähet kulkemahan,", "Kun nyt lähdet kulkemaan,", "kun, nyt, lähteä, kulkea", "when, now, to set out, to go", ""),
    ("saat tästä ajelemahan", "saat tästä ajelemaan", "saada, tästä, ajella", "to get, from here, to drive about", ""),
    ("kera nuoren neitosesi,", "nuoren neitosi kanssa,", "nuori, neito, kanssa", "young, maiden's, with", ""),
    ("kanssa kaunihin kanasi,", "kauniin kanasi kanssa,", "kaunis, kana, kanssa", "beautiful, hen/girl's, with", ""),
    ("ellös vainen varpuistasi,", "älä vain varpuistasi,", "älä, vain, varpu", "don't, just, twig/branch", ""),
    ("tätä liinalinnuistamme,", "tätä liinalinnuistamme,", "tämä, liinalintu", "this, our linen-bird (bride)", ""),
    ("ellös vieruhun ve'elkö,", "älä vieruun vedä,", "älä, vierus, vetää", "don't, ditch-side, to pull", ""),
    ("aian kolkkihin ajelko,", "aidan kolkkiin aja,", "aita, kolkka, ajaa", "fence's, corner, to drive", ""),
    ("kaa'atelko kannon päähän,", "kaadattele kannon päähän,", "kaataa, kanto, pää", "to tip/topple, stump, end/head", ""),
    ("kivilöihin kiskotelko!", "kivilöihin kiskotelko!", "kivi, kiskata", "stones, to jerk/drag", ""),
    ("Ei ennen ison ko'issa,", "Ei ennen isän kotona,", "ei, ennen, isä, koti", "not, before, father's, home", ""),
    ("emon kaunon kartanoilla", "äidin kauniilla kartanolla", "äiti, kaunis, kartano", "mother's, beautiful, estate/yard", ""),
    ("neittä vieruihin ve'elty,", "neittä vieruihin vedetty,", "neito, vierus, vetää", "maiden, ditch-side, dragged", ""),
    ("aian kolkkihin ajeltu,", "aidan kolkkiin ajettu,", "aita, kolkka, ajaa", "fence's, corner, driven", ""),
    ("kaa'ateltu kannon päähän,", "kaadettu kannon päähän,", "kaataa, kanto, pää", "tipped/toppled, stump, end/head", ""),
    ("kivilöihin kiskoteltu.", "kivilöihin kiskoteltu.", "kivi, kiskata", "stones, jerked/dragged", ""),
    ("\"Sulhokainen, nuorukainen,", "\"Sulhokainen, nuorukainen,", "sulho, nuori", "little groom, little young one", ""),
    ("miehen kanta kaunokainen!", "miehen kanta kaunokainen!", "mies, kanta, kaunoinen", "man's, support/heel, beautiful one", ""),
    ("Ellös viekö neioistasi,", "Älä vie neioistasi,", "älä, viedä, neito", "don't, to take, maiden", ""),
    ("kuletelko kullaistasi", "kuletelko kullaistasi", "kuljettaa, kulta", "to convey, golden one", ""),
    ("nurkkihin nuhajamahan,", "nurkkiin nuhajamaan,", "nurkka, nuhata", "corners, to snuffle/grub", ""),
    ("soppihin sohajamahan!", "soppihin sohajamaan!", "soppi, sohata", "nooks, to poke/dig", ""),
    ("Ei neiti ison kotona,", "Ei neiti isän kotona,", "ei, neito, isä, koti", "not, maiden, father's, home", ""),
    ("emon entisen tuvilla", "äidin entisessä tuvassa", "äiti, entinen, tupa", "mother's, former, cottage/hall", ""),
    ("eip' on nurkissa nuhannut,", "ei ole nurkissa nuhannut,", "ei, olla, nurkka, nuhata", "not, to have been, corners, to snuffle/grub", ""),
    ("ei sohannut soppiloissa:", "ei sohannut soppiloissa:", "ei, sohata, soppi", "not, to poke/dig, nooks", ""),
    ("aina istui ikkunoissa,", "aina istui ikkunoissa,", "aina, istua, ikkuna", "always, to sit, windows", ""),
    ("keikkui keskilattioilla,", "keikkui keskilattioilla,", "keikkua, keski, lattia", "to sway/rock, middle, floors", ""),
    ("illat taattonsa ilona,", "illat isänsä ilona,", "ilta, isä, ilo", "evenings, father's, joy", ""),
    ("aamut äitin armahana.", "aamut äidin rakkaana.", "aamu, äiti, rakas", "mornings, mother's, dear", ""),
    ("\"Ellös vainen, sulho rukka,", "\"Älä vainen, sulho rukka,", "älä, vain, sulho, rukka", "don't, just, groom/suitor, poor", ""),
    ("ellös sie tätä kanaista", "älä sinä tätä kanaista", "älä, sinä, tämä, kanainen", "don't, you, this, little hen/girl", ""),
    ("viekö vehkahuhmarelle,", "vie vehkahuumarelle,", "viedä, vehka, huhmare", "to take, arum-plant, mortar", ""),
    ("panko parkin survontahan,", "panko parkin survontaan,", "panna, parkki, survoa", "to put, bark/tan, pounding", ""),
    ("olkileivän leivontahan,", "olkileivän leivontaan,", "olki, leipä, leipoa", "straw-bread, baking", ""),
    ("petäjäisen pieksäntähän!", "petäjäisen pieksäntään!", "petäjäinen, pieksää", "pine-bark's, beating/thrashing", ""),
    ("Ei neittä ison kotona,", "Ei neittä isän kotona,", "ei, neito, isä, koti", "not, maiden, father's, home", ""),
    ("emon kaunon kartanossa", "äidin kauniissa kartanossa", "äiti, kaunis, kartano", "mother's, beautiful, estate/yard", ""),
    ("viety vehkahuhmarelle,", "viety vehkahuumarelle,", "viedä, vehka, huhmare", "taken, arum-plant, mortar", ""),
    ("pantu parkin survontahan,", "pantu parkin survontaan,", "panna, parkki, survoa", "put, bark/tan, pounding", ""),
    ("olkileivän leivontahan,", "olkileivän leivontaan,", "olki, leipä, leipoa", "straw-bread, baking", ""),
    ("petäjäisen pieksäntähän.", "petäjäisen pieksäntään.", "petäjäinen, pieksää", "pine-bark's, beating/thrashing", ""),
    ("\"Vieös sä tätä kanoa,", "\"Vie sinä tätä kanoa,", "viedä, sinä, tämä, kana", "to take, you, this, hen/girl", ""),
    ("vieös viljamättähälle,", "vie viljamättähälle,", "viedä, vilja, mätäs", "to take, grain/fertile, mound", ""),
    ("ru'ispurnun purkajaksi,", "ruispurnun purkajaksi,", "ruis, purnu, purkaa", "rye-barrel's, opener/emptier", ""),
    ("ohrapurnun ottajaksi,", "ohrapurnun ottajaksi,", "ohra, purnu, ottaa", "barley-barrel's, taker", ""),
    ("leivän paksun paistajaksi,", "leivän paksun paistajaksi,", "leipä, paksu, paistaa", "bread, thick, baker", ""),
    ("oluen osoajaksi,", "oluen osoajaksi,", "olut, osoittaa", "beer/ale's, pointer/giver", ""),
    ("vehnäleivän leipojaksi,", "vehnäleivän leipojaksi,", "vehnä, leipä, leipoa", "wheat-bread, baker", ""),
    ("taikinan taputtajaksi!", "taikinan taputtajaksi!", "taikina, taputella", "dough, patter/kneader", ""),
    ("\"Sulho, viljon veljyeni!", "\"Sulho, viljan veljyeni!", "sulho, vilja, veli", "groom/suitor, dear/abundant, brother", ""),
    ("Ellös sie tätä kanoa,", "Älä sinä tätä kanoa,", "älä, sinä, tämä, kana", "don't, you, this, hen/girl", ""),
    ("ellös meiän hanhoistamme", "älä meidän hanhoistamme", "älä, me, hanhi", "don't, our, goose", ""),
    ("ikävillä itketelkö!", "ikävillä itketä!", "ikävä, itkeä", "with tedium/longing, to make cry", ""),
    ("Tulisiko tuhma tunti,", "Tulisiko tuhma tunti,", "tulla, tuhma, tunti", "to come, stupid/dull, hour", ""),
    ("saisi neiollen ikävä,", "saisi neidolle ikävä,", "saada, neito, ikävä", "to get, maiden, longing/tedium", ""),
    ("pistä puuru puikkoloihin", "pistä puuro puikkoihin", "pistää, puuro, puikko", "to put, porridge, sticks", ""),
    ("tahi valkko valjahisin,", "tahi valkko valjaisihin,", "tahi, valkko, valjaat", "or, white horse, harness", ""),
    ("tuo neittä ison kotihin,", "tuo neittä isän kotiin,", "tuoda, neito, isä, koti", "to bring, maiden, father's, home", ""),
    ("emon tuttavan tuville!", "äidin tuttavaan tupaan!", "äiti, tuttu, tupa", "mother's, familiar, cottage/hall", "The instruction to take the bride home to her parents if she becomes homesick — 'put porridge in the sticks or harness the white horse' — is the singer-trickster asserting the bride's right of return. This counterbalances the old woman's bitter account of having nowhere to go."),
    ("\"Ellös sie tätä kanaista,", "\"Älä sinä tätä kanaista,", "älä, sinä, tämä, kanainen", "don't, you, this, little hen/girl", ""),
    ("ellös liinalinnuistamme", "älä liinalinnuistamme", "älä, liinalintu", "don't, our linen-bird (bride)", ""),
    ("oletelko orjanasi,", "pidä orjanasi,", "pitää, orja", "to keep, as your slave", ""),
    ("palkanpiikana pi'elkö,", "palkanpiikana pidä,", "palkka, piika, pitää", "hired-maid, to keep", ""),
    ("elä kiellä kellarista", "älä kiellä kellarista", "älä, kieltää, kellari", "don't, to forbid, cellar", ""),
    ("eläkä aitasta epeä!", "äläkä aitasta evää!", "älä, aitta, evätä", "don't, storehouse, to deny/withhold", ""),
    ("Ei neittä ison kotona,", "Ei neittä isän kotona,", "ei, neito, isä, koti", "not, maiden, father's, home", ""),
    ("emon kaunon kartanossa", "äidin kauniissa kartanossa", "äiti, kaunis, kartano", "mother's, beautiful, estate/yard", ""),
    ("oleteltu orjan arvon,", "pidetty orjan arvoin,", "pitää, orja, arvo", "kept, slave's, worth/value", ""),
    ("palkanpiikana pi'elty,", "palkanpiikana pidetty,", "palkka, piika, pitää", "hired-maid, kept", ""),
    ("ei kielletty kellarista", "ei kielletty kellarista", "ei, kieltää, kellari", "not, forbidden, cellar", ""),
    ("eikä aitasta evätty:", "eikä aitasta evätty:", "ei, aitta, evätä", "not, storehouse, denied/withheld", ""),
    ("aina viilti vehnäsiä,", "aina viilti vehnäisiä,", "aina, viiltää, vehnäinen", "always, to slash/slice, wheat-goods", ""),
    ("katseli kananmunia", "katseli kananmunia", "katsella, kananmuna", "to look at, chicken eggs", ""),
    ("maitotiinun tienohilla,", "maitotiinun tienohilla,", "maito, tiinu, tienoo", "milk-tub's, vicinity/side", ""),
    ("olutpuolikon povella,", "olutpuolikon povella,", "olut, puolikko, povi", "beer-half-keg's, bosom/side", ""),
    ("aamut aittoja avellen,", "aamut aittoja avellen,", "aamu, aitta, avata", "mornings, storehouses, opening", ""),
    ("illat luhtia lukiten.", "illat luhtia lukiten.", "ilta, luhti, lukita", "evenings, loft/storehouse, locking", ""),
    ("\"Sulhokainen, nuorukainen,", "\"Sulhokainen, nuorukainen,", "sulho, nuori", "little groom, little young one", ""),
    ("miehen kanta kaunokainen!", "miehen kanta kaunokainen!", "mies, kanta, kaunoinen", "man's, support/heel, beautiful one", ""),
    ("Kun neittä hyvin pitelet,", "Kun neittä hyvin pitelet,", "kun, neito, hyvin, pitää", "when, maiden, well, to keep", ""),
    ("niin hyväksi tunnetahan:", "niin hyväksi tunnetaan:", "niin, hyvä, tuntea", "so, good, to be known", ""),
    ("kun tulet apen kotihin,", "kun tulet apen kotiin,", "kun, tulla, appi, koti", "when, to come, father-in-law's, home", ""),
    ("luoksi ainoan anopin,", "ainoan anopin luo,", "ainoinen, anoppi, luo", "only, mother-in-law's, near", ""),
    ("itseäsi syötetähän,", "itseäsi syötetään,", "itse, syöttää", "yourself, to feed", ""),
    ("syötetähän, juotetahan,", "syötetään, juotetaan,", "syöttää, juottaa", "to feed, to give drink", ""),
    ("hevosesi riisutahan,", "hevosesi riisutaan,", "hevonen, riisua", "horse, to unharness", ""),
    ("tallihin talutetahan,", "talliin talutetaan,", "talli, taluttaa", "stable, to lead", ""),
    ("syötetähän, juotetahan,", "syötetään, juotetaan,", "syöttää, juottaa", "to feed, to give drink", ""),
    ("kauravakka kannetahan.", "kauravakka kannetaan.", "kaura, vakka, kantaa", "oat-container, to carry", ""),
    ("\"Ellös vainen neioistamme,", "\"Älä vainen neioistamme,", "älä, vain, neito", "don't, just, our maiden", ""),
    ("tätä liinalinnuistamme", "tätä liinalinnuistamme", "tämä, liinalintu", "this, our linen-bird (bride)", ""),
    ("sanoko su'uttomaksi,", "sano sukuiseksi,", "sanoa, suku", "to say, of lineage/kin", ""),
    ("laatiko lajittomaksi!", "laita lajilliseksi!", "laittaa, laji", "to make, of kind/sort", ""),
    ("Onpa tällä neiollamme", "Onpa tällä neiollamme", "olla, tämä, neito", "to be, this, our maiden", ""),
    ("suku suuri, laji laaja:", "suku suuri, laji laaja:", "suku, suuri, laji, laaja", "lineage, great, kind/sort, wide", ""),
    ("kappa ois kylveä papuja,", "kappa olisi kylveä papuja,", "kappa, olla, kylvää, papu", "a measure, to be, to sow, beans", ""),
    ("jyvä kullenki tulisi,", "jyvä kullekin tulisi,", "jyvä, kullekin, tulla", "grain, for each, to come/go", ""),
    ("kappa panna pellavaista,", "kappa panna pellavaa,", "kappa, panna, pellava", "a measure, to put, flax", ""),
    ("kuitu kullenki tulisi.", "kuitu kullekin tulisi.", "kuitu, kullekin, tulla", "fibre, for each, to come/go", ""),
    ("\"Ellös vainen, sulho rukka,", "\"Älä vainen, sulho rukka,", "älä, vain, sulho, rukka", "don't, just, groom/suitor, poor", ""),
    ("neioista pahoin pi'elkö,", "neioista pahoin pidä,", "neito, pahoin, pitää", "maiden, badly, to keep", ""),
    ("opastelko orjan ruoskin,", "opastellako orjan ruoskin,", "opastaa, orja, ruoska", "to instruct, slave's, whip", ""),
    ("nahkaruoskin nau'utelko,", "nahkaruoskin naurutella,", "nahka, ruoska, nauruttaa", "leather, whip, to make laugh/jeer at", ""),
    ("vitsoin viisin vingutelko,", "vitsoin viisin vingutelko,", "vitsa, viisi, vinguttaa", "switches, five, to make whine/whistle", ""),
    ("vajan päässä vangutelko!", "vajan päässä vangutelko!", "vaja, pää, vanguttaa", "shed's, end/head, to imprison/shake", ""),
    ("Eipä neittä ennenkänä,", "Eipä neittä ennenkään,", "ei, neito, ennen", "not, maiden, before", ""),
    ("ei ennen ison kotona", "ei ennen isän kotona", "ei, ennen, isä, koti", "not, before, father's, home", ""),
    ("opasteltu orjan ruoskin,", "opasteltu orjan ruoskin,", "opastaa, orja, ruoska", "instructed, slave's, whip", ""),
    ("nahkaruoskin nau'uteltu,", "nahkaruoskin nauruteltu,", "nahka, ruoska, nauruttaa", "leather, whip, made to laugh/jeer at", ""),
    ("vitsoin viisin vinguteltu,", "vitsoin viisin vinguteltu,", "vitsa, viisi, vinguttaa", "switches, five, made to whine/whistle", ""),
    ("vajan päässä vanguteltu.", "vajan päässä vanguteltu.", "vaja, pää, vanguttaa", "shed's, end/head, imprisoned/shaken", ""),
    ("\"Seiso seinänä e'essä,", "\"Seiso seinänä edessä,", "seistä, seinä, edessä", "to stand, wall, in front of", ""),
    ("pysy pihtipuolisena:", "pysy pihtipuolisena:", "pysyä, pihtipuoli", "to stay, door-post-like", ""),
    ("elä anna anopin lyöä", "älä anna anopin lyödä", "älä, antaa, anoppi, lyödä", "don't, to let, mother-in-law, to strike", ""),
    ("eläkä apen torua,", "äläkä apen torua,", "älä, appi, torua", "don't, father-in-law, to scold", ""),
    ("elä vierahan vihata,", "älä vierahan vihata,", "älä, vieras, vihata", "don't, stranger's, to hate", ""),
    ("talon toisen soimaella!", "talon toisen soimaella!", "talo, toinen, soimata", "house's, other, to reproach/blame", ""),
    ("Pere käski pieksämähän,", "Pere käski pieksämään,", "perhe, käskeä, piestä", "family, to order, to beat", ""),
    ("muu väki mukittamahan:", "muu väki mukittamaan:", "muu, väki, mukittaa", "other, folk/force, to pummel", ""),
    ("ethän raahi raukaistasi", "et raahi raukaistasi", "ei, raahata, raukka", "not, to drag, poor wretch", ""),
    ("etkä henno hertaistasi,", "etkä henno hertaistasi,", "ei, hennoa, herttainen", "not, to have the heart, dear one", ""),
    ("vuosin kolmin kuultuasi,", "kolmen vuoden kuultuasi,", "vuosi, kolme, kuulla", "year, three, having heard", ""),
    ("ainoisin aneltuasi!", "ainoisin aneltuasi!", "ainoinen, anella", "only one, having begged/asked for", ""),
    ("\"Neuvo, sulho, neitoasi,", "\"Neuvo, sulho, neitoasi,", "neuvoa, sulho, neito", "to advise, groom, maiden", ""),
    ("opeta omenoasi,", "opeta omenoasi,", "opettaa, omena", "to teach, apple (endearment)", ""),
    ("neuvo neittä vuotehella,", "neuvo neittä vuoteella,", "neuvoa, neito, vuode", "to advise, maiden, bed", ""),
    ("opeta oven takana,", "opeta oven takana,", "opettaa, ovi, taka", "to teach, door, behind", ""),
    ("vuosikausi kummassaki,", "vuosikausi kummassakin,", "vuosikausi, kumpainenkin", "year-season, in both", ""),
    ("yksi vuosi suusanalla,", "yksi vuosi suusanalla,", "yksi, vuosi, suusana", "one, year, word of mouth", ""),
    ("toinen silmän iskennällä,", "toinen silmän iskennällä,", "toinen, silmä, iskeä", "second, eye, winking", ""),
    ("kolmas on jalan polulla!", "kolmas on jalan polulla!", "kolmas, jalka, polku", "third, foot's, path", ""),
    ("\"Kun ei sitte siitä huoli", "\"Kun ei sitten siitä huoli", "kun, ei, sitten, siitä, huolia", "when, not, then, from that, to care", "The three-year discipline sequence — first year with words, second with eye-signals, third with foot-tapping, fourth (if necessary) with a birch rod in secret — is the singer-trickster's darkest joke: domestic violence encoded as an escalating pedagogical method."),
    ("eikä tuostana totelle,", "eikä tuostaan totelle,", "ei, tuosta, totella", "not, from that, to obey", ""),
    ("ota ruoko ruo'ostosta,", "ota ruoko ruovikosta,", "ottaa, ruoko, ruovikko", "to take, reed, reed-bed", ""),
    ("karvakorte kankahalta!", "karvakorte kankaalta!", "karvainen, korsi, kangas", "rough, stalk, heath/plain", ""),
    ("Sillä neuvo neitoasi,", "Sillä neuvo neitoasi,", "sillä, neuvoa, neito", "with that, to advise, maiden", ""),
    ("neuvo neittä neljäs vuosi,", "neuvo neittä neljäs vuosi,", "neuvoa, neito, neljäs, vuosi", "to advise, maiden, fourth, year", ""),
    ("korahuta korttehella,", "korahuta korttehella,", "korahtaa, korsi", "to startle/shake, stalk", ""),
    ("saran syrjällä syseä;", "saran syrjällä syseä;", "sara, syrjä, sysätä", "sedge's, side/edge, to push/shove", ""),
    ("viel' elä siimalla sivalla,", "vielä älä siimalla sivalla,", "vielä, älä, siima, sivaltaa", "still, don't, line/cord, to slash", ""),
    ("neittä raipalla rapoa!", "neittä raipalla rapoa!", "neito, raippa, rapoa", "maiden, strap/rod, to flog", ""),
    ("\"Vaan jos sitte siit' ei huoli,", "\"Vaan jos sitten siitä ei huoli,", "vaan, jos, sitten, siitä, huolia", "but, if, then, from that, to care", ""),
    ("viel' ei tuostana totelle,", "vielä ei tuostaan totelle,", "vielä, ei, tuosta, totella", "still, not, from that, to obey", ""),
    ("veä vitsa viiakosta,", "vedä vitsa viidakosta,", "vetää, vitsa, viidakko", "to pull, switch, thicket", ""),
    ("koivu korpinotkelmosta", "koivu korpinotkelmosta", "koivu, korpi, notkelma", "birch, wilderness, hollow/glen", ""),
    ("- tuopa turkin helman alla,", "- tuo turkin helman alla,", "tuoda, turkki, helma, alla", "to bring, fur coat's, hem, under", ""),
    ("talon toisen tietämättä - :", "talon toisen tietämättä -:", "talo, toinen, tietää", "house's, other, without knowing", ""),
    ("sitä näytä neiollesi,", "sitä näytä neidollesi,", "se, näyttää, neito", "that, to show, maiden", ""),
    ("hepäise, elä sivalla!", "hepäise, älä sivalla!", "hepäistä, ei, sivaltaa", "to flick/wave, don't, to slash", ""),
    ("\"Kun ei vielä siitä huoli,", "\"Kun ei vielä siitä huoli,", "kun, ei, vielä, siitä, huolia", "when, not, still, from that, to care", ""),
    ("ota tuostana totella,", "ota tuostaan totella,", "ottaa, tuosta, totella", "to take, from that, to obey", ""),
    ("neuvo neittä vitsasella,", "neuvo neittä vitsasella,", "neuvoa, neito, vitsa", "to advise, maiden, switch", ""),
    ("koivun oksalla opasta!", "koivun oksalla opasta!", "koivu, oksa, opastaa", "birch's, branch, to instruct", ""),
    ("Neuvo nelisnurkkaisessa,", "Neuvo nelikulmaisessa,", "neuvoa, nelikulmanen", "to advise, four-cornered (room)", ""),
    ("sano sammalhuonehessa,", "sano sammalhuoneessa,", "sanoa, sammal, huone", "to say, moss, room", ""),
    ("elä nurmella nukita,", "älä nurmella nukita,", "älä, nurmi, nukittaa", "don't, meadow, to strike/hit", ""),
    ("pieksä pellon pientarella:", "pieksä pellon pientarella:", "piestä, pelto, piennar", "to beat, field's, edge/brim", ""),
    ("kuuluisi kumu kylähän,", "kuuluisi kumu kylään,", "kuulua, kumu, kylä", "to be heard, rumble, village", ""),
    ("tora toisehen talohon,", "tora toiseen taloon,", "tora, toinen, talo", "quarrel/noise, other, house", ""),
    ("naisen itku naapurihin,", "naisen itku naapuriin,", "nainen, itku, naapuri", "woman's, crying, neighbour", ""),
    ("metsähän iso meteli.", "metsään iso meteli.", "metsä, iso, meteli", "forest, great, noise/racket", ""),
    ("\"Aina hauo hartioita,", "\"Aina hauo hartioita,", "aina, haottaa, hartia", "always, to beat/thrash, shoulders", ""),
    ("pehmitä perälihoja,", "pehmitä perälihoja,", "pehmittää, perä, liha", "to soften, back/buttocks, flesh", ""),
    ("elä silmiä sivele", "älä silmiä sivele", "älä, silmä, sivelä", "don't, eyes, to stroke/smear", ""),
    ("eläkä korvia koseta:", "äläkä korvia koseta:", "älä, korva, koskea", "don't, ears, to touch", ""),
    ("kuppi kulmalle tulisi,", "kuppi kulmalle tulisi,", "kuppi, kulma, tulla", "cup/bruise, corner, to come", ""),
    ("sinimarja silmän päälle.", "sinimarja silmän päälle.", "sinimarja, silmä, päälle", "blue-berry/bruise, eye, over", ""),
    ("Tuostapa kyty kysyisi,", "Tuostapa kyty kysyisi,", "tuosta, kyty, kysyä", "from that, sister-in-law, to ask", ""),
    ("tuosta appi arveleisi,", "tuosta appi arvelisi,", "tuosta, appi, arvella", "from that, father-in-law, to think", ""),
    ("kylän kyntäjät näkisi,", "kylän kyntäjät näkisi,", "kylä, kyntäjä, nähdä", "village's, ploughers, to see", ""),
    ("nauraisi kyläiset naiset:", "nauraisi kyläiset naiset:", "nauraa, kyläinen, nainen", "to laugh, village, women", ""),
    ("'Onko tuo soassa ollut,", "'Onko tuo sodassa ollut,", "onko, tuo, sota, olla", "is, that, war, to have been", ""),
    ("talununna tappelossa,", "tappelossa tappeltu,", "tappelu, tapella", "fight, fought", ""),
    ("vai onko suen repimä,", "vai onko suden repimä,", "vai, olla, susi, repiä", "or, to have been, wolf's, torn", ""),
    ("metsän karhun kaapaisema,", "metsän karhun kaapaisema,", "metsä, karhu, kaapata", "forest's, bear's, seized/grabbed", ""),
    ("vai susiko sulhasena,", "vai susiko sulhasena,", "vai, susi, sulhanen", "or, wolf, as groom/suitor", ""),
    ("karhu kanssakumppalina?'\"", "karhu kanssakumppanina?'\"", "karhu, kanssa, kumppani", "bear, with, companion", "The instruction on how to beat the wife — always shoulders and buttocks, never face or ears — followed by the warning that bruises on the face will make the neighbours ask if she's been in a war or mauled by a wolf, 'or was the wolf her groom and the bear her companion?' — is the trickster-singer's most disturbing moment: domestic violence as social etiquette."),
    ("Olipa ukko uunin päällä,", "Olipa ukko uunin päällä,", "olla, ukko, uuni, päällä", "to be, old man, oven, on top of", ""),
    ("mieronkierto kiukahalla.", "mieronkierto kiukaalla.", "miero, kierto, kiuas", "wanderer's, circuit, sauna stove", ""),
    ("Lausui ukko uunin päältä,", "Lausui ukko uunin päältä,", "lausua, ukko, uuni, päältä", "to utter, old man, oven, from on top of", ""),
    ("mieronkierto kiukahalta:", "mieronkierto kiukaalta:", "miero, kierto, kiuas", "wanderer's, circuit, sauna stove", ""),
    ("\"Ellös vainen, sulho rukka,", "\"Älä vainen, sulho rukka,", "älä, vain, sulho, rukka", "don't, just, groom/suitor, poor", ""),
    ("nouatelko naisen mieltä,", "nouatteleko naisen mieltä,", "nouattaa, nainen, mieli", "to pick at/follow, woman's, mind/will", ""),
    ("naisen mieltä, kiurun kieltä,", "naisen mieltä, kiurun kieltä,", "nainen, mieli, kiuru, kieli", "woman's, mind/will, skylark's, tongue", ""),
    ("kuin minä, poloinen poika!", "kuin minä, poloinen poika!", "kuin, minä, poloinen, poika", "like, I, wretched, boy", "The old man on the oven — the wanderer's-circuit man — echoing the vagrant woman's lesson in reverse: 'don't try to please women's minds as I, wretched boy, did.' He bought meat, bread, butter, beer, fish, yet got no goodness or tidiness. The trickster-sage on the oven as counter-voice to the entire bridal instruction tradition."),
    ("Lihat ostin, leivät ostin,", "Lihat ostin, leivät ostin,", "liha, ostaa, leipä, ostaa", "meat, to buy, bread, to buy", ""),
    ("voit ostin, oluet ostin,", "voit ostin, oluet ostin,", "voi, ostaa, olut, ostaa", "butter, to buy, beer/ale, to buy", ""),
    ("kalat ostin kaikenlaiset,", "kalat ostin kaikenlaiset,", "kala, ostaa, kaikenlainen", "fish, to buy, all kinds of", ""),
    ("särpimet monensukuiset,", "särpimet monensukuiset,", "särvenne, monensukuinen", "relishes/side-dishes, many kinds of", ""),
    ("oluet omilta mailta,", "oluet omilta mailta,", "olut, oma, maa", "beers/ales, own, lands", ""),
    ("vehnät mailta vierahilta.", "vehnät mailta vierahilta.", "vehnä, maa, vieras", "wheat, lands, strange/foreign", ""),
    ("\"En sillä hyveä saanut", "\"En sillä hyvää saanut", "ei, sillä, hyvä, saada", "not, with that, good, to get", ""),
    ("enkä siistiä tavannut.", "enkä siistiä tavannut.", "ei, siisti, tavata", "not, tidy/neat, to find/meet", ""),
    ("Nainen kun tuli tupahan,", "Nainen kun tuli tupaan,", "nainen, kun, tulla, tupa", "woman, when, to come, cottage/hall", ""),
    ("tuli kuin tukan repijä,", "tuli kuin tukan repijä,", "tulla, kuin, tukka, repiä", "to come, like, hair, tearer", ""),
    ("muotoansa mullistellen,", "muotoaan mullistellen,", "muoto, mullistaa", "form/face, twisting/distorting", ""),
    ("silmiänsä väännitellen;", "silmiään väännitellen;", "silmä, vääntää", "eyes, twisting", ""),
    ("aina äyhki ähmissänsä,", "aina äyhki ähmissänsä,", "aina, äyhkiä, ähmi", "always, to puff/grunt, greedily", ""),
    ("vihoissansa virkkaeli,", "vihoissaan virkkaeli,", "viha, virkata", "in anger, to say/crochet", ""),
    ("kutsui kuppeloperäksi,", "kutsui kuppeloperäksi,", "kutsua, kuppelo, perä", "to call, tub-bottom, backside", ""),
    ("haukkui halkohakkuriksi.", "haukkui halkohakkuriksi.", "haukkua, halko, hakkuri", "to bark/scold, firewood, chopper", ""),
    ("\"Jopa muistin uuen mutkan,", "\"Jopa muistin uuden mutkan,", "jo, muistaa, uusi, mutka", "already, to remember, new, bend/trick", ""),
    ("toki toisen tien osasin:", "toki toisen tien osasin:", "toki, toinen, tie, osata", "however, second, road, to know how", ""),
    ("kun kolotin koivun oksan,", "kun kolotin koivun oksan,", "kun, kolottaa, koivu, oksa", "when, to tap/knock, birch's, branch", ""),
    ("jo likisti linnuksensa;", "jo likisti linnuksensa;", "jo, likistää, lintu", "already, to press/snuggle, like a bird", ""),
    ("kun karsin katajan latvan,", "kun karsin katajan latvan,", "kun, karsia, kataja, latva", "when, to prune, juniper's, crown/top", ""),
    ("jo kumarsi kullaksensa;", "jo kumarsi kullaksensa;", "jo, kumartaa, kulta", "already, to bow, as his golden one", ""),
    ("kun vielä panin pajuilla,", "kun vielä panin pajuilla,", "kun, vielä, panna, paju", "when, still, to put, willow-switches", ""),
    ("jo kapusi kaulahani.\"", "jo kapusi kaulaani.\"", "jo, kavuta, kaula", "already, to climb, neck", "The old man on the oven confessing his own trickster-solution — when I tapped a birch branch she snuggled like a bird; when I pruned a juniper top she bowed as my golden one; when I laid on the willow-switches she climbed my neck — is the darkest comedy of the whole instruction sequence: the ultimate 'wisdom' is that only the threat of violence produces affection."),
    ("Neito parka huokaiseikse,", "Neito parka huokailee,", "neito, parka, huokailla", "maiden, poor/wretched, to sigh", ""),
    ("huokaiseikse, henkäiseikse,", "huokailee, hengäilee,", "huokailla, hengäillä", "to sigh, to breathe", ""),
    ("itse itkulle hyräytyi.", "itse itkulle hyräytyi.", "itse, itku, hyräytyä", "herself, crying, to hum/drift into", ""),
    ("Sanan virkkoi, noin nimesi:", "Sanan virkkoi, noin nimitti:", "sana, virkkoa, nimittää", "word, to say, to name/call", ""),
    ("\"Lässäp' on nyt muien lähtö,", "\"Lähellä on nyt muiden lähtö,", "lähellä, nyt, muu, lähtö", "near, now, others', departure", ""),
    ("liki saanut muien liitto,", "lähelle saanut muiden liitto,", "lähelle, saada, muu, liitto", "near, gotten, others', union/bond", ""),
    ("minun lähtöni lähemmä,", "minun lähtöni lähempi,", "minä, lähtö, lähempi", "my, departure, nearer", ""),
    ("minun liittoni likemmä,", "minun liittoni lähempänä,", "minä, liitto, lähempänä", "my, union/bond, closer", ""),
    ("vaikk' on läyli lähteäki,", "vaikka on kova lähteäkin,", "vaikka, kova, lähteä", "even though, hard, to set out", ""),
    ("erota tukala tunti", "erota tukala tunti", "erotaa, tukala, tunti", "to separate, difficult, hour", ""),
    ("tästä kuulusta kylästä,", "tästä kuulusta kylästä,", "tästä, kuulu, kylä", "from this, renowned, village", ""),
    ("kaunihista kartanosta,", "kauniista kartanosta,", "kaunis, kartano", "beautiful, estate/yard", ""),
    ("jossa kasvoin kaunihisti,", "jossa kasvoin kauniisti,", "jossa, kasvaa, kauniisti", "where, to grow, beautifully", ""),
    ("ylenin ylen ehosti", "ylenin ylen ehosti", "yletä, ylen, ehosti", "to rise, very, elegantly", ""),
    ("kaiken kasvantoikäni,", "kaiken kasvantoikäni,", "kaikki, kasvu, ikä", "all, growth, age/time", ""),
    ("lapsipuolen polveani.", "lapsipuolen polveani.", "lapsi, puoli, polvi", "child, half/side, generation/knee", ""),
    ("\"Enkä tuota ennen luullut", "\"Enkä tuota ennen luullut", "ei, tuo, ennen, luulla", "not, that, before, to think/suppose", ""),
    ("enkä uskonut ikänä,", "enkä uskonut ikänä,", "ei, uskoa, ikänä", "not, to believe, ever", ""),
    ("en mä luullut luopuvani,", "en minä luullut luopuvani,", "ei, minä, luulla, luopua", "not, I, to think/suppose, to give up/leave", ""),
    ("uskonut eroavani", "uskonut eroavani", "uskoa, erotaa", "to believe, to separate", ""),
    ("tämän linnan liepeheltä,", "tämän linnan liepeeltä,", "tämä, linna, liepe", "this, castle/hall, edge/hem", ""),
    ("tämän harjun hartiolta.", "tämän harjun hartiolta.", "tämä, harju, hartia", "this, esker/ridge, shoulder", ""),
    ("Jo nyt luulen, jotta luovun,", "Jo nyt luulen, että luovun,", "jo, nyt, luulla, jotta, luopua", "already, now, to think/suppose, that, to give up/leave", ""),
    ("jopa uskon ja eroan:", "jo uskon ja eroan:", "jo, uskoa, ja, erotaa", "already, to believe, and, to separate", ""),
    ("ero- on tuopit tyhjettynä,", "ero- on tuopit tyhjettynä,", "ero, tuoppi, tyhjentää", "departure, tankards/mugs, emptied", ""),
    ("ero- juotuna oluet,", "ero- juotuna oluet,", "ero, juoda, olut", "departure, drunk, beers/ales", ""),
    ("kohta korjat käännettynä", "kohta korjat käännettynä", "kohta, korja, kääntää", "soon, sleighs, turned", ""),
    ("päin ulos, perin tupahan,", "päin ulos, perät tupaan,", "päin, ulos, perä, tupa", "facing, out, backs/sterns, cottage/hall", ""),
    ("lappe'in ison latohon,", "lappeelleen isoon latoon,", "lappeelleen, iso, lato", "on their side, great, barn", ""),
    ("kalten karjahuonehesen.", "kalten karjahuoneeseen.", "kalten, karja, huone", "tilted/askew, cattle, room", ""),
    ("\"Millä nyt erotessani,", "\"Millä nyt erotessani,", "millä, nyt, erotaa", "with what, now, while separating", ""),
    ("lähtiessäni, katala,", "lähtiessäni, katala,", "lähteä, katala", "while setting out, evil/base", ""),
    ("millä maksan maammon maion", "millä maksan äidin maidon", "millä, maksaa, äiti, maito", "with what, to pay, mother's, milk", ""),
    ("sekä taattoni hyvyyen,", "sekä isäni hyvyyden,", "sekä, isä, hyvyys", "and, father's, goodness/wealth", ""),
    ("millä veikon armauen,", "millä veikon armauden,", "millä, veikko, armaus", "with what, brother's, grace/dearness", ""),
    ("mielisiivot siskoseni?", "mielisiedon siskoni?", "mielisiivo, sisar", "decorous/kind, my sister", ""),
    ("\"Kiitän mä, iso, sinua", "\"Kiitän minä, isä, sinua", "kiittää, minä, isä, sinä", "to thank/praise, I, father, you", ""),
    ("entisistäni eloista,", "entisistä eloistani,", "entinen, elo", "former, livelihoods/lives", ""),
    ("murkinoista muinaisista,", "murkinoista muinaisista,", "murkina, muinainen", "meals, ancient/former", ""),
    ("parahimmista paloista.", "parhaimmista paloista.", "paras, pala", "best, pieces/portions", ""),
    ("\"Kiitän mä, emo, sinua", "\"Kiitän minä, äiti, sinua", "kiittää, minä, äiti, sinä", "to thank/praise, I, mother, you", ""),
    ("nuorna tuuiteltuasi,", "nuorena tuudittelustasi,", "nuori, tuudittaa", "young, rocking/lulling", ""),
    ("pienoisna pi'eltyäsi,", "pienenä pitämisestäsi,", "pieni, pitää", "small, keeping", ""),
    ("rinnoin ruokkieltuasi.", "rinnoilla ruokkimisestasi.", "rinta, ruokkia", "breasts, feeding/nurturing", ""),
    ("\"Vielä kiitän veikkoseni,", "\"Vielä kiitän veljeäni,", "vielä, kiittää, veli", "still, to thank/praise, brother", ""),
    ("veikkoseni, siskoseni,", "veljeäni, sisareni,", "veli, sisar", "my brother, my sister", ""),
    ("kostelen koko perehen,", "kostelen koko perheen,", "kostella, koko, perhe", "to repay, whole, family", ""),
    ("kaikki kasvinkumppalini,", "kaikki kasvinkumppanini,", "kaikki, kasvi, kumppani", "all, growing-place, companions", ""),
    ("joien joukossa elelin,", "joiden joukossa elelin,", "joiden, joukko, elellä", "whose, crowd, to live along", ""),
    ("kasvoin kanssa kasvinaian.", "kasvoin kanssa kasvinajan.", "kasvaa, kanssa, kasvinaika", "to grow, with, growing-time", "The bride's formal thanksgiving — to father for former livelihood, to mother for nursing and rocking, to brother and sister and all her growing-companions — is the trickster-singer's ceremonial close to the bridal instruction tradition. The giving of thanks is itself a kind of payment."),
    ("\"Ellös nyt, hyvä isoni,", "\"Älkää nyt, hyvä isäni,", "älkää, nyt, hyvä, isä", "don't, now, good, father", ""),
    ("ellös, ehtoinen emoni,", "älkää, ehtoinen äitini,", "älkää, ehtoinen, äiti", "don't, prosperous/noble, mother", ""),
    ("tahi muu sukuni suuri,", "tahi muu sukuni suuri,", "tahi, muu, suku, suuri", "or, other, lineage, great", ""),
    ("heimokuntani heleä,", "heimokuntani heleä,", "heimokunta, heleä", "kinship-group, radiant/clear", ""),
    ("tuosta huolelle ruvetko,", "tuosta huolelle ryhtykää,", "tuosta, huoli, ryhtyä", "from that, worry, to begin", ""),
    ("saako suurelle surulle,", "saako suurelle surulle,", "saako, suuri, suru", "nor, great, grief", ""),
    ("jos menenki muille maille,", "jos menenkin muille maille,", "jos, mennä, muu, maa", "if, to go, other, lands", ""),
    ("kulkenen johonkuhunki!", "kulkenen jonnekin!", "kulkea, jonnekin", "to travel, somewhere", ""),
    ("Paistanevi Luojan päivä,", "Paistaa Luojan päivä,", "paistaa, Luoja, päivä", "to shine, Creator's, sun/day", ""),
    ("kuu Luojan kumottanevi,", "kuu Luojan kumottaa,", "kuu, Luoja, kumottaa", "moon, Creator's, to gleam/reflect", ""),
    ("tähet taivon välkynevi,", "tähdet taivaan välkkyvät,", "tähti, taivas, välkkyä", "stars, sky's, to glitter/flash", ""),
    ("otavat ojentunevi", "Otavat ojentuvat", "Otava, ojentua", "Great Bears, to stretch out", ""),
    ("ilmassa etempänäki,", "ilmassa etempänäkin,", "ilma, etempänä", "sky/world, further away too", ""),
    ("maailmassa muuallaki,", "maailmassa muuallakin,", "maailma, muualla", "world, elsewhere", ""),
    ("ei yksin ison pihoilla,", "ei yksin isän pihoilla,", "ei, yksin, isä, piha", "not, only, father's, yards", ""),
    ("näillä kasvinkartanoilla.", "näillä kasvinkartanoilla.", "tämä, kasvi, kartano", "these, growing-place, estates/yards", ""),
    ("\"Lähen nyt tästä kuin lähenki,", "\"Lähden nyt tästä kuin lähdenkkin,", "lähteä, nyt, tästä", "to set out, now, from here", ""),
    ("tästä kullasta ko'ista,", "tästä kullasta kodista,", "tästä, kulta, koti", "from this, golden, home", ""),
    ("ison saamasta salista,", "isän saamasta salista,", "isä, saada, sali", "father's, gotten, hall", ""),
    ("äitin kestikellarista.", "äitin kestikellarista.", "äiti, kesti, kellari", "mother's, guest, cellar", ""),
    ("Heitän suoni, heitän maani,", "Heitän suoni, heitän maani,", "heittää, suo, maa", "to throw away, swamp, land", ""),
    ("heitän heinikkopihani,", "heitän heinikkopihani,", "heittää, heinikko, piha", "to throw away, grass-yard", ""),
    ("heitän valkeat veteni,", "heitän valkeat veteni,", "heittää, valkea, vesi", "to throw away, white/clear, waters", ""),
    ("heitän hiekkarantaseni", "heitän hiekkarantaseni", "heittää, hiekka, ranta", "to throw away, sandy, shore", ""),
    ("kylpeä kylän akoille,", "kylpeä kylän naisille,", "kylpeä, kylä, nainen", "to bathe, village's, women", ""),
    ("pasikoia paimenille.", "pasikoja paimenille.", "pasiko, paimen", "water-puddles, shepherds", ""),
    ("\"Heitän suot sorehtijoille,", "\"Heitän suot sorehtijoille,", "heittää, suo, sorsia", "to throw away, swamps, those hunting ducks", ""),
    ("maat heitän maleksijoille,", "maat heitän maleksijille,", "heittää, maa, maleksia", "to throw away, lands, wanderers", ""),
    ("lepiköt lepeäjille,", "lepiköt lepeäjille,", "lepikko, levätä", "alder-groves, resters", ""),
    ("kanervikot kaahlajille,", "kanervikot kaahlajille,", "kanervikko, kahlata", "heather-thickets, waders", ""),
    ("aitavieret astujille,", "aitavieret astujille,", "aita, vieri, astua", "fence-sides, steppers/walkers", ""),
    ("kujavarret kulkijoille,", "kujavarret kulkijoille,", "kuja, varsi, kulkea", "lane-stalks, travellers", ""),
    ("pihat pitkin juoksijoille,", "pihat pitkin juoksijoille,", "piha, pitkin, juosta", "yards, along, runners", ""),
    ("seinävieret seisojille,", "seinävieret seisojille,", "seinä, vieri, seistä", "wall-sides, standers", ""),
    ("siltalauat siivojille,", "siltalauat siivojille,", "silta, lauta, siivota", "bridge-planks, cleaners", ""),
    ("lattiat lakasijoille.", "lattiat lakasijoille.", "lattia, lakasta", "floors, sweepers", "The bride's formal leave-taking of the land — giving swamps to duck-hunters, lands to wanderers, alder-groves to resters, heather to waders, lanes to travellers, yards to runners, walls to standers, bridges to cleaners, floors to sweepers, fields to deer, forests to lynx, clearings to geese, groves to birds — is one of the most beautiful extended farewell catalogues in the epic."),
    ("Pellot heitän peuran juosta,", "Pellot heitän peuran juosta,", "heittää, pelto, peura, juosta", "to throw away, fields, deer, to run", ""),
    ("salot ilveksen samota,", "salot ilveksen samota,", "heittää, salo, ilves, samota", "to throw away, wildernesses, lynx, to wade", ""),
    ("ahot hanhien asua,", "ahot hanhien asua,", "heittää, aho, hanhi, asua", "to throw away, clearings, geese, to dwell", ""),
    ("lehot lintujen levätä.", "lehot lintujen levätä.", "heittää, lehto, lintu, levätä", "to throw away, groves, birds, to rest", ""),
    ("\"Lähen tästä kuin lähenki", "\"Lähden tästä kuin lähdenkkin", "lähteä, tästä", "to set out, from here", ""),
    ("toisen lähtijän keralla", "toisen lähtijän keralla", "toinen, lähtijä, keralla", "another's, one departing, with", ""),
    ("sykysyisen yön sylihin,", "syysyisen yön syliin,", "syysyinen, yö, syli", "autumnal, night's, embrace", ""),
    ("kevä'isen kierän päälle,", "keväisen kierran päälle,", "keväinen, kierto, päälle", "spring's, spinning/turning, over", ""),
    ("jottei jälki jäällä tunnu,", "jottei jälki jäällä tunnu,", "jottei, jälki, jää, tuntua", "so that not, track, ice, to feel", ""),
    ("jalan isku iljangolla,", "jalan isku liukkaalla,", "jalka, isku, liukas", "foot's, strike, slippery", ""),
    ("hangella hamosen toimi,", "hangella hamosen toimi,", "hanki, hame, toimi", "snowdrift, skirt's, action", ""),
    ("helman hiepsintä lumella.", "helman hiepsintä lumella.", "helma, hiepsintä, lumi", "hem's, brushing, snow", ""),
    ("\"Sitte toiste tultuani,", "\"Sitten toiste tultuani,", "sitten, toiste, tulla", "then, again, having come", ""),
    ("kotihini käytyäni", "kotiini käytyäni", "koti, käydä", "home, having visited", ""),
    ("eipä äiti ääntä kuulle,", "eipä äiti ääntä kuule,", "ei, äiti, ääni, kuulla", "not, mother, voice, to hear", ""),
    ("iso ei itkua tajunne,", "isä ei itkua tajua,", "ei, isä, itku, tajuta", "not, father, crying, to perceive", ""),
    ("jos ma kulmilla kujerran,", "jos minä kulmilla kujerran,", "jos, minä, kulma, kujertaa", "if, I, corner, to twitter/warble", ""),
    ("päälaella laulattelen:", "päälaella laulattelen:", "päälaki, laulattaa", "crown of head, to make sing", ""),
    ("jo on nousnut nuori nurmi,", "jo on noussut nuori nurmi,", "jo, olla, nousta, nuori, nurmi", "already, to have, risen, young, meadow", ""),
    ("kasvanut katajapehko", "kasvanut katajapehko", "kasvaa, kataja, pehko", "to have grown, juniper, thicket", ""),
    ("iholle imettäjäni,", "iholle imettäjäni,", "iho, imettäjä", "skin, nurse/suckling-mother's", ""),
    ("kasvopäille kantajani.", "kasvopäille kantajani.", "kasvot, kantaja", "face, bearer/carrier's", ""),
    ("\"Minun toiste tullessani", "\"Minun toiste tullessani", "minä, toiste, tulla", "my, again, while coming", ""),
    ("näille pitkille pihoille", "näille pitkille pihoille", "tämä, pitkä, piha", "these, long, yards", ""),
    ("muut ei tuntene minua", "muut ei tunne minua", "muu, ei, tuntea, minä", "others, not, to know, me", ""),
    ("kuin ne kaksi kappaletta:", "kuin ne kaksi kappaletta:", "kuin, ne, kaksi, kappale", "like, those, two, pieces", ""),
    ("alimainen aian vitsa,", "alimainen aidan vitsa,", "alimainen, aita, vitsa", "lowest, fence's, twig/switch", ""),
    ("perimäinen pellon seiväs,", "perimäinen pellon seiväs,", "perimäinen, pelto, seiväs", "most distant, field's, pole/stake", ""),
    ("nuo on piennä pistämäni,", "nuo on pienenä pistämäni,", "tuo, olla, pieni, pistää", "those, to have been, small, stuck/planted", ""),
    ("neitona vitsastamani.", "neitona vitsastamani.", "neito, vitsoittaa", "while a maiden, woven/tied", "The bride's farewell vision: when she returns as a visitor only the lowest fence-twig and the furthest field-pole will know her, things she planted as a child. Even the horse, cow, and dog that she fed as a girl will recognise her — but the human world will have forgotten her."),
    ("\"Emoni mahova lehmä,", "\"Äitini mahova lehmä,", "äiti, mahova, lehmä", "mother's, pregnant/big, cow", ""),
    ("minun nuorna juottamani,", "minun nuorena juottamani,", "minä, nuori, juottaa", "my, young, given to drink", ""),
    ("vasikkana vaalimani,", "vasikkana vaalimani,", "vasikka, vaalia", "as a calf, tended/nurtured", ""),
    ("ammoa rikottelevi", "ammoa rikottelee", "ammua, rikotella", "to moo, to break out", ""),
    ("pitkillä piharikoilla,", "pitkillä pihapolulla,", "pitkä, piha, polku", "long, yard-path", ""),
    ("talvisilla tanterilla:", "talvisilla tanterilla:", "talvinen, tanner", "winter's, ground/field", ""),
    ("tuo minua tuntenevi", "tuo minua tuntee", "tuo, minä, tuntea", "that, me, to know", ""),
    ("kotoiseksi tyttäreksi.", "kotoiseksi tyttäreksi.", "kotoinen, tytär", "homely, daughter", ""),
    ("\"Isoni ikioronen,", "\"Isäni ikuinen ori,", "isä, ikuinen, ori", "father's, eternal, stallion", ""),
    ("minun piennä syöttämäni,", "minun pienenä syöttämäni,", "minä, pieni, syöttää", "my, small, fed", ""),
    ("neitona apattamani,", "neitona ruokkimani,", "neito, ruokkia", "while a maiden, fed/nurtured", ""),
    ("hirnua rikottelevi", "hirnua rikottelee", "hirnua, rikotella", "to neigh, to break out", ""),
    ("pitkillä piharikoilla,", "pitkillä pihapolulla,", "pitkä, piha, polku", "long, yard-path", ""),
    ("talvisilla tanterilla:", "talvisilla tanterilla:", "talvinen, tanner", "winter's, ground/field", ""),
    ("tuntenevi tuo minua", "tuntee tuo minua", "tuntea, tuo, minä", "to know, that, me", ""),
    ("kotoiseksi tyttäreksi.", "kotoiseksi tyttäreksi.", "kotoinen, tytär", "homely, daughter", ""),
    ("\"Veikkoni ikuinen koira,", "\"Veljeni ikuinen koira,", "veli, ikuinen, koira", "brother's, eternal, dog", ""),
    ("minun lasna syöttämäni,", "minun lapsena syöttämäni,", "minä, lapsi, syöttää", "my, as a child, fed", ""),
    ("neitona opastamani,", "neitona opastamani,", "neito, opastaa", "while a maiden, instructed/trained", ""),
    ("haukkua rikottelevi", "haukkua rikottelee", "haukkua, rikotella", "to bark, to break out", ""),
    ("pitkillä piharikoilla,", "pitkillä pihapolulla,", "pitkä, piha, polku", "long, yard-path", ""),
    ("talvisilla tanterilla:", "talvisilla tanterilla:", "talvinen, tanner", "winter's, ground/field", ""),
    ("tuo minua tuntenevi", "tuo minua tuntee", "tuo, minä, tuntea", "that, me, to know", ""),
    ("kotoiseksi tyttäreksi.", "kotoiseksi tyttäreksi.", "kotoinen, tytär", "homely, daughter", ""),
    ("\"Muut ne ei minua tunne", "\"Muut ei minua tunne", "muu, ei, minä, tuntea", "others, not, me, to know", ""),
    ("kotihini tultuani,", "kotiini tultuani,", "koti, tulla", "home, having come", ""),
    ("vaikk' on vanhat valkamani,", "vaikka on vanhat valkamani,", "vaikka, vanha, valkama", "even though, old, harbours/landings", ""),
    ("entiset elosijani,", "entiset elopaikkani,", "entinen, elo, paikka", "former, life/livelihood, places", ""),
    ("sijoillansa siikasalmet,", "sijoillaan siikasalmet,", "sija, siika, salmi", "in their places, whitefish, straits", ""),
    ("asemillansa apajat...", "asemillaan apajat...", "asema, apaja", "in their positions, fishing-places", ""),
    ("\"Jää nyt, pirtti, terveheksi,", "\"Jää nyt, pirtti, terveeksi,", "jäädä, nyt, pirtti, terve", "to remain, now, cottage, healthy/farewell", ""),
    ("pirtti lautakattoinesi!", "pirtti lautakattoinesi!", "pirtti, lauta, katto", "cottage, plank, roof", ""),
    ("Hyvä on toiste tullakseni,", "Hyvä on toiste tullakseni,", "hyvä, toiste, tulla", "good, again, to come", ""),
    ("kaunis kaaputellakseni.", "kaunis kaaputellakseni.", "kaunis, kaaputella", "beautiful, to visit/wander to", ""),
    ("\"Jää nyt, sintsi, terveheksi,", "\"Jää nyt, eteinen, terveeksi,", "jäädä, nyt, eteinen, terve", "to remain, now, entrance hall, healthy/farewell", ""),
    ("sintsi lautasiltoinesi!", "eteinen lautasiltoinesi!", "eteinen, lauta, silta", "entrance hall, plank, bridge/floor", ""),
    ("Hyvä on toiste tullakseni,", "Hyvä on toiste tullakseni,", "hyvä, toiste, tulla", "good, again, to come", ""),
    ("kaunis kaaputellakseni.", "kaunis kaaputellakseni.", "kaunis, kaaputella", "beautiful, to visit/wander to", ""),
    ("\"Jääpä, piha, terveheksi,", "\"Jää, piha, terveeksi,", "jäädä, piha, terve", "to remain, yard, healthy/farewell", ""),
    ("piha pihlajaisinesi!", "piha pihlajaisinesi!", "piha, pihlaja", "yard, with your rowans", ""),
    ("Hyvä on toiste tullakseni,", "Hyvä on toiste tullakseni,", "hyvä, toiste, tulla", "good, again, to come", ""),
    ("kaunis kaaputellakseni.", "kaunis kaaputellakseni.", "kaunis, kaaputella", "beautiful, to visit/wander to", ""),
    ("\"Jätän kaikki terveheksi:", "\"Jätän kaikki terveeksi:", "jättää, kaikki, terve", "to leave, all, healthy/farewell", ""),
    ("maat ja metsät marjoinensa,", "maat ja metsät marjoinensa,", "maa, metsä, marja", "lands, forests, with their berries", ""),
    ("kujavieret kukkinensa,", "kujavieret kukkinensa,", "kuja, vieri, kukka", "lane-sides, with their flowers", ""),
    ("kankahat kanervinensa,", "kankahat kanervinensa,", "kangas, kanerva", "heaths/plains, with their heather", ""),
    ("järvet saoin saarinensa,", "järvet saoin saarinensa,", "järvi, sata, saari", "lakes, with their hundred islands", ""),
    ("syvät salmet siikoinensa,", "syvät salmet siikoinensa,", "syvä, salmi, siika", "deep, straits, with their whitefish", ""),
    ("hyvät kummut kuusinensa,", "hyvät kummut kuusinensa,", "hyvä, kumpu, kuusi", "good, mounds, with their spruces", ""),
    ("korpinotkot koivuinensa.\"", "korpinotkot koivuinensa.\"", "korpi, notkelma, koivu", "wilderness-hollows, with their birches", ""),
    ("Silloin seppo Ilmarinen", "Silloin seppä Ilmarinen", "silloin, seppä, Ilmarinen", "then, smith, Ilmarinen", ""),
    ("koppoi neien korjahansa,", "koppasi neidon korjaansa,", "kopata, neito, korja", "to grab/catch, maiden, into the sleigh", ""),
    ("iski virkkua vitsalla,", "iski virkkua vitsalla,", "iskeä, virkku, vitsa", "to strike, lively one, with a switch", ""),
    ("sanan virkkoi, noin nimesi:", "sanan virkkoi, noin nimitti:", "sana, virkkoa, nimittää", "word, to say, to name/call", ""),
    ("\"Jää hyvästi, järven rannat,", "\"Jää hyvästi, järven rannat,", "jäädä, hyvästi, järvi, ranta", "to remain, farewell, lake's, shores", ""),
    ("järven rannat, pellon penkat,", "järven rannat, pellon penkat,", "järvi, ranta, pelto, penkka", "lake's, shores, field's, banks", ""),
    ("kaikki mäntyset mäellä,", "kaikki männyt mäellä,", "kaikki, mänty, mäki", "all, pines, hill", ""),
    ("puut pitkät petäjikössä,", "puut pitkät petäjikössä,", "puu, pitkä, petäjikkö", "trees, long, pine-grove", ""),
    ("tuomikko tuvan takana,", "tuomikko tuvan takana,", "tuomi, tupa, taka", "bird-cherry grove, cottage, behind", ""),
    ("katajikko kaivotiellä,", "katajikko kaivotiellä,", "kataja, kaivo, tie", "juniper thicket, well-road", ""),
    ("kaikki maassa marjan varret,", "kaikki maassa marjan varret,", "kaikki, maa, marja, varsi", "all, earth, berry, plant/stalk", ""),
    ("marjan varret, heinän korret,", "marjan varret, heinän korret,", "marja, varsi, heinä, korsi", "berry, plant/stalk, hay, stalk", ""),
    ("pajupehkot, kuusen juuret,", "pajupehkot, kuusen juuret,", "paju, pehko, kuusi, juuri", "willow-thickets, spruce's, roots", ""),
    ("lepän lehvät, koivun kuoret!\"", "lepän lehvät, koivun kuoret!\"", "leppä, lehvä, koivu, kuori", "alder's, branches/fronds, birch's, bark", "Ilmarinen's farewell to the landscape — lake shores, field banks, pines on the hill, bird-cherry grove behind the cottage, juniper thicket on the well-road, all berry-stalks, hay-stalks, willow-thickets, spruce roots, alder fronds, birch bark — mirrors the bride's own farewell catalogue, the craftsman-trickster briefly revealing the same elegiac tenderness."),
    ("Siinä seppo Ilmarinen", "Siinä seppä Ilmarinen", "siinä, seppä, Ilmarinen", "there, smith, Ilmarinen", ""),
    ("läksi Pohjolan pihoilta.", "läksi Pohjolan pihoilta.", "lähteä, Pohjola, piha", "to set out, Northland's, yards", ""),
    ("Jäivät lapset laulamahan;", "Jäivät lapset laulamaan;", "jäädä, lapsi, laulaa", "to remain, children, to sing", ""),
    ("lapset lauloi jotta lausui:", "lapset lauloivat ja lausuivat:", "lapsi, laulaa, lausua", "children, to sing, to utter", ""),
    ("\"Lenti tänne musta lintu,", "\"Lensi tänne musta lintu,", "lentää, tänne, musta, lintu", "to fly, here, black, bird", ""),
    ("läpi korven koikutteli,", "läpi korven koikutteli,", "läpi, korpi, koikutella", "through, wilderness, to clamour/cry", ""),
    ("suostutteli meiltä sorsan,", "suostutteli meiltä sorsan,", "suostuttaa, meiltä, sorsa", "to persuade, from us, duck", ""),
    ("maanitteli meiltä marjan,", "maanitteli meiltä marjan,", "maanittaa, meiltä, marja", "to entice, from us, berry", ""),
    ("otti tuo omenan meiltä,", "otti tuo omenan meiltä,", "ottaa, tuo, omena, meiltä", "to take, that, apple, from us", ""),
    ("vietteli ve'en kalasen,", "vietteli veden kalasen,", "vietellä, vesi, kala", "to seduce/entice, water's, fish", ""),
    ("petti pienillä rahoilla,", "petti pienillä rahoilla,", "pettää, pieni, raha", "to deceive, small, money", ""),
    ("hope'illa houkutteli.", "hopeilla houkutteli.", "hopea, houkutella", "silver, to lure/entice", "The children left behind singing — 'a black bird flew here through the wilderness, persuaded our duck away, enticed our berry, took our apple, lured our water-fish, deceived with small money, lured with silver; who will take us to the water now?' — is the trickster-children's lament: the bride was their caretaker and now the household machinery stops."),
    ("Ken nyt vie ve'elle meitä,", "Ken nyt vie vedelle meitä,", "ken, nyt, viedä, vesi, me", "who, now, to take, water, us", ""),
    ("ken joelle juohattavi?", "ken joelle juohattaa?", "ken, joki, juohattaa", "who, river, to lead/take", ""),
    ("Saapi saavit seistäksensä,", "Saavat saavit seistäksensä,", "saada, saavi, seistä", "to get, tubs/buckets, to stand", ""),
    ("kolataksensa korennot,", "kolatakseen korennot,", "kolata, korento", "to rot, carrying-yokes", ""),
    ("olla sillat siivomatta,", "olla sillat siivomatta,", "olla, silta, siivota", "to be, bridges, uncleaned", ""),
    ("lattiat lakaisematta,", "lattiat lakaisematta,", "lattia, lakasta", "floors, unswept", ""),
    ("pinttyä pikarin laiat,", "pinttyä pikarin laiat,", "pinttyä, pikari, laita", "to get encrusted, cup's, sides", ""),
    ("tuopin korvat tummentua.", "tuopin korvat tummentua.", "tuoppi, korva, tummua", "tankard's, handles, to darken", ""),
    ("Itse seppo Ilmarinen", "Itse seppä Ilmarinen", "itse, seppä, Ilmarinen", "himself, smith, Ilmarinen", ""),
    ("nuoren neitonsa keralla", "nuoren neitonsa keralla", "nuori, neito, keralla", "young, maiden's, with", ""),
    ("ajoa kahuttelevi", "ajaa kahuttelee", "ajaa, kahutella", "to drive, to speed/rush", ""),
    ("noita Pohjan rannikoita,", "noita Pohjan rannikoita,", "tuo, Pohja, rannikko", "those, North's, coasts/shores", ""),
    ("simasalmien sivutse,", "simasalmien sivutse,", "sima, salmi, sivutse", "honey-strait's, past/beside", ""),
    ("hietaharjun hartioitse.", "hietaharjun hartioitse.", "hiekka, harju, hartia", "sandy, esker/ridge, shoulders", ""),
    ("Somer soitti, hiekka helkki,", "Somer soitti, hiekka helkki,", "somero, soittaa, hiekka, helkkää", "gravel, to sound, sand, to jingle", ""),
    ("reki vieri, tie vilisi,", "reki vieri, tie vilisi,", "reki, vierähtää, tie, vilistä", "sled, to roll/glide, road, to rush/speed", ""),
    ("rahe rautainen ramasi,", "rahe rautainen ramasi,", "rahe, rautainen, ramata", "runner, iron, to thunder", ""),
    ("jalas koivuinen kolasi,", "jalas koivuinen kolasi,", "jalas, koivuinen, kolata", "sled-runner, birch, to creak/rattle", ""),
    ("kapla patvinen pasasi,", "kapla patvinen pasasi,", "kapla, patvinen, pasata", "swingletree-pin, firm, to creak/crack", ""),
    ("vemmel tuominen tutasi,", "vemmel tuominen tutasi,", "vempele, tuomi, tutista", "swingletree, bird-cherry, to rattle/vibrate", ""),
    ("vinkui vitsaiset saverkot,", "vinkui vitsaiset saverkot,", "vinkahtaa, vitsainen, saverkko", "to whine/squeal, twig-made, shaft-bow", ""),
    ("vapoi vaskirenkahaiset", "vapoi vaskirenkahaiset", "vapista, vaski, rengas", "to tremble/shake, copper/bronze, rings", ""),
    ("juostessa hyvän hevosen,", "juostessa hyvän hevosen,", "juosta, hyvä, hevonen", "while running, good, horse", ""),
    ("hyvän laukin laukatessa.", "hyvän laukin laukatessa.", "hyvä, laukki, laukata", "good, steed, while galloping", ""),
    ("Ajoi päivän, tuosta toisen,", "Ajoi päivän, tuosta toisen,", "ajaa, päivä, tuosta, toinen", "to drive, day, from that, second", ""),
    ("ajoi kohta kolmannenki,", "ajoi kohta kolmannenkin,", "ajaa, kohta, kolmas", "to drive, soon, third too", ""),
    ("käsi ohjassa orosen,", "käsi ohjassa orin,", "käsi, ohjake, ori", "hand, in the reins, stallion's", ""),
    ("toinen neien kainalossa,", "toinen neidon kainalossa,", "toinen, neito, kainalos", "other, maiden's, armpit", ""),
    ("jalka laialla rekosen,", "jalka laidalla rekosen,", "jalka, laita, reki", "foot, side, sled", ""),
    ("jalka toinen viltin alla.", "jalka toinen viltin alla.", "jalka, toinen, vilttu", "foot, other, blanket, under", ""),
    ("Virkku juoksi, matka joutui,", "Virkku juoksi, matka joutui,", "virkku, juosta, matka, joutua", "lively one, to run, journey, to progress", ""),
    ("päivä vieri, tie lyheni.", "päivä vieri, tie lyheni.", "päivä, vierähtää, tie, lyhentyä", "day, to roll, road, to shorten", ""),
    ("Päivänäpä kolmantena", "Päivänäpä kolmantena", "päivä, kolmas", "on the day, third", ""),
    ("aletessa aurinkoisen", "aletessa aurinkoisen", "aletessa, aurinkoinen", "while lowering/setting, sunny", ""),
    ("jo sepon koti näkyvi,", "jo seppän koti näkyy,", "jo, seppä, koti, näkyä", "already, smith's, home, to be seen", ""),
    ("tuvat Ilman tuulottavi.", "tuvat ilmassa tuulettavat.", "tupa, ilma, tuulettaa", "cottages, sky/air, to air/ventilate", ""),
    ("Noki nousi nuoraisena,", "Noki nousi nuoraisena,", "noki, nousta, nuorainen", "soot, to rise, youthfully/freshly", ""),
    ("savu paksuna pakeni,", "savu paksuna pakeni,", "savu, paksu, paeta", "smoke, thick, to flee/rise", ""),
    ("tuprusi savu tuvasta,", "tuprusi savu tuvasta,", "tupruaa, savu, tupa", "to puff/billow, smoke, cottage/hall", ""),
    ("ylös pilvihin kohosi.", "ylös pilviin kohosi.", "ylös, pilvi, kohota", "up, clouds, to rise", "Ilmarinen and the bride arriving home on the third day — smoke billowing from the cottage, the sled runners thundering on the iron runners, birch sled-boards creaking, copper rings trembling — is the craftsman-trickster finally arriving at his own hearth. The smoke rising young and thick to the clouds is the house welcoming its new mistress."),
]

thin_border = Border(
    left=Side(style='thin', color='CCCCCC'),
    right=Side(style='thin', color='CCCCCC'),
    top=Side(style='thin', color='CCCCCC'),
    bottom=Side(style='thin', color='CCCCCC')
)
fill_even = PatternFill("solid", start_color="F7F3E9")
fill_odd  = PatternFill("solid", start_color="FFFFFF")
fill_trickster = PatternFill("solid", start_color="FFF3CD")
normal_font    = Font(name="Arial", size=10)
trickster_font = Font(name="Arial", size=10, italic=True, color="7B5E00")

for i, (orig, modern, basic, trans, trick) in enumerate(verses, start=2):
    row_fill = fill_even if i % 2 == 0 else fill_odd
    for col, val in enumerate([orig, modern, basic, trans, trick], start=1):
        cell = ws.cell(row=i, column=col, value=val)
        cell.font = trickster_font if (col == 5 and trick) else normal_font
        cell.fill = fill_trickster if (col == 5 and trick) else row_fill
        cell.border = thin_border
        cell.alignment = Alignment(wrap_text=True, vertical="top")

ws.column_dimensions['A'].width = 32
ws.column_dimensions['B'].width = 32
ws.column_dimensions['C'].width = 30
ws.column_dimensions['D'].width = 32
ws.column_dimensions['E'].width = 55
ws.freeze_panes = "A2"
ws.row_dimensions[1].height = 30
for r in range(2, len(verses)+2):
    ws.row_dimensions[r].height = 30

out = "Kalevala_Runo_24_Analysis.xlsx"
wb.save(out)
print("Saved:", out, "–", len(verses), "verses")
