from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

wb = Workbook()
ws = wb.active
ws.title = "Runo 44"

headers = ["A – Alkuperäinen säe", "B – Nykykieli", "C – Perusmuodot", "D – Käännös (EN)", "E – Trickster-huomio"]
header_fill = PatternFill("solid", start_color="2F4F6F", end_color="2F4F6F")
header_font = Font(name="Arial", bold=True, color="FFFFFF", size=11)

for col, h in enumerate(headers, 1):
    cell = ws.cell(row=1, column=col, value=h)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

verses = [
    ("Vaka vanha Väinämöinen",
     "Vaka vanha Väinämöinen",
     "vakaa, vanha, Väinämöinen",
     "Steady old Väinämöinen",
     ""),

    ("arvelevi aivossansa:",
     "arvelee aivoissaan:",
     "arvella, aivot",
     "ponders in his mind:",
     "The trickster inward reflection — Väinämöinen planning his next move alone."),

    ("\"Nytpä soitanto sopisi,",
     "\"Nyt soittaminen sopisi,",
     "nyt, soittaminen, sopia",
     "\"Now playing music would be fitting,",
     ""),

    ("ilon teentä kelpoaisi",
     "ilon tekeminen kelpuutettaisiin",
     "ilo, tekeminen, kelpuuttaa",
     "making joy would be welcome",
     ""),

    ("näillä uusilla oloilla,",
     "näillä uusilla oloilla,",
     "nämä, uusi, olo",
     "in these new conditions,",
     ""),

    ("kaunihilla kartanoilla!",
     "kauniilla kartanoilla!",
     "kaunis, kartano",
     "on these beautiful estates!",
     ""),

    ("Vaan on kantele kaonnut,",
     "Mutta kantele on kadonnut,",
     "mutta, kantele, kadota",
     "But the kantele has been lost,",
     "The kantele — the trickster's primary instrument of power — is gone. This loss drives the entire runo."),

    ("iloni iäti mennyt",
     "iloni iäksi mennyt",
     "ilo, iäksi, mennä",
     "my joy gone forever",
     ""),

    ("kalaisehen kartanohon,",
     "kalaiseen kartanoon,",
     "kalainen, kartano",
     "to the fishy domain,",
     ""),

    ("lohisehen louhikkohon,",
     "lohiseen louhikkoon,",
     "lohinen, louhikko",
     "to the salmon-filled rocky place,",
     ""),

    ("meren hauan haltijoille,",
     "meren hauenhaltijoille,",
     "meri, hauki, haltija",
     "to the keepers of the sea's pike,",
     ""),

    ("Vellamon ikiväelle.",
     "Vellamon ikuiselle väelle.",
     "Vellamo, ikuinen, väki",
     "to the eternal people of Vellamo.",
     ""),

    ("Eikä tuota tuonekana,",
     "Eikä sitä sinne,",
     "eikä, se, sinne",
     "And that one will not",
     ""),

    ("Ahto antane takaisin.",
     "Ahto anna takaisin.",
     "Ahto, antaa, takaisin",
     "Ahto give back again.",
     "The sea-god Ahto will not return the kantele — the trickster's tool is truly lost to another power."),

    ("\"Oi on seppo Ilmarinen!",
     "\"Oi on seppä Ilmarinen!",
     "oi, seppä, Ilmarinen",
     "\"Oh the smith Ilmarinen!",
     ""),

    ("Taoit ennen, taoit eilen,",
     "Taoit ennen, taoit eilen,",
     "takoa, ennen, eilen",
     "You forged before, you forged yesterday,",
     ""),

    ("taopa tänäki päänä!",
     "tao tänäkin päivänä!",
     "takoa, tänäkin, päivä",
     "forge also on this day!",
     ""),

    ("Tao rautainen harava,",
     "Tao rautainen harava,",
     "takoa, rautainen, harava",
     "Forge an iron rake,",
     "Väinämöinen commissions a new tool to recover his instrument — the trickster always finds a workaround."),

    ("haravahan piit tiheät,",
     "haravaan piit tiheät,",
     "harava, piikki, tiheä",
     "the rake with dense tines,",
     ""),

    ("piit tiheät, varsi pitkä,",
     "piit tiheät, varsi pitkä,",
     "piikki, tiheä, varsi, pitkä",
     "dense tines, a long handle,",
     ""),

    ("jolla lainehet haroan,",
     "jolla laineet haraan,",
     "jolla, laine, harata",
     "with which I will rake the waves,",
     ""),

    ("laposille aallot lasken,",
     "laposille aallot lasken,",
     "lapanen, aalto, laskea",
     "spread the waves onto the blades,",
     ""),

    ("meren ruoikot ru'olle,",
     "meren ruovikot ruulle,",
     "meri, ruovikko, ruo",
     "the sea's reed-beds onto the rake,",
     ""),

    ("rannat kaikki karhikoille,",
     "rannat kaikki karhikoille,",
     "ranta, kaikki, karhikko",
     "all the shores onto the harrows,",
     ""),

    ("soitto jälle saa'akseni,",
     "soitto jälleen saadakseni,",
     "soitto, jälleen, saada",
     "to get my instrument back again,",
     ""),

    ("kantelo tavatakseni",
     "kantele tavatakseni",
     "kantele, tavata",
     "to find my kantele",
     ""),

    ("kalaisesta kaartehesta,",
     "kalaisesta kaartehesta,",
     "kalainen, kaarre",
     "from the fishy bend,",
     ""),

    ("lohisesta louhikosta!\"",
     "lohisesta louhikosta!\"",
     "lohinen, louhikko",
     "from the salmon-filled rocky place!\"",
     ""),

    ("Se on seppo Ilmarinen,",
     "Se on seppä Ilmarinen,",
     "se, seppä, Ilmarinen",
     "That is the smith Ilmarinen,",
     ""),

    ("takoja iän-ikuinen,",
     "takoja iänikuinen,",
     "takoja, iänikuinen",
     "the eternal forger,",
     ""),

    ("takoi rautaisen haravan",
     "takoi rautaisen haravan",
     "takoa, rautainen, harava",
     "forged the iron rake",
     ""),

    ("varren vaskisen keralla.",
     "varren vaskirankaisella.",
     "varsi, vaskinen",
     "with a copper handle.",
     ""),

    ("Piit takoi satoa syltä,",
     "Piit takoi sataa syltä,",
     "piikki, takoa, sata, syli",
     "He forged the tines a hundred fathoms,",
     ""),

    ("varren viittä valmisteli.",
     "varren viittä valmisteli.",
     "varsi, viisi, valmistella",
     "made the handle five (fathoms).",
     "The enormous rake — the trickster's tools are always supernaturally oversized."),

    ("Siitä vanha Väinämöinen",
     "Siitä vanha Väinämöinen",
     "siitä, vanha, Väinämöinen",
     "Then old Väinämöinen",
     ""),

    ("otti rautaisen haravan.",
     "otti rautaisen haravan.",
     "ottaa, rautainen, harava",
     "took the iron rake.",
     ""),

    ("Astui tietä pikkaraisen,",
     "Astui tietä pikkaraisen,",
     "astua, tie, pikkarainen",
     "Walked a tiny bit of road,",
     ""),

    ("kulki matkoa palasen",
     "kulki matkaa palasen",
     "kulkea, matka, palanen",
     "travelled a small piece of journey",
     ""),

    ("teloille teräksisille,",
     "teloille teräksisille,",
     "tela, teräksinen",
     "to the steel rollers,",
     ""),

    ("vaskisille valkamoille.",
     "vaskisille valkamoille.",
     "vaskinen, valkama",
     "to the copper harbours.",
     ""),

    ("Tuoss' oli purtta, kaksi purtta,",
     "Tuossa oli pursi, kaksi purtta,",
     "tuossa, pursi, kaksi",
     "There was a vessel, two vessels,",
     ""),

    ("kaksi valmista venettä",
     "kaksi valmista venettä",
     "kaksi, valmis, vene",
     "two ready boats",
     ""),

    ("teloilla teräksisillä,",
     "teloilla teräksisillä,",
     "tela, teräksinen",
     "on the steel rollers,",
     ""),

    ("vaskisilla valkamoilla:",
     "vaskisilla valkamoilla:",
     "vaskinen, valkama",
     "on the copper harbours:",
     ""),

    ("yksi pursi uusi pursi,",
     "yksi pursi uusi pursi,",
     "yksi, pursi, uusi",
     "one vessel a new vessel,",
     ""),

    ("toinen pursi vanha pursi.",
     "toinen pursi vanha pursi.",
     "toinen, pursi, vanha",
     "the other vessel an old vessel.",
     ""),

    ("Sanoi vanha Väinämöinen,",
     "Sanoi vanha Väinämöinen,",
     "sanoa, vanha, Väinämöinen",
     "Old Väinämöinen said,",
     ""),

    ("virkki uuelle venolle:",
     "sanoi uudelle veneelle:",
     "sanoa, uusi, vene",
     "spoke to the new boat:",
     "The trickster speaks to inanimate objects — commanding a boat as if it were a person."),

    ("\"Lähepä, veno, vesille,",
     "\"Lähde, vene, vesille,",
     "lähteä, vene, vesi",
     "\"Go, boat, onto the waters,",
     ""),

    ("pursi, aalloillen ajaite",
     "pursi, aalloille aja",
     "pursi, aalto, ajaa",
     "vessel, drive onto the waves",
     ""),

    ("käsivarren kääntämättä,",
     "käsivartta kääntämättä,",
     "käsivarsi, kääntää",
     "without turning a forearm,",
     ""),

    ("peukalon pitelemättä!\"",
     "peukaloa pitelemättä!\"",
     "peukalo, pitää",
     "without holding a thumb!\"",
     "The boat obeys without being steered — the trickster-shaman's magic over nature and objects."),

    ("Läksipä veno vesille,",
     "Lähti vene vesille,",
     "lähteä, vene, vesi",
     "The boat went onto the waters,",
     ""),

    ("pursi aalloillen ajoihe.",
     "pursi aalloille ajoi.",
     "pursi, aalto, ajaa",
     "the vessel drove onto the waves.",
     ""),

    ("Vaka vanha Väinämöinen",
     "Vaka vanha Väinämöinen",
     "vakaa, vanha, Väinämöinen",
     "Steady old Väinämöinen",
     ""),

    ("itse istuihe perähän;",
     "itse istuutui perään;",
     "itse, istua, perä",
     "himself sat down at the stern;",
     ""),

    ("läksi merta luutimahan,",
     "lähti merta luutimaan,",
     "lähteä, meri, luutia",
     "set off to sweep the sea,",
     ""),

    ("lainetta lakaisemahan.",
     "lainetta lakaisemaan.",
     "laine, lakaista",
     "to brush the waves.",
     ""),

    ("Luopi lumpehet kokohon,",
     "Luopi lumpehet kokoon,",
     "luoda, lumme, kokoon",
     "He rakes the water-lilies together,",
     ""),

    ("haravoipi rannan raiskat,",
     "haravoipi rannan raiskat,",
     "haravoida, ranta, raiska",
     "rakes the shore's debris,",
     ""),

    ("ruoposteli ruo'on ruutut,",
     "ruoposteli ruovon tyviosat,",
     "ruopottaa, ruoko, tyvi",
     "dredged the reed-clumps,",
     ""),

    ("ruo'on ruutut, kaislan kaitut,",
     "ruovon tyviosat, kaislikon kaitut,",
     "ruoko, tyvi, kaislikko, kaitu",
     "the reed-stumps, the sedge-tangles,",
     ""),

    ("joka hauanki harasi,",
     "joka hauankin harasi,",
     "joka, haapa, harata",
     "raked every channel too,",
     ""),

    ("karit kaikki karhieli:",
     "karit kaikki karheli:",
     "kari, kaikki, karheilla",
     "harrowed all the reefs:",
     ""),

    ("eipä saanut, ei tavannut",
     "eipä saanut, ei tavannut",
     "ei, saada, ei, tavata",
     "he did not get, did not find",
     "The trickster's search fails — the first rake yields nothing. Setback before the new solution."),

    ("hauinluista soittoansa,",
     "hauinluista soittoaan,",
     "hauki, luu, soitto",
     "his pike-bone instrument,",
     ""),

    ("ikimennyttä iloa,",
     "ikimennyttä iloaan,",
     "ikimennyt, ilo",
     "his forever-gone joy,",
     ""),

    ("kaonnutta kanteloa.",
     "kadonnutta kantelettaan.",
     "kadota, kantele",
     "his vanished kantele.",
     ""),

    ("Vaka vanha Väinämöinen",
     "Vaka vanha Väinämöinen",
     "vakaa, vanha, Väinämöinen",
     "Steady old Väinämöinen",
     ""),

    ("astuvi kohen kotia",
     "astuu kohti kotia",
     "astua, kohti, koti",
     "walks toward home",
     ""),

    ("alla päin, pahoilla mielin,",
     "alla päin, pahoilla mielin,",
     "alla, pää, paha, mieli",
     "head down, in a bad mood,",
     "Even the trickster feels dejection — the rare moment of genuine emotional defeat."),

    ("kaiken kallella kypärin.",
     "kaiken vinossa kypärässä.",
     "kaikki, vino, kypärä",
     "hat tilted all askew.",
     "The tilted hat as visual cue for a trickster's low spirits — a comic and humanising detail."),

    ("Itse tuon sanoiksi kertoi:",
     "Itse sen sanoiksi kertoi:",
     "itse, se, sana, kertoa",
     "Himself spoke it into words:",
     ""),

    ("\"Ei tuota enämpi olle",
     "\"Ei sitä enää ole",
     "ei, se, enää, olla",
     "\"There is no more",
     ""),

    ("hauin hampahan iloa,",
     "hauenhampaisen iloa,",
     "hauki, hammas, ilo",
     "of the pike-tooth joy,",
     ""),

    ("kalanluista luikutusta!\"",
     "kalanluisesta luikutusta!\"",
     "kala, luu, luikuttaa",
     "of the fish-bone gliding!\"",
     ""),

    ("Astuessansa ahoa,",
     "Astuessaan ahoa,",
     "astua, aho",
     "As he walked the meadow,",
     ""),

    ("saloviertä vierressänsä",
     "saloviertä vierressään",
     "salo, vierä, vieressä",
     "as he rolled along the forest edge",
     ""),

    ("kuuli koivun itkeväksi,",
     "kuuli koivun itkevän,",
     "kuulla, koivu, itkeä",
     "he heard a birch tree weeping,",
     "The trickster hears a tree weeping — the liminal world of nature communicates with the shaman-trickster."),

    ("puun visan vetistäväksi.",
     "puun visan vetistävän.",
     "puu, visa, vetistää",
     "the tree's burl oozing moisture.",
     ""),

    ("Jopa luoksi luontelihe,",
     "Jo luokse asteli,",
     "jo, luokse, astella",
     "He approached it,",
     ""),

    ("lähemmäksi laittelihe.",
     "lähemmäksi laittautui.",
     "lähemmäksi, laittautua",
     "drew himself closer.",
     ""),

    ("Kysytteli, lausutteli:",
     "Kysytteli, lausutteli:",
     "kysyä, lausua",
     "He questioned, he spoke:",
     ""),

    ("\"Mit' itket, ihana koivu,",
     "\"Mitä itket, ihana koivu,",
     "mitä, itkeä, ihana, koivu",
     "\"What do you weep for, lovely birch,",
     "Väinämöinen speaks to a tree as an equal — the trickster-shaman's communion with all of nature."),

    ("puu vihanta, vierettelet,",
     "puu vihreä, vierettelet,",
     "puu, vihreä, vierittää",
     "green tree, you roll (tears),",
     ""),

    ("vyöhyt valkea, valitat?",
     "vyöhyt valkea, valitat?",
     "vyöhyt, valkea, valittaa",
     "white-belted one, you lament?",
     ""),

    ("Ei sua sotahan vieä,",
     "Ei sinua sotaan viedä,",
     "ei, sinä, sota, viedä",
     "You are not being taken to war,",
     ""),

    ("ei tahota tappelohon.\"",
     "ei tahdota tappeloon.\"",
     "ei, tahtoa, tappelee",
     "you are not wanted for battle.\"",
     ""),

    ("Koivu taiten vastaeli,",
     "Koivu taitavasti vastasi,",
     "koivu, taitava, vastata",
     "The birch skilfully answered,",
     ""),

    ("itse virkki puu vihanta:",
     "itse sanoi puu vihreä:",
     "itse, sanoa, puu, vihreä",
     "the green tree itself said:",
     ""),

    ("\"Niinpä muutamat sanovi,",
     "\"Niinpä muutamat sanovat,",
     "niinpä, muutama, sanoa",
     "\"So some say,",
     ""),

    ("moniahat arvelevi",
     "monet arvelevat",
     "moni, arvella",
     "many think",
     ""),

    ("elävän minun ilossa,",
     "eläväni ilossa,",
     "elää, ilo",
     "that I live in joy,",
     ""),

    ("riemussa remuelevan:",
     "riemussa remuelevan:",
     "riemu, remuella",
     "that I revel in rejoicing:",
     ""),

    ("minä hoikka huolissani,",
     "minä hoikka huolissani,",
     "minä, hoikka, huoli",
     "I, slender one, am in my worries,",
     ""),

    ("ikävissäni iloitsen,",
     "ikävissäni iloitsen,",
     "ikävä, iloita",
     "I rejoice in my longing (i.e. I suffer),",
     "Irony in the birch's lament — 'rejoicing in longing' is bitter paradox, the voice of a suffering creature."),

    ("panen pakkopäivissäni,",
     "elän pakotettuna päivissäni,",
     "panna, pakko, päivä",
     "I spend my days under compulsion,",
     ""),

    ("murehissa murmattelen.",
     "murehissa murmattelen.",
     "muree, murmattaa",
     "I mutter in my sorrows.",
     ""),

    ("\"Typeryyttä, tyhjä, itken,",
     "\"Tyhmyyttä, tyhjänä, itken,",
     "tyhmyys, tyhjä, itkeä",
     "\"In foolishness, empty one, I weep,",
     ""),

    ("vajauttani valitan,",
     "vajauttani valitan,",
     "vajaus, valittaa",
     "I lament my insufficiency,",
     ""),

    ("kun olen osatoin, raukka,",
     "kun olen osaton, raukka,",
     "kun, osaton, raukka",
     "since I am hapless, wretch,",
     ""),

    ("tuiki, vaivainen, varatoin",
     "aivan vaivainen, varatoin",
     "aivan, vaivainen, varatoin",
     "utterly wretched, lacking resources",
     ""),

    ("näillä paikoilla pahoilla,",
     "näillä paikoilla pahoilla,",
     "nämä, paikka, paha",
     "in these evil places,",
     ""),

    ("lake'illa laitumilla.",
     "lakeilla laitumilla.",
     "lakea, laidun",
     "on the flat pastures.",
     ""),

    ("\"Osalliset, onnelliset",
     "\"Osalliset, onnelliset",
     "osallinen, onnellinen",
     "\"Those who have their share, the fortunate ones",
     ""),

    ("tuota toivovat alati",
     "toivovat sitä alati",
     "toivoa, se, alati",
     "always wish for that",
     ""),

    ("kesän kaunihin tulevan,",
     "kauniin kesän tulevan,",
     "kaunis, kesä, tulla",
     "for the beautiful summer to come,",
     ""),

    ("suven suuren lämpiävän.",
     "suuren suven lämpiävän.",
     "suuri, suvi, lämmetä",
     "for the great summer to warm.",
     ""),

    ("Toisinpa minä typerä,",
     "Toisin minä typerä,",
     "toisin, minä, typerä",
     "Differently I, foolish one,",
     ""),

    ("minä vaivainen varoan",
     "minä vaivainen varoan",
     "minä, vaivainen, varoa",
     "I, wretched one, dread",
     ""),

    ("- kuoreni kolottavaksi,",
     "- kuoreni kalvettavaksi,",
     "kuori, kalvetta",
     "- my bark to be peeled,",
     ""),

    ("lehtivarvat vietäväksi!",
     "lehtivarvat vietäväksi!",
     "lehtivarpu, viedä",
     "my leafy branches to be taken!",
     "The birch dreads summer's exploitation by humans — a nature-spirit's lament, the voice of the exploited."),

    ("\"Useinpa minun utuisen,",
     "\"Usein minua, utuista,",
     "usein, minä, utuinen",
     "\"Often me, misty one,",
     ""),

    ("use'in, utuisen raukan,",
     "usein, utuista raukkaa,",
     "usein, utuinen, raukka",
     "often the misty wretch,",
     ""),

    ("lapset kerkeän keväimen",
     "lapset nopean kevään",
     "lapsi, nopea, kevät",
     "children of the swift spring",
     ""),

    ("luokseni lähenteleikse,",
     "luokseni lähentyvät,",
     "luokse, lähentää",
     "approach me,",
     ""),

    ("veitsin viisin viiltelevät",
     "veitsin viisi viiltelevät",
     "veitsi, viisi, viiltää",
     "with five knives they slash",
     ""),

    ("halki mahlaisen mahani.",
     "halki mahlaisen mahani.",
     "halki, mahlainen, maha",
     "through my sappy belly.",
     ""),

    ("Paimenet pahat kesällä",
     "Paimenet pahat kesällä",
     "paimen, paha, kesä",
     "Evil shepherds in summer",
     ""),

    ("vievät vyöni valkeaisen,",
     "vievät vyöni valkeaisen,",
     "viedä, vyö, valkea",
     "carry off my white belt (bark),",
     ""),

    ("ken lipiksi, ken tupeksi,",
     "ken lipiksi, ken tupaksi,",
     "ken, lipike, ken, tupakki",
     "one for a cover, one for a tobacco-pouch,",
     ""),

    ("kenpä marjatuohiseksi.",
     "kenpä marjatuoheksi.",
     "ken, marja, tuohi",
     "someone for a berry-bark-box.",
     ""),

    ("\"Use'in minun utuisen,",
     "\"Usein minua, utuista,",
     "usein, minä, utuinen",
     "\"Often me, misty one,",
     ""),

    ("use'in, utuisen raukan,",
     "usein, utuista raukkaa,",
     "usein, utuinen, raukka",
     "often the misty wretch,",
     ""),

    ("tytöt allani asuvat,",
     "tytöt allani asuvat,",
     "tyttö, alla, asua",
     "girls rest beneath me,",
     ""),

    ("vierelläni viehkuroivat,",
     "vierelläni viehkuroivat,",
     "vierellä, viehkuroida",
     "flirt beside me,",
     ""),

    ("lehvät päältä leikkelevät,",
     "lehvät päältä leikkelevät,",
     "lehvä, päältä, leikellä",
     "clip branches from above,",
     ""),

    ("varvat vastoiksi sitovat.",
     "varvat vastoiksi sitovat.",
     "varpu, vasta, sitoa",
     "tie twigs into bath-whisks.",
     ""),

    ("\"Use'in minä utuinen,",
     "\"Usein minä utuinen,",
     "usein, minä, utuinen",
     "\"Often I, misty one,",
     ""),

    ("use'in, utuinen raukka,",
     "usein, utuinen raukka,",
     "usein, utuinen, raukka",
     "often the misty wretch,",
     ""),

    ("kaaetahan kaskipuiksi,",
     "kaadetaan kaskipuiksi,",
     "kaataa, kaskipuu",
     "am felled for slash-and-burn wood,",
     ""),

    ("pinopuiksi pilkotahan.",
     "pinopuiksi pilkotaan.",
     "pinopuu, pilkkoa",
     "chopped into stack-wood.",
     ""),

    ("Kolmasti tänäi kesänä,",
     "Kolmasti tänä kesänä,",
     "kolmasti, tänä, kesä",
     "Three times this summer,",
     ""),

    ("tänä suurena suvena",
     "tänä suurena suvena",
     "tämä, suuri, suvi",
     "this great summer,",
     ""),

    ("miehet allani asuivat,",
     "miehet allani asuivat,",
     "mies, alla, asua",
     "men stood beneath me,",
     ""),

    ("kirvestänsä kitkuttivat",
     "kirvestään kitkuttivat",
     "kirves, kitkuttaa",
     "wielded their axes",
     ""),

    ("mun poloisen pään menoksi,",
     "minun poloisen pään menoksi,",
     "minä, poloinen, pää, meno",
     "for the going of my poor head,",
     ""),

    ("heikon henkeni lähöksi.",
     "heikon henkeni lähtemiseksi.",
     "heikko, henki, lähteä",
     "for the departing of my weak spirit.",
     "The birch faces repeated mortal threats — her speech lists exploitation methodically, like a trickster enumerating grievances."),

    ("\"Se oli ilo kesästä,",
     "\"Se oli ilo kesästä,",
     "se, ilo, kesä",
     "\"That was the joy of summer,",
     "Bitter irony — 'that was the joy of summer' said about near-death. The birch uses the trickster's tool of ironic inversion."),

    ("riemu suuresta suvesta.",
     "riemu suuresta suvesta.",
     "riemu, suuri, suvi",
     "the rejoicing of the great summer.",
     ""),

    ("Ei ole talvi sen parempi,",
     "Ei ole talvi sen parempi,",
     "ei, talvi, parempi",
     "Winter is no better for it,",
     ""),

    ("lumen aika armahampi.",
     "lumen aika armahampi.",
     "lumi, aika, armas",
     "the time of snow no dearer.",
     ""),

    ("\"Jopa aina aikaisehen",
     "\"Jo aina aikaisin",
     "jo, aina, aikainen",
     "\"Already always early",
     ""),

    ("mure muo'on muuttelevi,",
     "mureheni muodon muuttelee,",
     "muree, muoto, muutella",
     "sorrow changes my form,",
     ""),

    ("pääni painuvi pahaksi,",
     "pääni painuu pahaksi,",
     "pää, painua, paha",
     "my head droops to badness,",
     ""),

    ("kasvot käypi kalveaksi",
     "kasvot käyvät kalpeaksi",
     "kasvot, käydä, kalpea",
     "my face goes pale",
     ""),

    ("muistellessa mustat päivät,",
     "muistellessa mustia päiviä,",
     "muistella, musta, päivä",
     "when remembering the dark days,",
     ""),

    ("pahat ajat arvellessa.",
     "pahoja aikoja arvellessa.",
     "paha, aika, arvella",
     "when pondering the bad times.",
     ""),

    ("\"Siitä tuuli tuskat tuopi,",
     "\"Siitä tuuli tuskat tuo,",
     "siitä, tuuli, tuska, tuoda",
     "\"From that the wind brings torments,",
     ""),

    ("halla huolet haike'immat:",
     "halla huolet haikeat:",
     "halla, huoli, haiku",
     "the frost the bitterest sorrows:",
     ""),

    ("tuuli vie vihannan turkin,",
     "tuuli vie vihreän turkin,",
     "tuuli, viedä, vihreä, turkki",
     "the wind takes away my green coat,",
     ""),

    ("halla kaunihin hamehen.",
     "halla kauniin hameeni.",
     "halla, kaunis, hame",
     "the frost my beautiful skirt.",
     ""),

    ("Niin minä vähävarainen,",
     "Niin minä vähävarainen,",
     "niin, minä, vähävarainen",
     "So I, the poorly-resourced one,",
     ""),

    ("minä, koito koivu raukka,",
     "minä, nuori koivu raukka,",
     "minä, koito, koivu, raukka",
     "I, the young wretched birch,",
     ""),

    ("jään aivan alastomaksi,",
     "jään aivan alastomaksi,",
     "jäädä, aivan, alaston",
     "I am left entirely naked,",
     ""),

    ("varsin vaattehettomaksi",
     "varsin vaatteettomaksi",
     "varsin, vaatteeton",
     "absolutely without clothing",
     ""),

    ("vilussa värisemähän,",
     "kylmässä värisemään,",
     "kylmä, väristä",
     "to shiver in the cold,",
     ""),

    ("pakkasessa parkumahan.\"",
     "pakkasessa parkumaan.\"",
     "pakkanen, parkua",
     "to howl in the frost.\"",
     "The birch's nakedness in winter — a nature-spirit reduced to the most vulnerable state, mirroring the trickster's occasional helplessness."),

    ("Sanoi vanha Väinämöinen:",
     "Sanoi vanha Väinämöinen:",
     "sanoa, vanha, Väinämöinen",
     "Old Väinämöinen said:",
     ""),

    ("\"Elä itke, puu vihanta,",
     "\"Älä itke, puu vihreä,",
     "älä, itkeä, puu, vihreä",
     "\"Do not weep, green tree,",
     ""),

    ("vesa lehti, vierettele,",
     "vesa lehti, vierettele,",
     "vesa, lehti, vierittää",
     "leafy shoot, do not roll (tears),",
     ""),

    ("vyöhyt valkea, valita!",
     "vyöhyt valkea, älä valita!",
     "vyöhyt, valkea, valittaa",
     "white-belted one, do not lament!",
     ""),

    ("Saat sinä olevan onnen,",
     "Saat sinä olevan onnen,",
     "saada, sinä, olla, onni",
     "You will get existing fortune,",
     "The trickster promises the birch a new destiny — he turns the tree's suffering into an opportunity for transformation."),

    ("elon uuen armahamman;",
     "elon uuden armaampaa;",
     "elo, uusi, armas",
     "a dearer new life;",
     ""),

    ("kohta itkenet ilosta,",
     "kohta itkenet ilosta,",
     "kohta, itkeä, ilo",
     "soon you will weep from joy,",
     ""),

    ("riemusta remahutellet.\"",
     "riemusta remahutellet.\"",
     "riemu, remahtaa",
     "you will burst out from rejoicing.\"",
     ""),

    ("Siitä vanha Väinämöinen",
     "Siitä vanha Väinämöinen",
     "siitä, vanha, Väinämöinen",
     "Then old Väinämöinen",
     ""),

    ("koivun soitoksi kuvasi.",
     "koivun soitoksi kuvasi.",
     "koivu, soitto, kuvata",
     "shaped the birch into an instrument.",
     "The trickster transforms the suffering birch into a kantele — converting sorrow into art and power. A classic trickster act of creative transformation."),

    ("Veisteli kesäisen päivän,",
     "Veisteli kesäisen päivän,",
     "veistää, kesäinen, päivä",
     "He carved through a summer's day,",
     ""),

    ("kalkutteli kanteletta",
     "kalkutteli kanteletta",
     "kalkuttaa, kantele",
     "chipped away at the kantele",
     ""),

    ("nenässä utuisen niemen,",
     "nenässä utuisen niemen,",
     "nenä, utuinen, niemi",
     "at the tip of the misty headland,",
     ""),

    ("päässä saaren terhenisen.",
     "päässä saaren terhenisen.",
     "pää, saari, terheninen",
     "at the head of the foggy island.",
     "The same misty headland mentioned as the Sampo's destination — the trickster's sacred creative space."),

    ("Veisti kopan kanteletta,",
     "Veisti kopan kanteletta,",
     "veistää, koppa, kantele",
     "He carved the body of the kantele,",
     ""),

    ("emäpuun iloa uutta,",
     "emäpuun iloa uutta,",
     "emäpuu, ilo, uusi",
     "the mother-wood of new joy,",
     ""),

    ("kopan koivusta lujasta,",
     "kopan koivusta lujasta,",
     "koppa, koivu, luja",
     "the body from sturdy birch,",
     ""),

    ("emäpuun visaperästä.",
     "emäpuun visaperästä.",
     "emäpuu, visaperä",
     "the mother-wood from the curly-grained root.",
     ""),

    ("Sanoi vanha Väinämöinen,",
     "Sanoi vanha Väinämöinen,",
     "sanoa, vanha, Väinämöinen",
     "Old Väinämöinen said,",
     ""),

    ("itse lausui, noin nimesi:",
     "itse lausui, noin sanoi:",
     "itse, lausua, sanoa",
     "himself spoke, named it thus:",
     ""),

    ("\"Tuoss' on koppa kanteletta,",
     "\"Tuossa on koppa kanteletta,",
     "tuossa, koppa, kantele",
     "\"There is the body of the kantele,",
     ""),

    ("emäpuu iki-iloa.",
     "emäpuu ikuista iloa.",
     "emäpuu, ikuinen, ilo",
     "the mother-wood of eternal joy.",
     ""),

    ("Mistä naulat saatanehe,",
     "Mistä naulat saataneen,",
     "mistä, naula, saada",
     "From where can the pegs be obtained,",
     ""),

    ("vääntimet perittänehe?\"",
     "vääntimet hankittaneen?\"",
     "vääntin, hankkia",
     "the tuning-pegs acquired?\"",
     ""),

    ("Kasvoi tammi tanhualla,",
     "Kasvoi tammi tanhualla,",
     "kasvaa, tammi, tanhuo",
     "An oak grew in the yard,",
     ""),

    ("puu pitkä pihan perällä,",
     "puu pitkä pihan perällä,",
     "puu, pitkä, piha, perä",
     "a tall tree at the back of the courtyard,",
     ""),

    ("tammessa tasaiset oksat,",
     "tammessa tasaiset oksat,",
     "tammi, tasainen, oksa",
     "in the oak even branches,",
     ""),

    ("joka oksalla omena,",
     "joka oksalla omena,",
     "joka, oksa, omena",
     "on every branch an apple,",
     ""),

    ("omenalla kultapyörä,",
     "omenalla kultapyörä,",
     "omena, kultapyörä",
     "on the apple a golden wheel,",
     ""),

    ("kultapyörällä käkönen.",
     "kultapyörällä käkönen.",
     "kultapyörä, käki",
     "on the golden wheel a cuckoo.",
     "The magical oak with cuckoo — a visionary, impossible tree from the trickster-shaman's world, yielding golden materials."),

    ("Kun käki kukahtelevi,",
     "Kun käki kukahtelee,",
     "kun, käki, kukahtelee",
     "When the cuckoo calls,",
     ""),

    ("sanoin viisin virkkelevi,",
     "sanoin viidellä virkkelee,",
     "sana, viisi, virkkoa",
     "speaks in five words,",
     ""),

    ("kulta suusta kumpuavi,",
     "kulta suusta kumpuaa,",
     "kulta, suu, kumputa",
     "gold wells from its mouth,",
     ""),

    ("hopea valahtelevi",
     "hopea valahtelee",
     "hopea, valaa",
     "silver pours",
     ""),

    ("kultaiselle kunnahalle,",
     "kultaiselle kunnahalle,",
     "kultainen, kunnaha",
     "onto the golden knoll,",
     ""),

    ("hope'iselle mäelle:",
     "hopeiselle mäelle:",
     "hopeinen, mäki",
     "onto the silver hill:",
     ""),

    ("siitä naulat kantelehen,",
     "siitä naulat kantelehen,",
     "siitä, naula, kantele",
     "from that the pegs for the kantele,",
     ""),

    ("vääntimet visaperähän!",
     "vääntimet visaperään!",
     "vääntin, visaperä",
     "the tuning-pegs for the curly-grained root!",
     "Gold and silver from a cuckoo's song become the kantele's pegs — the trickster obtains materials from magical, non-human sources."),

    ("Sanoi vanha Väinämöinen,",
     "Sanoi vanha Väinämöinen,",
     "sanoa, vanha, Väinämöinen",
     "Old Väinämöinen said,",
     ""),

    ("itse virkki, noin nimesi:",
     "itse sanoi, noin sanoi:",
     "itse, sanoa",
     "himself said, named it thus:",
     ""),

    ("\"Sain ma naulat kantelehen,",
     "\"Sain minä naulat kantelehen,",
     "saada, minä, naula, kantele",
     "\"I got the pegs for the kantele,",
     ""),

    ("vääntimet visaperähän.",
     "vääntimet visaperään.",
     "vääntin, visaperä",
     "the tuning-pegs for the curly root.",
     ""),

    ("Vielä uupuvi vähäisen,",
     "Vielä uupuu vähäinen,",
     "vielä, uupua, vähäinen",
     "Still lacking a little,",
     ""),

    ("viittä kieltä kanteloinen.",
     "viisi kieltä kanteloisella.",
     "viisi, kieli, kantele",
     "five strings for the kantele.",
     ""),

    ("Mistä tuohon kielet saisin,",
     "Mistä tuohon kielet saisin,",
     "mistä, tuo, kieli, saada",
     "From where could I get the strings for it,",
     ""),

    ("äänöset asetteleisin?\"",
     "äänet asettelisin?\"",
     "ääni, asettaa",
     "set in place the sounds?\"",
     "The trickster systematically solves each construction problem — methodical improvisation."),

    ("Läksi kieltä etsimähän.",
     "Lähti kieltä etsimään.",
     "lähteä, kieli, etsiä",
     "He set off to look for strings.",
     ""),

    ("Astuvi ahoa myöten:",
     "Astuu ahoa myöten:",
     "astua, aho, myöten",
     "He walks through the meadow:",
     ""),

    ("istui immikkö aholla,",
     "istui tyttö aholla,",
     "istua, tyttö, aho",
     "a girl sat on the meadow,",
     ""),

    ("nuori neitonen norolla.",
     "nuori neito norolla.",
     "nuori, neito, noro",
     "a young maiden on the stream-bank.",
     ""),

    ("Ei se impi itkenynnä,",
     "Ei se tyttö itkenytkään,",
     "ei, tyttö, itkeä",
     "The girl was not weeping,",
     ""),

    ("ei varsin ilonnutkana;",
     "ei varsinaisesti iloinnutkaan;",
     "ei, varsinainen, iloita",
     "nor was she truly rejoicing;",
     ""),

    ("ilman lauloi itseksensä:",
     "ilman lauloi itseksensä:",
     "ilman, laulaa, itsekseen",
     "she sang to herself for nothing:",
     ""),

    ("lauloi iltansa kuluksi,",
     "lauloi iltansa kuluksi,",
     "laulaa, ilta, kulu",
     "sang to pass her evening,",
     ""),

    ("sulhon toivossa tulevan,",
     "sulhon toivossa tulevan,",
     "sulho, toivo, tulla",
     "in hope of a suitor coming,",
     ""),

    ("armahansa aikehessa.",
     "rakkaansa aikeessa.",
     "rakas, aihe",
     "with intention toward her beloved.",
     ""),

    ("Vaka vanha Väinämöinen",
     "Vaka vanha Väinämöinen",
     "vakaa, vanha, Väinämöinen",
     "Steady old Väinämöinen",
     ""),

    ("tuonne kengättä kepitti,",
     "tuonne kengättä kepitti,",
     "tuo, kengätön, kepittää",
     "there without shoes he trotted,",
     ""),

    ("ilman hampsi hattaratta.",
     "ilman hatutta ampsi.",
     "ilman, hattu, harppoa",
     "strode without a hat.",
     "The trickster approaches in undignified haste — barefoot and hatless, revealing his impulsive nature."),

    ("Sitte sinne tultuansa",
     "Sitten sinne tultuaan",
     "sitten, sinne, tulla",
     "Then upon arriving there",
     ""),

    ("alkoi hapsia anella.",
     "alkoi hiuksia anella.",
     "alkaa, hius, anella",
     "he began to beg for hair.",
     "The trickster begging from a young woman — he acquires the last kantele component through supplication, not magic."),

    ("Itse tuon sanoiksi virkki:",
     "Itse sen sanoiksi sanoi:",
     "itse, se, sana, virkkoa",
     "Himself spoke it into words:",
     ""),

    ("\"Anna, impi, hapsiasi,",
     "\"Anna, tyttö, hiuksiasi,",
     "antaa, tyttö, hius",
     "\"Give, girl, your hair,",
     ""),

    ("hieprukka, hivuksiasi",
     "hienoinen, hivuksiasi",
     "hienoinen, hivus",
     "fine one, your hair-strands",
     ""),

    ("kanteloisen kielosiksi,",
     "kanteloisen kieliksi,",
     "kantele, kieli",
     "as strings for the kantele,",
     ""),

    ("ääniksi ilon ikuisen!\"",
     "ääneksi ikuisen ilon!\"",
     "ääni, ikuinen, ilo",
     "as sounds of eternal joy!\"",
     "Väinämöinen appeals to the maiden's vanity — framing her hair as a source of 'eternal joy', a flattering trickster persuasion."),

    ("Antoi impi hapsiansa,",
     "Antoi tyttö hiuksiaan,",
     "antaa, tyttö, hius",
     "The girl gave her hair,",
     ""),

    ("hienoja hivuksiansa;",
     "hienoja hivuksiaan;",
     "hieno, hivus",
     "her fine hair-strands;",
     ""),

    ("antoi hasta viisi, kuusi",
     "antoi heti viisi, kuusi",
     "antaa, heti, viisi, kuusi",
     "she gave right away five, six",
     ""),

    ("sekä seitsemän hivusta:",
     "sekä seitsemän hivusta:",
     "sekä, seitsemän, hivus",
     "and seven hair-strands:",
     ""),

    ("siit' on kielet kantelessa,",
     "siitä ovat kielet kantelessa,",
     "siitä, kieli, kantele",
     "from that are the strings in the kantele,",
     ""),

    ("ääntimet iki-ilossa.",
     "äänet ikuisessa ilossa.",
     "ääni, ikuinen, ilo",
     "the sounds in eternal joy.",
     "A young woman's freely given hair becomes the voice of the kantele — the trickster transforms the personal into the cosmic."),

    ("Saip' on soitto valmihiksi.",
     "Sai soiton valmiiksi.",
     "saada, soitto, valmis",
     "The instrument was completed.",
     ""),

    ("Siitä vanha Väinämöinen",
     "Siitä vanha Väinämöinen",
     "siitä, vanha, Väinämöinen",
     "Then old Väinämöinen",
     ""),

    ("istuiksen alakivelle,",
     "istuutui alakivelle,",
     "istua, alakivi",
     "sat himself on a low stone,",
     ""),

    ("paatiselle portahalle.",
     "paatiselle portaalle.",
     "paatinen, porras",
     "on a stone threshold.",
     ""),

    ("Otti kantelon käsille,",
     "Otti kantelon käsiinsä,",
     "ottaa, kantele, käsi",
     "Took the kantele in his hands,",
     ""),

    ("ilon itsensä lähemmä.",
     "ilon lähemmäksi itselleen.",
     "ilo, lähemmä, itse",
     "brought joy closer to himself.",
     ""),

    ("Kären käänti taivahalle,",
     "Kären käänsi taivaalle,",
     "kare, kääntää, taivas",
     "Turned the scroll upward toward the sky,",
     ""),

    ("ponnen polville tukesi:",
     "ponnen polville tukesi:",
     "ponsi, polvi, tukea",
     "supported the base on his knees:",
     ""),

    ("ääniä asettelevi,",
     "ääniä asettelee,",
     "ääni, asettaa",
     "he arranges the sounds,",
     ""),

    ("säveliä sääntelevi.",
     "säveliä säätelee.",
     "sävel, säädellä",
     "regulates the melodies.",
     ""),

    ("Sai äänet asetetuksi,",
     "Sai äänet asetetuiksi,",
     "saada, ääni, asettaa",
     "Got the sounds arranged,",
     ""),

    ("soittonsa sovitetuksi,",
     "soittonsa sovitetuksi,",
     "soitto, sovittaa",
     "his playing tuned,",
     ""),

    ("niin käänti alakäsille,",
     "niin käänsi alakäsille,",
     "niin, kääntää, alakäsi",
     "then turned it to the lower hand,",
     ""),

    ("poikkipuolin polvillensa.",
     "poikkipuolin polvillaan.",
     "poikkipuolin, polvi",
     "crosswise on his knees.",
     ""),

    ("Laski kynttä kymmenkunnan,",
     "Laski kynttä kymmenkuntaa,",
     "laskea, kynsi, kymmen",
     "He set a full ten nails,",
     ""),

    ("viisi sormea viritti",
     "viisi sormea viritti",
     "viisi, sormi, virittää",
     "set five fingers",
     ""),

    ("kielille kapahumahan,",
     "kielille kapahtamaan,",
     "kieli, kapahtaa",
     "to spring onto the strings,",
     ""),

    ("sävelille hyppimähän.",
     "sävelille hyppimään.",
     "sävel, hyppiä",
     "to jump on the melodies.",
     ""),

    ("Siinä vanha Väinämöinen",
     "Siinä vanha Väinämöinen",
     "siinä, vanha, Väinämöinen",
     "There old Väinämöinen",
     ""),

    ("kun on soitti kanteletta",
     "kun soitti kanteletta",
     "kun, soittaa, kantele",
     "when he played the kantele",
     ""),

    ("käsin pienin, hoikin sormin,",
     "käsin pienin, hoikin sormin,",
     "käsi, pieni, hoikka, sormi",
     "with small hands, with slender fingers,",
     ""),

    ("peukaloin ulos kiverin,",
     "peukaloin ulospäin käännetyin,",
     "peukalo, ulospäin, kääntää",
     "with thumbs turned outward,",
     ""),

    ("jopa virkki puu visainen,",
     "jo sanoi puu visainen,",
     "jo, sanoa, puu, visainen",
     "already spoke the curly-grained wood,",
     "The kantele speaks — the trickster's instrument has a voice of its own, as if alive."),

    ("vesa lehti vieretteli,",
     "vesa lehti vieritti,",
     "vesa, lehti, vierittää",
     "the leafy shoot shed (tears of joy),",
     ""),

    ("kukahti käkösen kulta,",
     "kukahti käkösen kulta,",
     "kukahtaa, käki, kulta",
     "the cuckoo's gold rang out,",
     ""),

    ("hivus impyen ilosi.",
     "hiukset tytön iloitsivat.",
     "hius, tyttö, iloita",
     "the girl's hair rejoiced.",
     "All three materials — birch-wood, cuckoo-gold, and maiden-hair — respond with joy when played. The trickster's creation is cosmically alive."),

    ("Sormin soitti Väinämöinen,",
     "Sormin soitti Väinämöinen,",
     "sormi, soittaa, Väinämöinen",
     "With fingers Väinämöinen played,",
     ""),

    ("kielin kantelo kajasi:",
     "kielin kantele kajasi:",
     "kieli, kantele, kajaa",
     "with strings the kantele rang out:",
     ""),

    ("vuoret loukkui, paaet paukkui,",
     "vuoret louskuivat, paaden paukkui,",
     "vuori, louskua, paasi, paukkua",
     "the mountains crashed, the flat rocks banged,",
     ""),

    ("kaikki kalliot tärähti,",
     "kaikki kalliot tärähtivät,",
     "kaikki, kallio, tärähtää",
     "all the cliffs shook,",
     ""),

    ("kivet laikkui lainehilla,",
     "kivet laimuivat lainehilla,",
     "kivi, laimuta, laine",
     "the stones gleamed on the waves,",
     ""),

    ("somerot vesillä souti,",
     "somerot vesillä soutivat,",
     "somero, vesi, soutaa",
     "the pebbles rowed on the waters,",
     ""),

    ("petäjät piti iloa,",
     "petäjät pitivät iloa,",
     "petäjä, pitää, ilo",
     "the pine trees kept joy,",
     ""),

    ("kannot hyppi kankahilla.",
     "kannot hyppisivät kankahilla.",
     "kanto, hyppiä, kangas",
     "the stumps jumped on the heaths.",
     "The whole of nature responds to the kantele — the trickster-shaman's music as cosmic force reshaping reality."),

    ("Kälykset Kalevan naiset,",
     "Kälyt Kalevan naiset,",
     "käly, Kaleva, nainen",
     "The sisters-in-law, the women of Kaleva,",
     ""),

    ("kesken kirjan neulomisen",
     "kesken kirjan neulomisen",
     "keski, kirja, neuloa",
     "in the middle of sewing embroidery",
     ""),

    ("ne tuohon jokena juoksi,",
     "ne tuohon jokena juoksivat,",
     "ne, tuo, joki, juosta",
     "they rushed there like a river,",
     ""),

    ("kaikki virtana vilisi,",
     "kaikki virtana vilisi,",
     "kaikki, virta, villistä",
     "all swarmed there like a current,",
     ""),

    ("nuoret naiset naurusuulla,",
     "nuoret naiset naurusuulla,",
     "nuori, nainen, nauruinen, suu",
     "young women with laughing mouths,",
     ""),

    ("emännät ilolla mielin",
     "emännät iloisin mielin",
     "emäntä, iloinen, mieli",
     "housewives with joyful spirits",
     ""),

    ("soitteloa kuulemahan,",
     "soitteloa kuulemaan,",
     "soittelo, kuulla",
     "to hear the playing,",
     ""),

    ("iloa imehtimähän.",
     "iloa ihmettelemään.",
     "ilo, ihmetellä",
     "to marvel at the joy.",
     ""),

    ("Mi oli miehiä lähellä,",
     "Mitä miehiä oli lähellä,",
     "mitä, mies, lähellä",
     "Whatever men were nearby,",
     ""),

    ("ne kaikki lakit käessä;",
     "ne kaikki hatut kädessä;",
     "ne, kaikki, hattu, käsi",
     "all held their hats in hand;",
     "Hats off in awe — the trickster's music commands universal reverence."),

    ("mi oli akkoja lähellä,",
     "mitä akkoja oli lähellä,",
     "mitä, akka, lähellä",
     "whatever old women were nearby,",
     ""),

    ("ne kaikki käsi posella.",
     "ne kaikki käsi posella.",
     "ne, kaikki, käsi, poski",
     "all had their hand on their cheek.",
     ""),

    ("Tyttäret vesissä silmin,",
     "Tyttäret vesissä silmin,",
     "tytär, vesi, silmä",
     "Daughters with wet eyes,",
     ""),

    ("pojat maassa polvillansa",
     "pojat maassa polvillaan",
     "poika, maa, polvi",
     "boys on their knees on the ground",
     ""),

    ("kanteloista kuuntelivat,",
     "kanteleesta kuuntelivat,",
     "kantele, kuunnella",
     "listened to the kantele,",
     ""),

    ("iloa imehtelivät.",
     "iloa ihmetteli vät.",
     "ilo, ihmetellä",
     "marvelled at the joy.",
     ""),

    ("Sanoivat samalla suulla,",
     "Sanoivat samalla suulla,",
     "sanoa, sama, suu",
     "They said with the same mouth,",
     ""),

    ("yhen kielen kerkesivät:",
     "yhden kielen saivat aikaan:",
     "yksi, kieli, kerkeä",
     "came to one voice:",
     ""),

    ("\"Ei ole tuota ennen kuultu",
     "\"Ei ole tuota ennen kuultu",
     "ei, tuo, ennen, kuulla",
     "\"That has never been heard before",
     ""),

    ("noin suloista soitantoa,",
     "niin suloista soittamista,",
     "niin, suloinen, soittaminen",
     "such sweet playing,",
     ""),

    ("sinä ilmoisna ikänä,",
     "sinä ilmoisena ikänä,",
     "sinä, ilmoinen, ikä",
     "in that open eternity,",
     ""),

    ("kuuna kullan valkeana!\"",
     "kuuna kullan valkeana!\"",
     "kuu, kulta, valkea",
     "as long as the golden moon shines white!\"",
     "The crowd's unanimous verdict — the new kantele surpasses all previous music. The trickster's creation exceeds even his own past achievements."),

    ("Kuuluvi sorea soitto,",
     "Kuuluu sorea soitto,",
     "kuulua, sorea, soitto",
     "The beautiful playing was heard,",
     ""),

    ("kuului kuutehen kylähän.",
     "kuului kuuteen kylään.",
     "kuulua, kuusi, kylä",
     "heard across six villages.",
     ""),

    ("Eik' ollut sitä otusta,",
     "Eikä ollut sitä otusta,",
     "eikä, olla, se, otus",
     "Nor was there that creature,",
     ""),

    ("ku ei tullut kuulemahan",
     "joka ei tullut kuulemaan",
     "joka, ei, tulla, kuulla",
     "that did not come to hear",
     ""),

    ("tuota soittoa suloista,",
     "tuota soittoa suloista,",
     "tuo, soitto, suloinen",
     "that sweet playing,",
     ""),

    ("kajahusta kanteloisen.",
     "kajahusta kanteleisen.",
     "kajahdus, kantelinen",
     "the resonance of the kantele.",
     ""),

    ("Mi oli metsän eläintä,",
     "Mitä oli metsän eläintä,",
     "mitä, metsä, eläin",
     "Whatever was of forest animals,",
     ""),

    ("kyykistyivät kynsillehen",
     "kyykistyivät kynsillään",
     "kyykistyä, kynsi",
     "they crouched on their claws",
     ""),

    ("kanteloista kuulemahan,",
     "kanteleesta kuulemaan,",
     "kantele, kuulla",
     "to hear the kantele,",
     ""),

    ("iloa imehtimähän.",
     "iloa ihmettelemään.",
     "ilo, ihmetellä",
     "to marvel at the joy.",
     ""),

    ("Ilman linnut lentäväiset",
     "Ilman linnut lentäväiset",
     "ilma, lintu, lentävä",
     "The flying birds of the air",
     ""),

    ("varvuille varustelihe,",
     "oksille varustautuivat,",
     "oksa, varustautua",
     "perched on branches,",
     ""),

    ("veen kalaset kaikenlaiset",
     "veden kalat kaikenlaiset",
     "vesi, kala, kaikenlainen",
     "the fish of all kinds in the water",
     ""),

    ("rantahan rakentelihe.",
     "rantaan rakentautuivat.",
     "ranta, rakentautua",
     "gathered themselves to the shore.",
     ""),

    ("Matosetki maanalaiset",
     "Madotkin maanalaiset",
     "mato, maanalainen",
     "Even the underground worms",
     ""),

    ("päälle mullan muuttelihe",
     "päälle mullan muuttelivat",
     "päälle, multa, muuttaa",
     "moved up above the earth",
     ""),

    ("- käänteleivät, kuuntelevat",
     "- kääntelivät, kuuntelivat",
     "kääntää, kuunnella",
     "- turned themselves, listened",
     ""),

    ("tuota soittoa suloista,",
     "tuota soittoa suloista,",
     "tuo, soitto, suloinen",
     "to that sweet playing,",
     ""),

    ("kantelen iki-iloa,",
     "kantelen ikuista iloa,",
     "kantele, ikuinen, ilo",
     "the kantele's eternal joy,",
     ""),

    ("Väinämöisen väännätystä.",
     "Väinämöisen väännätystä.",
     "Väinämöinen, väännätys",
     "Väinämöinen's twisting (playing).",
     "Even worms come from underground — the trickster's music reaches into every level of existence, from sky to underworld."),

    ("Siinä vanha Väinämöinen",
     "Siinä vanha Väinämöinen",
     "siinä, vanha, Väinämöinen",
     "There old Väinämöinen",
     ""),

    ("kyllä soitteli somasti,",
     "kyllä soitteli somasti,",
     "kyllä, soitella, soma",
     "played indeed beautifully,",
     ""),

    ("kajahutti kaunihisti.",
     "kajahutti kauniisti.",
     "kajahtaa, kauniisti",
     "made it resound beautifully.",
     ""),

    ("Soitti päivän, soitti toisen",
     "Soitti päivän, soitti toisen",
     "soittaa, päivä, toinen",
     "He played one day, played a second",
     ""),

    ("yhtehen rupeamahan,",
     "yhtäjaksoisesti,",
     "yhtäjaksoinen",
     "in one continuous stretch,",
     ""),

    ("yhen aamun atriahan,",
     "yhden aamun ateriaan,",
     "yksi, aamu, ateria",
     "for one morning's meal-time,",
     ""),

    ("yhen vyönsä vyötäntähän,",
     "yhden vyönsä vyötäntään,",
     "yksi, vyö, vyötää",
     "for one putting-on of his belt,",
     ""),

    ("yhen paitansa panohon.",
     "yhden paitansa panoon.",
     "yksi, paita, pano",
     "for one putting-on of his shirt.",
     "He plays for days without stopping to eat or dress — the trickster consumed entirely by his art."),

    ("Kun hän soitteli kotona,",
     "Kun hän soitteli kotona,",
     "kun, hän, soitella, koti",
     "When he played at home,",
     ""),

    ("huonehessa honkaisessa,",
     "huoneessa honkaisessa,",
     "huone, honkainen",
     "in the pine-wood house,",
     ""),

    ("niin katot kajahtelivat,",
     "niin katot kajahtelivat,",
     "niin, katto, kajahtaa",
     "then the ceilings rang,",
     ""),

    ("permannot pemahtelivat;",
     "permannot pemahtelivat;",
     "permanto, pemahtaa",
     "the floors thudded;",
     ""),

    ("laet lauloi, ukset ulvoi,",
     "laet lauloivat, ovet ulvoivat,",
     "laki, laulaa, ovi, ulvoa",
     "the lofts sang, the doors howled,",
     ""),

    ("kaikki ikkunat iloitsi,",
     "kaikki ikkunat iloitsivat,",
     "kaikki, ikkuna, iloita",
     "all the windows rejoiced,",
     ""),

    ("kiukoa kivinen liikkui,",
     "kiuas kivinen liikkui,",
     "kiuas, kivinen, liikkua",
     "the stone stove moved,",
     ""),

    ("patsas patvinen pajahti.",
     "patsas patvinen kajahti.",
     "patsas, patvinen, kajahtaa",
     "the birch-bark pillar rang.",
     "The entire house is animated by the music — the trickster's art transforms domestic space into a living, vibrating entity."),

    ("Kun hän kulki kuusikossa,",
     "Kun hän kulki kuusikossa,",
     "kun, hän, kulkea, kuusikko",
     "When he walked through the spruce grove,",
     ""),

    ("vaelti petäjikössä,",
     "vaelti petäjikössä,",
     "vaeltaa, petäjikkö",
     "wandered through the pine forest,",
     ""),

    ("kuusoset kumartelihe,",
     "kuuset kumartautuivat,",
     "kuusi, kumartautua",
     "the spruces bowed,",
     ""),

    ("männyt mäellä kääntelihe,",
     "männyt mäellä kääntelivät,",
     "mänty, mäki, kääntää",
     "the pines on the hill turned,",
     ""),

    ("käpöset keolle vieri,",
     "käpyset keolle vierivät,",
     "käpy, keko, vierimä",
     "the pine-cones rolled into heaps,",
     ""),

    ("havut juurelle hajosi.",
     "havut juurelle hajosivat.",
     "havu, juuri, hajota",
     "the spruce-branches scattered to the roots.",
     ""),

    ("Kun hän liikahti lehossa",
     "Kun hän liikahti lehossa",
     "kun, hän, liikahtaa, leho",
     "When he stirred in the grove",
     ""),

    ("tahi astahti aholla,",
     "tai astahti aholla,",
     "tai, astuhtaa, aho",
     "or stepped on the meadow,",
     ""),

    ("lehot leikkiä pitivät,",
     "lehdot leikkiä pitivät,",
     "lehto, leikki, pitää",
     "the groves played,",
     ""),

    ("ahot ainoista iloa,",
     "ahot yksinkertaista iloa,",
     "aho, ainoa, ilo",
     "the meadows showed singular joy,",
     ""),

    ("kukat kulkivat kutuhun,",
     "kukat kulkivat kutuhun,",
     "kukka, kulkea, kutu",
     "the flowers moved toward the call,",
     ""),

    ("vesat nuoret notkahteli.",
     "vesat nuoret notkahtivat.",
     "vesa, nuori, notkahta",
     "the young shoots bent.",
     "Wherever the trickster walks, nature dances and bows — the ultimate image of the shaman-trickster's total harmony with the natural world."),
]

# Style config
orig_fill = PatternFill("solid", start_color="F0F4F8", end_color="F0F4F8")
modern_fill = PatternFill("solid", start_color="EAF4EA", end_color="EAF4EA")
basic_fill = PatternFill("solid", start_color="FFF8E7", end_color="FFF8E7")
trans_fill = PatternFill("solid", start_color="F8F0FF", end_color="F8F0FF")
trick_fill = PatternFill("solid", start_color="FFE8E8", end_color="FFE8E8")
thin = Side(style='thin', color='CCCCCC')
border = Border(left=thin, right=thin, top=thin, bottom=thin)
fills = [orig_fill, modern_fill, basic_fill, trans_fill, trick_fill]

for i, (orig, mod, basic, trans, trick) in enumerate(verses, start=2):
    row = [orig, mod, basic, trans, trick]
    for col, (val, fill) in enumerate(zip(row, fills), start=1):
        cell = ws.cell(row=i, column=col, value=val)
        cell.font = Font(name="Arial", size=10)
        cell.alignment = Alignment(wrap_text=True, vertical="top")
        cell.fill = fill
        cell.border = border

ws.column_dimensions['A'].width = 32
ws.column_dimensions['B'].width = 32
ws.column_dimensions['C'].width = 30
ws.column_dimensions['D'].width = 38
ws.column_dimensions['E'].width = 55
ws.freeze_panes = "A2"
ws.row_dimensions[1].height = 30
for i in range(2, len(verses) + 2):
    ws.row_dimensions[i].height = 28

wb.save("kalevala_runo44.xlsx")
print(f"Done. {len(verses)} verses processed.")
