from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

wb = Workbook()
ws = wb.active
ws.title = "Runo 42"

# Headers
headers = ["A – Alkuperäinen säe", "B – Nykykieli", "C – Perusmuodot", "D – Käännös (EN)", "E – Trickster-huomio"]
header_fill = PatternFill("solid", start_color="2F4F6F", end_color="2F4F6F")
header_font = Font(name="Arial", bold=True, color="FFFFFF", size=11)

for col, h in enumerate(headers, 1):
    cell = ws.cell(row=1, column=col, value=h)
    cell.font = header_font
    cell.fill = header_fill
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

# Data: (original, modern Finnish, basic forms, English translation, trickster note)
verses = [
    ("Vaka vanha Väinämöinen,",
     "Vaka vanha Väinämöinen,",
     "vakaa, vanha, Väinämöinen",
     "steady, old, Väinämöinen",
     "Väinämöinen is the wise shaman-trickster figure: his epithet 'vaka' (steady) is ironic given his cunning plans."),

    ("toinen seppo Ilmarinen,",
     "toinen seppä Ilmarinen,",
     "toinen, seppä, Ilmarinen",
     "the second, the smith, Ilmarinen",
     ""),

    ("kolmas lieto Lemmin poika,",
     "kolmas lieto Lemmin poika,",
     "kolmas, lieto, Lempi, poika",
     "the third, carefree/fickle, Lempi's son",
     "Lemminkäinen's epithet 'lieto' (carefree, fickle) marks him as a trickster type: impulsive, boastful, unreliable."),

    ("tuo on kaunis Kaukomieli,",
     "tuo on kaunis Kaukomieli,",
     "tuo, kaunis, Kaukomieli",
     "that one is handsome Kaukomieli (Far-mind)",
     "Kaukomieli ('Far-mind') suggests someone whose thoughts roam beyond boundaries — a trickster trait."),

    ("läksi selvälle merelle,",
     "lähti selvälle merelle,",
     "lähteä, selvä, meri",
     "set off onto the open sea",
     ""),

    ("lake'ille lainehille",
     "lakeille lainehille",
     "lakea, laine",
     "onto the flat waves",
     ""),

    ("tuonne kylmähän kylähän,",
     "tuonne kylmään kylään,",
     "tuo, kylmä, kylä",
     "to that cold village",
     ""),

    ("pimeähän Pohjolahan,",
     "pimeään Pohjolaan,",
     "pimeä, Pohjoola",
     "to dark Pohjola (the North)",
     ""),

    ("miehen syöjähän sijahan,",
     "miehen syöjään sijaan,",
     "mies, syödä, sija",
     "to the place that devours men",
     "Pohjola is characterized as a devouring, dangerous place — the trickster's destination, the liminal underworld."),

    ("urohon upottajahan.",
     "urohon upottajaan.",
     "uros, upottaa",
     "the drowner of heroes",
     ""),

    ("Kenpä tuossa soutajaksi?",
     "Kenpä tuossa soutajaksi?",
     "ken, tuo, soutaja",
     "Who then to be the rower there?",
     ""),

    ("Yks' on seppo Ilmarinen.",
     "Yksi on seppä Ilmarinen.",
     "yksi, seppä, Ilmarinen",
     "One is the smith Ilmarinen.",
     ""),

    ("Sepä tuossa soutajaksi",
     "Sepä tuossa soutajaksi",
     "se, tuo, soutaja",
     "He then as the rower",
     ""),

    ("airoillen ylimäisille;",
     "airoille ylimmäisille;",
     "airo, ylimmäinen",
     "at the upper oars;",
     ""),

    ("toinen lieto Lemminkäinen",
     "toinen lieto Lemminkäinen",
     "toinen, lieto, Lemminkäinen",
     "the other, fickle Lemminkäinen",
     ""),

    ("airoillen alimaisille.",
     "airoille alimmaisille.",
     "airo, alimmainen",
     "at the lower oars.",
     ""),

    ("Vaka vanha Väinämöinen",
     "Vaka vanha Väinämöinen",
     "vakaa, vanha, Väinämöinen",
     "Steady old Väinämöinen",
     ""),

    ("itse istuihe perähän.",
     "itse istuutui perään.",
     "itse, istua, perä",
     "himself sat at the stern.",
     "The trickster takes the steering position — he controls the direction."),

    ("Laskea karehtelevi;",
     "Laskea karehtelee;",
     "laskea, karrella",
     "He sails along gliding;",
     ""),

    ("laski halki lainehien,",
     "laski halki laineiden,",
     "laskea, halki, laine",
     "sailed across the waves,",
     ""),

    ("noien kuohujen kovien,",
     "noiden kuohujen kovien,",
     "nuo, kuohu, kova",
     "through the hard surges,",
     ""),

    ("lakkipäien lainehien",
     "lakkipäisten laineiden",
     "lakkipäinen, laine",
     "the capped (white-crested) waves",
     ""),

    ("vasten Pohjan valkamoita,",
     "vasten Pohjan valkamoita,",
     "vasten, pohja, valkama",
     "against the harbours of the North,",
     ""),

    ("ennen tiettyjä teloja.",
     "ennen tuttuja teloja.",
     "ennen, tuttu, tela",
     "the previously known rollers (for beaching boats).",
     ""),

    ("Jopa tuonne tultuansa,",
     "Jo tuonne tultuaan,",
     "jo, tuo, tulla",
     "Once arrived there,",
     ""),

    ("matkan päähän päästyänsä",
     "matkan päähän päästyään",
     "matka, pää, päästä",
     "having reached the end of the journey",
     ""),

    ("vetivät venosen maalle,",
     "vetivät veneen maalle,",
     "vetää, vene, maa",
     "they pulled the boat ashore,",
     ""),

    ("tempasivat tervarinnan",
     "tempasivat tervarinnan",
     "tempaista, tervarinne",
     "snatched the tar-sided hull",
     ""),

    ("teloille teräksisille,",
     "teloille teräksisille,",
     "tela, teräksinen",
     "onto the steel rollers,",
     ""),

    ("valkamoille vaskisille.",
     "valkamoille vaskisille.",
     "valkama, vaskinen",
     "onto the copper harbours.",
     ""),

    ("Tulivat tuville tuosta,",
     "Tulivat tuvalle tuosta,",
     "tulla, tupa",
     "They came to the cabin from there,",
     ""),

    ("pian pistihe sisälle.",
     "pian pisti sisälle.",
     "pian, pistää, sisälle",
     "soon slipped inside.",
     "Stealthy, quick entry — trickster infiltration of enemy space."),

    ("Kysyi Pohjolan emäntä,",
     "Kysyi Pohjolan emäntä,",
     "kysyä, Pohjola, emäntä",
     "The mistress of Pohjola asked,",
     "Louhi is herself a trickster figure — a powerful witch who questions intruders."),

    ("tutkaeli tullehilta:",
     "tutkaili tulleista:",
     "tutkailla, tulla",
     "probed the arrivals:",
     ""),

    ("\"Mipä miehillä sanoma,",
     "\"Mikä miehillä sanoma,",
     "mikä, mies, sanoma",
     "\"What news do the men bring,",
     ""),

    ("urohilla uusi tieto?\"",
     "urohilla uusi tieto?\"",
     "uros, uusi, tieto",
     "what new knowledge for the heroes?\"",
     ""),

    ("Vaka vanha Väinämöinen,",
     "Vaka vanha Väinämöinen,",
     "vakaa, vanha, Väinämöinen",
     "Steady old Väinämöinen,",
     ""),

    ("tuopa tuohon vastoavi:",
     "tuo vastaa siihen:",
     "tuo, vastata",
     "that one replies to it:",
     ""),

    ("\"Sammosta sanomat miesten,",
     "\"Sammosta sanomat miesten,",
     "Sampo, sanoma, mies",
     "\"The men's news is about the Sampo,",
     "Väinämöinen's deceptive framing — he is being deliberately vague. Classic trickster rhetorical strategy."),

    ("kirjokannesta urosten:",
     "kirjokannesta urosten:",
     "kirjokansi, uros",
     "the heroes' news about the coloured lid:",
     ""),

    ("saimme sampuen jaolle,",
     "saimme sammon jaolle,",
     "saada, Sampo, jako",
     "we have gained the Sampo for sharing,",
     "Framing the theft as a 'share' is a trickster rhetorical trick — he pretends it is a negotiation."),

    ("kirjokannen katselulle.\"",
     "kirjokannen katselulle.\"",
     "kirjokansi, katselu",
     "the coloured lid for viewing.\"",
     ""),

    ("Itse Pohjolan emäntä",
     "Itse Pohjolan emäntä",
     "itse, Pohjola, emäntä",
     "The mistress of Pohjola herself",
     ""),

    ("sanan virkkoi, noin nimesi:",
     "sanan virkkoi, noin sanoi:",
     "sana, virkkoa, sanoa",
     "spoke a word, named it thus:",
     ""),

    ("\"Ei pyyssä kahen jakoa,",
     "\"Ei pyssyssä kahden jakoa,",
     "ei, pyy, kaksi, jako",
     "\"There is no sharing of two from a hazel-grouse,",
     "Louhi uses a proverbial, trickster-like saying to refuse sharing."),

    ("oravassa miehen kolmen.",
     "oravassa miehen kolmen.",
     "orava, mies, kolme",
     "no sharing among three men of a squirrel.",
     ""),

    ("Hyvä on sampuen hyrätä,",
     "Hyvä on sammon hyrätä,",
     "hyvä, Sampo, hyrrätä",
     "Good it is for the Sampo to spin,",
     ""),

    ("kirjokannen kahnatella",
     "kirjokannen kahnatella",
     "kirjokansi, kahnatella",
     "for the coloured lid to grind",
     ""),

    ("Pohjolan kivimäessä,",
     "Pohjolan kivimäessä,",
     "Pohjola, kivimäki",
     "in the stone hill of Pohjola,",
     ""),

    ("vaaran vaskisen sisässä.",
     "vaaran vaskisen sisässä.",
     "vaara, vaskinen, sisä",
     "inside the copper hill.",
     ""),

    ("Hyvä olla itseniki",
     "Hyvä olla itsenikin",
     "hyvä, olla, itse",
     "Good it is for me myself",
     ""),

    ("sammon suuren haltijana.\"",
     "sammon suuren haltijana.\"",
     "Sampo, suuri, haltija",
     "to be the keeper of the great Sampo.\"",
     "Louhi asserts sole ownership — her possessiveness is a counter-trickster move."),

    ("Vaka vanha Väinämöinen",
     "Vaka vanha Väinämöinen",
     "vakaa, vanha, Väinämöinen",
     "Steady old Väinämöinen",
     ""),

    ("sanan virkkoi, noin nimesi:",
     "sanan virkkoi, noin sanoi:",
     "sana, virkkoa, sanoa",
     "spoke a word, named it thus:",
     ""),

    ("\"Kun et antane osoa,",
     "\"Kun et anna osaa,",
     "kun, antaa, osa",
     "\"If you will not give a share,",
     "Väinämöinen's ultimatum is a bluff — he already plans to steal it. Classic trickster double-speak."),

    ("tuota sammon toista puolta,",
     "tuota sammon toista puolta,",
     "tuo, Sampo, toinen, puoli",
     "that other half of the Sampo,",
     ""),

    ("niin on kaiken kantanemme,",
     "niin on kaiken kantamamme,",
     "niin, kaikki, kantaa",
     "then we will carry it all,",
     ""),

    ("vienemme venehesemme.\"",
     "viemme veneessämme.\"",
     "viemä, vene",
     "take it in our boat.\"",
     ""),

    ("Louhi, Pohjolan emäntä,",
     "Louhi, Pohjolan emäntä,",
     "Louhi, Pohjola, emäntä",
     "Louhi, mistress of Pohjola,",
     ""),

    ("tuo tuosta pahoin pahastui.",
     "tuo tuosta pahoin pahastui.",
     "tuo, pahoin, pahastua",
     "that one was greatly angered by this.",
     ""),

    ("Kutsui Pohjolan kokohon,",
     "Kutsui Pohjolan kokoon,",
     "kutsua, Pohjola, koolle",
     "She summoned Pohjola together,",
     ""),

    ("nuoret miehet miekkoinensa,",
     "nuoret miehet miekkoineen,",
     "nuori, mies, miekka",
     "the young men with their swords,",
     ""),

    ("urohot asehinensa",
     "urohot aseineen",
     "uros, ase",
     "the heroes with their weapons",
     ""),

    ("pään varalle Väinämöisen.",
     "pään varalle Väinämöisen.",
     "pää, vara, Väinämöinen",
     "against the head of Väinämöinen.",
     ""),

    ("Vaka vanha Väinämöinen",
     "Vaka vanha Väinämöinen",
     "vakaa, vanha, Väinämöinen",
     "Steady old Väinämöinen",
     ""),

    ("kävi kanteloisehensa,",
     "kävi kanteleelleen,",
     "käydä, kantele",
     "went to his kantele,",
     "The kantele is Väinämöinen's trickster tool — music as a weapon of deception and control."),

    ("itse istui soittamahan,",
     "itse istui soittamaan,",
     "itse, istua, soittaa",
     "himself sat down to play,",
     ""),

    ("alkoi soittoa somasti.",
     "alkoi soittaa somasti.",
     "alkaa, soittaa, soma",
     "began to play beautifully.",
     ""),

    ("Tuota kaikki kuulemahan,",
     "Tuota kaikki kuulemaan,",
     "tuo, kaikki, kuulla",
     "All came to listen to it,",
     ""),

    ("iloa imehtimähän,",
     "iloa ihastelemaan,",
     "ilo, ihastella",
     "to marvel at the joy,",
     ""),

    ("miehet mielellä hyvällä,",
     "miehet mielellä hyvällä,",
     "mies, mieli, hyvä",
     "men with good spirits,",
     ""),

    ("naiset suulla nauravalla,",
     "naiset suulla nauravalla,",
     "nainen, suu, nauraa",
     "women with laughing mouths,",
     ""),

    ("urohot vesissä silmin,",
     "urohot vesissä silmin,",
     "uros, vesi, silmä",
     "heroes with wet eyes,",
     ""),

    ("pojat maassa polvillansa.",
     "pojat maassa polvillaan.",
     "poika, maa, polvi",
     "boys on their knees on the ground.",
     ""),

    ("Väkeä väsyttelevi,",
     "Väkeä väsyttelee,",
     "väki, väsyttää",
     "He wearies the people,",
     "Väinämöinen uses music to subdue his enemies — a signature trickster maneuver: winning by charm rather than force."),

    ("rahvahaista raukaisevi:",
     "rahvasta raukaisee:",
     "rahvas, raukaista",
     "lulls the folk to exhaustion:",
     ""),

    ("kaikki nukkui kuuntelijat",
     "kaikki nukkuivat kuuntelijat",
     "kaikki, nukkua, kuuntelija",
     "all the listeners fell asleep",
     "Putting enemies to sleep with music is a classic trickster/shaman trick — magical deception."),

    ("sekä vaipui katselijat;",
     "sekä vaipuivat katselijat;",
     "sekä, vaipua, katselija",
     "and the watchers sank down;",
     ""),

    ("nukkui nuoret, nukkui vanhat",
     "nukkuivat nuoret, nukkuivat vanhat",
     "nukkua, nuori, vanha",
     "the young slept, the old slept",
     ""),

    ("Väinämöisen soitantohon.",
     "Väinämöisen soittoon.",
     "Väinämöinen, soitto",
     "to Väinämöinen's playing.",
     ""),

    ("Siitä viisas Väinämöinen,",
     "Siitä viisas Väinämöinen,",
     "siitä, viisas, Väinämöinen",
     "Then wise Väinämöinen,",
     ""),

    ("tietäjä iän-ikuinen,",
     "tietäjä iänikuinen,",
     "tietäjä, iänikuinen",
     "the eternal knower/seer,",
     "'Tietäjä' (wise man, shaman) — the trickster as magical knowledge-holder."),

    ("tapasi on taskuhunsa,",
     "tapasi taskuunsa,",
     "tapailla, tasku",
     "felt into his pocket,",
     "Secretive action while others sleep — the trickster acting under cover."),

    ("kulki kukkaroisehensa.",
     "kulki kukkaroilleen.",
     "kulkea, kukkaroida",
     "went to his pouch.",
     ""),

    ("Ottavi uniset neulat,",
     "Ottaa uniset neulat,",
     "ottaa, uninen, neula",
     "He takes the sleep-needles,",
     "Magic needles that induce sleep — a quintessential trickster's tool, used covertly."),

    ("voiteli unella silmät,",
     "voiteli unella silmät,",
     "voidella, uni, silmä",
     "anointed the eyes with sleep,",
     ""),

    ("ripset ristihin panevi,",
     "ripset ristiin panee,",
     "ripsi, risti, panna",
     "placed the eyelashes crosswise,",
     ""),

    ("painoi luomet lukkosehen",
     "painoi luomet lukkoon",
     "painaa, luomi, lukko",
     "pressed the eyelids into a lock",
     "Locking eyes shut — magical act of restraint and control, trickster's power over others."),

    ("väeltä väsyneheltä,",
     "väeltä väsyneeltä,",
     "väki, väsynyt",
     "of the exhausted people,",
     ""),

    ("urohilta uinuvilta:",
     "urohilta uinuvilta:",
     "uros, uinua",
     "of the slumbering heroes:",
     ""),

    ("pani pitkähän unehen,",
     "pani pitkään uneen,",
     "panna, pitkä, uni",
     "put into a long sleep,",
     ""),

    ("viikommaksi nukkumahan",
     "viikoksi nukkumaan",
     "viikko, nukkua",
     "to sleep for a week",
     ""),

    ("koko Pohjolan perehen",
     "koko Pohjolan perheen",
     "koko, Pohjola, perhe",
     "the whole household of Pohjola",
     ""),

    ("ja kaiken kyläisen kansan.",
     "ja kaiken kyläisen kansan.",
     "ja, kaikki, kyläinen, kansa",
     "and all the village folk.",
     "Complete domination through deception and magic — ultimate trickster victory over enemies."),

    ("Meni sammon saa'antahan,",
     "Meni sammon saantaan,",
     "mennä, Sampo, saanti",
     "He went to get the Sampo,",
     ""),

    ("kirjokannen katsontahan",
     "kirjokannen katsomiseen",
     "kirjokansi, katsominen",
     "to look upon the coloured lid",
     ""),

    ("Pohjolan kivimäestä,",
     "Pohjolan kivimäestä,",
     "Pohjola, kivimäki",
     "from the stone hill of Pohjola,",
     ""),

    ("vaaran vaskisen sisästä,",
     "vaaran vaskisen sisästä,",
     "vaara, vaskinen, sisä",
     "from inside the copper hill,",
     ""),

    ("yheksän lukon takoa,",
     "yhdeksän lukon takaa,",
     "yhdeksän, lukko, takaa",
     "from behind nine locks,",
     "Breaking through nine locks — trickster overcoming supernatural obstacles."),

    ("takasalvan kymmenennen.",
     "takasalvan kymmenennen.",
     "takasalpa, kymmenes",
     "the tenth bolt/bar.",
     ""),

    ("Tuossa vanha Väinämöinen",
     "Tuossa vanha Väinämöinen",
     "tuossa, vanha, Väinämöinen",
     "There old Väinämöinen",
     ""),

    ("lauloa hyrähtelevi",
     "laulaa hyrähtelee",
     "laulaa, hyrähdellä",
     "hums and sings",
     "Singing to open locks — magic song as a trickster's key, bypassing physical barriers."),

    ("vaaran vaskisen ovilla,",
     "vaaran vaskisen ovilla,",
     "vaara, vaskinen, ovi",
     "at the doors of the copper hill,",
     ""),

    ("kivilinnan liepehillä:",
     "kivilinnan liepeillä:",
     "kilinlinna, liepe",
     "at the edges of the stone fortress:",
     ""),

    ("jopa liikkui linnan portit,",
     "jo liikkuivat linnan portit,",
     "jo, liikkua, linna, portti",
     "already the fortress gates moved,",
     ""),

    ("järkkyi rautaiset saranat.",
     "järkkyivät rautaiset saranat.",
     "järkkyä, rautainen, sarana",
     "the iron hinges shook.",
     ""),

    ("Itse seppo Ilmarinen,",
     "Itse seppä Ilmarinen,",
     "itse, seppä, Ilmarinen",
     "The smith Ilmarinen himself,",
     ""),

    ("tuopa tuossa toisna miesnä.",
     "tuo tuossa toisena miehenä.",
     "tuo, toinen, mies",
     "that one there as the second man.",
     ""),

    ("Voilla voiti lukkoloita,",
     "Voilla voiteli lukkoja,",
     "voi, voidella, lukko",
     "Greased the locks with butter,",
     "Ilmarinen uses a practical, cunning method to silence the locks — collaborative trickery."),

    ("saranoita rasvasilla,",
     "saranoita rasvaisilla,",
     "sarana, rasvainen",
     "the hinges with grease,",
     ""),

    ("jottei ukset ulvahuisi",
     "jottei ovet ulvahtaisi",
     "jotta, ovi, ulvahtaa",
     "so that the doors would not howl",
     ""),

    ("eikä naukuisi saranat.",
     "eikä naukuisi saranat.",
     "eikä, naukua, sarana",
     "nor the hinges creak.",
     "Silencing the doors — stealth and cunning, essential trickster tools."),

    ("Lukot sormin luksutteli,",
     "Lukkoja sormilla luksutteli,",
     "lukko, sormi, luksutella",
     "Picked the locks with fingers,",
     ""),

    ("salvat kuokalla kohotti:",
     "salvat kuokalla nosti:",
     "salpa, kuokka, nostaa",
     "lifted the bolts with a hoe:",
     "Using a farm tool as a lockpick — improvised trickster resourcefulness."),

    ("jo lukot lusuna vieri,",
     "jo lukot lusuna vierivät,",
     "jo, lukko, lusuna, vierimä",
     "already the locks slid loose,",
     ""),

    ("ovet vahvat aukieli.",
     "ovet vahvat aukesivat.",
     "ovi, vahva, aueta",
     "the strong doors opened.",
     ""),

    ("Siitä vanha Väinämöinen",
     "Siitä vanha Väinämöinen",
     "siitä, vanha, Väinämöinen",
     "Then old Väinämöinen",
     ""),

    ("itse tuon sanoiksi virkki:",
     "itse sen sanoiksi sanoi:",
     "itse, se, sana, virkkoa",
     "himself spoke it into words:",
     ""),

    ("\"Oi sie lieto Lemmin poika,",
     "\"Oi sinä lieto Lemmin poika,",
     "oi, sinä, lieto, Lempi, poika",
     "\"Oh you, fickle son of Lempi,",
     ""),

    ("ylimäinen ystäväni!",
     "ylimmäinen ystäväni!",
     "ylimmäinen, ystävä",
     "my dearest friend!",
     "Väinämöinen flatters Lemminkäinen to get him to do the risky task — a trickster's manipulation."),

    ("Mene sampo ottamahan,",
     "Mene sampo ottamaan,",
     "mennä, Sampo, ottaa",
     "Go to take the Sampo,",
     ""),

    ("kirjokansi kiskomahan!\"",
     "kirjokansi kiskomaan!\"",
     "kirjokansi, kiskoa",
     "to wrench the coloured lid!\"",
     "Delegating the dangerous task to the trickster-apprentice — shifting risk, trickster behavior."),

    ("Tuopa lieto Lemminkäinen",
     "Tuo lieto Lemminkäinen",
     "tuo, lieto, Lemminkäinen",
     "That fickle Lemminkäinen",
     ""),

    ("tahi kaunis Kaukomieli,",
     "tai kaunis Kaukomieli,",
     "tai, kaunis, Kaukomieli",
     "or handsome Kaukomieli,",
     ""),

    ("kyllä kärkäs käskemättä,",
     "kyllä kärkäs käskemättä,",
     "kyllä, kärkäs, käskeä",
     "quite keen without being commanded,",
     "Lemminkäinen acts eagerly without orders — impulsive trickster nature, self-motivated."),

    ("kehumattaki kepeä,",
     "kehumattakin kepeä,",
     "kehua, kepeä",
     "nimble without even being praised,",
     ""),

    ("meni sammon saa'antahan,",
     "meni sammon saantaan,",
     "mennä, Sampo, saanti",
     "went to get the Sampo,",
     ""),

    ("kirjokannen kiskontahan.",
     "kirjokannen kiskomiseen.",
     "kirjokansi, kiskoa",
     "to wrench the coloured lid.",
     ""),

    ("Sanoi tuonne mennessänsä,",
     "Sanoi tuonne mennessään,",
     "sanoa, tuo, mennä",
     "Said as he went there,",
     ""),

    ("kerskaeli käyessänsä:",
     "kerskaili käydessään:",
     "kerskuilla, käydä",
     "boasted as he went:",
     "Boasting while acting — a hallmark trickster trait: self-aggrandizement and bragging."),

    ("\"Mi lienee minussa miestä,",
     "\"Mikä lienee minussa miestä,",
     "mikä, lienee, minä, mies",
     "\"What manliness there may be in me,",
     ""),

    ("urosta Ukon pojassa,",
     "urosta Ukon pojassa,",
     "uros, Ukko, poika",
     "what heroism in the son of Ukko,",
     "Lemminkäinen claims divine heroic descent to inflate his self-image — trickster hubris."),

    ("senpä sampo siirtyköhön,",
     "sen takia sampo siirtykoon,",
     "se, Sampo, siirtyä",
     "so let the Sampo move,",
     ""),

    ("kirjokansi kääntyköhön",
     "kirjokansi kääntykoon",
     "kirjokansi, kääntyä",
     "let the coloured lid turn",
     ""),

    ("jalan oikean avulla,",
     "jalan oikean avulla,",
     "jalka, oikea, apu",
     "with the help of the right foot,",
     "Lemminkäinen plans to use his body as a lever — a boastful, physical trickster approach."),

    ("takakannan koskemalla!\"",
     "takakannan koskemalla!\"",
     "takakanta, koskea",
     "by touching with the heel!\"",
     ""),

    ("Siirrytteli Lemminkäinen,",
     "Siirrytteli Lemminkäinen,",
     "siirtyä, Lemminkäinen",
     "Lemminkäinen kept trying to shift it,",
     ""),

    ("siirrytteli, käännytteli,",
     "siirrytteli, käännytteli,",
     "siirtyä, kääntyä",
     "kept shifting, kept turning,",
     ""),

    ("sylin sampoa syleili,",
     "sylein sampoa syleili,",
     "syli, Sampo, syleilemä",
     "embraced the Sampo with his arms,",
     ""),

    ("polvin maassa puuhaeli:",
     "polvin maassa puuhaili:",
     "polvi, maa, puuhata",
     "laboured on his knees on the ground:",
     ""),

    ("eipä sampo liikukana,",
     "eipä sampo liiku lainkaan,",
     "ei, Sampo, liikkua",
     "the Sampo would not move at all,",
     "The trickster fails — his boasting exceeded his ability. The Sampo resists."),

    ("kirjokansi kallukana;",
     "kirjokansi kallahda lainkaan;",
     "kirjokansi, kallahtaa",
     "the coloured lid would not budge;",
     ""),

    ("sen oli juuret juurruteltu",
     "sen oli juuret juurrutettu",
     "se, juuri, juurruttaa",
     "its roots had been rooted",
     ""),

    ("yheksän sylen syvähän.",
     "yhdeksän sylen syvyyteen.",
     "yhdeksän, syli, syvyys",
     "nine fathoms deep.",
     ""),

    ("Hyvä on härkä Pohjolassa,",
     "Hyvä on härkä Pohjolassa,",
     "hyvä, härkä, Pohjola",
     "There is a good ox in Pohjola,",
     ""),

    ("jok' on vahva vartalolta,",
     "joka on vahva vartalolta,",
     "joka, vahva, vartalo",
     "that is strong in body,",
     ""),

    ("ylen sitkeä sivulta,",
     "ylen sitkeä sivulta,",
     "ylen, sitkeä, sivu",
     "exceedingly tough in flank,",
     ""),

    ("suonilta kovin sorea;",
     "suonilta kovin sorea;",
     "suoni, kovin, sorea",
     "very fine in sinew;",
     ""),

    ("sen on syltä sarvet pitkät,",
     "sillä on syltä sarvet pitkät,",
     "se, syli, sarvi, pitkä",
     "its horns a fathom long,",
     ""),

    ("puolentoista turpa paksu.",
     "puolentoista turpa paksu.",
     "puolitoista, turpa, paksu",
     "its muzzle one-and-a-half (fathoms) thick.",
     ""),

    ("Otti härän heinikosta,",
     "Otti härän heinikosta,",
     "ottaa, härkä, heinikko",
     "He took the ox from the meadow,",
     ""),

    ("auran pellon pientarelta;",
     "auran pellon pientarelta;",
     "aura, pelto, piennar",
     "the plough from the field's edge;",
     ""),

    ("sillä kynti sammon juuret,",
     "sillä kynti sammon juuret,",
     "se, kyntää, Sampo, juuri",
     "with it ploughed up the Sampo's roots,",
     "Lemminkäinen pragmatically uses the environment's own resources — adaptive trickster thinking."),

    ("kirjokannen kiinnittimet:",
     "kirjokannen kiinnittimet:",
     "kirjokansi, kiinnitin",
     "the fastenings of the coloured lid:",
     ""),

    ("saipa sampo liikkumahan,",
     "sai sampo liikkumaan,",
     "saada, Sampo, liikkua",
     "the Sampo began to move,",
     ""),

    ("kirjokansi kallumahan.",
     "kirjokansi kallahtamaan.",
     "kirjokansi, kallahtaa",
     "the coloured lid began to budge.",
     ""),

    ("Siitä vanha Väinämöinen,",
     "Siitä vanha Väinämöinen,",
     "siitä, vanha, Väinämöinen",
     "Then old Väinämöinen,",
     ""),

    ("toinen seppo Ilmarinen,",
     "toinen seppä Ilmarinen,",
     "toinen, seppä, Ilmarinen",
     "the second, smith Ilmarinen,",
     ""),

    ("kolmas lieto Lemminkäinen",
     "kolmas lieto Lemminkäinen",
     "kolmas, lieto, Lemminkäinen",
     "the third, fickle Lemminkäinen",
     ""),

    ("saattelivat sammon suuren",
     "saattelivat sammon suuren",
     "saatella, Sampo, suuri",
     "escorted the great Sampo",
     ""),

    ("Pohjolan kivimäestä,",
     "Pohjolan kivimäestä,",
     "Pohjola, kivimäki",
     "from the stone hill of Pohjola,",
     ""),

    ("vaaran vaskisen sisästä.",
     "vaaran vaskisen sisästä.",
     "vaara, vaskinen, sisä",
     "from inside the copper hill.",
     ""),

    ("Veivät sen venosehensa,",
     "Veivät sen veneeseen,",
     "viedä, se, vene",
     "They carried it to their boat,",
     ""),

    ("latjasivat laivahansa.",
     "latasivat laivaan.",
     "ladata, laiva",
     "loaded it onto their vessel.",
     "The stolen treasure loaded — the trickster heist is complete."),

    ("Saivat sammon purtehensa,",
     "Saivat sammon purteensa,",
     "saada, Sampo, pursi",
     "They got the Sampo into their vessel,",
     ""),

    ("kirjokannen kaarillensa;",
     "kirjokannen kaarillensa;",
     "kirjokansi, kaari",
     "the coloured lid onto their bow-ribs;",
     ""),

    ("työntivät venon vesille,",
     "työnsivät veneen vesille,",
     "työntää, vene, vesi",
     "pushed the boat into the water,",
     ""),

    ("satalauan lainehille.",
     "satalaidan lainehille.",
     "satalapa, laine",
     "onto the waves by the hundred-plank.",
     ""),

    ("Tyrskähti veno vetehen,",
     "Tyrskähti vene veteen,",
     "tyrskähtää, vene, vesi",
     "The boat splashed into the water,",
     ""),

    ("läksi laioin lainehesen.",
     "lähti laitoineen lainehille.",
     "lähteä, laita, laine",
     "set off with its sides onto the waves.",
     ""),

    ("Kysyi seppo Ilmarinen,",
     "Kysyi seppä Ilmarinen,",
     "kysyä, seppä, Ilmarinen",
     "The smith Ilmarinen asked,",
     ""),

    ("sanan virkkoi, noin nimesi:",
     "sanan virkkoi, noin sanoi:",
     "sana, virkkoa, sanoa",
     "spoke a word, named it thus:",
     ""),

    ("\"Minne sampo saatetahan,",
     "\"Minne sampo viedään,",
     "minne, Sampo, saattaa",
     "\"Where is the Sampo to be taken,",
     ""),

    ("kunnepa kuletetahan",
     "minne se kuljetetaan",
     "minne, kuljettaa",
     "where is it to be conveyed",
     ""),

    ("näiltä paikoilta pahoilta,",
     "näiltä paikoilta pahoilta,",
     "nämä, paikka, paha",
     "from these evil places,",
     ""),

    ("poloisesta Pohjolasta?\"",
     "poloisesta Pohjolasta?\"",
     "poloinen, Pohjola",
     "from miserable Pohjola?\"",
     ""),

    ("Vaka vanha Väinämöinen",
     "Vaka vanha Väinämöinen",
     "vakaa, vanha, Väinämöinen",
     "Steady old Väinämöinen",
     ""),

    ("itse virkki, noin nimesi:",
     "itse sanoi, noin sanoi:",
     "itse, sanoa",
     "himself said, named it thus:",
     ""),

    ("\"Tuonne sampo saatetahan,",
     "\"Tuonne sampo viedään,",
     "tuo, Sampo, saattaa",
     "\"The Sampo is to be taken there,",
     ""),

    ("kirjokansi kaimatahan",
     "kirjokansi kuljetaan",
     "kirjokansi, kaimata",
     "the coloured lid conveyed",
     ""),

    ("nenähän utuisen niemen,",
     "nenään utuisen niemen,",
     "nenä, utuinen, niemi",
     "to the tip of the misty headland,",
     "Vagueness about the destination — the trickster never fully reveals his plans."),

    ("päähän saaren terhenisen,",
     "päähän saaren terhenisen,",
     "pää, saari, terheninen",
     "to the head of the foggy island,",
     ""),

    ("siellä onnen ollaksensa,",
     "siellä onnen ollakseen,",
     "siellä, onni, olla",
     "there to be for good fortune,",
     ""),

    ("ainian asuaksensa.",
     "aina asuakseen.",
     "aina, asua",
     "to dwell there forever.",
     ""),

    ("On siellä vähän sijoa,",
     "On siellä vähän sijaa,",
     "olla, siellä, vähän, sija",
     "There is a little room there,",
     ""),

    ("toki paikkoa palanen,",
     "toki paikkaa palanenkin,",
     "toki, paikka, palanen",
     "indeed a little piece of place,",
     ""),

    ("syömätöintä, lyömätöintä,",
     "syömätöntä, lyömätöntä,",
     "syömätön, lyömätön",
     "undevoured, unbeaten,",
     ""),

    ("miekan miehen käymätöintä.\"",
     "miekan miehen käymätöntä.\"",
     "miekka, mies, käymätön",
     "untrodden by the sword-man.\"",
     "Describing a hidden, safe place — the trickster's secret refuge beyond the reach of authority."),

    ("Siitä vanha Väinämöinen",
     "Siitä vanha Väinämöinen",
     "siitä, vanha, Väinämöinen",
     "Then old Väinämöinen",
     ""),

    ("läksi poies Pohjolasta,",
     "lähti pois Pohjolasta,",
     "lähteä, pois, Pohjola",
     "left away from Pohjola,",
     ""),

    ("läksi mielellä hyvällä,",
     "lähti mielellä hyvällä,",
     "lähteä, mieli, hyvä",
     "left in good spirits,",
     ""),

    ("iloten omille maille.",
     "iloiten omille maille.",
     "iloita, oma, maa",
     "rejoicing toward his own lands.",
     "Triumphant departure — the trickster has won."),

    ("Itse tuossa noin saneli:",
     "Itse tuossa noin saneli:",
     "itse, tuo, sanella",
     "He himself then spoke thus:",
     ""),

    ("\"Käänny, pursi, Pohjolasta,",
     "\"Käänny, pursi, Pohjolasta,",
     "kääntyä, pursi, Pohjola",
     "\"Turn, boat, away from Pohjola,",
     ""),

    ("käännäite kohen kotia,",
     "käänny kohti kotia,",
     "kääntyä, kohti, koti",
     "turn toward home,",
     ""),

    ("perin maille vierahille!",
     "periytyneille maille vieraille!",
     "perintö, maa, vieras",
     "to the far foreign lands!",
     ""),

    ("\"Tuuittele, tuuli, purtta,",
     "\"Tuuittele, tuuli, purtta,",
     "tuuittaa, tuuli, pursi",
     "\"Blow, wind, the boat along,",
     "Väinämöinen commands the natural world — the trickster-shaman's power over nature."),

    ("soutele, vesi, venettä,",
     "soutele, vesi, venettä,",
     "soutaa, vesi, vene",
     "row, water, the vessel,",
     ""),

    ("anna airoillen apua,",
     "anna airoille apua,",
     "antaa, airo, apu",
     "give help to the oars,",
     ""),

    ("huoparille huoitusta",
     "huoparille huoitusta",
     "huopari, huoitus",
     "relief to the helmsman",
     ""),

    ("noilla väljillä vesillä,",
     "noilla väljillä vesillä,",
     "nuo, väljä, vesi",
     "on those wide waters,",
     ""),

    ("ulapoilla auke'illa!",
     "ulapoilla aukaisilla!",
     "ulappa, aukeainen",
     "on the open expanses!",
     ""),

    ("\"Oisiko airot pikkaraiset,",
     "\"Olisivatko airot pienoiset,",
     "olla, airo, pienoi",
     "\"Were the oars but small,",
     ""),

    ("soutajat vähäväkiset,",
     "soutajat vähäväkiset,",
     "soutaja, vähäväkinen",
     "the rowers weak,",
     ""),

    ("pienoiset peränpitäjät,",
     "pienoiset peränpitäjät,",
     "pienoi, perä, pitää",
     "small the steersmen,",
     ""),

    ("lapset laivan hallitsijat,",
     "lapset laivan hallitsijat,",
     "lapsi, laiva, hallita",
     "children the rulers of the ship,",
     ""),

    ("anna, Ahto, airojasi,",
     "anna, Ahto, airojasi,",
     "antaa, Ahto, airo",
     "give, Ahto, your oars,",
     "Invoking Ahto (sea god) for help — trickster-shaman calling on supernatural aid."),

    ("venettäsi, veen isäntä,",
     "venettäsi, veden isäntä,",
     "vene, vesi, isäntä",
     "your boat, master of the waters,",
     ""),

    ("airot uuet ja paremmat,",
     "airot uudet ja paremmat,",
     "airo, uusi, hyvä",
     "new and better oars,",
     ""),

    ("mela toinen ja lujempi,",
     "mela toinen ja lujempi,",
     "mela, toinen, luja",
     "another and sturdier paddle,",
     ""),

    ("itse airoillen asetu,",
     "itse airoille asetu,",
     "itse, airo, asettua",
     "yourself take to the oars,",
     ""),

    ("sovitaite soutamahan!",
     "sovittaudu soutamaan!",
     "sovittautua, soutaa",
     "settle yourself to rowing!",
     ""),

    ("Anna juosta puisen purren,",
     "Anna juosta puisen purren,",
     "antaa, juosta, puinen, pursi",
     "Let the wooden vessel run,",
     ""),

    ("rautahangan hakkaella",
     "rautahangan hakulla",
     "rautahanka, hakku",
     "with the iron rowlock's stroke",
     ""),

    ("halki kuohujen kovien,",
     "halki kuohujen kovien,",
     "halki, kuohu, kova",
     "through the hard surges,",
     ""),

    ("lakkipäien lainehien!\"",
     "lakkipäisten laineiden!\"",
     "lakkipäinen, laine",
     "through the capped waves!\"",
     ""),

    ("Siitä vanha Väinämöinen",
     "Siitä vanha Väinämöinen",
     "siitä, vanha, Väinämöinen",
     "Then old Väinämöinen",
     ""),

    ("laskea karehtelevi.",
     "laskee karehtelee.",
     "laskea, karrella",
     "sails gliding along.",
     ""),

    ("Itse seppo Ilmarinen,",
     "Itse seppä Ilmarinen,",
     "itse, seppä, Ilmarinen",
     "The smith Ilmarinen himself,",
     ""),

    ("toinen lieto Lemminkäinen,",
     "toinen lieto Lemminkäinen,",
     "toinen, lieto, Lemminkäinen",
     "the other fickle Lemminkäinen,",
     ""),

    ("nepä tuossa soutelevat,",
     "nämä tuossa soutelevat,",
     "nämä, tuo, soutaa",
     "those two there rowing,",
     ""),

    ("soutelevat, joutelevat",
     "soutelevat, joutavat",
     "soutaa, joutaa",
     "rowing, gliding freely",
     ""),

    ("selviä selän vesiä,",
     "selviä selän vesiä,",
     "selvä, selkä, vesi",
     "across the clear open waters,",
     ""),

    ("lake'ita lainehia.",
     "lakeita lainehia.",
     "lakea, laine",
     "across the flat waves.",
     ""),

    ("Sanoi lieto Lemminkäinen:",
     "Sanoi lieto Lemminkäinen:",
     "sanoa, lieto, Lemminkäinen",
     "Fickle Lemminkäinen said:",
     ""),

    ("\"Olipa ennen aikoinani,",
     "\"Olikin ennen aikoinani,",
     "olla, ennen, aika",
     "\"There was a time in my days,",
     ""),

    ("oli vettä soutajalla",
     "oli vettä soutajalla",
     "olla, vesi, soutaja",
     "there was water for the rower",
     ""),

    ("sekä virttä laulajalla.",
     "sekä virsiä laulajalla.",
     "sekä, virsi, laulaja",
     "and songs for the singer.",
     ""),

    ("Vaan ei nyt, nykyisin aioin",
     "Vaan ei nyt, nykyisin aikoin",
     "vaan, ei, nyt, nykyisin, aika",
     "But not now, in these current times",
     ""),

    ("tuota kuulla kulloinkana",
     "tuota kuulla milloinkaan",
     "tuo, kuulla, milloinkaan",
     "can one ever hear that",
     ""),

    ("venehessä vierentätä,",
     "veneessä vierentämistä,",
     "vene, vierentää",
     "the rolling in the boat,",
     ""),

    ("lainehilla laulantata.\"",
     "lainehilla laulamista.\"",
     "laine, laulaa",
     "the singing on the waves.\"",
     "Lemminkäinen complains — he wants entertainment and glory, the trickster's craving for attention."),

    ("Vaka vanha Väinämöinen",
     "Vaka vanha Väinämöinen",
     "vakaa, vanha, Väinämöinen",
     "Steady old Väinämöinen",
     ""),

    ("sanan virkkoi, noin nimesi:",
     "sanan virkkoi, noin sanoi:",
     "sana, virkkoa, sanoa",
     "spoke a word, named it thus:",
     ""),

    ("\"Ei vesillä vieremistä,",
     "\"Ei vesillä vieremistä,",
     "ei, vesi, vieriminen",
     "\"No rolling on the waters,",
     ""),

    ("lainehilla laulamista!",
     "lainehilla laulamista!",
     "laine, laulaa",
     "no singing on the waves!",
     ""),

    ("Laulu laiskana pitävi,",
     "Laulu laiskana pitää,",
     "laulu, laiska, pitää",
     "Song keeps one idle,",
     ""),

    ("virret sou'un viivyttävi.",
     "virret soudun viivyttää.",
     "virsi, soutu, viivyttää",
     "songs delay the rowing.",
     "Väinämöinen pragmatically refuses song — the wise trickster can suppress his own nature when needed."),

    ("Päivä kultainen kuluisi,",
     "Päivä kultainen kuluisi,",
     "päivä, kultainen, kulua",
     "The golden day would pass,",
     ""),

    ("yöhyt kesken yllättäisi",
     "yö kesken yllättäisi",
     "yö, keski, yllättää",
     "night would catch us in the middle",
     ""),

    ("näillä väljillä vesillä,",
     "näillä väljillä vesillä,",
     "nämä, väljä, vesi",
     "on these wide waters,",
     ""),

    ("lake'illa lainehilla.\"",
     "lakeilla lainehilla.\"",
     "lakea, laine",
     "on the flat waves.\"",
     ""),

    ("Se on lieto Lemminkäinen",
     "Se on lieto Lemminkäinen",
     "se, lieto, Lemminkäinen",
     "That fickle Lemminkäinen",
     ""),

    ("sanan virkkoi, noin nimesi:",
     "sanan virkkoi, noin sanoi:",
     "sana, virkkoa, sanoa",
     "spoke a word, named it thus:",
     ""),

    ("\"Aika kuitenki kuluvi,",
     "\"Aika kuitenkin kuluu,",
     "aika, kuitenkin, kulua",
     "\"Time passes regardless,",
     ""),

    ("päivä kaunis karkelevi,",
     "päivä kaunis karkelee,",
     "päivä, kaunis, karkella",
     "the beautiful day dances along,",
     ""),

    ("yö tulla tuhuttelevi,",
     "yö tulla tuhuttelee,",
     "yö, tulla, tuhuttaa",
     "night comes blowing in,",
     ""),

    ("hämärä häkyttelevi,",
     "hämärä häkyttelee,",
     "hämärä, häkyttää",
     "the dusk hovers about,",
     ""),

    ("jos et laula polvenasi,",
     "jos et laula polveksesi,",
     "jos, laulaa, polvi",
     "if you do not sing your verse,",
     ""),

    ("hyrehi sinä ikänä.\"",
     "hyräile sinä ikinä.\"",
     "hyräillä, sinä, ikinä",
     "hum, ever.\"",
     "Lemminkäinen persistently pushes for song — the trickster who won't take no for an answer."),

    ("Laski vanha Väinämöinen",
     "Laski vanha Väinämöinen",
     "laskea, vanha, Väinämöinen",
     "Old Väinämöinen sailed",
     ""),

    ("selkeä meren sinisen,",
     "selkeää meren sinistä,",
     "selkeä, meri, sininen",
     "across the clear blue sea,",
     ""),

    ("laski päivän, laski toisen.",
     "laski päivän, laski toisen.",
     "laskea, päivä, toinen",
     "sailed one day, sailed a second.",
     ""),

    ("Päivänäpä kolmantena",
     "Päivänä kolmantena",
     "päivä, kolmas",
     "On the third day",
     ""),

    ("tuo on lieto Lemminkäinen",
     "tuo on lieto Lemminkäinen",
     "tuo, lieto, Lemminkäinen",
     "that fickle Lemminkäinen",
     ""),

    ("kerran toisen kertaeli:",
     "kerran toisen kerran kyseli:",
     "kerta, toinen, kerrata",
     "repeated it a second time:",
     ""),

    ("\"Miks' et laula, Väinämöinen,",
     "\"Miksi et laula, Väinämöinen,",
     "miksi, laulaa, Väinämöinen",
     "\"Why don't you sing, Väinämöinen,",
     ""),

    ("hyrehi, hyväntöläinen,",
     "hyräile, hyväntahtoinen,",
     "hyräillä, hyväntahtoinen",
     "hum, good-natured one,",
     ""),

    ("hyvän sammon saatuasi,",
     "hyvän sammon saatuasi,",
     "hyvä, Sampo, saada",
     "now that you have gotten the good Sampo,",
     ""),

    ("tien oikein osattuasi?\"",
     "tien oikein osattuasi?\"",
     "tie, oikein, osata",
     "now that you have found the right road?\"",
     "Lemminkäinen uses flattery to get Väinämöinen to sing — the trickster manipulating the trickster."),

    ("Vaka vanha Väinämöinen,",
     "Vaka vanha Väinämöinen,",
     "vakaa, vanha, Väinämöinen",
     "Steady old Väinämöinen,",
     ""),

    ("hänpä varman vastoavi:",
     "hän varman vastaa:",
     "hän, varma, vastata",
     "he confidently answers:",
     ""),

    ("\"Varahainen laulannaksi,",
     "\"Varhain laulamiseen,",
     "varhainen, laulaminen",
     "\"It is too early for singing,",
     ""),

    ("aikainen ilonpioksi.",
     "aikainen ilon pitoon.",
     "aikainen, ilo, pito",
     "too soon for merrymaking.",
     ""),

    ("Äsken laulanta sopisi,",
     "Äsken laulu sopisi,",
     "äsken, laulu, sopia",
     "Song would be fitting soon,",
     ""),

    ("ilon teentä kelpoaisi,",
     "ilon teko kelpuutettaisiin,",
     "ilo, teko, kelpuuttaa",
     "merrymaking would be welcome,",
     ""),

    ("kun omat ovet näkyisi,",
     "kun omat ovet näkyisivät,",
     "oma, ovi, näkyä",
     "when one's own doors would be seen,",
     ""),

    ("omat ukset ulvahtaisi.\"",
     "omat ovet ulvahtaisivat.\"",
     "oma, ovi, ulvahtaa",
     "when one's own doors would creak open.\"",
     "Väinämöinen defers celebration to safety at home — the prudent, calculating trickster."),

    ("Sanoi lieto Lemminkäinen:",
     "Sanoi lieto Lemminkäinen:",
     "sanoa, lieto, Lemminkäinen",
     "Fickle Lemminkäinen said:",
     ""),

    ("\"Oisinko itse perässä,",
     "\"Olisinko itse perässä,",
     "olla, itse, perä",
     "\"If I were myself at the stern,",
     ""),

    ("lauleleisin voiessani,",
     "laulaisin voidessani,",
     "laulaa, voida",
     "I would sing while I could,",
     ""),

    ("kukkuisin kyetessäni;",
     "kukkuisin kyetessäni;",
     "kukkua, kyetä",
     "I would crow while I was able;",
     ""),

    ("ehk' ei toiste voiakana,",
     "ehkä ei toisin voisikaan,",
     "ehkä, ei, toinen, voida",
     "perhaps one could not do otherwise,",
     ""),

    ("ei kyllin kyetäkänä.",
     "ei kylliksi kykenekkään.",
     "ei, kyllin, kyetä",
     "nor be capable enough.",
     ""),

    ("Kun et lauloa luvanne,",
     "Kun et laululle lupaa anna,",
     "kun, laulu, lupa, antaa",
     "Since you will not permit singing,",
     ""),

    ("itse laululle rupean.\"",
     "itse lauluun rupean.\"",
     "itse, laulu, ruveta",
     "I myself will begin to sing.\"",
     "Lemminkäinen takes unilateral action — the reckless trickster who defies authority."),

    ("Siinä lieto Lemminkäinen,",
     "Siinä lieto Lemminkäinen,",
     "siinä, lieto, Lemminkäinen",
     "There fickle Lemminkäinen,",
     ""),

    ("tuo on kaunis Kaukomieli,",
     "tuo on kaunis Kaukomieli,",
     "tuo, kaunis, Kaukomieli",
     "that handsome Kaukomieli,",
     ""),

    ("suutansa sovittelevi,",
     "suutaan sovittelee,",
     "suu, sovitella",
     "adjusts his mouth,",
     ""),

    ("säveltänsä säätelevi.",
     "sävelensä säätelee.",
     "sävel, säädellä",
     "regulates his melody.",
     ""),

    ("Sai itse hyräilemähän,",
     "Sai itse hyräilemään,",
     "saada, itse, hyräillä",
     "Got himself to humming,",
     ""),

    ("loihe, kurja, kukkumahan",
     "lähti, kurja, kukkumaan",
     "lähteä, kurja, kukkua",
     "the poor wretch started to crow",
     "The narrator calls Lemminkäinen 'kurja' (wretch/miserable) — undercutting his trickster bravado."),

    ("äreällä äänellänsä,",
     "äreällä äänellään,",
     "äreä, ääni",
     "with his harsh voice,",
     ""),

    ("käreällä kulkullansa.",
     "käreällä kurkkuäänellään.",
     "käreä, kurkku",
     "with his sharp, rasping throat.",
     ""),

    ("Lauloi lieto Lemminkäinen,",
     "Lauloi lieto Lemminkäinen,",
     "laulaa, lieto, Lemminkäinen",
     "Fickle Lemminkäinen sang,",
     ""),

    ("karjahteli Kaukomieli;",
     "karjahteli Kaukomieli;",
     "karjahtaa, Kaukomieli",
     "Kaukomieli bellowed;",
     ""),

    ("suu liikkui, järisi parta,",
     "suu liikkui, järisi parta,",
     "suu, liikkua, järistä, parta",
     "his mouth moved, his beard trembled,",
     ""),

    ("leukapielet lonkaeli.",
     "leukapielet lonkahteli.",
     "leukapielet, lonkahtaa",
     "his jaw-sides rattled.",
     ""),

    ("Laulu kuului loitommalle,",
     "Laulu kuului loitommalle,",
     "laulu, kuulua, loitto",
     "The song was heard far away,",
     ""),

    ("vierähys vesien poikki,",
     "vierähys vesien poikki,",
     "vierähys, vesi, poikki",
     "the rolling sound across the waters,",
     ""),

    ("kuului kuutehen kylähän,",
     "kuului kuuteen kylään,",
     "kuulua, kuusi, kylä",
     "was heard across six villages,",
     ""),

    ("seitsemän selän ylitse.",
     "seitsemän selän ylitse.",
     "seitsemän, selkä, yli",
     "across seven open waters.",
     "Lemminkäinen's song has vast reach — trickster noise causing unintended consequences."),

    ("Kurki istui kannon päässä,",
     "Kurki istui kannon päässä,",
     "kurki, istua, kanto, pää",
     "A crane sat on the top of a stump,",
     ""),

    ("märän mättähän nenässä,",
     "märän mättähän nenässä,",
     "märkä, mätäs, nenä",
     "on the point of a wet tussock,",
     ""),

    ("sormiluitansa lukevi,",
     "sormiluitaan laskee,",
     "sormiluut, laskea",
     "counting its finger-bones,",
     ""),

    ("jalkojansa nostelevi.",
     "jalkojaan nostelee.",
     "jalka, nostella",
     "lifting its legs.",
     ""),

    ("Sepä säikähti kovasti",
     "Sepä säikähti kovasti",
     "se, säikähtää, kovasti",
     "It was greatly frightened",
     ""),

    ("Lemminkäisen laulantata.",
     "Lemminkäisen laulamisesta.",
     "Lemminkäinen, laulaminen",
     "by Lemminkäinen's singing.",
     ""),

    ("Päästi kurki kumman kulkun,",
     "Päästi kurki kumman äänen,",
     "päästää, kurki, kumma, kulkku",
     "The crane let out a strange cry,",
     ""),

    ("säikähti pahan sävelen;",
     "säikähti pahan sävelen;",
     "säikähtää, paha, sävel",
     "startled by the bad melody;",
     ""),

    ("heti loihe lentämähän,",
     "heti lähti lentämään,",
     "heti, lähteä, lentää",
     "immediately started to fly,",
     ""),

    ("lenti poikki Pohjolahan.",
     "lensi poikki Pohjolaan.",
     "lentää, poikki, Pohjola",
     "flew across to Pohjola.",
     "The crane flies to Pohjola — an inadvertent messenger, the trickster's recklessness undoes the plan."),

    ("Sitte tuonne tultuansa,",
     "Sitten tuonne tultuaan,",
     "sitten, tuo, tulla",
     "Then upon arriving there,",
     ""),

    ("Pohjan suolle saatuansa",
     "Pohjan suolle saavuttuaan",
     "pohja, suo, saapua",
     "upon reaching the swamp of the North",
     ""),

    ("vielä parkaisi pahasti,",
     "vielä parkaisi pahasti,",
     "vielä, parkaista, pahasti",
     "cried out once more terribly,",
     ""),

    ("äkeästi ärjähteli:",
     "äkeästi ärjähti:",
     "äkeästi, ärjähtää",
     "shrieked angrily:",
     ""),

    ("sillä Pohjolan herätti,",
     "sillä Pohjolan herätti,",
     "sillä, Pohjola, herättää",
     "thereby woke Pohjola,",
     "Lemminkäinen's foolish singing indirectly awakens the enemy — the trickster's blunder with consequences."),

    ("pahan vallan valveutti.",
     "pahan vallan herätti.",
     "paha, valta, herättää",
     "roused the evil power.",
     ""),

    ("Nousi Pohjolan emäntä",
     "Nousi Pohjolan emäntä",
     "nousta, Pohjola, emäntä",
     "The mistress of Pohjola rose",
     ""),

    ("unen pitkän maattuansa.",
     "pitkän unen maattuaan.",
     "pitkä, uni, maata",
     "after sleeping a long sleep.",
     ""),

    ("Kävi karjakartanohon,",
     "Kävi karjakartanoon,",
     "käydä, karjakartano",
     "She went to the cattle yard,",
     ""),

    ("juoksi riistariihen luoksi;",
     "juoksi riistariitan luokse;",
     "juosta, riistariita",
     "ran to the game storehouse;",
     ""),

    ("katselevi karjoansa,",
     "katseli karjojaan,",
     "katsella, karja",
     "looked at her herds,",
     ""),

    ("elojansa arvelevi:",
     "eloaan arveli:",
     "elo, arvella",
     "pondered her livelihood:",
     ""),

    ("ei ollut karjoa kaonnut,",
     "ei ollut karjaa kadonnut,",
     "ei, karja, kadota",
     "no cattle had been lost,",
     ""),

    ("riistettynä riistojansa.",
     "riistettynä riistojaan.",
     "riistetty, riisto",
     "none of her game taken.",
     ""),

    ("Jo kävi kivimäelle,",
     "Jo kävi kivimäelle,",
     "jo, käydä, kivimäki",
     "Then she went to the stone hill,",
     ""),

    ("vaaran vaskisen ovelle.",
     "vaaran vaskisen ovelle.",
     "vaara, vaskinen, ovi",
     "to the door of the copper hill.",
     ""),

    ("Sanoi tuonne tultuansa:",
     "Sanoi tuonne tultuaan:",
     "sanoa, tuo, tulla",
     "Said upon arriving there:",
     ""),

    ("\"Voi, poloinen, päiviäni!",
     "\"Voi, poloinen, päiviäni!",
     "voi, poloinen, päivä",
     "\"Oh, wretched are my days!",
     ""),

    ("Jop' on täällä vieras käynyt,",
     "Jo on täällä vieras käynyt,",
     "jo, täällä, vieras, käydä",
     "A visitor has already been here,",
     "Louhi discovers the theft — the trickster's intrusion named as 'vieras' (stranger/visitor), euphemistic recognition."),

    ("kaikki lukot lonkaellut,",
     "kaikki lukot lonkauttanut,",
     "kaikki, lukko, lonkauttaa",
     "rattled all the locks,",
     ""),

    ("liikutellut linnan portit,",
     "liikutellut linnan portit,",
     "liikutella, linna, portti",
     "moved the fortress gates,",
     ""),

    ("särkenyt saranarauat!",
     "särkenyt saranarauat!",
     "särkeä, saranarauta",
     "broken the hinge-irons!",
     ""),

    ("Oisko täältä sampo saatu,",
     "Onko täältä sampo saatu,",
     "olla, täältä, Sampo, saada",
     "Has the Sampo been taken from here,",
     ""),

    ("otettu omin lupinsa?\"",
     "otettu omin luvin?\"",
     "ottaa, oma, lupa",
     "taken on its own authority?\"",
     "'Omin lupinsa' (on its own authority) — a bitter ironic phrase noting the theft was unauthorized."),

    ("Jo oli sieltä sampo saatu,",
     "Jo oli sieltä sampo saatu,",
     "jo, sieltä, Sampo, saada",
     "Already the Sampo had been taken from there,",
     ""),

    ("anastettu kirjokansi",
     "anastettu kirjokansi",
     "anastaa, kirjokansi",
     "the coloured lid stolen",
     "'Anastettu' (stolen/pilfered) — explicit naming of the trickster act."),

    ("Pohjolan kivimäestä,",
     "Pohjolan kivimäestä,",
     "Pohjola, kivimäki",
     "from the stone hill of Pohjola,",
     ""),

    ("vaaran vaskisen sisästä,",
     "vaaran vaskisen sisästä,",
     "vaara, vaskinen, sisä",
     "from inside the copper hill,",
     ""),

    ("yheksän lukon takoa,",
     "yhdeksän lukon takaa,",
     "yhdeksän, lukko, takaa",
     "from behind nine locks,",
     ""),

    ("takasalvan kymmenennen.",
     "takasalvan kymmenennen.",
     "takasalpa, kymmenes",
     "the tenth bolt/bar.",
     ""),

    ("Louhi, Pohjolan emäntä,",
     "Louhi, Pohjolan emäntä,",
     "Louhi, Pohjola, emäntä",
     "Louhi, mistress of Pohjola,",
     ""),

    ("tuo tuosta pahoin pahastui,",
     "tuo tuosta pahoin pahastui,",
     "tuo, pahoin, pahastua",
     "was greatly angered by this,",
     ""),

    ("katsoi valtansa vajuvan,",
     "katsoi valtansa vaipuvan,",
     "katsoa, valta, vaipua",
     "saw her power sinking,",
     ""),

    ("alenevan arvionsa.",
     "alenevan arvionsa.",
     "aleta, arvio",
     "her standing diminishing.",
     "Louhi recognizes her power is undermined — the trickster's theft as political act."),

    ("Uutarta rukoelevi:",
     "Uutarta rukoilee:",
     "uutar, rukoilla",
     "She prays to the fog-maiden:",
     ""),

    ("\"Ututyttö, terhenneiti!",
     "\"Ututyttö, terhenneito!",
     "utu, tyttö, terhen, neito",
     "\"Fog-girl, mist-maiden!",
     ""),

    ("Seulo seulalla utua,",
     "Seulo seulalla utua,",
     "seuloa, seula, utu",
     "Sieve fog with a sieve,",
     "Louhi as counter-trickster, using magic against magic."),

    ("terhenistä tepsuttele,",
     "terhenistä tepsuttele,",
     "terhen, tepsuttaa",
     "shake out the mist,",
     ""),

    ("laske talma taivahalta,",
     "laske talma taivaalta,",
     "laskea, talma, taivas",
     "send down haze from the sky,",
     ""),

    ("auer ilmasta alenna",
     "auer ilmasta alenna",
     "auer, ilma, alentaa",
     "lower vapour from the air",
     ""),

    ("selvälle meren selälle,",
     "selvälle meren selälle,",
     "selvä, meri, selkä",
     "onto the clear open sea,",
     ""),

    ("ulapalle aukealle,",
     "ulapalle aukealle,",
     "ulappa, aukeainen",
     "onto the open expanse,",
     ""),

    ("jottei päästä Väinämöisen,",
     "jottei päästä Väinämöistä,",
     "jotta, ei, päästää, Väinämöinen",
     "so as not to let Väinämöinen through,",
     ""),

    ("osata uvantolaisen!",
     "osata uvantolaisen!",
     "osata, uvantola",
     "reach the swimmer's shore!",
     ""),

    ("\"Kun ei tuosta kyllin tulle,",
     "\"Kun ei tuosta kyllin tule,",
     "kun, ei, kyllin, tulla",
     "\"If that is not enough,",
     ""),

    ("Iku-Turso, Äijön poika,",
     "Iku-Turso, Äijön poika,",
     "Iku-Turso, Äijö, poika",
     "Iku-Turso, son of Äijö,",
     "Invoking a sea monster — Louhi's trickster-counter-magic escalates."),

    ("nosta päätäsi merestä,",
     "nosta päätäsi merestä,",
     "nostaa, pää, meri",
     "raise your head from the sea,",
     ""),

    ("lakkoasi lainehesta!",
     "lakkaasi lainehesta!",
     "lakka, laine",
     "your cap from the waves!",
     ""),

    ("Kaataos Kalevan miehet,",
     "Kaada Kalevan miehet,",
     "kaataa, Kaleva, mies",
     "Fell the men of Kaleva,",
     ""),

    ("upota uvantolaiset,",
     "upota uvantolaiset,",
     "upottaa, uvantola",
     "drown the swimmers,",
     ""),

    ("hävitä häjyt urohot",
     "hävitä häijyt urohot",
     "hävittää, häijy, uros",
     "destroy the evil heroes",
     ""),

    ("alle aaltojen syvien!",
     "alle aaltojen syvien!",
     "alle, aalto, syvä",
     "under the deep waves!",
     ""),

    ("Saata sampo Pohjolahan",
     "Saata sampo Pohjolaan",
     "saattaa, Sampo, Pohjola",
     "Bring the Sampo to Pohjola",
     ""),

    ("venehestä vierimättä!",
     "veneestä vierimättä!",
     "vene, vierimättä",
     "without rolling from the boat!",
     ""),

    ("\"Kun ei tuosta kyllin tulle,",
     "\"Kun ei tuosta kyllin tule,",
     "kun, ei, kyllin, tulla",
     "\"If that is not enough,",
     ""),

    ("oi Ukko, ylijumala,",
     "oi Ukko, ylijumala,",
     "oi, Ukko, ylijumala",
     "oh Ukko, supreme god,",
     ""),

    ("ilman kultainen kuningas,",
     "ilman kultainen kuningas,",
     "ilma, kultainen, kuningas",
     "golden king of the air,",
     ""),

    ("hope'inen hallitsija,",
     "hopeinen hallitsija,",
     "hopeinen, hallitsija",
     "silver ruler,",
     ""),

    ("rakenna rajuinen ilma,",
     "rakenna rajuinen ilma,",
     "rakentaa, rajuinen, ilma",
     "build a violent storm,",
     ""),

    ("nosta suuri säien voima!",
     "nosta suuri säiden voima!",
     "nostaa, suuri, sää, voima",
     "raise the great force of the weather!",
     ""),

    ("Luo tuuli, lähetä aalto",
     "Luo tuuli, lähetä aalto",
     "luoda, tuuli, lähettää, aalto",
     "Create wind, send waves",
     ""),

    ("aivan vastahan venettä,",
     "aivan vastaan venettä,",
     "aivan, vasten, vene",
     "straight against the boat,",
     ""),

    ("jottei päästä Väinämöisen,",
     "jottei päästä Väinämöistä,",
     "jotta, ei, päästää, Väinämöinen",
     "so as not to let Väinämöinen through,",
     ""),

    ("kulkea uvantolaisen!\"",
     "kulkea uvantolaisen!\"",
     "kulkea, uvantola",
     "for the swimmer to travel!\"",
     ""),

    ("Ututyttö, neiti terhen,",
     "Ututyttö, neiti terhen,",
     "utu, tyttö, neito, terhen",
     "The fog-girl, mist-maiden,",
     ""),

    ("u'un huokuvi merelle,",
     "udun huokuu merelle,",
     "utu, huokua, meri",
     "breathed fog onto the sea,",
     ""),

    ("sumun ilmahan sukesi;",
     "sumun ilmaan sukesi;",
     "sumu, ilma, sukeutua",
     "spread mist into the air;",
     ""),

    ("piti vanhan Väinämöisen",
     "piti vanhan Väinämöisen",
     "pitää, vanha, Väinämöinen",
     "kept old Väinämöinen",
     ""),

    ("kokonaista kolme yötä",
     "kokonaista kolme yötä",
     "kokonainen, kolme, yö",
     "a full three nights",
     ""),

    ("sisässä meren sinisen",
     "sisässä meren sinisen",
     "sisä, meri, sininen",
     "within the blue sea",
     ""),

    ("pääsemättänsä perille,",
     "pääsemättä perille,",
     "päästä, perille",
     "unable to reach the destination,",
     "Fog as magical counter-trickster obstacle — Louhi's magic trapping the trickster."),

    ("kulkematta kunnekana.",
     "kulkematta minnekään.",
     "kulkea, minnekään",
     "unable to travel anywhere.",
     ""),

    ("Yön kolmen levättyänsä",
     "Kolmen yön levättyään",
     "kolme, yö, levätä",
     "After resting three nights",
     ""),

    ("sisässä meren sinisen",
     "sisässä meren sinisen",
     "sisä, meri, sininen",
     "within the blue sea",
     ""),

    ("virkki vanha Väinämöinen,",
     "sanoi vanha Väinämöinen,",
     "sanoa, vanha, Väinämöinen",
     "old Väinämöinen said,",
     ""),

    ("itse lausui, noin nimesi:",
     "itse lausui, noin sanoi:",
     "itse, lausua, sanoa",
     "himself spoke, named it thus:",
     ""),

    ("\"Ei ole mies pahempikana,",
     "\"Ei ole mies pahempikaan,",
     "ei, olla, mies, paha",
     "\"No man is worse,",
     ""),

    ("uros untelompikana",
     "uros untelompikaan",
     "uros, untelompi",
     "no hero more helpless",
     ""),

    ("u'ulla upottaminen,",
     "udulla upottaminen,",
     "utu, upottaa",
     "than being sunk by fog,",
     ""),

    ("terhenellä voittaminen.\"",
     "terhenellä voittaminen.\"",
     "terhen, voittaa",
     "overcome by mist.\"",
     "Väinämöinen refuses to accept defeat — the resilient trickster's defiance of setbacks."),

    ("Veti vettä kalvallansa,",
     "Veti vettä miekallaan,",
     "vetää, vesi, miekka",
     "He drew water with his sword,",
     ""),

    ("merta miekalla sivalti.",
     "merta miekalla sivalteli.",
     "meri, miekka, sivaltaa",
     "struck the sea with his sword.",
     "Using a sword against fog — the trickster improvises unexpected solutions."),

    ("Sima siukui kalvan tiestä,",
     "Mesi siukasi miekan tiestä,",
     "mesi, siukaista, miekka, tie",
     "Mead spurted from the sword's path,",
     ""),

    ("mesi miekan roiskehesta:",
     "mesi miekan roiskehesta:",
     "mesi, miekka, roiske",
     "honey from the sword's splash:",
     ""),

    ("nousi talma taivahalle,",
     "nousi talma taivaalle,",
     "nousta, talma, taivas",
     "the haze rose to the sky,",
     ""),

    ("utu ilmoillen yleni.",
     "utu ilmoihin yleni.",
     "utu, ilma, ylentää",
     "the fog rose up into the air.",
     ""),

    ("Selvisi meri sumusta,",
     "Selvisi meri sumusta,",
     "selvitä, meri, sumu",
     "The sea cleared of fog,",
     ""),

    ("meren aalto auteresta;",
     "meren aalto auteresta;",
     "meri, aalto, auter",
     "the sea-wave of haze;",
     ""),

    ("meri suureksi sukeutui,",
     "meri suureksi sukeutui,",
     "meri, suuri, sukeutua",
     "the sea expanded greatly,",
     ""),

    ("maailma isoksi täytyi.",
     "maailma isoksi täyttyi.",
     "maailma, iso, täyttyä",
     "the world became vast.",
     ""),

    ("Oli aikoa vähäinen,",
     "Oli aikaa vähäinen,",
     "olla, aika, vähäinen",
     "There was a short while,",
     ""),

    ("pirahteli pikkarainen.",
     "pirahteli pikkarainen.",
     "pirahteleva, pikkarainen",
     "a tiny moment passed.",
     ""),

    ("Jo kuului kova kohina",
     "Jo kuului kova kohina",
     "jo, kuulua, kova, kohina",
     "Already a loud roar was heard",
     ""),

    ("viereltä veno punaisen;",
     "viereltä venon punaisen;",
     "vieri, vene, punainen",
     "from beside the red boat;",
     ""),

    ("nousi kuohu korkeaksi",
     "nousi kuohu korkeaksi",
     "nousta, kuohu, korkea",
     "a surge rose high",
     ""),

    ("vasten purtta Väinämöisen.",
     "vasten purtta Väinämöisen.",
     "vasten, pursi, Väinämöinen",
     "against Väinämöinen's vessel.",
     ""),

    ("Siinä seppo Ilmarinen",
     "Siinä seppä Ilmarinen",
     "siinä, seppä, Ilmarinen",
     "There the smith Ilmarinen",
     ""),

    ("toki säikähti kovasti:",
     "kuitenkin säikähti kovasti:",
     "kuitenkin, säikähtää, kovasti",
     "still was greatly frightened:",
     ""),

    ("veret vieri kasvoiltansa,",
     "veri vieri kasvoiltaan,",
     "veri, vierimä, kasvot",
     "blood drained from his face,",
     ""),

    ("puna poskilta putosi.",
     "puna poskilta putosi.",
     "puna, poski, pudota",
     "colour fell from his cheeks.",
     ""),

    ("Veti viltin päänsä päälle,",
     "Veti viltin päänsä päälle,",
     "vetää, viltti, pää",
     "He pulled a blanket over his head,",
     "Ilmarinen hides in fear — contrasting the coward with the trickster-hero Väinämöinen."),

    ("yli korvien kohenti,",
     "yli korvien kohenti,",
     "yli, korva, kohentaa",
     "pulled it up over his ears,",
     ""),

    ("peitti kasvot kaunihisti,",
     "peitti kasvot kauniisti,",
     "peittää, kasvot, kauniisti",
     "covered his face nicely,",
     ""),

    ("silmänsä sitäi paremmin.",
     "silmänsä sitoi paremmin.",
     "silmä, sitoa, paremmin",
     "bound his eyes even better.",
     ""),

    ("Itse vanha Väinämöinen",
     "Itse vanha Väinämöinen",
     "itse, vanha, Väinämöinen",
     "Old Väinämöinen himself",
     ""),

    ("katsoi vierellä vesiä,",
     "katsoi vierellä vesiä,",
     "katsoa, vieri, vesi",
     "looked at the waters beside,",
     ""),

    ("loi silmät sivulle purren.",
     "loi silmät sivulle purren.",
     "luoda, silmä, sivu, pursi",
     "cast his eyes to the side of the vessel.",
     ""),

    ("Näki kummoa vähäisen:",
     "Näki kummaa vähäisen:",
     "nähdä, kumma, vähäinen",
     "He saw a small wonder:",
     ""),

    ("Iku-Turso, Äijön poika,",
     "Iku-Turso, Äijön poika,",
     "Iku-Turso, Äijö, poika",
     "Iku-Turso, son of Äijö,",
     ""),

    ("vieressä veno punaisen",
     "vieressä venon punaisen",
     "vieri, vene, punainen",
     "beside the red boat",
     ""),

    ("nosti päätänsä merestä,",
     "nosti päätään merestä,",
     "nostaa, pää, meri",
     "raised its head from the sea,",
     ""),

    ("lakkoansa lainehesta.",
     "lakkaansa lainehesta.",
     "lakka, laine",
     "its cap from the waves.",
     ""),

    ("Vaka vanha Väinämöinen",
     "Vaka vanha Väinämöinen",
     "vakaa, vanha, Väinämöinen",
     "Steady old Väinämöinen",
     ""),

    ("saipa korvat kourihinsa.",
     "sai korvat kouriin.",
     "saada, korva, koura",
     "got the ears in his fists.",
     "Väinämöinen grabs Iku-Turso by the ears — a bold, physical trickster dominance move."),

    ("Korvista kohottelevi,",
     "Korvista kohottaa,",
     "korva, kohottaa",
     "Lifts it by the ears,",
     ""),

    ("kysytteli, lausutteli,",
     "kysytteli, lausutteli,",
     "kysyä, lausua",
     "questioned, spoke,",
     ""),

    ("sanan virkkoi, noin nimesi:",
     "sanan virkkoi, noin sanoi:",
     "sana, virkkoa, sanoa",
     "spoke a word, named it thus:",
     ""),

    ("\"Iku-Turso, Äijön poika!",
     "\"Iku-Turso, Äijön poika!",
     "Iku-Turso, Äijö, poika",
     "\"Iku-Turso, son of Äijö!",
     ""),

    ("Miksi sie merestä nousit,",
     "Miksi sinä merestä nousit,",
     "miksi, sinä, meri, nousta",
     "Why did you rise from the sea,",
     ""),

    ("kuksi aallosta ylenit",
     "miksi aallosta ylenit",
     "miksi, aalto, ylentää",
     "why did you ascend from the wave",
     ""),

    ("etehen imehnisille,",
     "eteen ihmisille,",
     "eteen, ihminen",
     "before human beings,",
     ""),

    ("saanikka Kalevan poian?\"",
     "häiritäksesi Kalevan poikia?\"",
     "häiritä, Kaleva, poika",
     "to bother the sons of Kaleva?\"",
     ""),

    ("Iku-Turso, Äijön poika,",
     "Iku-Turso, Äijön poika,",
     "Iku-Turso, Äijö, poika",
     "Iku-Turso, son of Äijö,",
     ""),

    ("eikä tuo ihastu tuosta",
     "eikä tuo ihastunut siitä",
     "eikä, ihastua, siitä",
     "was not delighted by this",
     ""),

    ("eikä tuo kovin pelästy",
     "eikä kovin pelästynyt",
     "eikä, pelästyä",
     "nor very frightened",
     ""),

    ("eikä varsin vastaele.",
     "eikä oikein vastannut.",
     "eikä, vastata",
     "nor properly answered.",
     "Iku-Turso defies verbal response — an anti-trickster stance, or a different kind of trickster resistance."),

    ("Vaka vanha Väinämöinen",
     "Vaka vanha Väinämöinen",
     "vakaa, vanha, Väinämöinen",
     "Steady old Väinämöinen",
     ""),

    ("tarkoin toiste tutkaeli,",
     "tarkoin toisen kerran tutki,",
     "tarkoin, toinen, tutkia",
     "scrutinized carefully a second time,",
     ""),

    ("kolmasti kovin kysyvi:",
     "kolmasti kovasti kysyi:",
     "kolmasti, kovasti, kysyä",
     "asked hard a third time:",
     "The magic number three — the trickster knows how to invoke ritual power."),

    ("\"Iku-Turso, Äijön poika!",
     "\"Iku-Turso, Äijön poika!",
     "Iku-Turso, Äijö, poika",
     "\"Iku-Turso, son of Äijö!",
     ""),

    ("Miksi sie merestä nousit,",
     "Miksi sinä merestä nousit,",
     "miksi, sinä, meri, nousta",
     "Why did you rise from the sea,",
     ""),

    ("kuksi aallosta ylenit?\"",
     "miksi aallosta ylenit?\"",
     "miksi, aalto, ylentää",
     "why did you ascend from the wave?\"",
     ""),

    ("Iku-Turso, Äijön poika,",
     "Iku-Turso, Äijön poika,",
     "Iku-Turso, Äijö, poika",
     "Iku-Turso, son of Äijö,",
     ""),

    ("jo kerralla kolmannella",
     "jo kolmannella kerralla",
     "jo, kolmas, kerta",
     "now on the third time",
     ""),

    ("sanan vastaten sanovi:",
     "sanan vastauksena sanoi:",
     "sana, vastata, sanoa",
     "said in answer:",
     ""),

    ("\"Siksi mie merestä nousin,",
     "\"Siksi minä merestä nousin,",
     "siksi, minä, meri, nousta",
     "\"That is why I rose from the sea,",
     ""),

    ("siksi aallosta ylenin:",
     "siksi aallosta ylenin:",
     "siksi, aalto, ylentää",
     "that is why I ascended from the wave:",
     ""),

    ("oli mielessä minulla",
     "oli mielessäni",
     "olla, mieli, minä",
     "I had in mind",
     ""),

    ("surmata suku Kalevan,",
     "surmata suku Kalevan,",
     "surmata, suku, Kaleva",
     "to destroy the kin of Kaleva,",
     ""),

    ("saa'a sampo Pohjolahan.",
     "saada sampo Pohjolaan.",
     "saada, Sampo, Pohjola",
     "to get the Sampo back to Pohjola.",
     ""),

    ("Kun nyt lasket lainehisin,",
     "Kun nyt lasket lainehisin,",
     "kun, nyt, laskea, laine",
     "If you now let me into the waves,",
     "Iku-Turso negotiates his release — a bargain scene typical of trickster encounters."),

    ("heität vielä herjan hengen,",
     "heität vielä herjan hengen,",
     "heittää, vielä, herjata, henki",
     "if you still throw the wretched one's life away,",
     ""),

    ("enpä toiste tullekana",
     "en enää toiseen kertaan tule",
     "en, enää, toinen, tulla",
     "I will not come again",
     ""),

    ("etehen imehnisille.\"",
     "eteen ihmisille.\"",
     "eteen, ihminen",
     "before human beings.\"",
     ""),

    ("Silloin vanha Väinämöinen",
     "Silloin vanha Väinämöinen",
     "silloin, vanha, Väinämöinen",
     "Then old Väinämöinen",
     ""),

    ("heitti herjan lainehisin.",
     "heitti herjan lainehisin.",
     "heittää, herjata, laine",
     "threw the wretch into the waves.",
     ""),

    ("Itse tuon sanoiksi virkki:",
     "Itse sen sanoiksi sanoi:",
     "itse, se, sana, virkkoa",
     "Himself spoke it into words:",
     ""),

    ("\"Iku-Turso, Äijön poika!",
     "\"Iku-Turso, Äijön poika!",
     "Iku-Turso, Äijö, poika",
     "\"Iku-Turso, son of Äijö!",
     ""),

    ("Ellös sie merestä nousko,",
     "Älä sinä merestä nouse,",
     "älä, sinä, meri, nousta",
     "Do not rise from the sea,",
     "Väinämöinen issues a binding curse/command — the trickster as authority enforcer."),

    ("ellös aallosta yletkö",
     "älä aallosta ylety",
     "älä, aalto, ylettyä",
     "do not reach up from the wave",
     ""),

    ("etehen imehnisille",
     "eteen ihmisille",
     "eteen, ihminen",
     "before human beings",
     ""),

    ("tämän päivyen perästä!\"",
     "tämän päivän jälkeen!\"",
     "tämä, päivä, jälkeen",
     "after this day!\"",
     ""),

    ("Senpä päivyen perästä",
     "Siitä päivästä lähtien",
     "siitä, päivä, lähteä",
     "From that day on",
     ""),

    ("ei Turso merestä nouse",
     "ei Turso merestä nouse",
     "ei, Turso, meri, nousta",
     "Turso does not rise from the sea",
     ""),

    ("etehen imehnisille,",
     "eteen ihmisille,",
     "eteen, ihminen",
     "before human beings,",
     ""),

    ("kuni kuuta, aurinkoa,",
     "kuni kuuta, aurinkoa,",
     "niin kauan kuin, kuu, aurinko",
     "as long as moon, sun,",
     ""),

    ("kuni päiveä hyveä,",
     "kuni päivää hyvää,",
     "niin kauan kuin, päivä, hyvä",
     "as long as good day,",
     ""),

    ("ilmoa ihailtavata.",
     "ilmoa ihailtavaa.",
     "ilma, ihailtu",
     "admirable sky endures.",
     "Väinämöinen's permanent ban on Iku-Turso — trickster reshaping the cosmic order."),

    ("Siitä vanha Väinämöinen",
     "Siitä vanha Väinämöinen",
     "siitä, vanha, Väinämöinen",
     "Then old Väinämöinen",
     ""),

    ("laski eelle laivoansa.",
     "laski eteensä laivaansa.",
     "laskea, eteen, laiva",
     "set his ship forward.",
     ""),

    ("Oli aikoa vähäinen,",
     "Oli aikaa vähäinen,",
     "olla, aika, vähäinen",
     "There was a short while,",
     ""),

    ("pirahteli pikkarainen.",
     "pirahteli pikkarainen.",
     "pirahteleva, pikkarainen",
     "a tiny moment passed.",
     ""),

    ("Jo Ukko, ylijumala,",
     "Jo Ukko, ylijumala,",
     "jo, Ukko, ylijumala",
     "Already Ukko, the supreme god,",
     ""),

    ("itse ilmojen isäntä,",
     "itse ilmojen isäntä,",
     "itse, ilma, isäntä",
     "himself the master of the skies,",
     ""),

    ("virkki tuulet tuulemahan,",
     "käski tuulet tuulemaan,",
     "käskeä, tuuli, tuulla",
     "commanded the winds to blow,",
     ""),

    ("säät rajut rajuamahan.",
     "säät rajut raivomaan.",
     "sää, rajuinen, raivota",
     "the fierce weather to storm.",
     "The supreme god acts as Louhi's agent — trickster now faces divine opposition."),

    ("Nousi tuulet tuulemahan,",
     "Nousivat tuulet tuulemaan,",
     "nousta, tuuli, tuulla",
     "The winds rose to blow,",
     ""),

    ("säät rajut rajuamahan.",
     "säät rajut raivomaan.",
     "sää, rajuinen, raivota",
     "the fierce weather to storm.",
     ""),

    ("Kovin läikkyi länsituuli,",
     "Kovasti läikkyi länsituuli,",
     "kovasti, läikkyä, länsituuli",
     "The west wind splashed hard,",
     ""),

    ("luoetuuli tuikutteli;",
     "luotetuuli tuikutteli;",
     "luotetuuli, tuikuttaa",
     "the northwest wind pricked;",
     ""),

    ("enemmän etelä tuuli,",
     "enemmän etelä tuuli,",
     "enemmän, etelä, tuuli",
     "more so the south wind blew,",
     ""),

    ("itä inkui ilkeästi;",
     "itä inkui ilkeästi;",
     "itä, ingata, ilkeästi",
     "the east whined evilly;",
     ""),

    ("kauheasti kaakko karjui,",
     "kauheasti kaakko karjui,",
     "kauheasti, kaakko, karjua",
     "terribly the southeast roared,",
     ""),

    ("pohjonen kovin porasi.",
     "pohjoinen kovasti porasi.",
     "pohjoinen, kovasti, porata",
     "the north drilled hard.",
     ""),

    ("Tuuli puut lehettömäksi,",
     "Tuuli puut lehettömiksi,",
     "tuuli, puu, lehdettömäksi",
     "The wind blew the trees leafless,",
     ""),

    ("havupuut havuttomaksi,",
     "havupuut havuttomiksi,",
     "havupuu, havuton",
     "the conifers needleless,",
     ""),

    ("kanervat kukattomaksi,",
     "kanervat kukattomiksi,",
     "kanerva, kukaton",
     "the heather flowerless,",
     ""),

    ("heinät helpehettömäksi.",
     "heinät helpehettömiksi.",
     "heinä, helpeheton",
     "the grasses without blades.",
     ""),

    ("Nosti mustia muria",
     "Nosti mustia mureja",
     "nostaa, musta, muri",
     "Raised dark boulders",
     ""),

    ("päälle selvien vesien.",
     "päälle selvien vesien.",
     "päälle, selvä, vesi",
     "above the clear waters.",
     ""),

    ("Kovin silloin tuulet tuuli,",
     "Kovasti silloin tuulet tuulivat,",
     "kovasti, silloin, tuuli, tuulla",
     "Fiercely then the winds blew,",
     ""),

    ("aallot hakkasi alusta.",
     "aallot hakkasivat alusta.",
     "aalto, hakata, alusta",
     "the waves beat from below.",
     ""),

    ("Veivät harpun hauinluisen,",
     "Veivät harpun hauinluisen,",
     "viedä, harppu, haukiluinen",
     "They took away the pike-bone harp,",
     "The kantele, Väinämöinen's trickster instrument, is lost to the sea — a devastating blow."),

    ("kantelon kalaneväisen",
     "kantelon kalaneväisen",
     "kantele, kalaneva",
     "the fish-fin kantele",
     ""),

    ("väen Vellamon hyväksi,",
     "väen Vellamon hyväksi,",
     "väki, Vellamo, hyvä",
     "for the enjoyment of Vellamo's people,",
     ""),

    ("Ahtolan iki-iloksi.",
     "Ahtolan ikuiseksi iloksi.",
     "Ahtola, ikuinen, ilo",
     "for the eternal joy of Ahtola.",
     ""),

    ("Ahto aalloilta havainnut,",
     "Ahto aalloilta havainnut,",
     "Ahto, aalto, havaita",
     "Ahto, having noticed from the waves,",
     ""),

    ("Ahon lapset lainehilta;",
     "Ahon lapset lainehilta;",
     "Aho, lapsi, laine",
     "Aho's children from the waves;",
     ""),

    ("ottivat sorean soiton,",
     "ottivat sorean soiton,",
     "ottaa, sorea, soitto",
     "took the fine instrument,",
     ""),

    ("kotihinsa korjasivat.",
     "kotiinsa korjasivat.",
     "koti, korjata",
     "carried it home.",
     "The sea spirits claim the trickster's tool — the magical object passing to another realm."),

    ("Siinä vanhan Väinämöisen",
     "Siinä vanhan Väinämöisen",
     "siinä, vanha, Väinämöinen",
     "There old Väinämöinen's",
     ""),

    ("ve'et silmihin vetihe.",
     "vedet silmiin vetivät.",
     "vesi, silmä, vetää",
     "waters drew to his eyes (he wept).",
     ""),

    ("Itse tuon sanoiksi virkki:",
     "Itse sen sanoiksi sanoi:",
     "itse, se, sana, virkkoa",
     "Himself spoke it into words:",
     ""),

    ("\"Sinne sattui saalahani,",
     "\"Sinne sattui saaliini,",
     "sinne, sattua, saalis",
     "\"There went my prize,",
     ""),

    ("meni mielisoittimeni,",
     "meni mielisoittimeni,",
     "mennä, mielisoitin",
     "my beloved instrument went,",
     ""),

    ("katosi iki-iloni!",
     "katosi ikuinen iloni!",
     "kadota, ikuinen, ilo",
     "my eternal joy vanished!",
     "The trickster mourns his lost tool — rare moment of genuine grief, showing the kantele's deep significance."),

    ("En tuota enämpi saane",
     "En tuota enää saa",
     "en, tuo, enää, saada",
     "I will not get that anymore",
     ""),

    ("sinä ilmoisna ikänä",
     "sinä ilmoisena ikänä",
     "sinä, ilmoinen, ikä",
     "in that open eternity",
     ""),

    ("hauin hampahan iloa,",
     "hauin hampahan iloa,",
     "hauki, hammas, ilo",
     "the joy of the pike's tooth,",
     ""),

    ("kalanluista luikutusta.\"",
     "kalanluista luikutusta.\"",
     "kala, luu, luikuttaa",
     "the sliding of fish-bones.\"",
     ""),

    ("Itse seppo Ilmarinen,",
     "Itse seppä Ilmarinen,",
     "itse, seppä, Ilmarinen",
     "The smith Ilmarinen himself,",
     ""),

    ("tuopa tuiki tuskautui.",
     "tuo tuikahti tuskautui.",
     "tuo, tuikahtaa, tuskautua",
     "that one was pained greatly.",
     ""),

    ("Sanan virkkoi, noin nimesi:",
     "Sanan virkkoi, noin sanoi:",
     "sana, virkkoa, sanoa",
     "Spoke a word, named it thus:",
     ""),

    ("\"Voi, poloinen, päiviäni,",
     "\"Voi, poloinen, päiviäni,",
     "voi, poloinen, päivä",
     "\"Oh, wretched are my days,",
     ""),

    ("kun läksin selille näille,",
     "kun lähdin selille näille,",
     "kun, lähteä, selkä, nämä",
     "when I set out onto these open waters,",
     ""),

    ("ulapoille auke'ille,",
     "ulapoille aukaisille,",
     "ulappa, aukeainen",
     "onto the open expanses,",
     ""),

    ("polin puulle pyörivälle,",
     "polille pyörivälle puulle,",
     "polvi, pyörivä, puu",
     "onto the rolling log of suffering,",
     ""),

    ("varvalle vapisevalle!",
     "varpulle vapisevalle!",
     "varpu, vapista",
     "onto the trembling twig!",
     ""),

    ("Jo on tukka tuulta nähnyt,",
     "Jo on tukka tuulta nähnyt,",
     "jo, tukka, tuuli, nähdä",
     "Already the hair has seen wind,",
     ""),

    ("hivus säätä hirveätä,",
     "hivus säätä hirveätä,",
     "hivus, sää, hirveä",
     "the hair has seen terrible weather,",
     ""),

    ("parta päiviä pahoja,",
     "parta päiviä pahoja,",
     "parta, päivä, paha",
     "the beard has seen bad days,",
     ""),

    ("nähnyt näilläki vesillä;",
     "nähnyt näilläkin vesillä;",
     "nähdä, näilläkin, vesi",
     "seen even on these waters;",
     ""),

    ("harvoin on havaita tainnut",
     "harvoin on havaittu",
     "harvoin, havaita",
     "rarely has one been able to observe",
     ""),

    ("tuulta ennen tuon näöistä,",
     "tuulta ennen tuon näköistä,",
     "tuuli, ennen, näköinen",
     "wind like that before,",
     ""),

    ("noita kuohuja kovia,",
     "noita kuohuja kovia,",
     "nuo, kuohu, kova",
     "those hard surges,",
     ""),

    ("lakkipäitä lainehia.",
     "lakkipäisiä lainehia.",
     "lakkipäinen, laine",
     "those capped waves.",
     ""),

    ("Jo nyt on tuuli turvanani,",
     "Jo nyt on tuuli turvanani,",
     "jo, nyt, tuuli, turva",
     "Now the wind is my protection,",
     ""),

    ("meren aalto armonani!\"",
     "meren aalto armonani!\"",
     "meri, aalto, armo",
     "the sea-wave my mercy!\"",
     "Dark irony — Ilmarinen's 'protection' is the deadly storm. The trickster's world is full of such bitter ironies."),

    ("Vaka vanha Väinämöinen,",
     "Vaka vanha Väinämöinen,",
     "vakaa, vanha, Väinämöinen",
     "Steady old Väinämöinen,",
     ""),

    ("tuopa tuossa arvelevi:",
     "tuo tuossa arvelee:",
     "tuo, tuossa, arvella",
     "that one there pondered:",
     ""),

    ("\"Ei venossa vieremistä,",
     "\"Ei veneessä vieremistä,",
     "ei, vene, vieriminen",
     "\"No rolling in the boat,",
     ""),

    ("purressa parahtamista!",
     "purressa parahtamista!",
     "pursi, parahtaa",
     "no crying out in the vessel!",
     ""),

    ("Itku ei hä'ästä päästä,",
     "Itku ei häädästä päästä,",
     "itku, ei, häätö, päästää",
     "Weeping does not free from trouble,",
     ""),

    ("parku päivistä pahoista.\"",
     "parku päivistä pahoista.\"",
     "parku, päivä, paha",
     "howling does not free from bad days.\"",
     "The trickster's philosophy: action over lamentation — stoic pragmatism."),

    ("Siitä tuon sanoiksi virkki,",
     "Siitä sen sanoiksi sanoi,",
     "siitä, se, sana, virkkoa",
     "Then spoke it into words,",
     ""),

    ("itse lausui, noin nimesi:",
     "itse lausui, noin sanoi:",
     "itse, lausua, sanoa",
     "himself spoke, named it thus:",
     ""),

    ("\"Vesi, kiellä poikoasi,",
     "\"Vesi, kiellä poikaasi,",
     "vesi, kieltää, poika",
     "\"Water, restrain your son,",
     "Väinämöinen commands the waters — trickster-shaman invoking elemental authority."),

    ("laine, lastasi epeä,",
     "laine, lastasi hepeä,",
     "laine, lapsi, hepeä",
     "wave, your child with urgency,",
     ""),

    ("Ahto, aaltoja aseta,",
     "Ahto, aaltoja aseta,",
     "Ahto, aalto, asettaa",
     "Ahto, calm the waves,",
     ""),

    ("Vellamo, ve'en väkeä,",
     "Vellamo, veden väkeä,",
     "Vellamo, vesi, väki",
     "Vellamo, the water's force,",
     ""),

    ("ettei parsku parraspuille,",
     "ettei parskahda parraspuille,",
     "ettei, parskua, parraspuu",
     "so that it doesn't splash on the gunwales,",
     ""),

    ("pääse päälle kaarieni!",
     "pääse päälle kaarieni!",
     "päästä, päälle, kaari",
     "get over my bow-ribs!",
     ""),

    ("\"Nouse, tuuli, taivahalle,",
     "\"Nouse, tuuli, taivaalle,",
     "nousta, tuuli, taivas",
     "\"Rise, wind, up to the sky,",
     ""),

    ("ylös pilvihin ajaite,",
     "ylös pilviin aja,",
     "ylös, pilvi, ajaa",
     "drive up into the clouds,",
     ""),

    ("sukuhusi, syntyhysi,",
     "sukuhusi, syntyisi,",
     "suku, syntyä",
     "to your kindred, to your birthplace,",
     ""),

    ("heimohon, perehesesi!",
     "heimoon, perheeseesi!",
     "heimo, perhe",
     "to your clan, to your family!",
     ""),

    ("Elä kaa'a puista purtta,",
     "Älä kaada puista purtta,",
     "älä, kaataa, puinen, pursi",
     "Do not fell the wooden vessel,",
     ""),

    ("vierrä hongaista venettä!",
     "vierrä hongaista venettä!",
     "vierittää, honkainen, vene",
     "do not roll the pine boat!",
     ""),

    ("Ennen kaa'a puut palolla,",
     "Ennen kaada puut palolla,",
     "ennen, kaataa, puu, palo",
     "Rather fell the trees on the burning land,",
     ""),

    ("kuuset kummuilla kumoa!\"",
     "kuuset kummuilla kumoa!\"",
     "kuusi, kumpu, kumota",
     "topple the spruces on the hills!\"",
     "Väinämöinen redirects the storm's destruction — the cunning trickster negotiating with nature."),

    ("Se on lieto Lemminkäinen,",
     "Se on lieto Lemminkäinen,",
     "se, lieto, Lemminkäinen",
     "That fickle Lemminkäinen,",
     ""),

    ("itse kaunis Kaukomieli,",
     "itse kaunis Kaukomieli,",
     "itse, kaunis, Kaukomieli",
     "himself handsome Kaukomieli,",
     ""),

    ("sanan virkkoi, noin nimesi:",
     "sanan virkkoi, noin sanoi:",
     "sana, virkkoa, sanoa",
     "spoke a word, named it thus:",
     ""),

    ("\"Tule, kokko turjalainen!",
     "\"Tule, kotka turjalainen!",
     "tulla, kotka, turjalainen",
     "\"Come, eagle of the North!",
     "Lemminkäinen improvises by calling an eagle — trickster's creativity under pressure."),

    ("Tuopa kolme sulkoasi,",
     "Tuo kolme sulkaa,",
     "tuoda, kolme, sulka",
     "Bring three of your feathers,",
     ""),

    ("kokko, kolme, kaarne, kaksi",
     "kotka, kolme, kaarne, kaksi",
     "kotka, kolme, kaarne, kaksi",
     "eagle, three, raven, two",
     ""),

    ("varaksi vähän venehen,",
     "varaksi pienen veneen,",
     "vara, pieni, vene",
     "as a precaution for the small boat,",
     ""),

    ("pahan purren parraspuuksi!\"",
     "pahan purren parraspuuksi!\"",
     "paha, pursi, parraspuu",
     "as a gunwale for the poor vessel!\"",
     ""),

    ("Itse laitoa lisäsi,",
     "Itse laitaa lisäsi,",
     "itse, laita, lisätä",
     "He himself added to the side,",
     ""),

    ("varppehia valmisteli;",
     "varppehia valmisteli;",
     "varppe, valmistella",
     "prepared the planks;",
     ""),

    ("liitti tuohon liikalaiat,",
     "liitti tuohon ylälaiat,",
     "liittää, tuo, ylälapa",
     "attached the upper strakes to it,",
     ""),

    ("koko sylen korkeuiset,",
     "koko sylen korkuiset,",
     "koko, syli, korkuinen",
     "a whole fathom in height,",
     ""),

    ("aallon käymättä ylitse,",
     "aallon käymättä ylitse,",
     "aalto, käydä, ylitse",
     "so that the wave would not go over,",
     ""),

    ("partahille parskumatta.",
     "partahille parskumatta.",
     "parras, parskua",
     "without splashing on the gunwales.",
     ""),

    ("Jo oli kyllin laitoaki,",
     "Jo oli kyllin laitoakin,",
     "jo, kyllin, laita",
     "Already there were enough sides,",
     ""),

    ("venehessä varppehia",
     "veneessä varppehia",
     "vene, varppe",
     "enough planks in the boat",
     ""),

    ("tuulen tuiman tuikutella,",
     "tuulen tuiman tuikutella,",
     "tuuli, tuima, tuikuttaa",
     "for the fierce wind to prick,",
     ""),

    ("aallon ankaran lykätä,",
     "aallon ankaran lykätä,",
     "aalto, ankara, lykätä",
     "for the harsh wave to push,",
     ""),

    ("kuohuja kulettaessa,",
     "kuohuja kulettaessa,",
     "kuohu, kuljettaa",
     "when carrying through surges,",
     ""),

    ("mäkipäitä mentäessä.",
     "mäkipäitä mentäessä.",
     "mäkipäinen, mennä",
     "when going through hill-heads (high waves).",
     "The trickster team survives through improvised ingenuity — adapting the boat to the storm's challenges."),
]

# Style config
orig_fill = PatternFill("solid", start_color="F0F4F8", end_color="F0F4F8")
modern_fill = PatternFill("solid", start_color="EAF4EA", end_color="EAF4EA")
basic_fill = PatternFill("solid", start_color="FFF8E7", end_color="FFF8E7")
trans_fill = PatternFill("solid", start_color="F8F0FF", end_color="F8F0FF")
trick_fill = PatternFill("solid", start_color="FFE8E8", end_color="FFE8E8")
thin = Side(style='thin', color='CCCCCC')
border = Border(left=thin, right=thin, top=thin, bottom=thin)

fills = [orig_fill, modern_fill, basic_fill, trans_fill, trick_fill]

for i, (orig, mod, basic, trans, trick) in enumerate(verses, start=2):
    row = [orig, mod, basic, trans, trick]
    for col, (val, fill) in enumerate(zip(row, fills), start=1):
        cell = ws.cell(row=i, column=col, value=val)
        cell.font = Font(name="Arial", size=10)
        cell.alignment = Alignment(wrap_text=True, vertical="top")
        cell.fill = fill
        cell.border = border

# Column widths
ws.column_dimensions['A'].width = 32
ws.column_dimensions['B'].width = 32
ws.column_dimensions['C'].width = 30
ws.column_dimensions['D'].width = 38
ws.column_dimensions['E'].width = 55

# Freeze header
ws.freeze_panes = "A2"

# Row heights
ws.row_dimensions[1].height = 30
for i in range(2, len(verses) + 2):
    ws.row_dimensions[i].height = 28

wb.save("kalevala_runo42.xlsx")
print("Done")
