from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
wb = Workbook()
ws = wb.active
ws.title = "Runo 28"

headers = ["A – Alkuperäinen säe", "B – Nykysuomi", "C – Perusmuodot", "D – Käännös (EN)", "E – Trickster-huomioita"]
hf = PatternFill("solid", start_color="1F4E79")
hfont = Font(bold=True, color="FFFFFF", name="Arial", size=11)
for col, h in enumerate(headers, 1):
    cell = ws.cell(row=1, column=col, value=h)
    cell.font = hfont; cell.fill = hf
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

verses = [
    ("Jo nyt Ahti Saarelainen,", "Jo nyt Ahti Saarelainen,", "jo, nyt, Ahti, Saarelainen", "Now already Ahti the Islander,", ""),
    ("itse lieto Lemminkäinen,", "itse lieto Lemminkäinen,", "itse, lieto, Lemminkäinen", "himself light-hearted Lemminkäinen,", ""),
    ("pistäiksen on piilemähän,", "pistäytyy piilemään,", "pistäytyä, piillä", "darts into hiding,", "Trickster in flight — the consequence of his reckless killing. Flight is as defining as the audacity."),
    ("painaikse pakenemahan", "painautuu pakenемaan", "painautua, paeta", "presses himself to flee", ""),
    ("pimeästä Pohjolasta,", "pimeästä Pohjolasta,", "pimeä, Pohjola", "from dark Pohjola,", ""),
    ("sangasta Saran talosta.", "sangasta Saran talosta.", "sanka, Sara, talo", "from the dense house of Sara.", ""),
    ("Läksi tuiskuna tuvasta,", "Lähti tuiskuna tuvasta,", "lähteä, tuisku, tupa", "Left the cabin like a gust of wind,", "Trickster's exit: as a whirlwind — elemental speed, no farewell."),
    ("savuna pihalle saapi", "savuna pihalle saapuu", "savu, piha, saapua", "arrives in the yard like smoke", "Smoke-transformation — trickster's shape-shifting escape from danger."),
    ("pakohon pahoja töitä,", "pakoon pahoja töitä,", "pako, paha, työ", "fleeing from wicked deeds,", "The trickster's 'wicked deeds' (killing) necessitate escape — consequence of boundary-crossing."),
    ("pillojansa piilemähän.", "pilvojansa piilemään.", "pilvi/pillu, piillä", "to hide his misdeeds.", ""),
    ("Niin pihalle tultuansa", "Niin pihalle tultuaan", "niin, piha, tulla", "Upon coming to the yard thus", ""),
    ("katseleikse, käänteleikse,", "katselee, kääntelee,", "katsella, käännellä", "he looks around, turns about,", "Trickster assesses his situation — the cunning fugitive surveying escape routes."),
    ("etsi entistä oritta.", "etsi entistä orittaan.", "etsiä, entinen, ori", "sought his former stallion.", ""),
    ("Näe ei entistä oroa:", "Ei näe entistä oriaan:", "ei, nähdä, entinen, ori", "He does not see his former stallion:", ""),
    ("näki paaen pellon päässä,", "näki paaden pellon päässä,", "nähdä, paasi, pelto, pää", "saw a flat rock at the field's end,", ""),
    ("pajupehkon pientarella.", "pajupehkon pientarella.", "pajupehko, piennar", "at the edge of a willow thicket.", ""),
    ("Mikäs neuvoksi tulevi,", "Mikäs neuvoksi tulee,", "mikä, neuvo, tulla", "What comes as counsel,", ""),
    ("mikä neuvon antajaksi,", "mikä neuvon antajaksi,", "mikä, neuvo, antaja", "what as the giver of advice,", ""),
    ("ettei pää pahoin menisi,", "ettei pää pahoin menisi,", "ettei, pää, paha, mennä", "so that the head would not go badly,", ""),
    ("tukka turhi'in tulisi,", "tukka turhiin tulisi,", "tukka, turha, tulla", "the hair not come to nothing,", ""),
    ("hivus hieno lankeaisi", "hivus hieno lankeaisi", "hivus, hieno, langeta", "the fine hair not fall", ""),
    ("näillä Pohjolan pihoilla?", "näillä Pohjolan pihoilla?", "nämä, Pohjola, piha", "on these Pohjola yards?", ""),
    ("Jo kumu kylästä kuului,", "Jo kumina kylästä kuului,", "jo, kumina, kylä, kuulua", "Already a rumble was heard from the village,", "The approaching army — sounds of pursuit reaching the trickster's ears."),
    ("tomu toisista taloista,", "tomu toisista taloista,", "tomu, toinen, talo", "dust from other houses,", ""),
    ("välkytys kylän väliltä,", "välkytys kylän väliltä,", "välkytys, kylä, väli", "a glinting from between the villages,", ""),
    ("silmän isku ikkunoilta.", "silmäys ikkunoilta.", "silmäys, ikkuna", "a flash from the windows.", ""),
    ("Tuossa lieto Lemminkäisen,", "Tuossa liedon Lemminkäisen,", "tuossa, lieto, Lemminkäinen", "There for light-hearted Lemminkäinen,", ""),
    ("tuon on Ahti Saarelaisen,", "tuon Ahti Saarelaisen,", "tuo, Ahti, Saarelainen", "for that Ahti the Islander,", ""),
    ("täytyi toisiksi ruveta,", "täytyi toisiksi ruveta,", "täytyä, toinen, ruveta", "it was necessary to become another,", "Shape-shifting as survival — the trickster's core ability deployed under threat."),
    ("piti muiksi muutellaita.", "piti muiksi muuttautua.", "pitää, muu, muuttautua", "he had to transform into something else.", ""),
    ("Kokkona ylös kohosi,", "Kotkana ylös kohosi,", "kotka, ylös, kohota", "He rose up as an eagle,", "Bird transformation — trickster escapes by becoming a raptor (earlier he was a duck)."),
    ("tahtoi nousta taivahalle:", "tahtoi nousta taivaalle:", "tahtoa, nousta, taivas", "wanted to rise to the sky:", ""),
    ("päivä poltti poskipäitä,", "päivä poltti poskipäitä,", "päivä, polttaa, poskipää", "the sun burned his cheeks,", ""),
    ("kuuhut kulmia valaisi.", "kuu kulmia valaisi.", "kuu, kulma, valaista", "the moon lit up his brows.", ""),
    ("Siinä lieto Lemminkäinen", "Siinä lieto Lemminkäinen", "siinä, lieto, Lemminkäinen", "There light-hearted Lemminkäinen", ""),
    ("Ukkoa rukoelevi:", "Ukkoa rukoili:", "Ukko, rukoilla", "prayed to Ukko:", "Trickster enlists the sky-god again — using divine power as a tool, as in Runo 26."),
    ("\"Oi Ukko, hyvä Jumala,", "\"Oi Ukko, hyvä Jumala,", "oi, Ukko, hyvä, Jumala", "\"O Ukko, good God,", ""),
    ("mies on tarkka taivahinen,", "mies on tarkka taivainen,", "mies, tarkka, taivainen", "the precise heavenly man,", ""),
    ("jymypilvien pitäjä,", "jymypilvien pitäjä,", "jymypilvi, pitäjä", "holder of the thunder-clouds,", ""),
    ("hattarojen hallitsija!", "hattarojen hallitsija!", "hattara, hallitsija", "ruler of the fleecy clouds!", ""),
    ("Laaipa utuinen ilma,", "Laaipa utuinen ilma,", "laajeta, utuinen, ilma", "Spread a misty sky,", ""),
    ("luopa pilvi pikkarainen,", "luopa pilvi pikkarainen,", "luoda, pilvi, pikkarainen", "create a small cloud,", ""),
    ("jonka suojassa menisin,", "jonka suojassa menisin,", "jonka, suoja, mennä", "in whose shelter I could go,", "Trickster asks for a cloud-disguise — deception extended even to cosmological scale."),
    ("kotihini koitteleisin", "kotiin koitteleisin", "koti, koitella", "could try to reach home", ""),
    ("luoksi ehtoisen emoni,", "luokse rakkaani äitini,", "luokse, rakas, emo/äiti", "to my dear mother,", ""),
    ("tykö valtavanhempani!\"", "luo valtavanhempani!\"", "luo, valta, vanhempi", "to my powerful parent!\"", ""),
    ("Lenteä lekuttelevi,", "Lentää lekuttelee,", "lentää, lekutella", "He flies fluttering,", ""),
    ("katsoi kerran jälkehensä:", "katsoi kerran taakseen:", "katsoa, kerta, taakse", "looked once behind him:", ""),
    ("keksi harmoan havukan", "keksi harmaan haukan", "keksiä, harmaa, haukka", "spotted a grey hawk", ""),
    ("- sen silmät paloi tulena", "- sen silmät palavat tulena", "se, silmä, palaa, tuli", "- its eyes burned like fire", ""),
    ("kuni pojan pohjolaisen,", "kuin pojan pohjolaisen,", "kuin, poika, pohjolainen", "like the northern lad's,", "The pursuing hawk has the eyes of the man Lemminkäinen killed — eerie supernatural pursuit."),
    ("Pohjan entisen isännän.", "Pohjan entisen isännän.", "Pohja, entinen, isäntä", "the former master of Pohjola.", ""),
    ("Sanoi harmoa havukka:", "Sanoi harmaa haukka:", "sanoa, harmaa, haukka", "The grey hawk said:", ""),
    ("\"Ohoh Ahti veikkoseni!", "\"Ohoh Ahti veikkoseni!", "ohoh, Ahti, veli/veikko", "\"Oh dear, Ahti my kinsman!", ""),
    ("Muistatko muinaista sotoa,", "Muistatko muinaista sotaa,", "muistaa, muinainen, sota", "Do you remember the old battle,", "The hawk (spirit of the slain) challenges Lemminkäinen — the trickster's past deeds pursue him."),
    ("tasapäätä tappeloa?\"", "tasapäätä tappeluа?\"", "tasapää, tappelu", "the equal-headed combat?\"", ""),
    ("Sanoi Ahti Saarelainen,", "Sanoi Ahti Saarelainen,", "sanoa, Ahti, Saarelainen", "Said Ahti the Islander,", ""),
    ("virkkoi kaunis Kaukomieli:", "virkkoi kaunis Kaukomieli:", "virkata, kaunis, Kaukomieli", "beautiful Kaukomieli uttered:", ""),
    ("\"Havukkani, lintuseni!", "\"Haukkani, lintuseni!", "haukka, lintu", "\"My hawk, my bird!", ""),
    ("Käännäite kohin kotia!", "Käänny kohti kotia!", "kääntyä, kohti, koti", "Turn toward home!", "Trickster dismisses the pursuing spirit with cool disdain — refuses to be intimidated."),
    ("Sano tuonne tultuasi", "Sano sinne tultuasi", "sanoa, sinne, tulla", "When you get there say", ""),
    ("pimeähän Pohjolahan:", "pimeään Pohjolaan:", "pimeä, Pohjola", "to dark Pohjola:", ""),
    ("'Kova on kokko kourin saa'a,", "'Kova on kotka kourin saada,", "kova, kotka, koura, saada", "'Hard is the eagle to catch in the claws,", "Trickster sends a defiant message back to his enemies through the pursuing bird — audacious even in flight."),
    ("kynälintu kynsin syöä.'\"", "kynälintu kynsin syödä.'\"", "kynälintu, kynsi, syödä", "the feather-bird hard to eat with claws.'\"", ""),
    ("Jo kohta kotihin joutui", "Jo kohta kotiin joutui", "jo, kohta, koti, joutua", "Soon he arrived home", ""),
    ("luoksi ehtoisen emonsa", "luokse rakkaansa äitinsä", "luokse, rakas, emo/äiti", "to his dear mother", ""),
    ("suulla surkeannäöllä,", "surkeannäköisellä suulla,", "surkeannäköinen, suu", "with a sorry-looking face,", "Trickster arrives home defeated — rare moment of vulnerability."),
    ("syämellä synkeällä.", "sydämellä synkeällä.", "sydän, synkeä", "with a dark heart.", ""),
    ("Emo vastahan tulevi", "Äiti vastaan tulee", "äiti/emo, vastaаn, tulla", "Mother comes to meet him", ""),
    ("kulkiessansa kujoa,", "kulkiessaan kujaa,", "kulkea, kuja", "while walking the alley,", ""),
    ("aitoviertä astuessa.", "aitoviertä astuessa.", "aita, vieri, astua", "stepping along the fence-side.", ""),
    ("Ennätti emo kysyä:", "Ennätti äiti kysyä:", "ennättää, äiti/emo, kysyä", "Mother managed to ask:", ""),
    ("\"Poikueni, nuorempani,", "\"Poikaseni, nuorempani,", "poika, nuori", "\"My son, my younger one,", ""),
    ("lapseni, vakavampani!", "lapseni, vakavampani!", "lapsi, vakava", "my child, my more serious one!", ""),
    ("Mit' olet pahoilla mielin", "Mitä olet pahoilla mielin", "mitä, olla, paha, mieli", "What are you with troubled mind", ""),
    ("Pohjolasta tullessasi?", "Pohjolasta tullessasi?", "Pohjola, tulla", "coming from Pohjola?", ""),
    ("Onko sarkoin vaarrettuna", "Onko sarkasi vanhentunut", "onko, sarka, vaarretta", "Has your cloth worn out", ""),
    ("noissa Pohjolan pioissa?", "noissa Pohjolan pidoissa?", "nuo, Pohjola, pidot", "at those Pohjola feasts?", ""),
    ("Jos on sarkoin vaarrettuna,", "Jos on sarka vanhentunut,", "jos, sarka, vaarretta", "If the cloth has worn out,", ""),
    ("saat sinä paremman sarkan,", "saat sinä paremman sarkan,", "saada, sinä, parempi, sarka", "you will get better cloth,", ""),
    ("taattosi soasta saaman,", "isäsi sodasta saaman,", "isä/taatto, sota, saada", "won by your father in war,", ""),
    ("tavoittaman tappelosta.\"", "tavoittaman tappeluста.\"", "tavoittaa, tappelu", "seized in battle.\"", "Mother's reassuring offer — trickster's deeds have a parental safety net."),
    ("Sanoi lieto Lemminkäinen:", "Sanoi lieto Lemminkäinen:", "sanoa, lieto, Lemminkäinen", "Light-hearted Lemminkäinen said:", ""),
    ("\"Oi emoni, kantajani!", "\"Oi äitini, kantajani!", "oi, emo/äiti, kantaja", "\"O my mother, my bearer!", ""),
    ("Ken mun sarkoin vaarteleisi!", "Kuka minua sarkassa vaartaisi!", "kuka, minä, sarka, vaartaa", "Who would diminish me in cloth!", "Trickster's pride reasserts itself immediately — deflects each maternal concern with boast."),
    ("Itse vaartaisin isännät,", "Itse vaartaisin isännät,", "itse, vaartaa, isäntä", "I myself would diminish the masters,", ""),
    ("vaartaisin sata urosta,", "vaartaisin sata urosta,", "vaartaa, sata, uros", "would diminish a hundred heroes,", ""),
    ("tuhat miestä tunnustaisin.\"", "tuhat miestä tunnistaisin.\"", "tuhat, mies, tunnistaa", "would identify a thousand men.\"", ""),
    ("Sanoi äiti Lemminkäisen:", "Sanoi äiti Lemminkäisen:", "sanoa, äiti, Lemminkäinen", "Lemminkäinen's mother said:", ""),
    ("\"Mit' olet pahoilla mielin?", "\"Mitä olet pahoilla mielin?", "mitä, olla, paha, mieli", "\"What are you with troubled mind?", ""),
    ("Oletko voitettu orihin,", "Oletko voitettu orihessa,", "olla, voitettu, ori", "Have you been defeated in a stallion,", ""),
    ("herjattu hevosen varsoin?", "herjattu hevosen varsoilla?", "herjata, hevonen, varsa", "shamed in horse-foals?", ""),
    ("Jos olet voitettu orihin,", "Jos olet voitettu orihessa,", "jos, olla, voitettu, ori", "If you have been defeated in a stallion,", ""),
    ("ostaos ori parempi", "osta ori parempi", "ostaa, ori, parempi", "buy a better stallion", ""),
    ("ison saamilla eloilla,", "isän saamilla eloilla,", "isä, saada, elo", "with the wealth your father got,", ""),
    ("vanhemman varustamilla!\"", "vanhemman varustamilla!\"", "vanhempi, varustaa", "equipped by your parent!\"", ""),
    ("Sanoi lieto Lemminkäinen:", "Sanoi lieto Lemminkäinen:", "sanoa, lieto, Lemminkäinen", "Light-hearted Lemminkäinen said:", ""),
    ("\"Oi emoni, kantajani!", "\"Oi äitini, kantajani!", "oi, emo/äiti, kantaja", "\"O my mother, my bearer!", ""),
    ("Ken mun herjaisi hevosin", "Kuka minua herjaisi hevosessa", "kuka, minä, herjata, hevonen", "Who would shame me in a horse", ""),
    ("eli varsoin voitteleisi!", "tai varsoissa voittelisi!", "tai, varsa, voitella", "or best me in foals!", ""),
    ("Itse herjaisin isännät,", "Itse herjaisin isännät,", "itse, herjata, isäntä", "I myself would shame the masters,", ""),
    ("voittaisin oron ajajat,", "voittaisin oriin ajajat,", "voittaa, ori, ajaja", "would beat the stallion-drivers,", ""),
    ("miehet vankat varsoinensa,", "miehet vankat varsoineen,", "mies, vankka, varsa", "the sturdy men with their foals,", ""),
    ("urohot orihinensa.\"", "urohot oriineen.\"", "uros, ori", "the heroes with their stallions.\"", "Repeated boast pattern — trickster always claims superiority in every field questioned."),
    ("Sanoi äiti Lemminkäisen:", "Sanoi äiti Lemminkäinen:", "sanoa, äiti, Lemminkäinen", "Lemminkäinen's mother said:", ""),
    ("\"Mit' olet pahoilla mielin,", "\"Mitä olet pahoilla mielin,", "mitä, olla, paha, mieli", "\"What are you with troubled mind,", ""),
    ("kuta synke'in syämin", "mitä synkemmin sydämin", "mitä, synkkä, sydän", "with what darker heart", ""),
    ("Pohjolasta tultuasi?", "Pohjolasta tultuasi?", "Pohjola, tulla", "coming from Pohjola?", ""),
    ("Oletko naisin naurettuna", "Oletko naisten nauramana", "olla, nainen, nauraa", "Have you been laughed at by women", ""),
    ("eli piioin pilkattuna?", "tai piikain pilkkaamana?", "tai, piika, pilkata", "or mocked by maids?", ""),
    ("Jos olet naisin naurettuna", "Jos olet naisten nauramana", "jos, olla, nainen, nauraa", "If you have been laughed at by women", ""),
    ("eli piioin pilkattuna,", "tai piikain pilkkaamana,", "tai, piika, pilkata", "or mocked by maids,", ""),
    ("toiset toiste pilkatahan,", "toiset toisia pilkataan,", "toinen, toinen, pilkata", "others mock one another,", ""),
    ("naiset vasta nauretahan.\"", "naiset vasta nauretaan.\"", "nainen, vasta, nauraa", "women in turn are laughed at.\"", ""),
    ("Sanoi lieto Lemminkäinen:", "Sanoi lieto Lemminkäinen:", "sanoa, lieto, Lemminkäinen", "Light-hearted Lemminkäinen said:", ""),
    ("\"Oi emoni, kantajani!", "\"Oi äitini, kantajani!", "oi, emo/äiti, kantaja", "\"O my mother, my bearer!", ""),
    ("Ken mun naisin naurattaisi", "Kuka minua naisten naurattaisi", "kuka, minä, nainen, naurattaa", "Who would make women laugh at me", ""),
    ("eli piioin pilkkoaisi!", "tai piikain pilkkaisi!", "tai, piika, pilkata", "or would mock me with maids!", ""),
    ("Itse nauraisin isännät,", "Itse nauraisin isännät,", "itse, nauraa, isäntä", "I myself would laugh at the masters,", ""),
    ("kaikki piiat pilkkoaisin,", "kaikki piiat pilkkaisin,", "kaikki, piika, pilkata", "would mock all the maids,", ""),
    ("nauraisin sataki naista,", "nauraisin satakin naista,", "nauraa, sata, nainen", "would laugh at even a hundred women,", ""),
    ("tuhat muuta morsianta.\"", "tuhat muuta morsianta.\"", "tuhat, muu, morsian", "a thousand other brides.\"", "Trickster's reflexive boasting after each question — classic defensive pride masking vulnerability."),
    ("Sanoi äiti Lemminkäisen:", "Sanoi äiti Lemminkäinen:", "sanoa, äiti, Lemminkäinen", "Lemminkäinen's mother said:", ""),
    ("\"Mi sinulla, poikueni?", "\"Mitä sinulla, poikaseni?", "mitä, sinä, poika", "\"What is with you, my son?", ""),
    ("On sulle satunen saanut", "Onko sinulle sattunut", "olla, sinä, sattua", "Has something happened to you", ""),
    ("Pohjolassa käyessäsi,", "Pohjolassa käydessäsi,", "Pohjola, käydä", "while you went to Pohjola,", ""),
    ("vainko liioin syötyäsi,", "vai liiaksi syötyäsi,", "vai, liikaa, syödä", "or having eaten too much,", ""),
    ("syötyäsi, juotuasi", "syötyäsi, juotuasi", "syödä, juoda", "having eaten, having drunk", ""),
    ("olet öisillä sijoilla", "olet öisillä sijoilla", "olla, öinen, sija", "have you in nighttime places", ""),
    ("nähnyt outoja unia?\"", "nähnyt outoja unia?\"", "nähdä, outo, uni", "seen strange dreams?\"", "Mother's persistent, tender interrogation — she suspects the worst."),
    ("Silloin lieto Lemminkäinen", "Silloin lieto Lemminkäinen", "silloin, lieto, Lemminkäinen", "Then light-hearted Lemminkäinen", ""),
    ("sai tuossa sanoneheksi:", "sai tuossa sanotuksi:", "saada, tuo, sanoa", "managed there to say it:", ""),
    ("\"Akat noita arvelkohot", "\"Akkojen arvelkoot", "akka, arvella", "\"Let the old women speculate about", "Trickster dismisses the topic of dreams with sexist deflection — avoiding confession through mockery."),
    ("öisiä unennäköjä!", "öisiä unennäköjä!", "öinen, unennäkö", "nighttime dream-visions!", ""),
    ("Muistan yölliset uneni,", "Muistan yölliset uneni,", "muistaa, yöllinen, uni", "I remember my nightly dreams,", ""),
    ("sen paremmin päivälliset.", "sen paremmin päivälliset.", "paremmin, päivällinen", "and all the better the daytime ones.", ""),
    ("Oi emoni, vanha vaimo!", "Oi äitini, vanha vaimo!", "oi, emo/äiti, vanha, vaimo", "O my mother, old woman!", ""),
    ("Sääli säkkihin evästä,", "Sääli säkkiin evästä,", "säälitä, säkki, eväs", "Pack provisions into a sack,", "Trickster pivots sharply from evasion to urgent demand — flight instinct overrides all else."),
    ("pane jauhot palttinahan,", "pane jauhot palttinaan,", "panna, jauho, palttina", "put flour in linen,", ""),
    ("suolat riepuhun sovita!", "suolat riepuun sovita!", "suola, riepu, sovittaa", "fit the salts in a rag!", ""),
    ("Pois tuli pojalle lähtö,", "Pois tuli pojalle lähtö,", "pois, tulla, poika, lähtö", "Away-going has come for the lad,", ""),
    ("matka maasta ottaminen,", "matka maasta ottaminen,", "matka, maa, ottaa", "a journey of taking from the land,", ""),
    ("tästä kullasta ko'ista,", "tästä kultaisesta kodista,", "tästä, kultainen, koti", "from this golden home,", ""),
    ("kaunihista kartanosta:", "kauniista kartanosta:", "kaunis, kartano", "from this beautiful manor:", ""),
    ("miehet miekkoja hiovat,", "miehet miekkoja hiovat,", "mies, miekka, hioa", "men are sharpening swords,", "The threat made concrete — trickster finally admits the real situation."),
    ("kärestävät keihä'itä.\"", "kärestävät keihäitä.\"", "kärestää, keihäs", "are honing spears.\"", ""),
    ("Emo ennätti kysyä,", "Äiti ennätti kysyä,", "äiti/emo, ennättää, kysyä", "Mother managed to ask,", ""),
    ("vaivan nähnyt vaaitella:", "vaivaa nähty arvioida:", "vaiva, nähdä, vaaitella", "having suffered to weigh:", ""),
    ("\"Miksi miekkoja hiovat,", "\"Miksi miekkoja hiovat,", "miksi, miekka, hioa", "\"Why are they sharpening swords,", ""),
    ("kärestävät keihä'itä?\"", "kärestävät keihäitä?\"", "kärestää, keihäs", "honing spears?\"", ""),
    ("Virkkoi lieto Lemminkäinen,", "Virkkoi lieto Lemminkäinen,", "virkata, lieto, Lemminkäinen", "Light-hearted Lemminkäinen uttered,", ""),
    ("sanoi kaunis Kaukomieli:", "sanoi kaunis Kaukomieli:", "sanoa, kaunis, Kaukomieli", "beautiful Kaukomieli said:", ""),
    ("\"Siksi miekkoja hiovat,", "\"Siksi miekkoja hiovat,", "siksi, miekka, hioa", "\"They are sharpening swords for that,", ""),
    ("kärestävät keihä'itä:", "kärestävät keihäitä:", "kärestää, keihäs", "honing spears:", ""),
    ("mun poloisen pään varalle,", "minun poloisen pään varalle,", "minä, poloinen, pää, varalle", "for my poor head,", ""),
    ("vasten kauloa katalan.", "vasten kaulaani katalan.", "vasten, kaula, katala", "against my wretched neck.", ""),
    ("Tuli työ, tapahtui seikka", "Tuli työ, tapahtui seikka", "tulla, työ, tapahtua, seikka", "A deed came, a thing happened", "Trickster finally confesses obliquely — 'a deed happened' (the killing) presented as if it were external fate."),
    ("noilla Pohjolan pihoilla:", "noilla Pohjolan pihoilla:", "nuo, Pohjola, piha", "on those Pohjola yards:", ""),
    ("tapoin pojan pohjolaisen,", "tapoin pojan pohjolaisen,", "tappaa, poika, pohjolainen", "I killed the northern lad,", ""),
    ("itsen Pohjolan isännän.", "itse Pohjolan isännän.", "itse, Pohjola, isäntä", "the very master of Pohjola.", ""),
    ("Nousi Pohjola sotahan,", "Nousi Pohjola sotaan,", "nousta, Pohjola, sota", "Pohjola rose to war,", ""),
    ("takaturma tappelohon", "takaturma tappeluun", "takaturma, tappelu", "the back-misfortune to battle", ""),
    ("vasten vaivaista minua,", "vasten vaivaista minua,", "vasten, vaivainen, minä", "against poor me,", ""),
    ("yksinäisen ympärille.\"", "yksinäisen ympärille.\"", "yksinäinen, ympärille", "around the lone one.\"", "Trickster casts himself as victim of an army — the individual hero against collective force."),
    ("Emo tuon sanoiksi virkki,", "Äiti tuon sanoiksi virkki,", "äiti/emo, sanoa, virkata", "Mother spoke it into words,", ""),
    ("lausui vanhin lapsellensa:", "lausui vanhin lapselleen:", "lausua, vanhin, lapsi", "the eldest spoke to her child:", ""),
    ("\"Jo sanoin minä sinulle,", "\"Jo sanoin minä sinulle,", "jo, sanoa, minä, sinä", "\"I already told you,", ""),
    ("jo vainen varoittelinki,", "jo vain varoittelin kin,", "jo, vain, varoitella", "I already even warned you,", "Mother's 'I told you so' — validates her earlier three warnings (Runo 26)."),
    ("yhä kielteä käkesin", "yhä kieltoa käkin", "yhä, kielto, käkkiä", "kept urging refusal", ""),
    ("lähtemästä Pohjolahan.", "lähtemästä Pohjolaan.", "lähteä, Pohjola", "from going to Pohjola.", ""),
    ("Mahoit olla oikeassa,", "Voisit olla oikeassa,", "voida, olla, oikea", "You could have been right,", ""),
    ("eleä emon tuvilla,", "elää äidin tuvissa,", "elää, äiti/emo, tupa", "lived in mother's cabins,", ""),
    ("oman vanhemman varassa,", "oman vanhemman varassa,", "oma, vanhempi, vara", "under your own parent's protection,", ""),
    ("kantajasi kartanossa,", "kantajasi kartanossa,", "kantaja, kartano", "in your bearer's manor,", ""),
    ("ei oisi sotoa saanut,", "ei olisi sotaa saanut,", "ei, olla, sota, saada", "would not have gotten war,", ""),
    ("tapahtunut tappeloa.", "tapahtunut tappeluа.", "tapahtua, tappelu", "battle would not have occurred.", ""),
    ("\"Kunne nyt, poikani poloinen,", "\"Minne nyt, poikani poloinen,", "minne, nyt, poika, poloinen", "\"Where now, my poor son,", ""),
    ("kunne, kannettu katala,", "minne, kannettu katala,", "minne, kantaa, katala", "where, wretched carried one,", ""),
    ("lähet pillan piilentähän,", "lähdet pilaa piilentämään,", "lähteä, pila, piillä", "do you go to hide your misdeeds,", ""),
    ("työn pahan pakenentahan,", "työtä pahaa pakenтамaan,", "työ, paha, paeta", "to flee from the wicked deed,", ""),
    ("ettei pää pahoin menisi,", "ettei pää pahoin menisi,", "ettei, pää, paha, mennä", "so that the head would not go badly,", ""),
    ("kaula kaunis katkeaisi,", "kaula kaunis katkeaisi,", "kaula, kaunis, katketa", "the fine neck would not break,", ""),
    ("tukka turhi'in tulisi,", "tukka turhiin tulisi,", "tukka, turha, tulla", "the hair not come to nothing,", ""),
    ("hivus hieno lankeaisi?\"", "hivus hieno lankeaisi?\"", "hivus, hieno, langeta", "the fine hair not fall?\"", ""),
    ("Sanoi lieto Lemminkäinen:", "Sanoi lieto Lemminkäinen:", "sanoa, lieto, Lemminkäinen", "Light-hearted Lemminkäinen said:", ""),
    ("\"En tieä sitä sijoa,", "\"En tiedä sitä sijaa,", "ei, tietää, sija", "\"I do not know that place,", "The trickster admits not knowing — rare moment of genuine uncertainty."),
    ("kunne painuisin pakohon", "minne painuisin pakoon", "minne, painua, pako", "where I would press to flee", ""),
    ("pillojani piilemähän.", "pilojani piilemään.", "pila, piillä", "to hide my misdeeds.", ""),
    ("Oi emoni, kantajani!", "Oi äitini, kantajani!", "oi, emo/äiti, kantaja", "O my mother, my bearer!", ""),
    ("Kunne käsket piilemähän?\"", "Minne käsket piilemään?\"", "minne, käskeä, piillä", "Where do you tell me to hide?\"", "Trickster defers to mother for direction — the wanderer who always returns to the source."),
    ("Sanoi äiti Lemminkäisen,", "Sanoi äiti Lemminkäinen,", "sanoa, äiti, Lemminkäinen", "Lemminkäinen's mother said,", ""),
    ("itse lausui, noin nimesi:", "itse lausui, näin nimesi:", "itse, lausua, nimetä", "herself spoke, named it thus:", ""),
    ("\"En mä tieä, kunne käsken,", "\"En minä tiedä, minne käsken,", "ei, minä, tietää, minne, käskeä", "\"I do not know where to send you,", ""),
    ("kunne käsken ja kehoitan.", "minne käsken ja kehoitan.", "minne, käskeä, kehottaa", "where to command and urge you.", ""),
    ("Menet männyksi mäelle,", "Menet männyksi mäelle,", "mennä, mänty, mäki", "You would go as a pine on the hill,", "Mother lists all natural hiding-places — each is dangerous. Trickster cannot safely become nature."),
    ("katajaksi kankahalle,", "katajaksi kankaalle,", "kataja, kangas", "as a juniper on the heath,", ""),
    ("tuho sielläki tulevi,", "tuho sielläkin tulee,", "tuho, siellä, tulla", "ruin comes even there,", ""),
    ("kova onni kohtoavi:", "kova onni kohtaa:", "kova, onni, kohdata", "hard fate meets you:", ""),
    ("use'in mäkinen mänty", "usein mäkinen mänty", "usein, mäkinen, mänty", "the hill-pine is often", ""),
    ("pärepuiksi leikatahan,", "pärepuiksi leikataan,", "pärepuu, leikata", "cut into splint-wood,", ""),
    ("usei'in kataja kangas", "usein kankaankатaja", "usein, kangas, kataja", "the heath-juniper often", ""),
    ("seipähiksi karsitahan.", "seipäiksi karsitaan.", "seiväs, karsia", "trimmed into stakes.", ""),
    ("\"Nouset koivuksi norolle", "\"Nouset koivuksi norolle", "nousta, koivu, noro", "\"You would rise as a birch in the dell,", ""),
    ("tahikka lehtohon lepäksi,", "tai lehtoon lepäksi,", "tai, lehto, leppä", "or as an alder in the grove,", ""),
    ("tuho sielläki tulisi,", "tuho sielläkin tulisi,", "tuho, siellä, tulla", "ruin would come even there,", ""),
    ("kova onni kohti saisi:", "kova onni kohtaisi:", "kova, onni, kohdata", "hard fate would meet you:", ""),
    ("use'in noroinen koivu", "usein noroinen koivu", "usein, noro, koivu", "the dell-birch often", ""),
    ("pinopuiksi pilkotahan,", "pinopuiksi pilkotaan,", "pinopuu, pilkkoa", "split into stack-wood,", ""),
    ("use'in lepikkölehto", "usein lepikkölehto", "usein, lepikkö, lehto", "the alder-grove often", ""),
    ("hakatahan halmeheksi.", "hakataan halmeheksi.", "hakata, halme", "chopped into a clearing.", ""),
    ("\"Menet marjaksi mäelle,", "\"Menet marjaksi mäelle,", "mennä, marja, mäki", "\"You would go as a berry on the hill,", ""),
    ("puolukaksi kankahalle,", "puolukaksi kankaalle,", "puolukka, kangas", "as a lingonberry on the heath,", ""),
    ("näille maille mansikoiksi,", "näille maille mansikoiksi,", "nämä, maa, mansikka", "as strawberries on these lands,", ""),
    ("mustikoiksi muille maille,", "mustikoiksi muille maille,", "mustikka, muu, maa", "as bilberries on other lands,", ""),
    ("tuho sielläki tulisi,", "tuho sielläkin tulisi,", "tuho, siellä, tulla", "ruin would come even there,", ""),
    ("kova onni kohtoaisi:", "kova onni kohtaisi:", "kova, onni, kohdata", "hard fate would meet you:", ""),
    ("noppisivat nuoret neiet,", "noppoisivat nuoret neidet,", "noppia, nuori, neito", "young maidens would pick you,", ""),
    ("tinarinnat riipisivät.", "tinarinnat riipisivät.", "tinarinta, riipsiä", "the tin-breasted ones would pluck you.", ""),
    ("\"Mene hauiksi merehen,", "\"Mene hauvaksi mereen,", "mennä, hauki, meri", "\"Go as a pike into the sea,", "Mother's survey of all nature-forms: tree, berry, fish, wolf — none safe. Trickster cannot become nature and survive."),
    ("siiaksi silajokehen,", "siiaksi silajokeen,", "siika, silajoki", "as a whitefish into the clear river,", ""),
    ("tuho sielläki tulisi,", "tuho sielläkin tulisi,", "tuho, siellä, tulla", "ruin would come even there,", ""),
    ("kova loppu loukahtaisi:", "kova loppu loukahtaisi:", "kova, loppu, loukahtaa", "a hard end would crash down:", ""),
    ("mies nuori, noentolainen,", "nuori mies, nokimainen,", "nuori, mies, noki", "a young man, sooty-looking,", ""),
    ("veisi verkkonsa vesille,", "veisi verkkonsa vesille,", "viedä, verkko, vesi", "would take his nets to the waters,", ""),
    ("nuoret nuotalla vetäisi,", "nuoret nuotalla vetäisi,", "nuori, nuotta, vetää", "would drag the young ones with a seine,", ""),
    ("vanhat saisi verkollansa.", "vanhat saisi verkoillaan.", "vanha, saada, verkko", "would catch the old ones with his net.", ""),
    ("\"Menet metsähän sueksi,", "\"Menet metsään sudeksi,", "mennä, metsä, susi", "\"You would go as a wolf in the forest,", ""),
    ("korpimaille kontioksi,", "korpimaille kontioksi,", "korpi, maa, kontio", "as a bear on the wilderness lands,", ""),
    ("tuho sielläki tulisi,", "tuho sielläkin tulisi,", "tuho, siellä, tulla", "ruin would come even there,", ""),
    ("kova onni kohtoaisi:", "kova onni kohtaisi:", "kova, onni, kohdata", "hard fate would meet you:", ""),
    ("mies nuori, noen näköinen,", "nuori mies, noen näköinen,", "nuori, mies, noki, näköinen", "a young man, soot-faced,", ""),
    ("kärestäisi keihä'änsä", "kärestäisi keihästään", "kärestää, keihäs", "would hone his spear", ""),
    ("surmataksensa sutoset,", "surmatakseen sudot,", "surmata, susi", "to kill the wolves,", ""),
    ("metsän karhut kaataksensa.\"", "metsän karhut kaatakseen.\"", "metsä, karhu, kaataa", "to fell the forest bears.\"", "Exhaustive list — the world has no safe hiding place for the trickster in animal form."),
    ("Silloin lieto Lemminkäinen", "Silloin lieto Lemminkäinen", "silloin, lieto, Lemminkäinen", "Then light-hearted Lemminkäinen", ""),
    ("sanan virkkoi, noin nimesi:", "sanan virkkoi, näin nimesi:", "sana, virkata, nimetä", "spoke a word, named it thus:", ""),
    ("\"Itse tieän ilke'immät,", "\"Itse tiedän ilkeimmät,", "itse, tietää, ilkeä", "\"I myself know the most wicked,", "Trickster reasserts self-knowledge — even in crisis he claims superior understanding."),
    ("paikat arvoan pahimmat,", "paikat arvan pahimmat,", "paikka, arvata, paha", "can estimate the worst places,", ""),
    ("kussa surma suin pitäisi,", "missä surma suoraan kohtaisi,", "missä, surma, suoraan, kohdata", "where death would meet me straight,", ""),
    ("kova loppu loukahtaisi.", "kova loppu loukahtaisi.", "kova, loppu, loukahtaa", "a hard end would crash down.", ""),
    ("Oi emo, elättäjäni,", "Oi äiti, elättäjäni,", "oi, äiti/emo, elättää", "O mother, my nurturer,", ""),
    ("maammo, maion-antajani!", "äitini, maidon-antajani!", "äiti, maito, antaja", "my mother, my milk-giver!", ""),
    ("Kunne käsket piilemähän,", "Minne käsket piilemään,", "minne, käskeä, piillä", "Where do you tell me to hide,", ""),
    ("kunne käsket ja kehoitat?", "minne käsket ja kehoitat?", "minne, käskeä, kehottaa", "where do you command and urge?", ""),
    ("Aivan on surma suun e'essä,", "Aivan on surma suun edessä,", "aivan, surma, suu, edessä", "Death is right before the mouth,", "Trickster openly admits mortal danger — the bravado drops for a moment of genuine fear."),
    ("paha päivä parran päällä,", "paha päivä parran päällä,", "paha, päivä, parta, päällä", "an evil day upon the beard,", ""),
    ("yksi päivä miehen päätä,", "yksi päivä miehen päätä,", "yksi, päivä, mies, pää", "one day for a man's head,", ""),
    ("tuskin täytehen sitänä.\"", "tuskin täyteen sitäkään.\"", "tuskin, täysi, se", "barely enough for even that.\"", ""),
    ("Silloin äiti Lemminkäisen", "Silloin äiti Lemminkäinen", "silloin, äiti, Lemminkäinen", "Then Lemminkäinen's mother", ""),
    ("itse virkki, noin nimesi:", "itse virkki, näin nimesi:", "itse, virkata, nimetä", "herself uttered, named it thus:", ""),
    ("\"Sanon ma hyvänki paikan,", "\"Sanon minä hyvänkin paikan,", "sanoa, minä, hyvä, paikka", "\"I will tell even a good place,", ""),
    ("ani armahan nimitän,", "erittäin rakasta nimitän,", "erittäin, rakas, nimetä", "name a very dear one,", ""),
    ("missä piillä pillomuksen,", "missä piillä pahantekonsa,", "missä, piillä, pahanteko", "where to hide misdeeds,", ""),
    ("paeta pahan-alaisen:", "paeta pahan alaisen:", "paeta, paha, alainen", "to flee the evil one:", ""),
    ("muistan maata pikkuruisen,", "muistan maata pikkuisen,", "muistaa, maa, pikkuinen", "I remember a little land,", "The mother reveals the secret refuge — her knowledge saves the trickster as it did in Runo 26."),
    ("tieän paikkoa palasen,", "tiedän paikkaa palaselta,", "tietää, paikka, palanen", "know a piece of a place,", ""),
    ("syömätöintä, lyömätöintä,", "syömätöntä, lyömätöntä,", "syömätön, lyömätön", "untouched by eating, untouched by hitting,", ""),
    ("miekan miehen käymätöintä.", "miekkaa miehen käymätöntä.", "miekka, mies, käydä", "untrodden by the sword of man.", "A land unknown to violence — the trickster's sanctuary beyond the reach of normal order."),
    ("Sie vanno valat ikuiset,", "Sinä vanno valat ikuiset,", "sinä, vannoa, vala, ikuinen", "You swear eternal oaths,", ""),
    ("valehettomat, vakaiset,", "valehtelemattomat, vakaiset,", "valehtelematon, vakaa", "truthful, steadfast,", ""),
    ("kuunna, kymmennä kesänä", "kymmenellä kesällä", "kymmenen, kesä", "for ten summers", ""),
    ("et sotia käyäksesi", "ettet sotaan käydäksesi", "ettei, sota, käydä", "that you will not go to war", "The oath demanded — trickster must bind himself with words, his own medium turned against him."),
    ("hopeankana halulla", "hopeasta halusta", "hopea, halu", "out of desire for silver", ""),
    ("tahi kullan tarpehella!\"", "tai kullan tarpeella!\"", "tai, kulta, tarve", "or need for gold!\"", ""),
    ("Sanoi lieto Lemminkäinen:", "Sanoi lieto Lemminkäinen:", "sanoa, lieto, Lemminkäinen", "Light-hearted Lemminkäinen said:", ""),
    ("\"Vannon mie valat vakaiset,", "\"Vannon minä valat vakaiset,", "vannoa, minä, vala, vakaa", "\"I swear the steadfast oaths,", ""),
    ("en kesänä ensimäisnä,", "en kesänä ensimmäisenä,", "ei, kesä, ensimmäinen", "not in the first summer,", "Trickster swears — but hedged ('not the first summer, not yet the second either'). Classic trickster equivocation."),
    ("tok' en vielä toisnakana", "enkä vielä toisenakaan", "eikä, vielä, toinen", "nor yet in the second either", ""),
    ("saa'a suurihin sotihin,", "lähde suuriin sotiin,", "lähteä, suuri, sota", "will I go to great wars,", ""),
    ("noihin miekan melskehisin.", "noihin miekan meluihin.", "nuo, miekka, melske", "to those sword-clamors.", ""),
    ("Viel' on haavat hartioissa,", "Vielä on haavat hartioissa,", "vielä, haava, hartia", "Still are the wounds in the shoulders,", "Trickster references his own battle-wounds as justification for the oath — self-serving honesty."),
    ("syvät reiät ryntähissä", "syvät reiät rintakehässä", "syvä, reikä, rintakehä", "deep holes in the chest", ""),
    ("entisistäkin iloista,", "entisistäkin iloista,", "entinen, ilo", "even from former joys,", ""),
    ("mennehistä melskehistä", "menneistä melskistä", "mennyt, melske", "from past commotions", ""),
    ("suurilla sotamä'illä,", "suurilla sotamäillä,", "suuri, sota, mäki", "on great war-hills,", ""),
    ("miesten tappotanterilla.\"", "miesten tappotantereilla.\"", "mies, tappotanner", "on men's killing-grounds.\"", "Trickster swears peace while reminding all of his violent past — the oath is strategic, not moral."),
    ("Silloin äiti Lemminkäisen", "Silloin äiti Lemminkäinen", "silloin, äiti, Lemminkäinen", "Then Lemminkäinen's mother", ""),
    ("sanan virkkoi, noin nimesi:", "sanan virkkoi, näin nimesi:", "sana, virkata, nimetä", "spoke a word, named it thus:", ""),
    ("\"Otapa isosi pursi,", "\"Ota isäsi pursi,", "ottaa, isä, pursi", "\"Take your father's boat,", "The father's boat — trickster inherits the means of escape. Father's legacy enables the son's survival."),
    ("lähe tuonne piilemähän", "lähde sinne piilemään", "lähteä, sinne, piillä", "go there to hide", ""),
    ("ylitse meren yheksän,", "ylitse yhdeksän meren,", "ylitse, yhdeksän, meri", "across nine seas,", ""),
    ("meri-puolen kymmenettä,", "meri puolelle kymmenettä,", "meri, puoli, kymmenes", "to the sea-side of the tenth,", ""),
    ("saarehen selällisehen,", "saareen selkäiseen,", "saari, selkäinen", "to a far island,", ""),
    ("luotohon merellisehen!", "luotoon merelliseen!", "luoto, merellinen", "to a sea islet!", ""),
    ("Siell' ennen isosi piili,", "Siellä ennen isäsi piili,", "siellä, ennen, isä, piillä", "There your father hid before,", ""),
    ("sekä piili jotta säilyi", "sekä piili että säilyi", "sekä, piillä, että, säilyä", "both hid and survived", "The father's precedent — trickster's exile is a repetition of his father's, a hereditary pattern."),
    ("suurina sotakesinä,", "suurina sotakesinä,", "suuri, sota, kesä", "in great war-summers,", ""),
    ("vainovuosina kovina;", "vainovuosina kovina;", "vaino, vuosi, kova", "in hard pursuit-years;", ""),
    ("hyvä oli siellä ollaksensa,", "hyvä oli siellä ollakseen,", "hyvä, siellä, olla", "it was good to be there,", ""),
    ("armas aikaellaksensa.", "rakas aikaellakseen.", "rakas, aikailla", "dear to spend time there.", ""),
    ("Siellä piile vuosi, toinen,", "Siellä piily vuosi, toinen,", "siellä, piillä, vuosi, toinen", "There hide a year, a second,", ""),
    ("käy kotihin kolmannella", "käy kotiin kolmannella", "käydä, koti, kolmas", "come home on the third", ""),
    ("tutuille ison tuville,", "tutuille isän tuville,", "tuttu, isä, tupa", "to the familiar paternal cabins,", ""),
    ("vanhempasi valkamoille!\"", "vanhempasi valkamoille!\"", "vanhempi, valkamo", "to your parent's moorings!\"", "Exile with a return date — the trickster's banishment is temporary. He will come back. The cycle continues."),
]

af = PatternFill("solid", start_color="EBF3FB")
tf = PatternFill("solid", start_color="FFF2CC")
nf = PatternFill("solid", start_color="FFFFFF")
thin = Side(style="thin", color="BDD7EE")
border = Border(left=thin, right=thin, top=thin, bottom=thin)

for ri, verse in enumerate(verses, 2):
    fill = af if ri % 2 == 0 else nf
    for ci, val in enumerate(verse, 1):
        cell = ws.cell(row=ri, column=ci, value=val)
        cell.font = Font(name="Arial", size=10)
        cell.alignment = Alignment(wrap_text=True, vertical="top")
        cell.border = border
        cell.fill = tf if (ci == 5 and val) else fill

ws.column_dimensions["A"].width = 38
ws.column_dimensions["B"].width = 38
ws.column_dimensions["C"].width = 35
ws.column_dimensions["D"].width = 40
ws.column_dimensions["E"].width = 55
ws.freeze_panes = "A2"
ws.row_dimensions[1].height = 30
for ri in range(2, len(verses) + 2):
    ws.row_dimensions[ri].height = 40

wb.save("kalevala_runo28.xlsx")
print("Saved.")
